### ISSUE TITLE
Feature request for LiftoverVcf to process special case of hg19<-->GRCh37 GVCFs

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#1002]
Application to research is detailed by scientists below. This sounds rather useful to me. Original post is on GATK forum and link to it is at the end. 

The usecase would be special in that no other reference combinations  would be allowed. Liftover applies to the genomic coordinates AND the `INFO` field, if it contains a GVCF block's `END` coordinates.

Here's some background information on the GVCF format:
<img width="1384" alt="screenshot 2017-11-15 15 41 37" src="https://user-images.githubusercontent.com/11543866/33348640-1d9d7444-d465-11e7-8b83-0c78d210eb33.png">

Instead of relying on a CHAIN file, perhaps there could be a special parameter that allows conversion between +/-`chr` for datasets with non-mito autosomes. If mito would be allowed, then a CHAIN file would be required for the shift in coordinates and `chrM`<-->`MT`. 

---
> @aneek said:
> @ shlee
> 
> Hi, thank you very much for your suggestion. We will be glad if you can put a feature request for us. My colleague in this research will let you know the details about the purpose of GVCF conversion in this forum discussion following my post. 
> 
> Kind regards,
> Aneek
> 

@shlee 
Hi, I am Neethu and here I am briefing the purpose of this conversion. We have approximately 400 exomes, which are aligned to GRCH37. we have done the joint genotyping , VQSR  and also calculated allele frequency based on this 400 exomes. We are using this allele frequency to narrow down the number of variants and to identify pathogenic variants for rare Mendelian disorders. We have another set of exomes (~80) which are aligned to hg19. we would like to combine both sets and calculate the allele frequencies. As one set is already aligned to hg19 and generated the gvcf, rather than redoing it based on Grch37, we used LiftoverVCF. But we come across the above mentioned problems. It would be really great if you can help us in this regard.

Thanks and Regards,
Neethu

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/44201#Comment_44201

**Comment by sooheelee** [comment]
Hey @yfarjoun, this is something that came up in the forum. Can I assign you?

**Comment by yfarjoun** [comment]
The issue isn't defined well enough. it seems that liftover should work as currently written...I'm still not convinced that it doesn't.
