### ISSUE TITLE
CollectHsMetrics errors with IllegalStateException: Could not find percentile: 0.2

### ISSUE THREAD

**Issue by cbrueffer** [broadinstitute/picard#1003]
### Affected tool(s)
CollectHsMetrics 

### Affected version(s)
- [x] Latest public release version [2.15.0]
- [ ] Latest development/master branch as of [date of test?]

### Description
```
[Wed Nov 29 18:56:29 CET 2017] picard.analysis.directed.CollectHsMetrics done. Elapsed time: 14.78 minutes.
Runtime.totalMemory()=348127232
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalStateException: Could not find percentile: 0.2
	at htsjdk.samtools.util.Histogram.getPercentile(Histogram.java:327)
	at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.calculateTargetCoverageMetrics(TargetMetricsCollector.java:688)
	at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.finish(TargetMetricsCollector.java:626)
	at picard.metrics.MultiLevelCollector$AllReadsDistributor.finish(MultiLevelCollector.java:208)
	at picard.metrics.MultiLevelCollector.finish(MultiLevelCollector.java:324)
	at picard.analysis.directed.CollectTargetedMetrics.doWork(CollectTargetedMetrics.java:153)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
```

#### Steps to reproduce

1. download the target and probe BED files from https://www.idtdna.com/pages/products/nextgen/target-capture/xgen-lockdown-panels/xgen-pan-cancer-panel
2. lift over from hg19 to hg38
3. convert BED files to interval file using Picard BedToInterval and hg38 FASTA file
4. run CollectHsMetrics as follows:

```
java -jar picard.jar CollectHsMetrics I=X.bam O=X_metrics.txt R=hg38.fa BAIT_INTERVALS=xgen-pan-cancer-probes-lifted_hg19_to_hg38.interval_list TARGET_INTERVALS=xgen-pan-cancer-targets-lifted_hg19_to_hg38.interval_list
```

#### Expected behavior

The metrics file X_metrics.txt should be written.

#### Actual behavior

Crash and no output file, see stackstrace above.

**Comment by cbrueffer** [comment]
The problem was that I hadn't converted the liftover files back to BED format, this resulted in BedToIntervalList output files only containing headers, no actual intervals.

**Comment by yfarjoun** [comment]
it seems that you had no coverage....I'm adding a better error message to
protect against similar issues in the future.

**Comment by cbrueffer** [comment]
Hi Yossi,

indeed; what threw me off was that neither BedToIntervalList nor CollectHsMetrics complained about completely malformed / empty BED/IntervalList input but happily pretended to work :-)

Thanks for having a look at this!

**Comment by erarroji** [comment]
Hi,

I have exactly the same problem, but i convert my bed files to interval list without lift over them. I already check both of my interval files and they are ok. Do you have any clue of what can be the problem?

Thank you

**Comment by yfarjoun** [comment]
can you please show the run-logs?

also, please run IntervalListTools on the interval lists and show the logs.

thanks.

**Comment by erarroji** [comment]
Hi Yossi,

This is the complete run-log of the CollectHsMetrics
`CollectHsMetrics BAIT_INTERVALS=[/mnt/BRCAness/ref/V6SureSelect/AgilentSSV6baitlist.interval_list] TARGET_INTERVALS=[/mnt/BRCAness/ref/V6SureSelect/AgilentSSV6_targets_list.interval_list] INPUT=190.sortedDeDup.bam OUTPUT=/mnt/BRCAness/Run1Novogen/Calidad/PicardQC/190_hs_metrics.txt REFERENCE_SEQUENCE=/mnt/BRCAness/ref/ucsc.hg19.fasta    METRIC_ACCUMULATION_LEVEL=[ALL_READS] NEAR_DISTANCE=250 MINIMUM_MAPPING_QUALITY=20 MINIMUM_BASE_QUALITY=20 CLIP_OVERLAPPING_READS=true COVERAGE_CAP=200 SAMPLE_SIZE=10000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
INFO	2017-12-07 16:37:11	CollectHsMetrics	Processed     1,000,000 records.  Elapsed time: 00:00:04s.  Time for last 1,000,000:    4s.  Last read position: chr1:17,983,029
INFO	2017-12-07 16:37:14	CollectHsMetrics	Processed     2,000,000 records.  Elapsed time: 00:00:07s.  Time for last 1,000,000:    2s.  Last read position: chr1:45,472,419
INFO	2017-12-07 16:37:17	CollectHsMetrics	Processed     3,000,000 records.  Elapsed time: 00:00:10s.  Time for last 1,000,000:    3s.  Last read position: chr1:149,104,208
INFO	2017-12-07 16:37:21	CollectHsMetrics	Processed     4,000,000 records.  Elapsed time: 00:00:14s.  Time for last 1,000,000:    3s.  Last read position: chr1:200,801,875
INFO	2017-12-07 16:37:23	CollectHsMetrics	Processed     5,000,000 records.  Elapsed time: 00:00:16s.  Time for last 1,000,000:    2s.  Last read position: chr2:11,053,380
INFO	2017-12-07 16:37:26	CollectHsMetrics	Processed     6,000,000 records.  Elapsed time: 00:00:19s.  Time for last 1,000,000:    2s.  Last read position: chr2:87,635,104
INFO	2017-12-07 16:37:29	CollectHsMetrics	Processed     7,000,000 records.  Elapsed time: 00:00:22s.  Time for last 1,000,000:    2s.  Last read position: chr2:177,036,851
INFO	2017-12-07 16:37:33	CollectHsMetrics	Processed     8,000,000 records.  Elapsed time: 00:00:26s.  Time for last 1,000,000:    3s.  Last read position: chr2:242,794,427
INFO	2017-12-07 16:37:36	CollectHsMetrics	Processed     9,000,000 records.  Elapsed time: 00:00:29s.  Time for last 1,000,000:    3s.  Last read position: chr3:52,255,236
INFO	2017-12-07 16:37:39	CollectHsMetrics	Processed    10,000,000 records.  Elapsed time: 00:00:32s.  Time for last 1,000,000:    2s.  Last read position: chr3:155,668,913
INFO	2017-12-07 16:37:42	CollectHsMetrics	Processed    11,000,000 records.  Elapsed time: 00:00:35s.  Time for last 1,000,000:    2s.  Last read position: chr4:17,710,850
INFO	2017-12-07 16:37:45	CollectHsMetrics	Processed    12,000,000 records.  Elapsed time: 00:00:37s.  Time for last 1,000,000:    2s.  Last read position: chr4:183,720,762
INFO	2017-12-07 16:37:47	CollectHsMetrics	Processed    13,000,000 records.  Elapsed time: 00:00:40s.  Time for last 1,000,000:    2s.  Last read position: chr5:117,015,956
INFO	2017-12-07 16:37:50	CollectHsMetrics	Processed    14,000,000 records.  Elapsed time: 00:00:43s.  Time for last 1,000,000:    2s.  Last read position: chr5:176,958,237
INFO	2017-12-07 16:37:53	CollectHsMetrics	Processed    15,000,000 records.  Elapsed time: 00:00:46s.  Time for last 1,000,000:    3s.  Last read position: chr6:43,190,362
INFO	2017-12-07 16:37:57	CollectHsMetrics	Processed    16,000,000 records.  Elapsed time: 00:00:49s.  Time for last 1,000,000:    3s.  Last read position: chr6:167,595,196
INFO	2017-12-07 16:37:59	CollectHsMetrics	Processed    17,000,000 records.  Elapsed time: 00:00:52s.  Time for last 1,000,000:    2s.  Last read position: chr7:64,596,799
INFO	2017-12-07 16:38:02	CollectHsMetrics	Processed    18,000,000 records.  Elapsed time: 00:00:55s.  Time for last 1,000,000:    2s.  Last read position: chr7:128,446,348
INFO	2017-12-07 16:38:05	CollectHsMetrics	Processed    19,000,000 records.  Elapsed time: 00:00:58s.  Time for last 1,000,000:    2s.  Last read position: chr8:22,476,116
INFO	2017-12-07 16:38:07	CollectHsMetrics	Processed    20,000,000 records.  Elapsed time: 00:01:00s.  Time for last 1,000,000:    2s.  Last read position: chr8:133,919,086
INFO	2017-12-07 16:38:10	CollectHsMetrics	Processed    21,000,000 records.  Elapsed time: 00:01:03s.  Time for last 1,000,000:    2s.  Last read position: chr9:69,420,345
INFO	2017-12-07 16:38:13	CollectHsMetrics	Processed    22,000,000 records.  Elapsed time: 00:01:06s.  Time for last 1,000,000:    2s.  Last read position: chr9:133,266,296
INFO	2017-12-07 16:38:16	CollectHsMetrics	Processed    23,000,000 records.  Elapsed time: 00:01:09s.  Time for last 1,000,000:    2s.  Last read position: chr10:32,158,471
INFO	2017-12-07 16:38:18	CollectHsMetrics	Processed    24,000,000 records.  Elapsed time: 00:01:11s.  Time for last 1,000,000:    2s.  Last read position: chr10:104,183,771
INFO	2017-12-07 16:38:21	CollectHsMetrics	Processed    25,000,000 records.  Elapsed time: 00:01:14s.  Time for last 1,000,000:    2s.  Last read position: chr11:6,592,898
INFO	2017-12-07 16:38:24	CollectHsMetrics	Processed    26,000,000 records.  Elapsed time: 00:01:17s.  Time for last 1,000,000:    2s.  Last read position: chr11:64,681,605
INFO	2017-12-07 16:38:27	CollectHsMetrics	Processed    27,000,000 records.  Elapsed time: 00:01:20s.  Time for last 1,000,000:    2s.  Last read position: chr11:116,692,206
INFO	2017-12-07 16:38:30	CollectHsMetrics	Processed    28,000,000 records.  Elapsed time: 00:01:23s.  Time for last 1,000,000:    2s.  Last read position: chr12:43,354,816
INFO	2017-12-07 16:38:32	CollectHsMetrics	Processed    29,000,000 records.  Elapsed time: 00:01:25s.  Time for last 1,000,000:    2s.  Last read position: chr12:109,526,191
INFO	2017-12-07 16:38:35	CollectHsMetrics	Processed    30,000,000 records.  Elapsed time: 00:01:28s.  Time for last 1,000,000:    2s.  Last read position: chr13:50,134,061
INFO	2017-12-07 16:38:38	CollectHsMetrics	Processed    31,000,000 records.  Elapsed time: 00:01:31s.  Time for last 1,000,000:    2s.  Last read position: chr14:60,975,970
INFO	2017-12-07 16:38:41	CollectHsMetrics	Processed    32,000,000 records.  Elapsed time: 00:01:34s.  Time for last 1,000,000:    2s.  Last read position: chr15:20,668,138
INFO	2017-12-07 16:38:43	CollectHsMetrics	Processed    33,000,000 records.  Elapsed time: 00:01:36s.  Time for last 1,000,000:    2s.  Last read position: chr15:72,668,060
INFO	2017-12-07 16:38:46	CollectHsMetrics	Processed    34,000,000 records.  Elapsed time: 00:01:39s.  Time for last 1,000,000:    2s.  Last read position: chr16:1,584,413
INFO	2017-12-07 16:38:49	CollectHsMetrics	Processed    35,000,000 records.  Elapsed time: 00:01:42s.  Time for last 1,000,000:    2s.  Last read position: chr16:29,086,355
INFO	2017-12-07 16:38:52	CollectHsMetrics	Processed    36,000,000 records.  Elapsed time: 00:01:45s.  Time for last 1,000,000:    2s.  Last read position: chr16:72,108,497
INFO	2017-12-07 16:38:55	CollectHsMetrics	Processed    37,000,000 records.  Elapsed time: 00:01:48s.  Time for last 1,000,000:    2s.  Last read position: chr17:7,592,353
INFO	2017-12-07 16:38:57	CollectHsMetrics	Processed    38,000,000 records.  Elapsed time: 00:01:50s.  Time for last 1,000,000:    2s.  Last read position: chr17:38,543,560
INFO	2017-12-07 16:39:00	CollectHsMetrics	Processed    39,000,000 records.  Elapsed time: 00:01:53s.  Time for last 1,000,000:    2s.  Last read position: chr17:71,386,514
INFO	2017-12-07 16:39:03	CollectHsMetrics	Processed    40,000,000 records.  Elapsed time: 00:01:56s.  Time for last 1,000,000:    2s.  Last read position: chr18:22,619,778
INFO	2017-12-07 16:39:06	CollectHsMetrics	Processed    41,000,000 records.  Elapsed time: 00:01:59s.  Time for last 1,000,000:    2s.  Last read position: chr19:4,054,370
INFO	2017-12-07 16:39:09	CollectHsMetrics	Processed    42,000,000 records.  Elapsed time: 00:02:01s.  Time for last 1,000,000:    2s.  Last read position: chr19:15,271,420
INFO	2017-12-07 16:39:11	CollectHsMetrics	Processed    43,000,000 records.  Elapsed time: 00:02:04s.  Time for last 1,000,000:    2s.  Last read position: chr19:39,440,637
INFO	2017-12-07 16:39:14	CollectHsMetrics	Processed    44,000,000 records.  Elapsed time: 00:02:07s.  Time for last 1,000,000:    2s.  Last read position: chr19:50,238,704
INFO	2017-12-07 16:39:17	CollectHsMetrics	Processed    45,000,000 records.  Elapsed time: 00:02:10s.  Time for last 1,000,000:    2s.  Last read position: chr20:19,998,015
INFO	2017-12-07 16:39:20	CollectHsMetrics	Processed    46,000,000 records.  Elapsed time: 00:02:13s.  Time for last 1,000,000:    2s.  Last read position: chr20:62,187,135
INFO	2017-12-07 16:39:23	CollectHsMetrics	Processed    47,000,000 records.  Elapsed time: 00:02:15s.  Time for last 1,000,000:    2s.  Last read position: chr22:21,538,000
INFO	2017-12-07 16:39:25	CollectHsMetrics	Processed    48,000,000 records.  Elapsed time: 00:02:18s.  Time for last 1,000,000:    2s.  Last read position: chr22:47,068,802
INFO	2017-12-07 16:39:28	CollectHsMetrics	Processed    49,000,000 records.  Elapsed time: 00:02:21s.  Time for last 1,000,000:    2s.  Last read position: chrX:64,771,724
INFO	2017-12-07 16:39:31	CollectHsMetrics	Processed    50,000,000 records.  Elapsed time: 00:02:24s.  Time for last 1,000,000:    2s.  Last read position: chrX:154,842,554
[Thu Dec 07 16:39:32 CST 2017] picard.analysis.directed.CollectHsMetrics done. Elapsed time: 2.47 minutes.
Runtime.totalMemory()=5752487936
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalStateException: Could not find percentile: 0.2
	at htsjdk.samtools.util.Histogram.getPercentile(Histogram.java:327)
	at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.calculateTargetCoverageMetrics(TargetMetricsCollector.java:688)
	at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.finish(TargetMetricsCollector.java:626)
	at picard.metrics.MultiLevelCollector$AllReadsDistributor.finish(MultiLevelCollector.java:208)
	at picard.metrics.MultiLevelCollector.finish(MultiLevelCollector.java:324)
	at picard.analysis.directed.CollectTargetedMetrics.doWork(CollectTargetedMetrics.java:153)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)`

For the IntervalListTools I ran it like this:
`java -jar picard.jar IntervalListTools \
I=AgilentSSV6_targets_list.interval_list \
SI=AgilentSSV6baitlist.interval_list \
O=new.interval_list`

 This is the output of the run-log

`IntervalListTools INPUT=[AgilentSSV6_targets_list.interval_list] OUTPUT=new.interval_list SECOND_INPUT=[AgilentSSV6baitlist.interval_list]    PADDING=0 UNIQUE=false SORT=true ACTION=CONCAT SCATTER_COUNT=1 INCLUDE_FILTERED=false BREAK_BANDS_AT_MULTIPLES_OF=0 SUBDIVISION_MODE=INTERVAL_SUBDIVISION INVERT=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Dec 07 17:54:04 CST 2017] picard.util.IntervalListTools done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=1513619456
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Second List found when action was CONCAT. Ignoring second list.
        at picard.util.IntervalListTools$Action$1.act(IntervalListTools.java:117)
        at picard.util.IntervalListTools.doWork(IntervalListTools.java:201)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)`

**Comment by yfarjoun** [comment]
you didn't run IntervalListTools correctly. I put the exact commandline in the other issue you opened.
