### ISSUE TITLE
CollectHsMetrics errors with IllegalStateException: Could not find percentile: 0.2

### ISSUE THREAD

**Issue by erarroji** [broadinstitute/picard#1019]
### Affected tool
CollectHsMetrics

### Affected version(s)
- [ ] Latest public release version [version?]

### Description 
picard.analysis.directed.CollectHsMetrics done. Elapsed time: 2.74 minutes.
Runtime.totalMemory()=5752487936
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalStateException: Could not find percentile: 0.2
at htsjdk.samtools.util.Histogram.getPercentile(Histogram.java:327)
at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.calculateTargetCoverageMetrics(TargetMetricsCollector.java:688)
at picard.analysis.directed.TargetMetricsCollector$PerUnitTargetMetricCollector.finish(TargetMetricsCollector.java:626)
at picard.metrics.MultiLevelCollector$AllReadsDistributor.finish(MultiLevelCollector.java:208)
at picard.metrics.MultiLevelCollector.finish(MultiLevelCollector.java:324)
at picard.analysis.directed.CollectTargetedMetrics.doWork(CollectTargetedMetrics.java:153)
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

#### Steps to reproduce
1. Download bed files from https://earray.chem.agilent.com/suredesign for SureSelect All Exome V6
1. Convert target and bait files form bed to interval list with bedToInterval
1. My reference was already index
1. Run CollectHSMetrics with de command below:

`java -jar picard.jar CollectHsMetrics \
I=190.sortedDeDup.bam \
O=/190_hs_metrics.txt \
R=/ucsc.hg19.fasta \
BAIT_INTERVALS=/AgilentSSV6baitlist.interval_list \
TARGET_INTERVALS=/AgilentSSV6_targets_list.interval_list`

#### Expected behavior
Metrics in the output file "190_hs_metrics.txt"

#### Actual behavior
Crash and no output file.

----

**Comment by yfarjoun** [comment]
Could you please run IntervalListTools on your interval-list:
```
java -jar picard.jar IntervalListTools I=/AgilentSSV6baitlist.interval_list  O=/dev/null
```
and also 
```
java -jar picard.jar IntervalListTools I=/AgilentSSV6_targets_list.interval_list  O=/dev/null
```
and post the screen output?

**Comment by erarroji** [comment]
For: 

`java -jar picard.jar IntervalListTools I=/AgilentSSV6baitlist.interval_list  O=/dev/null`

`IntervalListTools INPUT=[AgilentSSV6baitlist.interval_list] OUTPUT=/dev/null    PADDING=0 UNIQUE=false SORT=true ACTION=CONCAT SCATTER_COUNT=1 INCLUDE_FILTERED=false BREAK_BANDS_AT_MULTIPLES_OF=0 SUBDIVISION_MODE=INTERVAL_SUBDIVISION INVERT=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
INFO	2017-12-07 18:07:44	IntervalListTools	Produced 243190 intervals totalling 60456963 unique bases.
[Thu Dec 07 18:07:44 CST 2017] picard.util.IntervalListTools done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1513619456`

And for
`java -jar picard.jar IntervalListTools I=/AgilentSSV6_targets_list.interval_list  O=/dev/null`

`picard IntervalListTools I=AgilentSSV6_targets_list.interval_list  O=/dev/null
18:09:49.853 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/Bioinfo/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Dec 07 18:09:49 CST 2017] IntervalListTools INPUT=[AgilentSSV6_targets_list.interval_list] OUTPUT=/dev/null    PADDING=0 UNIQUE=false SORT=true ACTION=CONCAT SCATTER_COUNT=1 INCLUDE_FILTERED=false BREAK_BANDS_AT_MULTIPLES_OF=0 SUBDIVISION_MODE=INTERVAL_SUBDIVISION INVERT=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
INFO	2017-12-07 18:09:49	IntervalListTools	Produced 0 intervals totalling 0 unique bases.
[Thu Dec 07 18:09:49 CST 2017] picard.util.IntervalListTools done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=1513619456`

Guess is the target interval list

**Comment by yfarjoun** [comment]
Looks like it... If you're all set please close the ticket.

**Comment by erarroji** [comment]
Thank you for all the help, also i want to thank you for the amazing software.

**Comment by yfarjoun** [comment]
you're very welcome. 

@vdauwera you might want to collect this "thanks" for your files :-)
