### ISSUE TITLE
LiftoverVcf throws exception on record with "AF=."

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/picard#1037]
## Bug Report

This line of code in LiftoverUtils throws an exception if the value is "." for a key:
                final double attributeToReverse = vc.getAttributeAsDouble(key, -1);
Unfortunately, "." is a valid value -- and it's what's present in the gnomAD VCF sometimes.

### Affected tool(s)

LiftoverVcf with default parameters

### Affected version(s)
- [X] Latest public release version [version?]
- [X] Latest development/master branch as of [date of test?]

**Comment by yfarjoun** [comment]
fixed by #1080
