### ISSUE TITLE
Documentation request: CollectHsMetrics PerTargetCoverage output fields

### ISSUE THREAD

**Issue by willhooper** [broadinstitute/picard#1047]
### Tool(s) involved
Picard - CollectHsMetrics 

### Description 
Hi, I couldn't find documentation for the following fields in the PerTargetCoverage output file output by CollectHsMetrics. Could you please confirm/provide definitions for these? 

a.	%gc (GC content for target ?)
b.	pct_0x (the percentage of bases per target with 0x coverage ?)
c.	read_count (the reads mapping to the target?)

Thanks, 
Will

**Comment by yfarjoun** [comment]
This was added somewhat ad-hoc-ishly....should be converted into a full-fledged metrics file, I think.

yes for a and b, 

c is the number of reads that had bases that counted towards coverage in that target. (so, for example clipped bases are not included)

**Comment by willhooper** [comment]
Great, thanks for your help!
