### ISSUE TITLE
FilterVcf marks all entries with AllGtsFiltered regardless of filter input

### ISSUE THREAD

**Issue by freekvh** [broadinstitute/picard#1069]
### Affected tool(s)
Picard FilterVcf

### Affected version(s)
picard-2.16.0

### Description 
FilterVcf filters out everything, ignores MIN_DP setting

#### Steps to reproduce
Create VCF from BAM file:
`bcftools mpileup -Ou -f \$refGenome $bamFile | bcftools call -vmO z -o $bamFile.vcf.gz`

Filter VCF
`java -jar $PICARD FilterVcf I=$bamFile.vcf.gz MIN_DP=0 O=$bamFile_filtered.vcf.gz`

Check what filter did:
```
gzcat $bamFile_filtered.vcf.gz | head -n 400 | tail -n 4

gzip: stdout: Broken pipe
1       1041950 .       T       C       225     AllGtsFiltered  AC=2;AN=2;DP=146;DP4=0,0,79,53;MQ=60;MQ0F=0;MQSB=1;SGB=-0.693147;VDB=0.00255721 GT:FT:PL 1/1:LowDP;LowGQ:255,255,0
1       1042190 .       G       A       202     AllGtsFiltered  AC=2;AN=2;DP=27;DP4=0,0,1,23;MQ=60;MQ0F=0;MQSB=1;SGB=-0.692831;VDB=0.00588527   GT:FT:PL 1/1:LowDP;LowGQ:232,72,0
1       1042400 .       C       T       22.44   AllGtsFiltered  AC=2;AN=2;DP=2;DP4=0,0,1,0;MQ=60;MQ0F=0;SGB=-0.379885   GT:FT:PL        1/1:LowDP;LowGQ:52,3,0
1       1043223 .       CCT     C       228     AllGtsFiltered  AC=2;AN=2;DP=97;DP4=8,0,87,2;IDV=89;IMF=0.917526;INDEL;MQ=60;MQ0F=0;MQSB=1;SGB=-0.693147;VDB=0.482114     GT:FT:PL        1/1:LowDP;LowGQ:255,165,0
```

#### Expected behavior
Entries with a DP > 0 should not have AllGtsFiltered in the filtered column

#### Actual behavior
All entries have AllGtsFiltered regardless of MIN_DP setting

**Comment by yfarjoun** [comment]
The tool filters at the genotype level. your genotypes do not have DP (or GQ for that matter) and are thus assumed to be 0 and are thus filtered. 

The documentation could say this more clearly perhaps, and in the case of a single-sample vcf one can be rightfully confused.

**Comment by freekvh** [comment]
Hi,

Sorry to bother you again, I understand your comment, I added the required tags using:
` bcftools mpileup --threads 8 -Ou -d 1000000 --min-BQ 13 -a AD,INFO/AD,ADF,INFO/ADF,ADR,INFO/ADR,DP,SP -f $refGenome $bamFile | bcftools call --threads 8 -vmO z -o $bamFile.vcf.gz`

However, the filter step still adds AllGtsFiltered to genotypes with a DP>0:
`java -jar $PICARD FilterVcf I=0018_037_P2017SEQE33R_S1.bam.vcf.gz MIN_DP=0 O=$bamFile_filtered.vcf.gz`
```
 gzcat 0018_037_P2017SEQE33R_S1.bam_filtered.vcf.gz | head -n 400 | tail -n 4
1       1073854 .       T       C       30.42   AllGtsFiltered  AC=2;AD=0,1;ADF=0,1;ADR=0,0;AN=2;DP=2;DP4=0,0,1,0;MQ=60;MQ0F=0;SGB=-0.379885    GT:AD:ADF:ADR:DP:FT:PL:SP       1/1:0,1:0,1:0,0:1:LowGQ:60,3,0:0
1       1080437 .       G       A       21.45   AllGtsFiltered  AC=2;AD=0,2;ADF=0,1;ADR=0,1;AN=2;DP=2;DP4=0,0,1,1;MQ=60;MQ0F=0;MQSB=1;SGB=-0.453602;VDB=0.28    GT:AD:ADF:ADR:DP:FT:PL:SP       1/1:0,2:0,1:0,1:2:LowGQ:51,6,0:0

gzip: 1 1082764 .       T       C       148     AllGtsFiltered  AC=2;AD=0,18;ADF=0,18;ADR=0,0;AN=2;DP=19;DP4=0,0,18,0;MQ=60;MQ0F=0;SGB=-0.691153;VDB=0.207747   GT:AD:ADF:ADR:DP:FT:PL:SP       1/1:0,18:0,18:0,0:18:LowGQ:178,54,0:0
stdout: Broken pipe
1       1083795 .       C       G       91      AllGtsFiltered  AC=2;AD=0,5;ADF=0,5;ADR=0,0;AN=2;DP=5;DP4=0,0,5,0;MQ=60;MQ0F=0;SGB=-0.590765;VDB=0.498872       GT:AD:ADF:ADR:DP:FT:PL:SP       1/1:0,5:0,5:0,0:5:LowGQ:121,15,0:0
```

**Comment by yfarjoun** [comment]
I do not see GQ in the genotype field...which is why its filtered with
LowGQ.

**Comment by freekvh** [comment]
Ah, I see, Thanx a lot for your swift replies, it works now.

For posterity, I added:
`-f GQ,GP`
to the finale `bcftools call` command to get the GQ field added to the FORMAT column, now the filter acts as expected.

Highest regards.
