### ISSUE TITLE
bug report FilterSamReads

### ISSUE THREAD

**Issue by hxin** [broadinstitute/picard#1070]
----

### Affected tool(s)
java -jar /home/xinhe/bin/picard.jar FilterSamReads 

### Affected version(s)
Latest public release version

### Description 
java -jar picard.jar FilterSamReads \
I=input.bam \
O=output.bam \
READ_LIST_FILE=read_names.txt \
FILTER=includeReadList

This command gives an error:
READ_LIST_FILE can only be specified when using FILTER=includeReadList, found value: read_names.txt

I went into the code and found the following code:
 protected String[] customCommandLineValidation() {

        List<String> errors = new ArrayList<>();

        if (INPUT.equals(OUTPUT)) errors.add("INPUT file and OUTPUT file must differ!");

        checkInputs(Filter.includeReadList, READ_LIST_FILE, "READ_LIST_FILE").ifPresent(errors::add);
        checkInputs(Filter.excludeAligned, READ_LIST_FILE, "READ_LIST_FILE").ifPresent(errors::add);
        checkInputs(Filter.includePairedIntervals, INTERVAL_LIST, "INTERVAL_LIST").ifPresent(errors::add);
        checkInputs(Filter.includeJavascript, JAVASCRIPT_FILE, "JAVASCRIPT_FILE").ifPresent(errors::add);

        if (!errors.isEmpty()) return errors.toArray(new String[errors.size()]);

        return super.customCommandLineValidation();
    }

    private Optional<String> checkInputs(final Filter filter, final File inputFile, final String inputFileVariable) {
        if (FILTER == filter && inputFile == null)
            return Optional.of(String.format("%s must be specified when using FILTER=%s, but it was null.", inputFileVariable, FILTER));
        if (FILTER != filter && inputFile != null)
            return Optional.of(String.format("%s can only be specified when using FILTER=%s, found value: %s", inputFileVariable, FILTER, inputFile));
        return Optional.empty();
    }

The checking logic is not correct because when providing 'READ_LIST_FILE' and 'FILTER=includeReadList', the code 

`checkInputs(Filter.excludeAligned, READ_LIST_FILE, "READ_LIST_FILE").ifPresent(errors::add);`

will always go into 

` if (FILTER != filter && inputFile != null)
return Optional.of(String.format("%s can only be specified when using FILTER=%s, found value: %s", inputFileVariable, FILTER, inputFile));` 

and generate the above error.

**Comment by yfarjoun** [comment]
Thanks for the report. There's already a PR for fixing this: https://github.com/broadinstitute/picard/pull/1055
