### ISSUE TITLE
Integrate @ExperimentalFeature and @BetaFeature tags

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/picard#1072]
The version of Barclay used by Picard includes both`@ExperimentalFeature` and `@BetaFeature`  annotations that can be used to tag command line tools. `@ExperimentalFeature` is intended for tools that are truly experimental, and may not have a future, and `@BetaFeature` for tools that are not yet complete.

PicardCommandLine should be changed to honor these when displaying the tool list by adding a corresponding prefix.
Tools that currently have the word "Experimental" should probably be tagged with `@ExperimentalFeature`,and have the text removed.

**Comment by yfarjoun** [comment]
fixed
