### ISSUE TITLE
pileup: filtered snp count larger than total snp count

### ISSUE THREAD

**Issue by royfrancis** [broadinstitute/picard#1075]
I ran picard 2.2.4  `CollectVariantCallingMetrics` as below:

```sh
java -Xmx16G -jar picard.jar CollectVariantCallingMetrics \
SD="dr.dna.toplevel.dict" \
DBSNP="dr-vega-dbsnp.vcf" \
I="sample.vcf" \
O="sample-picard-vcm.vcf"
```

In the results I find that `FILTERED_SNPS` is larger than `TOTAL_SNPS`.

| TOTAL_SNPS | NUM_IN_DB_SNP | NOVEL_SNPS | FILTERED_SNPS | PCT_DBSNP |
| ---- | ---- | ---- | ---- | ---- |
| 13661852 | 161470 | 13500382 | 13824436 | 0.011819 |

I tried on another VCF file with INDELs and get similar results:

| TOTAL_INDELS | NOVEL_INDELS | FILTERED_INDELS |
| ---- | ---- | ---- |
| 2875443 | 2862192 | 3173177 |

The VCF files are generated from the GATK pipeline.

I would expect every metric to be be less than or equal to total counts. I was wondering if this is expected behaviour? And how this can be explained?

**Comment by yfarjoun** [comment]
Note, that TOTAL_SNPS is (confusingly) the number of **Passing** SNPs...not the total...so there's no reason that FILTERED_SNPS will be less than TOTAL_SNPS.
