### ISSUE TITLE
MultiQC interoperability

### ISSUE THREAD

**Issue by michaelmayer2** [broadinstitute/picard#1082]
### Affected tool(s)
https://github.com/ewels/MultiQC

### Affected version(s)
tested with MultiQC version 1.4 and picard 2.17.3

### Description 
some versions after picard 2.5.0 was released picard does no longer seem to print the full java path in front of the respective tool used, e.g. 
in picard 2.5.0 if you call CollectRnaSeqMetrics it will print "# picard.analysis.CollectRnaSeqMetrics..." in the output file while for example with picard 2.5.0 it only prints "# CollectRnaSeqMetrics..." strangely enough for the METRICS_CLASS etc. the java path is still prefixed (e.g. picard.analysis.RnaSeqMetrics)
Not sure if this is related with the switch to a different build system in picard. 
There is an issue open at MultiQC (https://github.com/ewels/MultiQC/issues/655) that tries to patch MultiQC but I wonder if the issue is better fixed in picard. 

#### Steps to reproduce
1) Run Picard with "CollectRnaSeqMetrics" using version 2.17.3
2) Run multiqc 1.4 against those picard files

#### Expected behavior
multiqc detects that there is picard files and then outputs some html files for further analysis

#### Actual behavior
multiqc does not find any picard files and hence does not produce any output. Only if one manually adds the picard.analysis before the CollectRnaSeqMetrics, multiqc will run ok and produce the html output.

**Comment by yfarjoun** [comment]
this is odd. @cmnbroad coudl this be related to barclay?

**Comment by cmnbroad** [comment]
@yfarjoun This probably changed as a result of https://github.com/broadinstitute/barclay/pull/54.

**Comment by yfarjoun** [comment]
so now the Picard metrics only show the simple name of the class rather than the fully-qualified name?

**Comment by cmnbroad** [comment]
The command line in the header has only the simple name, yes. The metrics class itself still has the fully qualified name.

**Comment by yfarjoun** [comment]
@gbggrant  I'm leaning towards "will not fix"....what do you think?

**Comment by magicDGS** [comment]
I personally think that it is clearer for the command line to have only the tool name and not the full qualifier, but I also understand the problem with MultiQC. I vote for the "will not fix" as an API user , @yfarjoun
