### ISSUE TITLE
MarkDuplicate documentation incorrect

### ISSUE THREAD

**Issue by bwlang** [broadinstitute/picard#1087]
### Affected tool(s)
_MarkDuplicates READ_NAME_REGEX_

### Affected version(s)
- [x ] Latest public release version 2.17.2
- [ x] Latest development/master branch as of 2018-01-18

### Description 
Mark dup docs say 
"Note that if the default regex is specified, a regex match is not actually done"...
the [default regex](https://github.com/broadinstitute/picard/blob/e7d6c8f8cf110e6f74edefdef86fba64d01ad0fa/src/main/java/picard/sam/util/ReadNameParser.java#L27) is "<optimized capture of last three ':' separated fields as numeric values>".intern(); 
it's not possible to specify a command line argument that matches this  (due to the intern())

I'll send a PR related to this to fix the documentation.

PS
I found this code confusing since DEFAULT_READ_NAME_REGEX is not actually a regex.

**Comment by yfarjoun** [comment]
@sooheelee 

Can you take a look at this and see if the supplied commit improves the documentation in your eyes?

**Comment by sooheelee** [comment]
Sure. Do you need this soon or can it wait till the end of August when I’m back from vacation?

**Comment by yfarjoun** [comment]
this has waited for 7 months already......so there's no rush.

Thanks!

**Comment by sooheelee** [comment]
Much clearer. Sorry for the delay. Thanks for including me.
