### ISSUE TITLE
[Feature request] IlluminaBasecallsToSam and IllumianBasecallsToFastq output both sample and barcodes

### ISSUE THREAD

**Issue by svm-zhang** [broadinstitute/picard#1103]
Hello,

I have one following feature request:

### Tool(s) involved
IlluminaBasecallsToSam, IlluminaBasecallsToFastq (2.14.1-SNAPSHOT)

### Description
I have dual indexed paired-end libraries. Currently IlluminaBasecallstoSam gives me UMIs in BAMs, while IlluminaBasecallsToFastq gives combination of sample barcodes without UMIs. I did not find options to do so. I would like both UMIs and sample bardes info in either Fastq or BAM file. For example, if I set RX as molecular barcode tag in a BAM: can I have something like

> RX:Z:[sample barcode][molecular barcode]-[sample barcode][molecular barcode]

Also, IlluminaBasecallstoFastq gives header line like below:

> ${READ_NAME} 1:N:0:AGTCAAGACTTT

Shouldn't it be something like this?

> 1:N:0:AGTCAA+GACTTT

Thanks for any help.

cheers,
Simo

**Comment by nh13** [comment]
In your BAM file, what’s in the BC tag (should be the sample barcode)?

**Comment by svm-zhang** [comment]
There are only RX tags for molecular barcodes, and no sample barcodes output. Are sample barcodes supposed to be in BAMs?

Simo

**Comment by nh13** [comment]
Yes, the BC tag can store them. Can you post a single line (record) from your BAM for us to see?

**Comment by svm-zhang** [comment]
First line of one of BAMs:

> MN00392_28_A000H2FCLW:1:11102:10000:11293       77      *       0       0       *       *       0       0       TGAAGATATTTTATTTCCTTTGTCCTTTTTCAGGAGAATTAGATTTCTATAGGATTTTTCTTTAGGAGATTTATTTTTTGGACTTCAAAGCAAGCTGGTATTTTCATACAAATTCTTCTAATTGCTGTGTGTCCCAGGCAGGGAGACGGT  AAAFFFFFFFFFFFFFFFFAFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF=FFAFAFFFF/AFFFFFF        BC:Z:TTA-CTG    RG:Z:sample1    QX:Z:FFF-FF#

The BC tag gives dual molecular indexes, but not sample barcodes.

my command line:
>java -Xmx16g -jar picard.jar IlluminaBasecallsToSam \
        BASECALLS_DIR=${basecalls} 
        LANE=1 
        BARCODES_DIR=./barcodes 
        READ_STRUCTURE=${read_structure} 
        RUN_BARCODE=${run_barcode} \
        TMP_DIR=./tmp 
        MOLECULAR_INDEX_TAG=RX 
        NUM_PROCESSORS=8 
        LIBRARY_PARAMS=${library_params}

**Comment by nh13** [comment]
Can you share the read structure you used? I’d expect both B and M in it for sample barcode and molecular barcode respectively.

**Comment by svm-zhang** [comment]
it's 150T6B3M6B3M150T

**Comment by nh13** [comment]
The command looks good. The read structure looks good. I don’t see why RX isn’t showing up! @yfarjoun, I need a second set of eyes.

**Comment by svm-zhang** [comment]
I also tried the latest version, 2.17.6-SNAPSHOT, and it did not generate sample barcodes as well. So it is not a version problem.

Thanks for looking into this.

**Comment by yfarjoun** [comment]
can you post your actual commandline and logs from the IlluminaBasecallsToSam command?

**Comment by yfarjoun** [comment]
(Given that the UMI is in the BC tag...I suspect that the command-line includes `MOLECULAR_INDEX_TAG=BC` which would overwrite the actual BC tag...)

**Comment by yfarjoun** [comment]
Ah, I see the commandline now....still, can you post the logs?

**Comment by yfarjoun** [comment]
```java
 // If it's a barcoded run and the read isn't assigned to a barcode, then add the barcode
        // that was read as an optional tag
        if (unmatchedBarcode != null) {
            sam.setAttribute(SAMTag.BC.name(), unmatchedBarcode);
        }
```
So, I think that @nh13 is incorrect and that BC will only contain the sample barcode in the case that a match is not found.

The fact that your BC has 2, 3-bp tags indicates that you ran IBCTS using `MOLECULAR_INDEX_TAG=BC`, not `MOLECULAR_INDEX_TAG=RX`...am I correct?

**Comment by svm-zhang** [comment]
@yfarjoun yes, you are absolutely correct. I used  `MOLECULAR_INDEX_TAG=BC` which overwrites the sample barcode. How should I do this properly so that I can have both sample and molecular barcode?

**Comment by svm-zhang** [comment]
Without `MOLECULAR_INDEX_TAG` option, the following is one line from one BAM:

> MN00392_28_A000H2FCLW:1:11102:10000:11376       77      *       0       0       *       *       0       0       ATTTTGGTAACAGTTGATATCTGGCTGTCCTTTTTGTAATGCAGAGTGAGAACTTTCCCTACCGTGTTTGATAAATGTTGTCCAGGTTCCATTGCCAAGAATGTGTTGTTGAAAATGTCTGTTTAGTTTTTAAAGATGGAACTCCACCCT  FFFFFFFF6FFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6FFFFFFFFFFFFFFFFFFFFF/FFFFFFFFFFFFFFF/FFFFFF/FFFFFFFFFFFFFFFFFFAFFFFF/FAFAAFFFFFFAFFFFFFFFFFF/F=FFF  RG:Z:MN003.1    QX:Z:FFF-FFF    RX:Z:AAC-GTA

Does sample barcode by default output to BAM?

Simo

**Comment by svm-zhang** [comment]
Just found out an interesting thing: when I checked the Undetermined BAM file, I can see both BC and RX tags. And this is the only BAM have these two together.

**Comment by nh13** [comment]
As Yossi correctly pointed out, the BC tag is only set if the read does not match one of the known barcodes, so it will only be present in the unmatched BAM. It would be a new feature to output the barcode based and perhaps qualities for all reads, and in particular those that match a known barcode.

**Comment by yfarjoun** [comment]
@svm-zhang Why do you want to have the barcode in the reads? After all, the reads have been assigned to the barcode that was given for the sample...so you know that the barcodes were "close" to the declared barcode for that sample....if you want to see the assignments, you can look at the output of ExtractIlluminaBarcodes which is the program that does the actual assignments. 

While this feature should be easy to implement, it would be good to know how it will be used, as  an alternative solution might already exist....

**Comment by svm-zhang** [comment]
@yfarjoun @nh13 First thanks for looking into this.

Sample barcodes give sample assignments in a sequencing run. And we particularly designed molecular barcodes to further mark PCR duplicates. When we map reads using BWA for example, we carry index info into the BAM (there is an option in BWA) so that we could use that info to differentiate PCR duplicates. This way avoids the necessity to read and write the BAM for a second time just to add the index part. Plus, many multiplex sequencing runs usually give Fastq files with casava 1.8 style header lines. Now IBCTS gives UMIs in the BAM, while IBCTF gives sample barcodes in the fastqs. I figured why not give both in Fastq files? Sample + molecular barcode both info give the complete index info, right?

Simo

**Comment by nh13** [comment]
I already don’t like the idea of stuffing more information into a FASTQ. Why not just use the BAM? I think this is something Picard does right, and others get wrong. Treat FASTQ as an intermediate and temporary format. But I realize folks may want FASTQs anyhow. I’d propose to wait for the need before implementing the feature for FASTQ output.

**Comment by svm-zhang** [comment]
How about generating sample barcode in BAMs with IBCTS? After all, the complete index has 9bp and not only just 3bp molecular barcodes.

**Comment by svm-zhang** [comment]
Using sample barcodes also as molecular barcodes for example?

**Comment by yfarjoun** [comment]
does that really make sense? after all all the reads from the same sample should have the same barcode, and even if not, they should have a different LB field in the `@RG` tag, which means that mark-duplicates should not treat them as the same. 

I suspect that your needs might come from an incorrect application of the conventions, and thus recommend that you familiarize yourself with them first. If you do and you still find that this is a pressing need, please feel free to re-open this issue and explain the need.
