### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ponomarevsy** [broadinstitute/picard#1105]
Hello,

I am trying to compile picard version 2.17.5 (although, I get the same error in version 2.17.6) with Java version 1.8.0_92. I am getting the following error:

» ./gradlew shadowJar
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/path-to-picard/Picard/picard-2.17.6/picard-tools-2.17.6/build.gradle' line: 20

* What went wrong:
An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version: '1.4.2']
> Failed to apply plugin [id 'org.ajoberstar.grgit']
   > One of setGitDir or setWorkTree must be called.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.674 secs

» which java                                             
/path-to-java/Java/1.8.0_92/bin/java

It also fails if I use an EasyBuild *.eb file to install Picard. I can provide more details, if needed. Please help!

**Comment by ponomarevsy** [comment]
This is on Red Hat Enterprise Linux Server release 7.2 (Maipo).

**Comment by lbergelson** [comment]
Hi @ponomarevsy, the problem is that the build is trying to use some information from the .git directory but can't find it.  Try cloning the repo and then building.  

```
git clone git@github.com:broadinstitute/picard.git
```

**Comment by ponomarevsy** [comment]
Thank you, sir. Doing "git clone https://github.com/broadinstitute/picard.git" instead of downloading the archives fixed it.
