### ISSUE TITLE
Questionable HsMetrics definition on PF_BASES_ALIGNED?

### ISSUE THREAD

**Issue by sharon558** [broadinstitute/picard#1114]
## Documentation request for HsMetrics
Version: picard 2.17.8.

### Description 
Does PF_BASES_ALIGNED include bases from duplicated reads?

The current definition from https://broadinstitute.github.io/picard/picard-metric-definitions.html#HsMetrics is as below:
PF_BASES_ALIGNED | The number of PF unique bases that are aligned to the reference genome with mapping scores > 0.

PF_UQ_BASES_ALIGNED | The number of bases in the PF_UQ_READS_ALIGNED reads. Accounts for clipping and gaps.

But inferred from the HsMetric results on my enrichment data, the PF_BASES_ALIGNED seems to include duplicates bases. Please see the table below.

BAIT_TERRITORY | TARGET_TERRITORY | TOTAL_READS | PF_READS | PF_UNIQUE_READS | PCT_PF_UQ_READS | PF_UQ_READS_ALIGNED | PF_BASES_ALIGNED | PF_UQ_BASES_ALIGNED | ON_BAIT_BASES | NEAR_BAIT_BASES | OFF_BAIT_BASES | ON_TARGET_BASES | PCT_SELECTED_BASES
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
632297 | 523516 | 18002174 | 18002174 | 9371342 | 0.520567 | 8266753 | 1.67E+09 | 8.16E+08 | 1.03E+09 | 3.67E+08 | 2.7E+08 | 3.05E+08 | 0.838223

**Comment by yfarjoun** [comment]
Yes. it does include duplicated bases.

**Comment by sharon558** [comment]
Thanks Yossi for the timely respond!

Just followoing up, does the ON_BAIT_BASES also include bases in duplicated reads?
ON_BAIT_BASES	The number of PF_BASES_ALIGNED that are mapped to the baited regions of the genome.

And is PCT_USABLE_BASES_ON_BAIT calculated as UNIQUE_On_Bait_bases / PF_Bases_with_Dup or UNIQUE_On_Bait_bases / PF_Bases_without_Dup ?

PCT_USABLE_BASES_ON_BAIT	The number of aligned, de-duped, on-bait bases out of the PF bases available.

**Comment by yfarjoun** [comment]
The ON_BAIT_BASES, NEAR_BAIT_BASES and OFF_BAIT_BASES do include duplicate
reads.

USABLE is ON_BAIT_BASES/PF_BASES, both of which include duplicates as well.

I hope this helps.

Yossi.
