### ISSUE TITLE
Regarding of piping (SortSam, SetNmMdAndUqTags) 

### ISSUE THREAD

**Issue by hmkim** [broadinstitute/picard#1116]
### Affected tool(s)
Picard

### Affected version(s)
- [2.17.8]
- [Feb 20, 2018]

### Description 

> 12:43:13.242 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/BiO/Install/picard-2.17.8/picard.jar!/com/intel/gkl/native/libgkl_compression.so
> [Tue Feb 20 12:43:13 KST 2018] SortSam INPUT=/BiO/Project/brandon-genome-analysis/analysis/brandon_wes.aligned.unsorted.duplicates_marked.bam OUTPUT=/dev/stdout SORT_ORDER=coordinate CREATE_INDEX=false CREATE_MD5_FILE=false    VERBOSITY=INFO QUIET=false VALIDATION_STRINGE
> NCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
> [Tue Feb 20 12:43:13 KST 2018] Executing as brandon on Linux 4.8.0-36-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12; Deflater: Intel; Inflater: Intel; Picard version: 2.17.8-SNAPSHOT
> 12:43:13.305 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/BiO/Install/picard-2.17.8/picard.jar!/com/intel/gkl/native/libgkl_compression.so
> [Tue Feb 20 12:43:13 KST 2018] SetNmMdAndUqTags INPUT=/dev/stdin OUTPUT=/BiO/Project/brandon-genome-analysis/analysis/brandon_wes.aligned.duplicate_marked.sorted.bam CREATE_INDEX=true CREATE_MD5_FILE=true REFERENCE_SEQUENCE=/BiO/Project/brandon-genome-analysis/ref/ftp.bro
> adinstitute.org/bundle/hg38/Homo_sapiens_assembly38.fasta    IS_BISULFITE_SEQUENCE=false SET_ONLY_UQ=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false
>  USE_JDK_INFLATER=false
> [Tue Feb 20 12:43:13 KST 2018] Executing as brandon on Linux 4.8.0-36-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12; Deflater: Intel; Inflater: Intel; Picard version: 2.17.8-SNAPSHOT
> INFO    2018-02-20 12:44:15     SortSam Read    10,000,000 records.  Elapsed time: 00:01:02s.  Time for last 10,000,000:   62s.  Last read position: chr2:175,924,030
> INFO    2018-02-20 12:45:16     SortSam Read    20,000,000 records.  Elapsed time: 00:02:02s.  Time for last 10,000,000:   60s.  Last read position: chr3:170,465,041
> INFO    2018-02-20 12:46:24     SortSam Read    30,000,000 records.  Elapsed time: 00:03:11s.  Time for last 10,000,000:   68s.  Last read position: chr13:52,415,440
> INFO    2018-02-20 12:47:32     SortSam Read    40,000,000 records.  Elapsed time: 00:04:19s.  Time for last 10,000,000:   68s.  Last read position: chr7:105,110,958
> INFO    2018-02-20 12:48:36     SortSam Read    50,000,000 records.  Elapsed time: 00:05:23s.  Time for last 10,000,000:   63s.  Last read position: chr20:51,791,992
> INFO    2018-02-20 12:49:34     SortSam Finished reading inputs, merging and writing to output now.
> [Tue Feb 20 12:49:37 KST 2018] picard.sam.SetNmMdAndUqTags done. Elapsed time: 6.40 minutes.
> Runtime.totalMemory()=16464216064
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
> Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; streamed file (filename not available)
>         at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:420)
>         at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
>         at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
>         at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:209)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:829)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:803)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
>         at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
>         at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
>         at java.util.Iterator.forEachRemaining(Iterator.java:116)
>         at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
>         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>         at picard.sam.SetNmMdAndUqTags.doWork(SetNmMdAndUqTags.java:141)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
>         at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
>         at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
> Caused by: java.io.IOException: Illegal seek
>         at java.io.RandomAccessFile.length(Native Method)
>         at htsjdk.samtools.seekablestream.SeekableFileStream.eof(SeekableFileStream.java:58)
>         at htsjdk.samtools.seekablestream.SeekableStream.available(SeekableStream.java:106)
>         at java.io.BufferedInputStream.read(BufferedInputStream.java:353)
>         at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:583)
>         at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:562)
>         at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:525)
>         at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
>         at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
>         at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
>         at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
>         at java.io.DataInputStream.read(DataInputStream.java:149)
>         at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:418)
>         ... 21 more
> [Tue Feb 20 12:49:37 KST 2018] picard.sam.SortSam done. Elapsed time: 6.40 minutes.
> Runtime.totalMemory()=21399863296
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
> Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; streamed file (filename not available)
>         at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:222)
>         at htsjdk.samtools.util.BlockCompressedOutputStream.writeGzipBlock(BlockCompressedOutputStream.java:389)
>         at htsjdk.samtools.util.BlockCompressedOutputStream.deflateBlock(BlockCompressedOutputStream.java:352)
>         at htsjdk.samtools.util.BlockCompressedOutputStream.write(BlockCompressedOutputStream.java:251)
>         at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:220)
>         at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:212)
>         at htsjdk.samtools.BAMRecordCodec.encode(BAMRecordCodec.java:142)
>         at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:143)
>         at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:226)
>         at picard.sam.SortSam.doWork(SortSam.java:167)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
>         at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
>         at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

#### Steps to reproduce
```
#!/bin/sh

set -o pipefail

PICARD_JAR=/BiO/Install/picard-2.17.8/picard.jar

ref_fasta=/BiO/Project/brandon-genome-analysis/ref/ftp.broadinstitute.org/bundle/hg38/Homo_sapiens_assembly38.fasta

input_bam=/BiO/Project/brandon-genome-analysis/analysis/brandon_wes.aligned.unsorted.duplicates_marked.bam
output_bam_basename=/BiO/Project/brandon-genome-analysis/analysis/brandon_wes.aligned.duplicate_marked.sorted

compression_level=5
java_opt_sort="-Xms16G"
java_opt_fix="-Xms16G"


java -Dsamjdk.compression_level=${compression_level} ${java_opt_sort} -jar ${PICARD_JAR} \
  SortSam \
  INPUT=${input_bam} \
  SORT_ORDER="coordinate" \
  CREATE_INDEX=false \
  CREATE_MD5_FILE=false \
  OUTPUT=/dev/stdout \
| \
java -Dsamjdk.compression_level=${compression_level} ${java_opt_fix} -jar ${PICARD_JAR} \
  SetNmMdAndUqTags \
  INPUT=/dev/stdin \
  OUTPUT=${output_bam_basename}.bam \
  CREATE_INDEX=true \
  CREATE_MD5_FILE=true \
  REFERENCE_SEQUENCE=${ref_fasta}

```

#### Expected behavior
Work

#### Actual behavior
Error

**Comment by lbergelson** [comment]
@hmkim Thanks for reporting this.  This was due to a bug in htsjdk, it should be fixed in picard 2.17.10  Please upgrade and try again.

**Comment by hmkim** [comment]
Yes, I used picard 2.17.10 and I solved it.

**Comment by pieterlukasse** [comment]
Are there more details about the bug itself? I'm using version 2.18.15 and I'm getting the same stack trace (expect for some difference in line numbers):
```
INFO    2020-10-13 04:50:51     SortSam Read    10,000,000 records.  Elapsed time: 00:01:32s.  Time for last 10,000,000:   92s.  Last read position: 11:110,697,280
INFO    2020-10-13 04:52:21     SortSam Read    20,000,000 records.  Elapsed time: 00:03:02s.  Time for last 10,000,000:   90s.  Last read position: 3:52,436,449
INFO    2020-10-13 04:53:46     SortSam Read    30,000,000 records.  Elapsed time: 00:04:27s.  Time for last 10,000,000:   85s.  Last read position: 11:94,204,759
INFO    2020-10-13 04:54:02     SortSam Finished reading inputs, merging and writing to output now.
INFO    2020-10-13 04:54:02     SortingCollection       Creating merging iterator from 64 files
INFO    2020-10-13 04:54:34     SortSam Wrote    10,000,000 records from a sorting collection.  Elapsed time: 00:05:14s.  Time for last 10,000,000:   31s.  Last read position: 6:138,197,184
INFO    2020-10-13 04:55:07     SortSam Wrote    20,000,000 records from a sorting collection.  Elapsed time: 00:05:48s.  Time for last 10,000,000:   33s.  Last read position: 12:133,253,057
[Tue Oct 13 04:55:37 UTC 2020] picard.sam.SortSam done. Elapsed time: 6.32 minutes.
Runtime.totalMemory()=33741602816
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; streamed file (filename not available)
        at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:222)
        at htsjdk.samtools.util.BlockCompressedOutputStream.writeGzipBlock(BlockCompressedOutputStream.java:429)
        at htsjdk.samtools.util.BlockCompressedOutputStream.deflateBlock(BlockCompressedOutputStream.java:392)
        at htsjdk.samtools.util.BlockCompressedOutputStream.write(BlockCompressedOutputStream.java:291)
        at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:220)
        at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:212)
        at htsjdk.samtools.BAMRecordCodec.encode(BAMRecordCodec.java:164)
        at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:143)
        at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:224)
        at picard.sam.SortSam.doWork(SortSam.java:167)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardComma
```
