### ISSUE TITLE
which sort mode to apply before MarkDuplicates

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#1119]
### The MarkDuplicates manpage says

> The program can take either coordinate-sorted or query-sorted inputs, however the behavior is slightly different.  When
> the input is coordinate-sorted, unmapped mates of mapped records and supplementary/secondary alignments are not marked
> as duplicates.  However, when the input is query-sorted **(actually query-grouped)**, then unmapped mates and
> secondary/supplementary reads are not excluded from the duplication test and can be marked as duplicate reads.

which option below is 'query-grouped' ? 'queryname' / 'reads' / 'duplicate'?

Q: Which order should I best use to properly mark the reads in pairs and unpaired as duplicates for optimal variant analysis with GATK?

### The SortSam I reads

> SO=SortOrder                  Sort order of output file.   Required. Possible values: {
>                               **queryname** (Sorts according to the readname. This will place read-pairs and other derived
>                               **reads** (secondary and supplementary) adjacent to each other. Note that the readnames are
>                               compared lexicographically, even though they may include numbers. In paired reads, Read1
>                               sorts before Read2.)
>                               **coordinate** (Sorts primarily according to the SEQ and POS fields of the record. The
>                               sequence will sorted according to the order in the sequence dictionary, taken from from
>                               the header of the file. Within each reference sequence, the reads are sorted by the
>                               position. Unmapped reads whose mates are mapped will be placed near their mates. Unmapped
>                               read-pairs are placed after all the mapped reads and their mates.)
>                               **duplicate** (Sorts the reads so that duplicates reads are adjacent. Required that the
>                               mate-cigar (MC) tag is present. The resulting will be sorted by library, unclipped 5-prime
>                               position, orientation, and mate's unclipped 5-prime position.)
>                               } 

Thanks in advance

**Comment by yfarjoun** [comment]
queryname is the option you want if you want the secondary and
supplementary reads to be duplicate marked as well as the primary reads.
However, for most variant-calling programs, this doesn't matter, as they
ignore these reads irrespective of the duplicate flag.

Y.

**Comment by splaisan** [comment]
Thanks Yossi, it is clear now. :-)
