### ISSUE TITLE
query on AddOrReplaceReadGroups

### ISSUE THREAD

**Issue by prasundutta87** [broadinstitute/picard#1122]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
AddOrReplaceReadGroups

### Affected version(s)
Picard version: 2.14.0-SNAPSHOT

### Description 
What does */* mean in the example below:
INFO	2018-02-19 04:59:09	AddOrReplaceReadGroups	Processed   980,000,000 records.  Elapsed time: 02:50:53s.  Time for last 1,000,000:   11s.  Last read position: */*
INFO	2018-02-19 04:59:19	AddOrReplaceReadGroups	Processed   981,000,000 records.  Elapsed time: 02:51:03s.  Time for last 1,000,000:    9s.  Last read position: */*

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by yfarjoun** [comment]
Unmapped.

**Comment by prasundutta87** [comment]
Thanks..
