### ISSUE TITLE
CollectRnaSeqMetrics - no coding reads found

### ISSUE THREAD

**Issue by prxrsp** [broadinstitute/picard#1123]
Hello, 

This is my code: 

`java -jar picard-2.8.0.jar CollectRnaSeqMetrics \
I= bam/Aligned.sortedByCoord.out.bam \
O= output.RNA_Metrics \
REF_FLAT= bam/refFlat.txt \
STRAND=NONE \
RIBOSOMAL_INTERVALS= bam/hg19.rRNA.interval_list.sam.txt
`

Almost all of my aligned reads are interpreted as intergenic. 
I have aligned to hg19 and my refFlat.txt file is also hg19 ([http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/refFlat.txt.gz
]). 

Can you please help?

Thanks!

**Comment by yfarjoun** [comment]
Please search the GATK forum for answers to this question. If you cannot find a solution, then post your question to the GATK forum at https://gatkforums.broadinstitute.org/gatk/discussions.
