### ISSUE TITLE
Trouble Running MarkDuplicates on bam  file

### ISSUE THREAD

**Issue by garrett-parker** [broadinstitute/picard#1128]
### Affected tool(s)
MarkDuplicates and REMOVE_DUPLICATES option

### Affected version(s)
Version 2.17.11

### Description 
I am trying to run the REMOVE_DUPLCATES option on a bam file I have created however I haven't been able to run MarkDuplicates despite trying to follow the instructions

#### Steps to reproduce
I entered the following command
$ java -jar $PICARD MarkDuplicates \ INPUT=reads.simulated.bam \ REMOVE_DUPLICATES=true \ OUTPUT=reads.simulated.picard.out.bam \ M=picard.duplication.metric.txt

#### Expected behavior
I want it to output a bam file without duplicates

#### Actual behavior
Received an error 

ERROR: Unrecognized option:  INPUT

What am I doing wrong?

Thanks

**Comment by yfarjoun** [comment]
This appears to be a user question (as opposed to a bug report , feature request, or documentation request)

Please search the GATK forum for answers to this question. If you cannot find a solution, then post your question to the GATK forum at https://gatkforums.broadinstitute.org/gatk/discussions.
