### ISSUE TITLE
Picard MergeSamFiles Killed java -jar error

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#1129]
Any idea what is causing this user's error?

---
@shlee 
Thank you for your answer. The command is MergeSamFiles

[Wed Feb 28 12:35:51 PST 2018] MergeSamFiles INPUT=[/home/bemmo/projects/rrg-jdrouin/bemmo/IAD/results/bwa/005.SS6.AB-Hu-Ex-A107/005.SS6.AB-Hu-Ex-A107.sam, /home/bemmo/projects/rrg-jdrouin/bemmo/IAD/results/bwa/006.SS6.AB-Hu-Ex-A107/006.SS6.AB-Hu-Ex-A107.sam, /home/bemmo/projects/rrg-jdrouin/bemmo/IAD/results/bwa/007.SS6.AB-Hu-Ex-A107/007.SS6.AB-Hu-Ex-A107.sam] OUTPUT=/home/bemmo/projects/rrg-jdrouin/bemmo/IAD/results/variants/AB-Hu-Ex-A107/AB-Hu-Ex-A107.bam USE_JDK_DEFLATER=true USE_JDK_INFLATER=true    SORT_ORDER=coordinate ASSUME_SORTED=false MERGE_SEQUENCE_DICTIONARIES=false USE_THREADING=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Feb 28 12:35:51 PST 2018] Executing as bemmo@cdr920.int.cedar.computecanada.ca on Linux 3.10.0-693.11.6.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Deflater: Jdk; Inflater: Jdk; Picard version: 2.17.3-SNAPSHOT
INFO    2018-02-28 12:35:51     MergeSamFiles   Sorting input files using temp directory [/tmp/bemmo]
INFO    2018-02-28 12:35:58     MergeSamFiles   Processed     1,000,000 records.  Elapsed time: 00:00:06s.  Time for last 1,000,000:    6s.  Last read position: chr15:26,889,500
INFO    2018-02-28 12:36:06     MergeSamFiles   Processed     2,000,000 records.  Elapsed time: 00:00:14s.  Time for last 1,000,000:    7s.  Last read position: chr6:35,231,712
INFO    2018-02-28 12:36:13     MergeSamFiles   Processed     3,000,000 records.  Elapsed time: 00:00:21s.  Time for last 1,000,000:    6s.  Last read position: chr3:47,622,264
INFO    2018-02-28 12:36:19     MergeSamFiles   Processed     4,000,000 records.  Elapsed time: 00:00:27s.  Time for last 1,000,000:    6s.  Last read position: chr7:15,613,034
INFO    2018-02-28 12:36:26     MergeSamFiles   Processed     5,000,000 records.  Elapsed time: 00:00:34s.  Time for last 1,000,000:    6s.  Last read position: chr17:38,490,029
INFO    2018-02-28 12:36:33     MergeSamFiles   Processed     6,000,000 records.  Elapsed time: 00:00:41s.  Time for last 1,000,000:    7s.  Last read position: chr15:81,358,297
INFO    2018-02-28 12:36:40     MergeSamFiles   Processed     7,000,000 records.  Elapsed time: 00:00:48s.  Time for last 1,000,000:    7s.  Last read position: chr1:1,228,522
INFO    2018-02-28 12:36:47     MergeSamFiles   Processed     8,000,000 records.  Elapsed time: 00:00:55s.  Time for last 1,000,000:    7s.  Last read position: chr6:87,589,803
INFO    2018-02-28 12:36:55     MergeSamFiles   Processed     9,000,000 records.  Elapsed time: 00:01:03s.  Time for last 1,000,000:    7s.  Last read position: chr1:42,610,992
INFO    2018-02-28 12:37:02     MergeSamFiles   Processed    10,000,000 records.  Elapsed time: 00:01:10s.  Time for last 1,000,000:    6s.  Last read position: chr1:235,728,122
/var/spool/slurmd/job5614122/slurm_script: line 27: 42247 Killed                  java -jar /cvmfs/soft.mugqic/CentOS6/software/picard/picard-2.17.3/picard.jar MergeSamFiles $file O=/home/bemmo/projects/rrg-jdrouin/bemmo/IAD/results/variants/AB-Hu-Ex-A107/AB-Hu-Ex-A107.bam USE_JDK_DEFLATER=true USE_JDK_INFLATER=true
12:37:10.830 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/cvmfs/soft.mugqic/CentOS6/software/picard/picard-2.17.3/picard.jar!/com/intel/gkl/native/libgkl_compression.so

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/46672#Comment_46672

**Comment by sooheelee** [comment]
@lbergelson @yfarjoun?

**Comment by lbergelson** [comment]
The only error I see is
```
/var/spool/slurmd/job5614122/slurm_script: line 27: 42247 Killed java -jar 
```

which implies that slurm killed their job for some reason.  Maybe it's running over the memory requirements?  Seems like a slurm / cluster configuration issue and not necessarily a picard one.

**Comment by sooheelee** [comment]
Thanks for the lightning response. I just asked the user what kind of memory are they giving the tool.

**Comment by sooheelee** [comment]
Another user has enlightened us with:

> This is a memory issue of slurm your job exeeds the default settings
