### ISSUE TITLE
picard 2.17.11-snapshot LiftoverVcf, java 9.0.4: nullPointerException in doWork

### ISSUE THREAD

**Issue by paul-shannon** [broadinstitute/picard#1136]
macos 10.12.3

Here's the full trace.  Any suggestions?
Thanks!

 - Paul

java -jar picard.jar LiftoverVcf \
          I=/Users/paul/s/examples/vcf/SCH_11923_B01_GRM_WGS_2017-04-27_5.recalibrated_variants.vcf.gz \
          O=lifted_over.vcf \
         CHAIN=hg19ToHg38.over.chain \
         REJECT=rejected_variants.vcf \
         R=hg38.fa
13:58:08.350 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/paul/s/tools/picard/picard.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Mon Mar 12 13:58:08 PDT 2018] LiftoverVcf INPUT=/Users/paul/s/examples/vcf/SCH_11923_B01_GRM_WGS_2017-04-27_5.recalibrated_variants.vcf.gz OUTPUT=lifted_over.vcf CHAIN=hg19ToHg38.over.chain REJECT=rejected_variants.vcf REFERENCE_SEQUENCE=hg38.fa    WARN_ON_MISSING_CONTIG=false LOG_FAILED_INTERVALS=true WRITE_ORIGINAL_POSITION=false LIFTOVER_MIN_MATCH=1.0 ALLOW_MISSING_FIELDS_IN_HEADER=false TAGS_TO_REVERSE=[AF] TAGS_TO_DROP=[MAX_AF] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Mar 12 13:58:08 PDT 2018] Executing as paul@riptide.local on Mac OS X 10.12.3 x86_64; Java HotSpot(TM) 64-Bit Server VM 9.0.4+11; Deflater: Intel; Inflater: Intel; Picard version: 2.17.11-SNAPSHOT
INFO	2018-03-12 13:58:08	LiftoverVcf	Loading up the target reference genome.
[Mon Mar 12 13:58:08 PDT 2018] picard.vcf.LiftoverVcf done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=268435456
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:271)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

**Comment by merceneryinbox** [comment]
Hello, Paul! In my case the cause was - absence of .dict file witch must be togever with the refered fasta file. May be it's your case too.

**Comment by paul-shannon** [comment]
Thank you, Oleg!  Yes - I have forgotten to generate the .dict file.

Having now done so, LiftoverVcf runs to completion, but produces very odd results, as you can see from these file sizes:

input:        7575370075 Mar 12 13:39 ADNI.808_indiv.minGQ_21.pass.ADNI_ID.chr5.vcf.gz
chain:            606773 Mar 12 13:12 hg19ToHg38.over.chain
dict:              52178 Mar 12 14:52 hg38.dict
fasta:        3273481150 Mar 12 13:27 hg38.fa
out:               57937 Mar 12 14:55 lifted_over.vcf
out index:         14131 Mar 12 14:55 lifted_over.vcf.idx
rejected:    17875944558 Mar 12 14:55 rejected_variants.vcf

This suggests that 0.0008% of the hg19 variants were lifted over.  And the rejects are 10G greater than the input.
Maybe there is something else dumb I am doing?   Here’s my command:

java -jar picard.jar LiftoverVcf \
          I=/Users/paul/s/examples/vcf/SCH_11923_B01_GRM_WGS_2017-04-27_5.recalibrated_variants.vcf.gz \
          O=lifted_over.vcf \
          CHAIN=hg19ToHg38.over.chain \
          REJECT=rejected_variants.vcf \
          R=hg38.fa

**Comment by yfarjoun** [comment]
Please check that your sequence names match up exactly wrt the chr part.
Look in the chain and your input file and target dict.

**Comment by paul-shannon** [comment]
You are right, Yossi.  Thank you.

The chain file, and the .dict file, both use the “chrN” format; my vcf skips “chr”.  

Can you recommend a quick fix?

 - Paul

**Comment by yfarjoun** [comment]
sed/chr//

?

**Comment by yfarjoun** [comment]
I mean

sed 's/chr//'
