### ISSUE TITLE
Error in MergeBamAlignment 

### ISSUE THREAD

**Issue by alrafaykhan** [broadinstitute/picard#1159]
`sudo java -jar ../picard/build/libs/picard.jar MergeBamAlignment ALIGNED= IonXpress_001.bam UNMAPPED=IonXpress_001_rawlib.basecaller.bam O=IonXpressMerge_alignments.bam R=../reference/hg19/hg19.fasta
`

> 22:13:45.558 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/rafay/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.so
> [Tue Apr 17 22:13:58 PKT 2018] MergeBamAlignment UNMAPPED_BAM=IonXpress_001_rawlib.basecaller.bam ALIGNED_BAM=[IonXpress_001.bam] OUTPUT=IonXpressMerge_alignments.bam REFERENCE_SEQUENCE=../reference/hg19/hg19.fasta    ADD_PG_TAG_TO_READS=true PAIRED_RUN=true CLIP_ADAPTERS=true IS_BISULFITE_SEQUENCE=false ALIGNED_READS_ONLY=false MAX_INSERTIONS_OR_DELETIONS=1 ATTRIBUTES_TO_REVERSE=[OQ, U2] ATTRIBUTES_TO_REVERSE_COMPLEMENT=[E2, SQ] READ1_TRIM=0 READ2_TRIM=0 ALIGNER_PROPER_PAIR_FLAGS=false SORT_ORDER=coordinate PRIMARY_ALIGNMENT_STRATEGY=BestMapq CLIP_OVERLAPPING_READS=true INCLUDE_SECONDARY_ALIGNMENTS=true ADD_MATE_CIGAR=true UNMAP_CONTAMINANT_READS=false MIN_UNCLIPPED_BASES=32 MATCHING_DICTIONARY_TAGS=[M5, LN] UNMAPPED_READ_STRATEGY=DO_NOT_CHANGE VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
> [Tue Apr 17 22:13:58 PKT 2018] Executing as root@rafaymatics on Linux 4.13.0-37-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: 2.17.11-5-geed3ea5-SNAPSHOT
> INFO    2018-04-17 22:13:58     SamAlignmentMerger      Processing SAM file(s): [IonXpress_001.bam]
> [Tue Apr 17 22:13:59 PKT 2018] picard.sam.MergeBamAlignment done. Elapsed time: 0.23 minutes.
> Runtime.totalMemory()=32440320
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
> Exception in thread "main" htsjdk.samtools.SAMException: Could not find dictionary next to reference file file:///home/rafay/gatkTest/../reference/hg19/hg19.fasta
>         at htsjdk.variant.utils.SAMSequenceDictionaryExtractor$TYPE$1.extractDictionary(SAMSequenceDictionaryExtractor.java:55)
>         at htsjdk.variant.utils.SAMSequenceDictionaryExtractor.extractDictionary(SAMSequenceDictionaryExtractor.java:149)
>         at picard.sam.SamAlignmentMerger.getDictionaryForMergedBam(SamAlignmentMerger.java:192)
>         at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:363)
>         at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:181)
>         at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:356)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
>         at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
>         at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

**Comment by yfarjoun** [comment]
Hi! 
Thanks for using Picard. 
Github issues are intended for developers, rather than users. 

For user problems we ask that you please look for a solution in the forum first: https://gatkforums.broadinstitute.org/gatk/post/question/gatk-support-forum 

If you cannot find the answer, please post your question there so it can be answered properly and be of assistance to future users!

Thanks again!

**Comment by Trandamere** [comment]
Hello:
      I made the same mistake. How did you solve it

**Comment by YuriPPAN** [comment]
> Hello: I made the same mistake. How did you solve it

I also made the same mistake. How did you solve it？

**Comment by AritaZ-hang** [comment]
> > Hello: I made the same mistake. How did you solve it
> 
> I also made the same mistake. How did you solve it？

I found a tutorial https://gatk.broadinstitute.org/hc/en-us/articles/360037422891-CreateSequenceDictionary-Picard perhaps it could solve the problem
