### ISSUE TITLE
running FastqToSam the ouput file is 0 byte

### ISSUE THREAD

**Issue by elainebblythe** [broadinstitute/picard#1161]
my command as follows:
```
java -jar ~/tools/picard/picard-2.8.2.jar FastqToSam \
     F1=../Q30_seq/read1.fastq \
     F2=../Q30_seq/read2.fastq \
     O=fastq_to_bam.bam \
     SM=S0_L004
```
the log file is no error,but the output is 0 byte.

[Tue Apr 24 16:38:12 CST 2018] picard.sam.FastqToSam FASTQ=../Q30_seq/read1.fastq FASTQ2=../Q30_seq/read2.fastq OUTPUT=fastq_to_bam.bam SAMPLE_NAME=S0_L004    USE_SEQUENTIAL_FASTQS=false READ_GROUP_NAME=A SORT_ORDER=queryname MIN_Q=0 MAX_Q=93 STRIP_UNPAIRED_MATE_NUMBER=false ALLOW_AND_IGNORE_EMPTY_LINES=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Tue Apr 24 16:38:12 CST 2018] Executing as lijie@node6 on Linux 2.6.32-504.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_77-b03; Picard version: 2.8.2-SNAPSHOT
INFO    2018-04-24 16:38:12     FastqToSam      Auto-detected quality format as: Standard.
INFO    2018-04-24 16:38:20     FastqToSam      Processed     1,000,000 records.  Elapsed time: 00:00:07s.  Time for last 1,000,000:    7s.  Last read position: * / *
..........
..........

**Comment by yfarjoun** [comment]
Thanks for the report. 

I'm not sure what the problem is. could you ask on the user forum first, as I suspect that this is a user problem, not a bug in the code.

https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum
