### ISSUE TITLE
Request info: can't find sources for google-cloud-nio-GATK4-custom-patch

### ISSUE THREAD

**Issue by osallou** [broadinstitute/picard#1164]
hi,
I can't find the sources related to org.broadinstitute:google-cloud-nio-GATK4-custom-patch:0.20.4-alpha-GCS-RETRY-FIX:shaded.
The binary jar is available in maven repo etc... but I can't find related sources.

Where are the sources for this specific package?

I am a Debian developer and was looking at upgrading picard in Debian, we need to build from source with all dependencies.
Thanks

**Comment by lbergelson** [comment]
Hi @osallou. That is understandably confusing.  The source jar is available from [central](http://search.maven.org/remotecontent?filepath=org/broadinstitute/google-cloud-nio-GATK4-custom-patch/0.20.4-alpha-GCS-RETRY-FIX/google-cloud-nio-GATK4-custom-patch-0.20.4-alpha-GCS-RETRY-FIX-sources.jar) as well, but it's obviously hard to build just from the sources.  

You can find it on github from [https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes](https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes).   We should really publish that some where more obvious.  It was meant as a short term workaround to a problem that turned into a long term workaround.

**Comment by osallou** [comment]
Will have a look, thanks.

Le mer. 25 avr. 2018 19:54, Louis Bergelson <notifications@github.com> a
écrit :
