### ISSUE TITLE
Help request on unit tests failing on Debian

### ISSUE THREAD

**Issue by osallou** [broadinstitute/picard#1166]
### Affected tool(s)

build from source, error during unit tests

### Affected version(s)

Latest release

### Description 

Hi,
while packaging for Debian, I face an issue with a test: testCbclConvert
While other tests 'till this one are ok, the unit tests are blocked on this one.
This may be related to other dependencies (gkl, etc..) but I found no way to see what is the problem.

#### Steps to reproduce

gradle unit tests (in debian, so code is patches for debian packaging)

gradle remains blocked on test testCbclConvert  and never exit (not even as failure).
Here is related log. We see an error (Exception: picard.PicardException), but test do not fail and do not write test result.

    Running Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest)
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: WARNING	2018-05-02 05:30:33	IlluminaBasecallsToFastq	ADAPTERS_TO_CHECK is not used
    
    Gradle suite > Gradle test > picard.illumina.IlluminaBasecallsToFastqTest.testCbclConvert STANDARD_ERROR
    WARNING	2018-05-02 05:30:33	IlluminaBasecallsToFastq	ADAPTERS_TO_CHECK is not used
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: 05:30:33.169 WARN  NativeLibraryLoader - OVERRIDE DEFAULT: Loading libgkl_compression.so from /usr/lib/gkl
    
    05:30:33.169 WARN  NativeLibraryLoader - OVERRIDE DEFAULT: Loading libgkl_compression.so from /usr/lib/gkl
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: 05:30:33.170 WARN  NativeLibraryLoader - LD_LIBRARY_PATH = null
    
    05:30:33.170 WARN  NativeLibraryLoader - LD_LIBRARY_PATH = null
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: 05:30:33.170 WARN  NativeLibraryLoader - OVERRIDE DEFAULT: Loading libgkl_compression.so from /usr/lib/gkl
    
    05:30:33.170 WARN  NativeLibraryLoader - OVERRIDE DEFAULT: Loading libgkl_compression.so from /usr/lib/gkl
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: 05:30:33.170 WARN  NativeLibraryLoader - LD_LIBRARY_PATH = null
    
    05:30:33.170 WARN  NativeLibraryLoader - LD_LIBRARY_PATH = null
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: [Wed May 02 05:30:33 UTC 2018] IlluminaBasecallsToFastq  --BASECALLS_DIR testdata/picard/illumina/151T8B8B151T_cbcl/Data/Intensities/BaseCalls --LANE 1 --RUN_BARCODE HiMom --MACHINE_NAME machine1 --FLOWCELL_BARCODE abcdeACXX --READ_STRUCTURE 151T8B8B151T --MULTIPLEX_PARAMS /tmp/dualBarcode.12168467984882276290.dir/barcode_double.params --MAX_READS_IN_RAM_PER_TILE 100  --NUM_PROCESSORS 0 --APPLY_EAMSS_FILTER true --FORCE_GC true --MINIMUM_QUALITY 2 --INCLUDE_NON_PF_READS true --IGNORE_UNEXPECTED_BARCODES false --READ_NAME_FORMAT CASAVA_1_8 --COMPRESS_OUTPUTS false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 2279706 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
    
    [Wed May 02 05:30:33 UTC 2018] IlluminaBasecallsToFastq  --BASECALLS_DIR testdata/picard/illumina/151T8B8B151T_cbcl/Data/Intensities/BaseCalls --LANE 1 --RUN_BARCODE HiMom --MACHINE_NAME machine1 --FLOWCELL_BARCODE abcdeACXX --READ_STRUCTURE 151T8B8B151T --MULTIPLEX_PARAMS /tmp/dualBarcode.12168467984882276290.dir/barcode_double.params --MAX_READS_IN_RAM_PER_TILE 100  --NUM_PROCESSORS 0 --APPLY_EAMSS_FILTER true --FORCE_GC true --MINIMUM_QUALITY 2 --INCLUDE_NON_PF_READS true --IGNORE_UNEXPECTED_BARCODES false --READ_NAME_FORMAT CASAVA_1_8 --COMPRESS_OUTPUTS false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 2279706 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: [Wed May 02 05:30:33 UTC 2018] Executing as debian@538c1dcffd55 on Linux 4.4.0-121-generic amd64; OpenJDK 64-Bit Server VM 10.0.1+10-Debian-3; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:null
    
    [Wed May 02 05:30:33 UTC 2018] Executing as debian@538c1dcffd55 on Linux 4.4.0-121-generic amd64; OpenJDK 64-Bit Server VM 10.0.1+10-Debian-3; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:null
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: INFO	2018-05-02 05:30:33	IlluminaBasecallsToFastq	READ STRUCTURE IS 151T8B8B151T
    INFO	2018-05-02 05:30:33	IlluminaBasecallsToFastq	READ STRUCTURE IS 151T8B8B151T
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: INFO	2018-05-02 05:30:33	CbclReader	Processing tile 1101
    INFO	2018-05-02 05:30:33	CbclReader	Processing tile 1101
    Test: Test method testCbclConvert(picard.illumina.IlluminaBasecallsToFastqTest) produced standard out/err: INFO	2018-05-02 05:30:33	CbclReader	Processing tile 1102
    INFO	2018-05-02 05:30:33	CbclReader	Processing tile 1102
    
    Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-299-thread-2"
    Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-299-thread-1"

**Comment by jacarey** [comment]
Huh interesting.. works fine for me in Intellij.

```WARNING	2018-05-02 11:26:44	IlluminaBasecallsToFastq	ADAPTERS_TO_CHECK is not used
11:26:44.312 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/jcarey/.gradle/caches/modules-2/files-2.1/com.intel.gkl/gkl/0.8.2/7f75ab95af10c2126a7570b81a4331b48bff39c/gkl-0.8.2.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed May 02 11:26:44 EDT 2018] IlluminaBasecallsToFastq BASECALLS_DIR=testdata/picard/illumina/151T8B8B151T_cbcl/Data/Intensities/BaseCalls LANE=1 RUN_BARCODE=HiMom MACHINE_NAME=machine1 FLOWCELL_BARCODE=abcdeACXX READ_STRUCTURE=151T8B8B151T MULTIPLEX_PARAMS=/tmp/dualBarcode.4355619317634498838.dir/barcode_double.params MAX_READS_IN_RAM_PER_TILE=100    NUM_PROCESSORS=0 APPLY_EAMSS_FILTER=true FORCE_GC=true MINIMUM_QUALITY=2 INCLUDE_NON_PF_READS=true IGNORE_UNEXPECTED_BARCODES=false READ_NAME_FORMAT=CASAVA_1_8 COMPRESS_OUTPUTS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed May 02 11:26:44 EDT 2018] Executing as jcarey@work on Linux 4.13.0-39-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_162-8u162-b12-0ubuntu0.17.10.2-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: null
INFO	2018-05-02 11:26:44	IlluminaBasecallsToFastq	READ STRUCTURE IS 151T8B8B151T
INFO	2018-05-02 11:26:44	CbclReader	Processing tile 1102
INFO	2018-05-02 11:26:44	CbclReader	Processing tile 1101
INFO	2018-05-02 11:26:44	NewIlluminaBasecallsConverter	Finished processing tile 1102
INFO	2018-05-02 11:26:44	NewIlluminaBasecallsConverter	Finished processing tile 1101
INFO	2018-05-02 11:26:49	NewIlluminaBasecallsConverter	Writing out tile 1101
INFO	2018-05-02 11:26:49	NewIlluminaBasecallsConverter	Writing out tile 1102
[Wed May 02 11:26:49 EDT 2018] picard.illumina.IlluminaBasecallsToFastq done. Elapsed time: 0.09 minutes.
Runtime.totalMemory()=637009920```

I'll need to get a test case set up that reliably fails so I can look at it.

**Comment by jacarey** [comment]
Additionally this freeze should have been fixed with https://github.com/broadinstitute/picard/commit/4c2e22a9c591b8b7e8a427d33478e43d45c113b5

Where any inner unhandled exceptions should bubble up and kill the completion executor.

**Comment by osallou** [comment]
I see thid fix was commited one week ago, so this is not the release we
have (not master).
I gonna test with the patch locally so see if it stops the thread and have
logs.

Thanks

**Comment by osallou** [comment]
I confirm I have no issue wiith the patch, thanks

Le mer. 2 mai 2018 à 19:28, olivier sallou <olivier.sallou@gmail.com> a
écrit :

> I see thid fix was commited one week ago, so this is not the release we
> have (not master).
> I gonna test with the patch locally so see if it stops the thread and have
> logs.
>
> Thanks
>
>
