### ISSUE TITLE
CreateSequenceDictionary command line incompatibile with older versions

### ISSUE THREAD

**Issue by stevendavis** [broadinstitute/picard#1168]
### Affected tool(s)
CreateSequenceDictionary 

### Affected version(s)
- [x] Latest public release version [2.18.4]
- [ ] Latest development/master branch as of [date of test?]

### Description 
The command line arguments have changed in a way that is not backwards compatible.

Picard version 2.8.3 accepted this command line:
	`java -jar picard.jar CreateSequenceDictionary R=reference.fasta O=reference.dict`

Picard version 2.18.4 produces this error message:
	ERROR: Unrecognized option: O

I can change my script to detect the version and execute Picard with different command line arguments depending on the version.  _**May I ask which Picard release introduced this change?**_

#### Documentation
The documentation still describes the O= command line argument:
http://broadinstitute.github.io/picard/command-line-overview.html#CreateSequenceDictionary

----

**Comment by yfarjoun** [comment]
can't reproduce. seems to work fine for me. Check for typos in your invocation.

**Comment by stevendavis** [comment]
@yfarjoun thank you for the prompt reply.

Indeed, my command line is a bit different and perhaps non-standard.  I'm writing a script that will be used by other people in other organizations.  In general, I don't know where the picard.jar file is located on someone else's file system.  Instead of using the java -jar command line option, I request users to set the $CLASSPATH and execute picard like this:

java picard.cmdline.PicardCommandLine CreateSequenceDictionary R=reference.fasta O=reference.dict

That worked fine in older versions, but not anymore.  This invocation results in different command line parsing now. Maybe there a better way to execute picard when I don't know the location of the jar file.  What do you recommend?

**Comment by tfenne** [comment]
@stevendavis You might suggest users install picard via conda/bioconda?  That also installs a shell script to invoke Picard, and adds it to the user's path.

**Comment by cmnbroad** [comment]
@stevendavis Do you get this error when you specify the 2.18.4 jar directly ? Can you post a full input command and the corresponding output ? Thx.
