### ISSUE TITLE
MergeableMetricsBase shouldn't require or allow static fields to be annotated

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/picard#1172]
### Affected tool(s)
MergeableMetricsBase

### Affected version(s)
- [x] Latest public release version 2.18.4
- [x] Latest development/master branch as of 5/18/18

### Description 
`MetricsFiles` that implement `MergeableMetricsBase` require all fields to be annotated with a merge strategy.  This should not include `static` fields.   It's easy to work around by specifying `@NoMergingKeepsValue` but it would be better to not have to.  It seems like it should instead require that they NOT be annotated, because combining static fields is nonsensical.

#### Steps to reproduce
1. add a static final constant to a subclass of MergeableMetrics
2. run a tool that tries to merge those metrics

#### Expected behavior
static fields are ignored during merging

#### Actual behavior
crash with `IllegalStateException` on line 151 of (MergeableMetricsBase)[https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/MergeableMetricBase.java]

### Other even more minor annoyance:
  The error message that's reported lists several options for annotating but not the one you actually want.  "All fields of this class must be annotated with @MergeByAdding, @NoMergingIsDerived, or @MergeByAssertEquals"

**Comment by yfarjoun** [comment]
yes...this seems like it should be possible to do. are you fixing this, or just stating it's broken state? can you provide a failing test?

**Comment by yfarjoun** [comment]
That said...static member in a metrics class? can you provide a usecase?

**Comment by yfarjoun** [comment]
nm. PR submitted in #1173 ...

**Comment by lbergelson** [comment]
@yfarjoun Thanks for the fix!  We specifically ran into this issue when making a metric class serialiazable.  This requires adding private constant called serialVersionUID.  It's weird to have to annotate how to merge constants...  I'm not sure if there's a general use for non-constant static members in a metrics class, it seems like a weird bad idea, but it seems even worse to try to merge them if there there.

**Comment by yfarjoun** [comment]
got it. Thanks for the explanation!
