### ISSUE TITLE
Picard CollectRnaSeqMetrics inconsistently generating histogram

### ISSUE THREAD

**Issue by brigranger** [broadinstitute/picard#1177]
### Affected tool(s)
CollectRnaSeqMetrics

### Affected version(s)
Picard version: 2.10.10, possibly others?

### Description 
I'm running bam files through a pipeline that involves Picard CollectRnaSeqMetrics and most of the time it generates a "histogram" section:

[ACC7_Plate3_H2_qc.rna_metrics.txt](https://github.com/broadinstitute/picard/files/2040734/ACC7_Plate3_H2_qc.rna_metrics.txt)

Sometimes however, using the same pipeline on a different input bam, it doesn't:
[ACC7_Plate3_H1_qc.rna_metrics.txt](https://github.com/broadinstitute/picard/files/2040730/ACC7_Plate3_H1_qc.rna_metrics.txt)

#### Steps to reproduce
I'm running this command:
```
java -Xmx3g -jar /usr/picard/picard.jar CollectRnaSeqMetrics \
  VALIDATION_STRINGENCY=SILENT \
  METRIC_ACCUMULATION_LEVEL=ALL_READS \
  INPUT="/cromwell_root/fc-7df41855-f366-4dae-9ca1-a12a225452c8/66426b2c-dfaf-4687-952b-54a6bcc15715/SmartSeq2SingleCell/42f1521e-f54c-434b-a32d-ec379b783e37/call-qc/RunHisat2Pipeline/e9460144-04b0-4193-a56a-63b4fae3cbd6/call-Hisat2/attempt-2/ACC7_Plate3_H1_qc.bam" \
  OUTPUT="ACC7_Plate3_H1_qc.rna_metrics.txt" \
  REF_FLAT="/cromwell_root/broad-references/hg38/v0/GRCh38_gencode.v27.refFlat.txt" \
  RIBOSOMAL_INTERVALS="/cromwell_root/broad-references/hg38/v0/gencode.v27.rRNA.interval_list" \
  STRAND_SPECIFICITY=NONE \
  CHART_OUTPUT="ACC7_Plate3_H1_qc.rna.coverage.pdf"
```

I can provide the bam, as it's very small, I suspect this, and possibly poor quality are ultimately causing this issue.

[example_bam.tar.gz](https://github.com/broadinstitute/picard/files/2040754/example_bam.tar.gz)

#### Expected behavior
I expect it to generate the second part of the rna_metrics.txt file titled "histogram", even if they're all zeros, though I'm not sure that would be the correct interpretation.

#### Actual behavior
This histogram section is missing.

**Comment by yfarjoun** [comment]
can you run again with a smaller value for MINIMUM_LENGTH? it is currently at 500 and I'm wondering if you're somehow only hitting really small transcripts which do not count towards the coverage. An empty histogram is not emitted...that's the standard behaviour...a bit confusing, I agree.

**Comment by brigranger** [comment]
Thanks @yfarjoun I'll give that a try and see if that changes anything. Do you have a suggestion for minimum length?

**Comment by yfarjoun** [comment]
Just to see if it changes anything, can you try with 1?

**Comment by brigranger** [comment]
No change other than the header.

**Comment by yfarjoun** [comment]
confirmed with user that this happens when there is no data to put into the histogram....
