### ISSUE TITLE
CollectSequencingArtifactMetrics PreAdapterDetailMetrics question

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#1179]
A researcher is asking for details beyond that given on the Metrics explanation page on how PreAdapterDetailMetrics calculates `PRO_REF_BASES`, `PRO_ALT_BASES`, `CON_REF_BASES`, `CON_ALT_BASES`.

---
Hi Shlee,

Thanks for pointing the FilterByOrientationBias tools to me!
I'm not saying anything wrong with picard PreAdapterDetailMetrics. I'm just trying to understand the mechanism of how it is defining PRO_REF_BASES, PRO_ALT_BASES, CON_REF_BASES, CON_ALT_BASES, that two reverse complementary context have opposite number of bases for pro and con.

Thanks, 
Wen 

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/49085#Comment_49085

**Comment by sooheelee** [comment]
@yfarjoun @meganshand, I see you've updated this tool/test recently. Would one of you be able to answer, please?

**Comment by meganshand** [comment]
@sooheelee I gave an example on the forum.

**Comment by sooheelee** [comment]
Thank you!

**Comment by chandrans** [comment]
@meganshand Can you jump back in? User's colleague came back with some follow up questions.
