### ISSUE TITLE
Make MarkDuplicates and UmiAwareMarkDuplicatesWithMateCigar capable of handling dual-index UMIs

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/picard#1192]
### Tool(s) involved
MarkDuplicates, UmiAwareMarkDuplicatesWithMateCigar

### Description

This ticket is to add an option to both MarkDuplicates and UmiAwareMarkDuplicatesWithMateCigar so that they can deduplicate duplex UMIs correctly.  At present both MarkDuplicates and UmiAwareMarkDuplicatesWithMateCigar are only single-index UMI aware.

Dual-index UMIs consist of two equal length UMIs concatenated together with a dash between them.  For example, AGT-GCA is a legal dual-index UMI and if we see the UMI GCA-AGT on another fragment with the same start-stop position that was sequenced in the opposite direction, we would like to correctly mark these as duplicates.

**Comment by nh13** [comment]
Can the MI tag have /A and /B to differentiate the two strands of the original duplex source molecule? See fgbio’s GroupReadsByUmi. Also, I think it’s important to mention in the docs that dual-index implies generating reads from a duplex source molecule, where both strands are observed. Can we have dual index but only read from one strand so this feature request could cause false collisions?

**Comment by fleharty** [comment]
@nh13 I agree and think we should include /A and /B to differentiate the two strands in MI similar to GroupReadsByUmi in fgbio.

"Can we have dual index but only read from one strand so this feature request could cause false collisions?"
I'm not entirely sure I know what you are getting at here, could you elaborate?

**Comment by fleharty** [comment]
My thought is that the default behavior would be to have this feature turned off, and that it would require being specified on the command line to turn it on.
Something like, DUPLEX=true (where by default it is false).

**Comment by nh13** [comment]
Any reason not to just use GroupReadsByUmi? The directed adjacency strategy is quite nice for error correction. You can then write a simple tool to post process them into DuplicationMetrics. Probably sub-optimal but just a thought.

**Comment by fleharty** [comment]
@nh13 Right now I'm using MarkDuplicates and UmiAwareMarkDuplicatesWithMateCigar and using them to generate metrics.  I'd like to be able to use them to generate metrics correctly on duplex UMIs.

I do also use GroupReadsByUmi (so that I can create consensus calls), and perhaps eventually I could use just that, but for now it would be very useful for me to be able to generate metrics using MarkDuplicates and UmiAwareMarkDuplicatesWithMateCigar.

**Comment by fleharty** [comment]
@nh13 I'm looking at the results from GroupReadsByUmi, and I don't see the /A and /B in the resulting MI tags, am I missing something?

**Comment by fleharty** [comment]
@nh13 
@yfarjoun 
As I'm looking into this, I suspect that UmiAwareMarkDuplicatesWMC is doing the wrong thing with the MI tag.

According to: https://samtools.github.io/hts-specs/SAMtags.pdf

MI:Z:str Molecular Identifier. A unique ID within the SAM file for the source molecule from which this
read is derived. All reads with the same MI tag represent the group of reads derived from the same
source molecule.

Right now, UmiAwareMarkDuplicatesWMC is putting in an inferred UMI.  I'm wondering if I should put in a number (as a string) into this field for each duplicate set, like fgbio does.  And use a different tag than MI for the inferred UMI.

**Comment by fleharty** [comment]
I figured out the issue with the missing /A and /B in the MI tag, I didn't use the paired strategy in GroupReadsByUmi.... so now I see it fine.

**Comment by fleharty** [comment]
@rebber I'm working on putting together a PR soon (working on it today, but may not go in today) for both MarkDuplicates and UmiAwareMarkDuplicatesWithMateCigar that will allow both to support duplex reads.

**Comment by fleharty** [comment]
@rebber 
I've made a PR which I believe resolves this issue.
https://github.com/broadinstitute/picard/pull/1235

**Comment by rebber** [comment]
Thank you! That's great!

**Comment by fleharty** [comment]
Closed via #1235
