### ISSUE TITLE
Javadocs won't be generated under Java 8

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/picard#121]
One of the things that breaks if you try to build Picard on Java 8 is javadocs. Specifically, it lints the Javadoc HTML by default, and will crash if it sees any unclosed carets etc.

Here's how to fix it: http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

**Comment by ronlevine** [comment]
Why not fix the unclosed carets? Isn't turning off doclint a bad thing? It will help with other syntax errors now and in the future.

**Comment by vdauwera** [comment]
Is this still a thing? We're on Java 8 now...

**Comment by yfarjoun** [comment]
I think this is solved.
