### ISSUE TITLE
Overflow in tile coordinates for optical duplicate marking

### ISSUE THREAD

**Issue by caherzee** [broadinstitute/picard#1216]
### Affected tool(s)
MarkDuplicates

### Affected version(s)
* Latest development/master branch as of 21/08
* Latest release 2.18.11

### Description 
The code for representing locations for optical duplicate marking uses shorts. We have seen this cause bugs due to overflows, resulting in incorrect optical duplicate counts. This happens when the locations’ values are > the maximum short, which we have seen in our data.

See ReadEnds.java -> ReadEnds extends PhysicalLocationShort -> should probably be ReadEnds extends PhysicalLocationInt

**Comment by yfarjoun** [comment]
This is a known issue that will probably not be fixed as a fix would involve making the code use that much more memory for what is perceived to a little gain. The current problem is that duplicates that are are around 0xff away in one of the coordinates are marked as "optical" erroneously, or, vice versa, opticals that are straddling a 0xef + n* 0xff are being not considered optical despite being so.  

This should only have negligible impact on the library-size estimates and ROI calculation and no effect on the actual duplicate marking. 

Do you disagree?

**Comment by lbergelson** [comment]
@yfarjoun Maybe we should change the interface to use shorts so it doesn't confuse people.  It confused us.

**Comment by yfarjoun** [comment]
But then it's impossible to use and get ints... For example one of the down
sampling tools uses the full integer value

**Comment by caherzee** [comment]
Hi,

This would use about 32 bits more per read. If I understand it correctly, Picard by default keeps 500000 reads in RAM, so this would cost 32 bits x 500000 = 2MB. That sounds acceptable to me.

I think it is preferable to fix the bug, or at least prompt a warning.

Thanks.

On 7 Sep 2018, at 22:39, Yossi Farjoun <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a known issue that will probably not be fixed as a fix would involve making the code use that much more memory for what is perceived to a little gain. The current problem is that duplicates that are are around 0xff away in one of the coordinates are marked as "optical" erroneously, or, vice versa, opticals that are straddling a 0xef + n* 0xff are being not considered optical despite being so.

This should only have negligible impact on the library-size estimates and ROI calculation and no effect on the actual duplicate marking.

Do you disagree?

**Comment by lbergelson** [comment]
Ah, ok.

**Comment by yfarjoun** [comment]
given that there are more errors with the optical-duplication detection (for example, duplicates are not detected across tile boundary) and lack of a clear need for ultra accurate optical duplication metrics, I'm not sure I agree that this is important.

However, if you can show that a significant portion of the error around optical duplication is due to this "bug", I will change my mind.
