### ISSUE TITLE
IlluminaBasecallsToFastq does not write unassigned reads to file

### ISSUE THREAD

**Issue by rithy8** [broadinstitute/picard#1227]
### Affected tool(s)
_IlluminaBasecallsToFastq._

### Affected version(s)
- [ x] Latest public release version [version?]
2.18.12
- [ ] Latest development/master branch as of [date of test?]

### Description 
IlluminaBasecallsToFastq writes reads with barcodes specified in MULTIPLEX_PARAMS only. There is no way to save unassigned reads (reads that do not matched the specified barcodes in MULTIPLEX_PARAMS) to r1 and r2 files.

#### Steps to reproduce
Parameters used: /usr/bin/time java  -Xmx100g -jar ${JAR_PATH} IlluminaBasecallsToFastq read_structure=151T8B8B151T RUN_BARCODE=172 LANE=1 MACHINE_NAME=NS500699 FLOWCELL_BARCODE=H755WBGX5 BASECALLS_DIR=${BASECALLS_DIR}  MAX_READS_IN_RAM_PER_TILE=1500000 APPLY_EAMSS_FILTER=false MULTIPLEX_PARAMS=my.csv IGNORE_UNEXPECTED_BARCODES=false TMP_DIR=../../tmp BARCODES_DIR=../../barcode_lane1_debug 2>&1 | tee result.txt.

#### Expected behavior
unassigned reads should be written to r1/r2 files.

#### Actual behavior
unassigned reads are not written.

**Comment by yfarjoun** [comment]
there should be a "N" or "NN" output file which contains all the unmatched reads....does it not exist?
