### ISSUE TITLE
picard build problem encountered

### ISSUE THREAD

**Issue by yl010** [broadinstitute/picard#1243]
Hi,

I'm trying to build picard but it failed due to java error?
Searched the internet but haven't found any solution yet
Could you please help solve this issue?
Thank you

Wanda

user@x3850x5:/Everythings/tools/picard$ ./gradlew shadowJar

FAILURE: Build failed with an exception.

* Where:
Build file '/Everythings/tools/picard/build.gradle' line: 57

* What went wrong:
A problem occurred evaluating root project 'picard'.
> The ClassLoader obtained from the Java ToolProvider is null. A Java 8 JDK must be installed. See https://github.com/broadinstitute/picard/blob/master/README.md#building-picard for information on how to build picard

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.542 secs

user@x3850x5:/Everythings/tools/picard$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

'

**Comment by lbergelson** [comment]
@yl010 It sounds like you might have the JRE( java runtime environment ) installed but not the JDK ( java development kit).  

 Could you try running `javac -version` and seeing what that says?

**Comment by yl010** [comment]
Indeed javac wasn't installed.
Though javac wasn't the only problem I ran into, but they were solved.
Thank you so much for helping =)
