### ISSUE TITLE
CollectOxoGMetrics - Error in the Method computeAlleleFraction

### ISSUE THREAD

**Issue by tyghjkyt** [broadinstitute/picard#1246]
### Affected tool(s)
CollectOxoGMetrics

### Affected version(s)
- [ ] Latest public release version 2.18.15
- [ ] Latest development/master branch as of Feb 7, 2018

### Description 
File: picard/src/main/java/picard/analysis/CollectOxoGMetrics.java
In the method computeAlleleFraction, I think some of the variables are assigned incorrectly.

```
// Get the read base, and get it in "as read" orientation
    final byte base = rec.getReadBase();
    final byte baseAsRead = samrec.getReadNegativeStrandFlag() ? SequenceUtil.complement(base) : base;
    final int read = samrec.getReadPairedFlag() && samrec.getSecondOfPairFlag() ? 2 : 1;

// Figure out how to count the alternative allele. If the damage is caused by oxidation of G
// during shearing (in non-rnaseq data), then we know that:
//     G>T observation is always in read 1
//     C>A observation is always in read 2
// But if the substitution is from other causes the distribution of A/T across R1/R2 will be
// random.

if (base == refBase) {
                    if (baseAsRead == 'G' && read == 1) ++counts.oxidatedC;
                    else if (baseAsRead == 'G' && read == 2) ++counts.controlC;
                    else if (baseAsRead == 'C' && read == 1) ++counts.controlC;
                    else if (baseAsRead == 'C' && read == 2) ++counts.oxidatedC;
} else if (base == altBase) {
                    if (baseAsRead == 'T' && read == 1) ++counts.oxidatedA;
                    else if (baseAsRead == 'T' && read == 2) ++counts.controlA;
                    else if (baseAsRead == 'A' && read == 1) ++counts.controlA;
                    else if (baseAsRead == 'A' && read == 2) ++counts.oxidatedA;
}
```
In the statement `if (base == refBase)`, `base` should be `baseAsRead` because `baseAsRead` is always on the forward strand, whereas `base` could be either on the forward strand or reverse strand.

Also, in here:
```
final byte altBase = (refBase == 'C') ? (byte) 'A' : (byte) 'T';
```
`altBase` equals A when `refBase` equals C and equals T when `refBase` equals G,A, or T. This is incorrect. `altBase` should only equal T when `refBase` equals G.

Let me know if I am mistaken or should try to explain more.

**Comment by tfenne** [comment]
@tyghjkyt I believe you are in fact mistaken.  The convention in SAM is that the bases in a mapped record are always stored to match the + strand of the genome.  If a record is marked as being `negativeStrand` that implies that it's bases have been [reverse-]complemented.

So in fact, `base` will always be the same strand/orientation as `refBase` and `baseAsRead` will be different about half the time.

**Comment by tyghjkyt** [comment]
Thank you for clearing that up @tfenne; can you (or anyone else) also take a look at the following line of code?
```
final byte altBase = (refBase == 'C') ? (byte) 'A' : (byte) 'T';
```
It fails in this special case: If `refBase = 'A'`, `altBase='T'`, and `base='T'`, `baseAsRead='A'`, `read=2`, then the program will count this position as an oxoG artifact when it should be counted as an A/T (or A-T to T-A) mutation.

The code should be corrected as follows:
```
final byte altBase = (refBase == 'C' || refBase == 'A') ? (byte) 'A' : (byte) 'T';
```

**Comment by yfarjoun** [comment]
thanks for your enthusiasm, @tyghjkyt 

Take a look at the only place where picard.analysis.CollectOxoGMetrics.Calculator#accept is being called, and note that refBase can only be G or C due to line picard/analysis/CollectOxoGMetrics.java:308

Now, perhaps a comment would help make the code more clear, but I do not think that it's a bug.
