### ISSUE TITLE
[bug report] ExtractIlluminaBarcodes generates barcodes with spaces (not compatible with IlluminaBasecallsToFastq)

### ISSUE THREAD

**Issue by joachimds** [broadinstitute/picard#1250]
### Affected tool(s)
ExtractIlluminaBarcodes
IlluminaBasecallsToFastq

### Affected version(s)
Identical errors on 2.18.15 and 2.18.16

### Description 

Demultiplexing MiSeq run via Picard. First do ExtractIlluminaBarcodes, then IlluminaBasecallsToFastq

Following command was used: 
java -jar picard.jar ExtractIlluminaBarcodes BASECALLS_DIR=/data/extra/big_working_dir/181023_M02947_0163_000000000-C33C5/Data/Intensities/BaseCalls OUTPUT_DIR=/data/extra/big_working_dir/LG_demulti2/ LANE=001 READ_STRUCTURE=151T10M8B BARCODE_FILE=/data/extra/big_working_dir/LG_demulti/barcode_file.txt METRICS_FILE=/data/extra/big_working_dir/LG_demulti/metrics.txt NUM_PROCESSORS=1 COMPRESS_OUTPUTS=false

java -jar picard.jar IlluminaBasecallsToFastq BASECALLS_DIR=/data/extra/big_working_dir/181023_M02947_0163_000000000-C33C5/Data/Intensities/BaseCalls/ LANE=001  READ_STRUCTURE=151T10M8B FLOWCELL_BARCODE=C33C5 MACHINE_NAME=M02947 RUN_BARCODE=0163 NUM_PROCESSORS=1 READ_NAME_FORMAT=CASAVA_1_8 COMPRESS_OUTPUTS=false MULTIPLEX_PARAMS=/data/extra/big_working_dir/LG_demulti/multiplex_file.txt IGNORE_UNEXPECTED_BARCODES=true TMP_DIR=/data/extra/big_working_dir/tmp/ BARCODES_DIR=/data/extra/big_working_dir/LG_demulti2/ TILE_LIMIT=1 FIRST_Tile=1115 INCLUDE_NON_PF_READS=false

IlluminaBasecallsToFastq crashes with an error indicating the barcode files generated by ExtractIlluminaBarcodes has more than the max 5 acceptable columns. Upon further investigation, it appears that an additional space is present (See below) between column 3 and 4 (for the rest the tab delimitation is correct).

........	N		8	0
........	N		8	0
........	N		8	0
.CC.C...	N	acgtacgt	2	2
CCTAC...	N	catgcatg[the space is here] 	2	2
TTTTC...	N	tgtgcaca	2	3
TCTCT...	N	tagctagc	2	3

This space error is very rare, only a few times in ~half of the tiles.

#### Steps to reproduce
See command above.

#### Expected behavior
No space in output generated by ExtractIlluminaBarcodes. Manually removal of spaces in the barcode files renders  IlluminaBasecallsToFastq functional.

#### Actual behavior
See above

**Comment by joachimds** [comment]
Hi, this is quite embarassing. Apparently there was an additional space in my input demux/barcodes file. This resulted in the reported barcode in the output file to have a space and consequently FASTQ file generation to crash... 

After correcting the input file (removing that single space), all is working fine.

**Comment by yfarjoun** [comment]
thanks for posting back.
