### ISSUE TITLE
pixel distance for MarkDuplicates Novaseq flow-cells

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#1252]
Dear,

It appears from a recent '''[Illumina page](https://emea.illumina.com/science/technology/next-generation-sequencing/sequencing-technology/patterned-flow-cells.html?langsel=/be/)''' that the new generation Novaseq patterned flow-cells are even more dense. The question is wether we should reflect this with a different value than 2500 for the _Optical Duplicate Distance_ when running MarkDuplicate with such date.

See last sentence below from the above link

> Advanced Systems Featuring Patterned Flow Cell Technology
> Patterned flow cell technology, pioneered on the HiSeq X Ten System, makes data-intensive applications more cost-effective, including the $1000 human genome. The HiSeq 3000/HiSeq 4000 Systems were the first Illumina sequencers to use patterned flow cells for diverse genomic applications.
> 
> The NovaSeq 6000 System unites the latest high-performance imaging with the next generation of Illumina patterned flow cell technology. The updated NovaSeq flow cell design further reduces the spacing between nanowells, significantly increasing cluster density and data output.

Thanks in advance for looking this up,
Stephane

PS: I also asked Illumina and will post their answer here.

**Comment by splaisan** [comment]
I got info from Illumina support but no value yet for the Novaseq platform and Picard MD which is logically _not officially supported_.

What do you have to say about **BBMap clumpify** as compared to Picard for handling optical and PCR duplicates?

+ nice post on **[Biostar](https://www.biostars.org/p/225338/)**

**Comment by splaisan** [comment]
BBTools clumpify advices a value of 12000 for the distance cutoff in Novaseq data processing (against 2500 for HiSeq) while Picard uses 2500 for both patterned flow-cells. Is there a reason for this discrepancy between man pages of both tools?

**Comment by yfarjoun** [comment]
we haven't seen a good reason to change the radius for NOVA data...

**Comment by Rohit-Satyam** [comment]
It seems Picard previously suggested the optimal distance for NovaSeq to be 2500 in older versions as stated [here](https://toolshed.g2.bx.psu.edu/repository/display_tool?repository_id=c45d6c51a4fcfc6c&render_repository_actions_for=tool_shed&tool_config=%2Fsrv%2Ftoolshed%2Fmain%2Fvar%2Fdata%2Frepos%2F000%2Frepo_259%2Fpicard_MarkDuplicates.xml&changeset_revision=f6ced08779c4)

`The maximum offset between two duplicate clusters in order to consider them optical
                              duplicates. This should be set to 100 for (circa 2011+) read names and typical flowcells.
                              Structured flow cells (NovaSeq, HiSeq 4000, X) should use ~2500.
                              For older conventions, distances could be to some fairly small number (e.g. 5-10 pixels)
                              Default value: 100.`

**Comment by mcdonrae** [comment]
Yes, @Rohit-Satyam I've tried to use what they suggest (2500) but it corrects it to 500, as it seems to be the max for the MarkDuplicates tool. 

For NovaSeq data, should I use a different duplicate marking tool?

**Comment by Nitin123-4** [comment]
What about X plus ?
