### ISSUE TITLE
queryname sorted BAM Markduplication ran a long time without any output

### ISSUE THREAD

**Issue by biozzq** [broadinstitute/picard#1253]
Dear all,
Recently, I ran the latest `Picard Markduplication (version, 2.18.17)` using the queryname sorted BAM as the input. It surprised me that the program has ran for 4 days but without any output. However, when I used the coordinate sorted BAM, it can be finished within four hours. Why is there such a big difference? Any suggestion will be greatly appreciated. Thank you very much.

log from queryname sorted with command `java -Xmx50g -Djava.io.tmpdir=`pwd` -jar ~/bin/picard_2.18.17.jar MarkDuplicates INPUT=$bam OUTPUT=$out ASSUME_SORT_ORDER=queryname METRICS_FILE=test VALIDATION_STRINGENCY=LENIENT`

`INFO   2018-11-25 22:26:00     MarkDuplicates  Read     4,000,000 records.  Elapsed time: 01:17:22s.  Time for last 1,000,000: 1,045s.  Last read position: NW_014641153.1:433
INFO    2018-11-25 22:26:00     MarkDuplicates  Tracking 1 as yet unmatched pairs. 1 records in RAM.
INFO    2018-11-25 22:41:02     MarkDuplicates  Read     5,000,000 records.  Elapsed time: 01:32:23s.  Time for last 1,000,000:  901s.  Last read position: 2:176,846,963
INFO    2018-11-25 22:41:02     MarkDuplicates  Tracking 0 as yet unmatched pairs. 0 records in RAM.`

log from queryname sorted with command `java -Xmx50g -Djava.io.tmpdir=`pwd` -jar ~/bin/picard_2.18.17.jar MarkDuplicates INPUT=$bam OUTPUT=$out ASSUME_SORT_ORDER=coordinate METRICS_FILE=test VALIDATION_STRINGENCY=LENIENT`

`NFO	2018-11-26 13:11:13	MarkDuplicates	Read 4,000,000 records. Elapsed time: 00:00:31s. Time for last 1,000,000: 5s. Last read position: 1:26,413,433
INFO	2018-11-26 13:11:13	MarkDuplicates	Tracking 194909 as yet unmatched pairs. 12186 records in RAM.
INFO	2018-11-26 13:11:19	MarkDuplicates	Read 5,000,000 records. Elapsed time: 00:00:37s. Time for last 1,000,000: 6s. Last read position: 1:33,392,936
INFO	2018-11-26 13:11:19	MarkDuplicates	Tracking 228684 as yet unmatched pairs. 15840 records in RAM.`

Best,
Zhuqing

**Comment by yfarjoun** [comment]
1. The way you are using `pwd` doesn't do what you thing it does. In particular, it uses the directory called `pwd` as temp, rather than (what I presume that you wanted) the current working directory. Yuo can see this be looking at the first line from the log file where all the parameters to the tool are explicitly written out. you want to use ${pwd} or `` `pwd` ``  
2. Are you using the same file in both cases? what is the file actually sorted as?

**Comment by yfarjoun** [comment]
> I used the same file in both case. 

But you should NOT do that....you should use a file that has the appropriate sort order!! The problem with queryname sort order is that it's difficult to check (the code is trying to be lenient and accept queryname **grouped** but to check this requires keeping track of all the names that were seen, and that's a waste of memory/disk & time....) 

So, for the queryname sorted run, use a query-name sorted (either picard or samtools) file, and for the coordinate-sorted run, use a coordinate-sorted file.

**Comment by biozzq** [comment]
Dear @yfarjoun

Sorry, not the sample BAM file. You can see the above detail commands. I used the appropriately sorted file in the command.  The BAM files generated from BWA have already sorted by queryname, so I used this BAM as the input for the queryname sorted run directly. Before the coordinate-sorted run, I have sorted the BAM by coordinate using Picard. 

Best wishes,
Zhuqing
