### ISSUE TITLE
LiftoverVCF + Badly formed variant context at location chr1:899903; getEnd()

### ISSUE THREAD

**Issue by arumds** [broadinstitute/picard#1258]
Hi,

I am using LiftoverVCF to convert hg38 to hg19 and below is the issue. Could someone help to fix this or is it a bug with picard?

```
$ picard LiftoverVcf I=114.vcf O=114.hg19.vcf CHAIN=hg38ToHg19.over.chain R=ucsc_hg19.fa REJECT=114_rejected_variants.vcf
Picked up _JAVA_OPTIONS: -Xmx64g
13:18:31.625 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/homeappl/picard/picard-tools-2.18.10/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Dec 20 13:18:31 EET 2018] LiftoverVcf INPUT=114.vcf OUTPUT=114.hg19.vcf CHAIN=hg38ToHg19.over.chain REJECT=114_rejected_variants.vcf REFERENCE_SEQUENCE=ucsc_hg19.fa    WARN_ON_MISSING_CONTIG=false LOG_FAILED_INTERVALS=true WRITE_ORIGINAL_POSITION=false WRITE_ORIGINAL_ALLELES=false LIFTOVER_MIN_MATCH=1.0 ALLOW_MISSING_FIELDS_IN_HEADER=false RECOVER_SWAPPED_REF_ALT=false TAGS_TO_REVERSE=[AF] TAGS_TO_DROP=[MAX_AF] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Dec 20 13:18:31 EET 2018] Executing as XXXX on Linux 2.6.32-642.15.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_151-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.10-SNAPSHOT
INFO	2018-12-20 13:18:32	LiftoverVcf	Loading up the target reference genome.
INFO	2018-12-20 13:18:56	LiftoverVcf	Lifting variants over and sorting (not yet writing the output file.)
[Thu Dec 20 13:18:57 EET 2018] picard.vcf.LiftoverVcf done. Elapsed time: 0.42 minutes.
Runtime.totalMemory()=7120355328
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException: Badly formed variant context at location chr1:899903; getEnd() was 899903 but this VariantContext contains an END key with value 964523
	at htsjdk.variant.variantcontext.VariantContext.validateStop(VariantContext.java:1321)
	at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1294)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at picard.util.LiftoverUtils.liftVariant(LiftoverUtils.java:108)
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:389)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

```

**Comment by yfarjoun** [comment]
is this a gvcf? could you post the CHROM through INFO columns that you have for the variant that is failing (chr1:899903)?

**Comment by mehar-GIT** [comment]
It is a single sample regular VCF. And surprisingly, the variant that is failing (chr1:899903) is not in the input VCF. The same behavior is observed with a different sample as well. It fails at certain variant which is not in the input file.

**Comment by yfarjoun** [comment]
I see. so this is happening for the newly created variant....could you look to see if any of the original variants have a END=964523?

**Comment by mehar-GIT** [comment]
Yes, there is an INDEL with that position:

```
$ grep 964523 114.vcf 
chr1	964523	.	A	ATCCGCAGGTCCGCAGTGGGGCTGCCGGGAGGGG	.	PASS	END=964523;HOMLEN=24;HOMSEQ=TCCGCAGGTCCGCAGTGGGGCTGC;SVLEN=33;SVTYPE=INS	GT:AD	0/1:35,12

```

**Comment by mehar-GIT** [comment]
any fix for this? or does it work only for SNP?

**Comment by yfarjoun** [comment]
OK. I see the problem. I've put in a PR into samtools/htsjdk#1247 that I need for a clean solution.

Thanks!

**Comment by mehar-GIT** [comment]
any update please?

**Comment by yfarjoun** [comment]
Sorry for the delay. Soon.

**Comment by yfarjoun** [comment]
with the new htsjdk I will be able to fix this...I just need the version of
htsjdk to be rev'ed (PR #1267) and then I'll be able to fix this. sorry for
the delay.

**Comment by nh13** [comment]
@yfarjoun as a heads up, I also encountered this issue on Picard version `2.18.7-SNAPSHOT`

**Comment by MaestSi** [comment]
I also experienced a similar issue with Picard version `2.18.27-1-g21ad30b-SNAPSHOT`.
Are there any updates?

**Comment by yfarjoun** [comment]
hopefully this will be resolved in the next release. thanks for the bug report.

**Comment by duartemolha** [comment]
I have installed the latest version and this is still occuring

java -Xmx10g  -jar ~/Programs/picard/build/libs/picard.jar LiftoverVcf I=my_vcf.vcf O=myvcf_hg38.vcf CHAIN=hg19ToHg38.over.chain.gz REJECT=rejected_variants.vcf R=hg38.fa

12:24:57.077 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/nfs/rodney/home/duartem/Programs/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Oct 18 12:24:57 BST 2019] LiftoverVcf INPUT=my_vcf.vcf OUTPUT=my_vcf_hg38.vcf CHAIN=hg19ToHg38.over.chain.gz REJECT=rejected_variants.vcf REFERENCE_SEQUENCE=hg38.fa    WARN_ON_MISSING_CONTIG=false LOG_FAILED_INTERVALS=true WRITE_ORIGINAL_POSITION=false WRITE_ORIGINAL_ALLELES=false LIFTOVER_MIN_MATCH=1.0 ALLOW_MISSING_FIELDS_IN_HEADER=false RECOVER_SWAPPED_REF_ALT=false TAGS_TO_REVERSE=[AF] TAGS_TO_DROP=[MAX_AF] DISABLE_SORT=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Oct 18 12:24:57 BST 2019] Executing as duartem@denzil on Linux 4.9.0-8-amd64 amd64; OpenJDK 64-Bit Server VM 1.8.0_222-8u222-b10-1~deb9u1-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.1-1-g7ffc61c-SNAPSHOT
INFO    2019-10-18 12:24:57     LiftoverVcf     Loading up the target reference genome.
INFO    2019-10-18 12:25:14     LiftoverVcf     Lifting variants over and sorting (not yet writing the output file.)
[Fri Oct 18 12:25:14 BST 2019] picard.vcf.LiftoverVcf done. Elapsed time: 0.29 minutes.
Runtime.totalMemory()=3988258816
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException: Badly formed variant context at location chr1:596697; getEnd() was 596797 but this VariantContext contains an END key with value 532177
        at htsjdk.variant.variantcontext.VariantContext.validateStop(VariantContext.java:1401)
        at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1383)
        at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:489)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:647)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:638)
        at picard.util.LiftoverUtils.liftVariant(LiftoverUtils.java:92)
        at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:426)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

Here is the offending line on the VCF:

1       532077  HG2_PB_SVrefine2PB10Xhap12_3    ACATTCATGCTCACTCATACACACCCAGATCATATATACACTCGTGCACACATTCACACTCATACACACCCAAATCATACTCACATTCATGCACACATGTT   A       20      NoConsensusGT   ClusterIDs=HG2_PB_SVrefine2PB10Xhap12_3:HG3_Ill_MetaSV_1:HG3_Ill_scalpel_3:HG3_Ill_GATKHCSBGrefine_1;NumClusterSVs=4;ExactMatchIDs=HG2_PB_SVrefine2PB10Xhap12_3:HG3_Ill_scalpel_3:HG3_Ill_GATKHCSBGrefine_1;NumExactMatchSVs=3;ClusterMaxShiftDist=0.00985221674876847;ClusterMaxSizeDiff=0.00985221674876847;ClusterMaxEditDist=0.00985221674876847;PBcalls=1;Illcalls=3;TenXcalls=0;CGcalls=0;PBexactcalls=1;Illexactcalls=2;TenXexactcalls=0;CGexactcalls=0;HG2count=1;HG3count=3;HG4count=0;NumTechs=2;NumTechsExact=2;SVLEN=-100;DistBack=85479;DistForward=996;DistMin=996;DistMinlt1000=TRUE;MultiTech=TRUE;MultiTechExact=TRUE;SVTYPE=DEL;END=532177;sizecat=100to299;DistPASSHG2gt49Minlt1000=.;DistPASSMinlt1000=.;MendelianError=.;HG003_GT=./.;HG004_GT=./.;TRall=TRUE;TRgt100=TRUE;TRgt10k=FALSE;segdup=TRUE;REPTYPE=CONTRAC;BREAKSIMLENGTH=325;REFWIDENED=1:531935-532359    GT:GTcons1:PB_GT:PB_REF:PB_ALT:PBHP_GT:PB_REF_HP1:PB_ALT_HP1:PB_REF_HP2:PB_ALT_HP2:TenX_GT:TenX_REF_HP1:TenX_ALT_HP1:TenX_REF_HP2:TenX_ALT_HP2:ILL250bp_GT:ILL250bp_REF:ILL250bp_ALT:ILLMP_GT:ILLMP_REF:ILLMP_ALT:BNG_LEN_DEL:BNG_LEN_INS:nabsys_svm   ./.:./.:./.:1:2:./.:0:0:0:0:./.:0:0:59:3:0/0:57:0:./.:.:.:.:.:.

**Comment by kirannarta** [comment]
I'm using picard-2.21.8-0 and still getting this error...

**Comment by yfarjoun** [comment]
hmmmm. I'm confused about this. My tests pass and so if someone who is encountering this problem could provide a small VCF + chain + target reference where this happens, I'll be happy to try to figure out what's going on and see if I can fi it.

**Comment by kirannarta** [comment]
Hi,
I am trying to liftover GRCh37 to Grch38. 
I have attached a vcf file containing only Indels from Chr1 (SNVs were lifted over without issues). 
The error is "Badly formed variant context at location chr1:3086128; getEnd() was 3086128 but this VariantContext contains an END key with value 3002692". 
I have also attached the chain file and the error file. 

Thanks for helping with this
[picard.zip](https://github.com/broadinstitute/picard/files/4208846/picard.zip)

**Comment by yfarjoun** [comment]
I'll see what I can do.

**Comment by yfarjoun** [comment]
I think I understand the problem. BTW @kirannarta, it seems that you are trying to lift-over a SV vcf which has very large deletions. Since these deletions span several intervals in the chain, many of them will no be lifted over correctly. I'm not sure what is the correct approach for lifting over symbolic variants of type <DEL>...but this tool, as written will not do justice to the TCGA SV vcf. if this is important functionality, please open a separate issue here, and we can discuss how that functionality will interact with the non-precise aspect of the liftover method.

I'll still fix the tool so that it doesn't crash, but many variants will be dropped (SV DELS)

**Comment by kirannarta** [comment]
Oh I see.. The error position is a small insertion though (1       3002692 .       C       CTGTT ). Is it that large deletions in the vcf will cause errors in insertions in those regions? I don't mind if large deletions are dropped for now. Thanks for working on it.

**Comment by yfarjoun** [comment]
no, the large deletions will just get dropped (noisily...you'll get lots of warnings in the output) and are not causing the problem with the small deletions.

**Comment by kirannarta** [comment]
Okay.. good to know. thanks
