### ISSUE TITLE
reference mismatch and also invalid refrence allele for annotation

### ISSUE THREAD

**Issue by aeltoukhi** [broadinstitute/picard#1260]
Please, How can I solve the mismatch and also when after liftover, the annotation program gives me an invalid reference allele
   Lifting variants over and sorting (not yet writing the output file.)
INFO    2019-01-02 21:12:31     LiftoverVcf     Processed 116415 variants.
INFO    2019-01-02 21:12:31     LiftoverVcf     0 variants failed to liftover.
INFO    2019-01-02 21:12:31     LiftoverVcf     31704 variants lifted over but had mismatching reference alleles after lift over.
INFO    2019-01-02 21:12:31     LiftoverVcf     27.2336% of variants were not successfully lifted over and written to the output.
INFO    2019-01-02 21:12:31     LiftoverVcf     liftover success by source contig:
INFO    2019-01-02 21:12:31     LiftoverVcf     1: 84711 / 116415 (72.7664%)
INFO    2019-01-02 21:12:31     LiftoverVcf     lifted variants by target contig:
INFO    2019-01-02 21:12:31     LiftoverVcf     1: 84711
WARNING 2019-01-02 21:12:31     LiftoverVcf     29374 variants with a swapped REF/ALT were identified, but were not recovered.  See RECOVER_SWAPPED_REF_ALT and associated caveats.
INFO    2019-01-02 21:12:31     LiftoverVcf     Writing out sorted records to final VCF.
[Wed Jan 02 21:12:50 CST 2019] picard.vcf.LiftoverVcf done. Elapsed time: 1.09 minutes.

**Comment by yfarjoun** [comment]
What's the question?
