### ISSUE TITLE
MarkDuplicates - UMI regular expression

### ISSUE THREAD

**Issue by caleblareau** [broadinstitute/picard#1274]
This concerns the`MarkDuplicates` call when supplying a  BARCODE_TAG.

I am dealing with an error "UMIs must match the regular expression ^[ATCGNatcgn-]*$." It's sort of hard to explain, but in my data setting, I have valid UMI tags that don't follow this regex pattern. Is there any specific reason this rule has to be enforced or alternatively any way around it?

**Comment by fleharty** [comment]
@caleblareau 
There are two possible solutions I see to this.
1. We could change the regular expression to be less restrictive (if it makes sense)
2. We could add an option to allow you to ignore the requirement of meeting the regular expression.

Could you send me some examples of your UMIs that don't satisfy this regular expression?

**Comment by caleblareau** [comment]
Thanks @fleharty. I would recommend option 2 as you suggested as my data might be an unusual case. 

Examples:
Exp62_UMI0063
Exp21-rep2_UMI0122
Exp21-rep1_AACGTGA

**Comment by yfarjoun** [comment]
seems like that information should be in the LB field of the RG tag....no? I'm not sure that it make sense to pack all that into the barcode....

**Comment by fleharty** [comment]
@caleblareau 
The contents of your UMI tag is certainly non-standard and I would even say... less than ideal.  There are all sorts of strange things that can happen with error correction on strings that don't contain DNA sequence.

Is it possible for you to modify your pipeline to have legal UMIs in the RX tag rather than have me modify UmiAwareMDWMC to accept illegal Umis?

**Comment by fleharty** [comment]
@caleblareau 
I'm reluctant to make changes to the code to allow UMIs like the ones you have.  The code relies on the assumption that the UMIs are strings of DNA sequences with a possible "-" to denote a separation between two duplex UMIs.  If this assumption is broken, then unexpected and undesired things can happen.

I'm closing this issue for now.  I think the most sensible solution is for you to correct the RX tags in your bam files.  If you object, and think we need to find another solution, feel free to reopen.

**Comment by caleblareau** [comment]
Hi @fleharty and @yfarjoun thank you for the suggestions. 

My experimental data is a setting multiple DNA barcode tags (typically through multiple beads in a single droplet) become associated with the same cell (see panel c here: https://www.nature.com/articles/ncomms14049/figures/1). I have developed an approach that identifies these "N>1" cells with high confidence, and now I am attempting to de-duplicate the UMI data. 

To be clear, consider the following example
bead 1: AGCT; bead 2: ACCC; UMI: GGGG; my algorithm indicates that bead 1 and bead 2 actually are marking the same single cell. Thus, I collapse over AGCT-GGGG and ACCC-GGGG to become the same original molecule, which I currently name using the examples above. 

I think now the easiest approach will be to use a modified CellID tag and leave the UMI field alone. 

Thank you for getting back to me so quickly and the thought that went into this. I should be able to work around the error with your suggestions.

-Caleb

**Comment by caleblareau** [comment]
@fleharty would it be possible to revisit expanding the scope of the permissible UMIs to including character `0-9`? I've retooled my data in the example above but ran into this issue again. Further, the manner in which 10x Genomics handles their barcoding results in the following ([see here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam)):

```
AGAATGGTCTGCAT-1
```

In cases where I want to use the cell barcode as a UMI for deduplication, I get the same error as above. This rather small increase in the permissible regex would be a big help. Please let me know if this is possible. Thanks!

**Comment by fleharty** [comment]
@caleblareau This may be possible.  Is the number always 0-9, or could it be larger like 342?

Why is the -1 not in a separate tag?

**Comment by caleblareau** [comment]
Thanks @fleharty. 

1) The number will be any positive integer value (342 is in theory permissible). In 10x convention, each distinct reaction is assigned a different integer value. When several reactions are analyzed together, one gets this distinct integer vlaue.

2) My initial answer here is "10x convention", but more practically, the `CB` tag is designed to specify a unique cell barcode. `ACGT-1` and `ACGT-2` represent two different cell barcodes (though `ACGT` would have been a barcode present in either reaction).

**Comment by fleharty** [comment]
@caleblareau 
One of the features of this tool is that it does error correction on the UMIs.

I'm assuming that you would want error correction on UMIs with the same cell barcode, but would not want error correction on UMIs that have differing cell barcodes.  Is that correct?

**Comment by caleblareau** [comment]
That would be correct yes that one shouldn't error-correct between integer values as they represent different cells.

However, I do note that these barcodes would already be error-corrected (the `CB` tags which have the `-1` already adjust the preceding DNA bases to the error-corrected... at least by 10x convention [see here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam). The `CR` tag reports the raw bases observed). 

So one could either 1) disable the error correction if you wanted when parsing these integer inedexed barcodes (would work fine for all 10x data) or 2) error correct within integer values as you described (would potentially catch other non-standard 10x data).

**Comment by fleharty** [comment]
One possibility would be to add an option, 
UMI_ERROR_CORRECTION which would default to true.  But if false, it would allow a much broader range of UMIs that include a more permissive regular expression and would turn off error correction.  This would solve your problem, but it seems a little kludgey to me, and I'd like to avoid that.

@yfarjoun Do you have any thoughts here that might be better?

**Comment by yfarjoun** [comment]
this was discussed _ad naseum_ in the sam-spec repository. the current status-quo is that:

Cells are identified by CB:
```
CB:Z:str Cell identifier, consisting of the optionally-corrected cellular barcode sequence and an optional
suffix. The sequence part is similar to the CR tag, but may have had sequencing errors etc corrected.
This may be followed by a suffix consisting of a hyphen (‘-’) and one or more alphanumeric characters to
form an identifier. In the case of the cellular barcode (CR) being based on multiple barcode sequences
the recommended implementation concatenates all the (corrected or uncorrected) barcodes with a
hyphen (‘-’) between the different barcodes. Sequencing errors etc aside, all reads from a single cell
are expected to have the same CB tag.
```

UMIs are placed in RX:
```
RX:Z:sequence+ Sequence bases from the unique molecular identifier. These could be either corrected or
uncorrected. Unlike MI, the value may be non-unique in the file. Should be comprised of a sequence of
bases. In the case of multiple unique molecular identifiers (e.g., one on each end of the template) the
recommended implementation concatenates all the barcodes with a hyphen (‘-’) between the different
barcodes.
```

While Molecules can be identified in the MI tag:
```
MI:Z:str Molecular Identifier. A unique ID within the SAM file for the source molecule from which this
read is derived. All reads with the same MI tag represent the group of reads derived from the same
source molecule.
```
Perhaps you want to use MI and we could discuss having markduplicates work differently when using RX (in which case the information is sequence bases) and when using MI (in which case the information is a string with no restrictions)

**Comment by caleblareau** [comment]
Thanks @yfarjoun and @fleharty for the discussion. For my purposes, it is easy enough to modify the `CB` tag into an `MI` tag that is currently compatible with the regex before running the MarkDuplicates. I would say that this only needs to be serious revisited if others demand the feature. I appreciate the help!

**Comment by fleharty** [comment]
@caleblareau Okay great, I'm closing the ticket.  Feel free to reopen if you think this needs to be revisited.

**Comment by Zepeng-Mu** [comment]
Hello,
I'm having the same issue with 10X results. Specifically it is the cellRanger convention that puts `-1` or `-2` at the end of CB that is causing the error. I can try changing CB to MI, but it would be great if the stringency is loosen so I do not need to modify every of my BAM.

Alternatively, I can use the CR tag from 10X BAM. But the catch is that CB is error-corrected and checked against a list of known CB.

Thanks!
