### ISSUE TITLE
SortSam documentation is misleading

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/picard#1283]
I've noticed that in the tool documentation for SortSam the following line is present:
```
For queryname-sorted alignments, all alignments are grouped using the queryname field but the alignments are not necessarily sorted within these groups. Reads having the same queryname are derived from the same template.
```
This seems to be wrong however, as it looks to me that SortSam passes the SortOrder to the writer which ultimately ends up instantiating a `SAMRecordQueryNameComparator` object and invoking the compare() function. While the first criteria for comparison is indeed `compareReadNames()`, there are many other criteria it uses after that (important ones being strandedness followed by primary/secondary). This line should be amended.

**Comment by sooheelee** [comment]
We can follow up similarly in the SortSamSpark documentation.

**Comment by yfarjoun** [comment]
I think that the point of the documentation is that we are not committing to any particular order within the same queryname...not that an order doesn't exist. this means that if we choose to change the implementation, we would not be breaking the contract. I think the documentation should remain unchanged.

**Comment by sooheelee** [comment]
Just a friendly reminder that GATK forum Tool docs is now pinned to software release versions (orange button in screenshot). So any changes to the implementation in the future can be accomodated with corresponding changes to the javadoc.

---
![screenshot 2019-02-22 16 49 37](https://user-images.githubusercontent.com/11543866/53273376-dc0df100-36c1-11e9-9b90-7e5199c9aebb.png)
