### ISSUE TITLE
Missing adapter strings from MarkIlluminaAdapters?

### ISSUE THREAD

**Issue by init-js** [broadinstitute/picard#1299]
### Tool(s) involved

MarkIlluminaAdapters (no special parameters)

### Description

I'm processing a mixture of fastqs produced with different versions of TruSeq DNA kits, and I ultimately was trying to determine whether I needed to pass a custom adapter string to MarkIlluminaAdapters that would cover all the kits. My hope was that the tool covered all official Illumina kits. There's no list of kits  supported in the documentation, as far as I know.

Looking into the built-in adapter strings defined in MarkIlluminaAdapters [IlluminaUtil.java (March 20th 2019)](https://github.com/broadinstitute/picard/blob/ef3f175c8f45a1f97aabbd5442a747fbe743103f/src/main/java/picard/util/IlluminaUtil.java#L130), I notice that for paired end reads, the 5' adapter featured is what is referred to as the "universal adapter" in the [Feb 2019 Illumina adapter reference](https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences-1000000002694-10.pdf).

At first glance, the following Illumina adapter sequences appeared to be missing from IlluminaUtil:

    - `Read1` adapter: `AGATCGGAAGAGCACACGTCTGAAC`
    - `Read2` adatpter: `AGATCGGAAGAGCGTCGTGTAGGGA`

But in the illumina pdf, they are a common prefix for all the following kits:

    - IDT for Illumina TruSeq DNA and RNA UD Indexes
    - TruSeq DNA and RNA CD Indexes
    - TruSeq Single Indexes
    - TruSeq DNA Methylation (legacy kit)

(The link for [the original illumina pdf](https://github.com/broadinstitute/picard/blob/ef3f175c8f45a1f97aabbd5442a747fbe743103f/src/main/java/picard/util/IlluminaUtil.java#L133
) stated the source code currently gives a 404)

I notice that `Read1` is the leading substring prefix for 3' strings `{INDEXED, DUAL_INDEXED}` in IlluminaUtils, and that the reverse complement of `Read2`, i.e. `TCCCTACACGACGCTCTTCCGATCT`, appears as the trailing suffix for 5' fields `{PAIRED_END, INDEXED, SINGLE_END, DUAL_INDEXED}`. The full string constants are much longer than the documented sequences however.

By virtue of being common prefixes to the detected adapters, is it correct to assume that `Read1` and `Read2` sequences are detected by IlluminaUtil, without the user having to specify anything extra? Is the entire set of adapters enabled, regardless of the nature of the input data (PE, SE, indexed, etc) ?

**Comment by yfarjoun** [comment]
As you notices, the strings in IlluminaUtils also include the position of the sample-index and the primer....

The default settings for MarkIlluminaAdapters only use 
IlluminaAdapterPair.INDEXED,
IlluminaAdapterPair.DUAL_INDEXED,
IlluminaAdapterPair.PAIRED_END

So it looks like it covers the Read1 Read2 sequences that you have.

**Comment by init-js** [comment]
Ok. I wasn't too certain how those constants had been constructed. I see now, with the NNNNs and all.

If I understand correctly, any other adapter sequence out there that is a prefix of those default ones (in read order), will be covered implicitly by the built-in set of adapters. That's good!

The doc should perhaps say that the FIVE_PRIME_ADAPTER should be fed in reverse complement form. It's opposite from what's in the illumina pdfs. That seems like a tripping point.

Thank you for the quick response!
