### ISSUE TITLE
CollectMultipleMetrics created a huge insert size file

### ISSUE THREAD

**Issue by curtisjamison** [broadinstitute/picard#1315]
### Affected tool(s)
CollectMultipleMetrics

### Affected version(s)
2.18.26-SNAPSHOT

### Description 
CollectMultipelMetrics has produced a massive insert_size histogram file. This has caused R to hang.

-rw-r--r-- 1 root root        1804 Apr 13 09:17 multiple_metrics.alignment_summary_metrics
-rw-r--r-- 1 root root       12277 Apr 13 09:17 multiple_metrics.base_distribution_by_cycle.pdf
-rw-r--r-- 1 root root       16449 Apr 13 09:17 multiple_metrics.base_distribution_by_cycle_metrics
-rw-r--r-- 1 root root           0 Apr 13 09:24 multiple_metrics.insert_size_histogram.pdf
-rw-r--r-- 1 root root   213151240 Apr 13 09:20 multiple_metrics.insert_size_metrics

head -20 multiple_metrics.insert_size_metrics
htsjdk.samtools.metrics.StringHeader
CollectMultipleMetrics INPUT=sorted1055.bam OUTPUT=multiple_metrics REFERENCE_SEQUENCE=/mnt/data/refData/1055/1055.fa    ASSUME_SORTED=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] PROGRAM=[CollectAlignmentSummaryMetrics, CollectBaseDistributionByCycle, CollectInsertSizeMetrics, MeanQualityByCycle, QualityScoreDistribution] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
htsjdk.samtools.metrics.StringHeader
Started on: Sat Apr 13 07:44:40 UTC 2019

METRICS CLASS        picard.analysis.InsertSizeMetrics
MEDIAN_INSERT_SIZE      MODE_INSERT_SIZE        MEDIAN_ABSOLUTE_DEVIATION       MIN_INSERT_SIZE MAX_INSERT_SIZE MEAN_INSERT_SIZE        STANDARD_DEVIATION      READ_PAIRSPAIR_ORIENTATION        WIDTH_OF_10_PERCENT     WIDTH_OF_20_PERCENT     WIDTH_OF_30_PERCENT     WIDTH_OF_40_PERCENT     WIDTH_OF_50_PERCENT     WIDTH_OF_60_PERCENT     WIDTH_OF_70_PERCENT       WIDTH_OF_80_PERCENT     WIDTH_OF_90_PERCENT     WIDTH_OF_95_PERCENT     WIDTH_OF_99_PERCENT     SAMPLE  LIBRARY READ_GROUP
429     411     68      1       249171748       428.633736      109.616728      303308748       FR      27      51      79      107     137     175     221     285     403       533     119278165
48240601.5      149     31452638        1       249230598       59308909.802558 47928464.879025 17711166        TANDEM  12624255        25464723        37939125        50422693  62905271        75252549        87861069        100135695       160474831       212041633       304297599

HISTOGRAM    java.lang.Integer
insert_size     All_Reads.fr_count      All_Reads.tandem_count
1       54      3
2       1197    0
3       1181    0
4       1220    0
5       1249    0
6       1313    0
7       1246    0
8       1301    0
...
249229987       0       1
249230009       0       1
249230062       0       1
249230081       0       1
249230212       0       1
249230214       0       1
249230312       0       1
249230435       0       1
249230598       0       1

Realignment did not help this issue.

**Comment by yfarjoun** [comment]
well, it's a "histogram" of all the insert sizes you have in the file...is it:
1. wrong?
2. not useful?
3. could be better?
4. you don't know how to load it into R?

**Comment by curtisjamison** [comment]
I understand that it is _supposed_ to be a histogram. I also think it is unreasonable to see insert sizes of ~250MB. Visual inspection of the file shows a normal distribution inserts in the expected 600–700 bp range, as all our other samples do, but then there are literally several hundred thousand lines like the ones at the tail of the file. Because of there spurious reads, R has locked up. So I guess that to answer your question, it would be 1-3.

**Comment by yfarjoun** [comment]
hmmm. I see the problem. In this case you should either run CollectInsertSize as a separate tool (rather than via CollectMultipleMetrics) and provide the HISTOGRAM_WIDTH argument, or rerun the R script later with that argument.

**Comment by yfarjoun** [comment]
this can be fixed if we ever get around to writing up a DSL for injecting arguments into individual CMM tools
