### ISSUE TITLE
Fatal error on MarkDuplicates

### ISSUE THREAD

**Issue by nuin** [broadinstitute/picard#1329]
## Bug Report

I am getting a fatal error with MarkDuplicates when trying to mark duplicated on a BWA generated BAM file. I have tried with version 2.19.2 installed by home-brew and a freshly built version from GitHub, with identical output. I am still using the old command line syntax.

### Affected tool(s)
MarkDuplicates 

```java -jar picard.jar MarkDuplicates INPUT=/Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.bam OUTPUT=/Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.dedup.bam METRICS_FILE=/Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.metrics.txt```

### Affected version(s)
2.19.2 and latest on GitHub

### Description 
The output is 

```********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicates -INPUT /Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.bam -OUTPUT /Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.dedup.bam -METRICS_FILE /Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.metrics.txt
**********


15:20:25.548 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/nuin/src/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Thu May 09 15:20:25 MDT 2019] MarkDuplicates INPUT=[/Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.bam] OUTPUT=/Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.dedup.bam METRICS_FILE=/Users/nuin/Projects/Data/Illumina_small/BAM/NA12877_1/BAM/NA12877_1.metrics.txt    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu May 09 15:20:25 MDT 2019] Executing as nuin@Paulos-iMac-Pro.local on Mac OS X 10.14.4 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_211-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.0-1-gc4dff1c-SNAPSHOT
INFO	2019-05-09 15:20:25	MarkDuplicates	Start of doWork freeMemory: 1014138720; totalMemory: 1029177344; maxMemory: 15271460864
INFO	2019-05-09 15:20:25	MarkDuplicates	Reading input file and constructing read end information.
INFO	2019-05-09 15:20:25	MarkDuplicates	Will retain up to 55331379 data points before spilling to disk.
INFO	2019-05-09 15:20:30	MarkDuplicates	Read     1,000,000 records.  Elapsed time: 00:00:04s.  Time for last 1,000,000:    4s.  Last read position: chr9:98,009,629
INFO	2019-05-09 15:20:30	MarkDuplicates	Tracking 509 as yet unmatched pairs. 135 records in RAM.
INFO	2019-05-09 15:20:33	MarkDuplicates	Read     2,000,000 records.  Elapsed time: 00:00:07s.  Time for last 1,000,000:    3s.  Last read position: chr16:68,863,325
INFO	2019-05-09 15:20:33	MarkDuplicates	Tracking 387 as yet unmatched pairs. 52 records in RAM.
INFO	2019-05-09 15:20:34	MarkDuplicates	Read 2443004 records. 0 pairs never matched.
INFO	2019-05-09 15:20:36	MarkDuplicates	After buildSortedReadEndLists freeMemory: 1980921848; totalMemory: 2719481856; maxMemory: 15271460864
INFO	2019-05-09 15:20:36	MarkDuplicates	Will retain up to 477233152 duplicate indices before spilling to disk.
INFO	2019-05-09 15:20:37	MarkDuplicates	Traversing read pair information and detecting duplicates.
INFO	2019-05-09 15:20:38	MarkDuplicates	Traversing fragment information and detecting duplicates.
INFO	2019-05-09 15:20:38	MarkDuplicates	Sorting list of duplicate records.
INFO	2019-05-09 15:20:39	MarkDuplicates	After generateDuplicateIndexes freeMemory: 2873101640; totalMemory: 6727663616; maxMemory: 15271460864
INFO	2019-05-09 15:20:39	MarkDuplicates	Marking 629356 records as duplicates.
INFO	2019-05-09 15:20:39	MarkDuplicates	Found 81 optical duplicate clusters.
INFO	2019-05-09 15:20:39	MarkDuplicates	Reads are assumed to be ordered by: coordinate
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000141644ea7, pid=10096, tid=0x0000000000002603
#
# JRE version: Java(TM) SE Runtime Environment (8.0_211-b12) (build 1.8.0_211-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.211-b12 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libgkl_compression2348235168616825397.dylib+0x6ea7]  deflate_medium+0x867
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/nuin/src/picard/build/libs/hs_err_pid10096.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Error log is attached. 
[hs_err_pid10096.log](https://github.com/broadinstitute/picard/files/3164082/hs_err_pid10096.log)

#### Expected behavior
A BAM file should be generated at the end.

#### Actual behavior
Truncated file is generated.

Any help appreciated.

**Comment by nuin** [comment]
Couple of BAMs that I was using were malformed. Will test again.

**Comment by nuin** [comment]
Tested with some other BAM files (analyses before) and got the same result, just reopened the issue.

Thanks

**Comment by mrnameless123** [comment]
@nuin  what is your java version, I figure out that this error is caused by incompatible java version 
I have two Java version in my device (12.0.1 and 1.8.0_102). With Java 1.8.0_102 is installed along with Picard from Bioconda environment, however, it actually caused the core dump error. While I downloaded a prebuilt Picard of the previous version from the problem does not happen. 

+

**Comment by mrnameless123** [comment]
@nuin  I have resolved the problem by adding the following parameters at the end of the script
`USE_JDK_DEFLATER=true USE_JDK_INFLATER=true`

**Comment by lbergelson** [comment]
I missed this issue when it was reported but it looks to be closely related to #1383 .  It's a segfault in the native compression / decompression library used to accelerate picard.  @mrnameless123 is correct that you can work around it by using the java code instead of the native version.  

Can people encountering this problem let me know what operating system they are running?  I've only been able to reproduce an segfault like this on OSX 10.14.6 for some reason.  

The good news is that there are people actively working on fixing bugs in the native code at the moment and I'm hopeful that the next release of it will fix these problems.

**Comment by Jordbear** [comment]
I encountered exactly this issue when trying to run DownsampleSam. The fix above worked but just FYI I'm running macOS Catalina 10.15.6

**Comment by hukai916** [comment]
I encountered a similar problem on OSX 10.15.6, and the error seems to pop up randomly. I run the same commands for 20 samples, only 14 success. By adding the two parameters suggested by @mrnameless123, the problem gets solved though.

**Comment by fleharty** [comment]
@hukai916 
This issue should be resolvable by using the arguments as mentioned above:
USE_JDK_DEFLATER=true USE_JDK_INFLATER=true

A fix is being worked on (not by me) from what I understand.  It will hopefully be resolved in the coming months.

**Comment by skchronicles** [comment]
Hey @lbergelson,

I have also run into the same issue; however, I am using a Docker image I have created for Picard. **I can also confirm that adding** `USE_JDK_DEFLATER=true USE_JDK_INFLATER=true` **solves the problem**.
![image](https://user-images.githubusercontent.com/18038345/97508059-0a42da00-1955-11eb-9827-a99f1b127899.png)

You can pull the image here, if you're interested: https://hub.docker.com/repository/docker/nciccbr/ccbr_picard

Here is the Dockerfile that can reproduce the error: 
```bash
# Picard/2.11.0 Dockerfile (v0.0.1)
FROM ubuntu:18.04

RUN mkdir -p /data2
RUN mkdir -p /opt2/picard/

# Update apt-get before downloading packages 
RUN apt-get update && \
    apt-get upgrade -y 

# Install Standard Java Runtime
RUN apt-get install -y \
	default-jre \
	wget && \
apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /opt2/picard

# Get specified release of Picard
ENV PICARD_VERSION="2.11.0"
RUN wget https://github.com/broadinstitute/picard/releases/download/${PICARD_VERSION}/picard.jar
RUN chmod a+x /opt2/picard/*.jar
ENV PICARDJARPATH=/opt2/picard

COPY Dockerfile /opt2/
WORKDIR /data2
```

https://github.com/skchronicles/Docker/blob/master/ccbr_picard/Dockerfile

**Comment by skchronicles** [comment]
Hey @lbergelson,

Just as a side note, I ended up bundling the `picardcloud.jar` in my Dockerfile above (I just added a COPY statement to get the jar file into the container's filesystem), and that also solved the problem (without the need to add `USE_JDK_DEFLATER=true` `USE_JDK_INFLATER=true`).

![image](https://user-images.githubusercontent.com/18038345/97627846-5435c980-1a02-11eb-8796-0299cacca734.png)

I am just going to use that JAR distribution instead.
