### ISSUE TITLE
MarkDuplicates questions

### ISSUE THREAD

**Issue by jingydz** [broadinstitute/picard#1332]
I run this step

> gatk MarkDuplicates -I /data/users/zhanglei/species/Medicago/result/SRR340101.sorted.bam -M SRR340101.markdup_metrics.txt -O SRR340101.output.markdup.bam && echo "SRR done **"

## Bug Report

[zhanglei@GenEngine result]$ gatk MarkDuplicates -I /data/users/zhanglei/species/Medicago/result/SRR340101.sorted.bam -M SRR340101.markdup_metrics.txt -O SRR340101.output.markdup.bam && echo "SRR done **"
Using GATK jar /home/software/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/software/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar MarkDuplicates -I /data/users/zhanglei/species/Medicago/result/SRR340101.sorted.bam -M SRR340101.markdup_metrics.txt -O SRR340101.output.markdup.bam
21:52:13.656 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/software/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Sun May 12 21:52:13 CST 2019] MarkDuplicates  --INPUT /data/users/zhanglei/species/Medicago/result/SRR340101.sorted.bam --OUTPUT SRR340101.output.markdup.bam --METRICS_FILE SRR340101.markdup_metrics.txt  --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --ADD_PG_TAG_TO_READS true --REMOVE_DUPLICATES false --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --OPTICAL_DUPLICATE_PIXEL_DISTANCE 100 --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Sun May 12 21:52:13 CST 2019] Executing as zhanglei@GenEngine on Linux 3.10.0-327.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_201-b09; Deflater: Intel; Inflater: Intel; Picard version: Version:4.0.3.0
INFO	2019-05-12 21:52:13	MarkDuplicates	Start of doWork freeMemory: 1616416712; totalMemory: 1647312896; maxMemory: 28631367680
INFO	2019-05-12 21:52:13	MarkDuplicates	Reading input file and constructing read end information.
INFO	2019-05-12 21:52:13	MarkDuplicates	Will retain up to 103736839 data points before spilling to disk.
[Sun May 12 21:52:14 CST 2019] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=1647312896
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
java.lang.IllegalArgumentException: Cannot add sequence that already exists in SAMSequenceDictionary: chromosome
	at htsjdk.samtools.SAMSequenceDictionary.setSequences(SAMSequenceDictionary.java:88)
	at htsjdk.samtools.SAMSequenceDictionary.<init>(SAMSequenceDictionary.java:60)
	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:121)
	at htsjdk.samtools.BAMFileReader.readHeader(BAMFileReader.java:667)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:298)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:176)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:396)
	at picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram.openInputs(AbstractMarkDuplicatesCommandLineProgram.java:215)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:480)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:232)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by yfarjoun** [comment]
It seems that your input file is not valid. Perhaps it has two @SQ header lines with the ID "chromosome"? (can look with `samtools view -H`)

Could you please run ValidateSamFile on your input and report the output of that program?

Thanks!

**Comment by jingydz** [comment]
(base) [zhangjingjing@GenEngine result]$ samtools view -H SRR340101.sorted.bam
@HD     VN:1.5  SO:coordinate
@SQ     SN:chromosome   LN:52991155
@SQ     SN:chromosome   LN:45729672
@SQ     SN:chromosome   LN:55515152
@SQ     SN:chromosome   LN:56582383
@SQ     SN:chromosome   LN:43630510
@SQ     SN:chromosome   LN:35275713
@SQ     SN:chromosome   LN:49172423
@SQ     SN:chromosome   LN:45569985
@SQ     SN:unplaced     LN:525692
@SQ     SN:unplaced     LN:496089
@SQ     SN:unplaced     LN:430703
@SQ     SN:unplaced     LN:387120
@SQ     SN:unplaced     LN:312633
@SQ     SN:unplaced     LN:286035
@SQ     SN:unplaced     LN:285178
@SQ     SN:unplaced     LN:273699
@SQ     SN:unplaced     LN:272641
@SQ     SN:unplaced     LN:264378
@SQ     SN:unplaced     LN:262975
@SQ     SN:unplaced     LN:253479
@SQ     SN:unplaced     LN:251186
@SQ     SN:unplaced     LN:239740
@SQ     SN:unplaced     LN:215127
@SQ     SN:unplaced     LN:208779
@SQ     SN:unplaced     LN:197404
@SQ     SN:unplaced     LN:197401
@SQ     SN:unplaced     LN:184292
@SQ     SN:unplaced     LN:181555
@SQ     SN:unplaced     LN:181084
@SQ     SN:unplaced     LN:173541
@SQ     SN:unplaced     LN:169951
@SQ     SN:unplaced     LN:161340
@SQ     SN:unplaced     LN:156237
@SQ     SN:unplaced     LN:152121
....
@SQ     SN:unplaced     LN:1006
@SQ     SN:unplaced     LN:1006
@SQ     SN:unplaced     LN:1004
@SQ     SN:unplaced     LN:124033
@RG     ID:foo  PL:ILLUMINA     SM:Medicago truncatula
@PG     ID:bwa  PN:bwa  VN:0.7.17-r1188 CL:bwa mem -t 10 -M -Y -R @RG\tID:foo\tPL:ILLUMINA\tSM:Medicago truncatula /data/users/zhanglei/species/Medicago/Medicago1.fa /data/users/zhanglei/species/Medicago/result/SRR340101.paired.1.fastq.gz /data/users/zhanglei/species/Medicago/result/SRR340101.paired.2.fastq.gz


(base) [zhangjingjing@GenEngine result]$ java -jar /data/users/zhangjingjing/anaconda2/share/picard-2.18.26-0/picard.jar ValidateSamFile I=SRR340101.sorted.bam MODE=SUMMARY
INFO    2019-05-13 15:00:20     ValidateSamFile

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    ValidateSamFile -I SRR340101.sorted.bam -MODE SUMMARY
**********


15:00:20.648 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data/users/zhangjingjing/anaconda2/share/picard-2.18.26-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon May 13 15:00:20 CST 2019] ValidateSamFile INPUT=SRR340101.sorted.bam MODE=SUMMARY    MAX_OUTPUT=100 IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 SKIP_MATE_VALIDATION=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon May 13 15:00:20 CST 2019] Executing as zhangjingjing@GenEngine on Linux 3.10.0-327.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_171-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.26-SNAPSHOT
WARNING 2019-05-13 15:00:20     ValidateSamFile NM validation cannot be performed without the reference. All other validations will still occur.
ERROR   2019-05-13 15:00:20     ValidateSamFile Cannot add sequence that already exists in SAMSequenceDictionary: chromosome
[Mon May 13 15:00:20 CST 2019] picard.sam.ValidateSamFile done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp

**Comment by yfarjoun** [comment]
So, it seems that the reference you are using is invalid as the name of each sequence must be unique. 

once you fix that, realign and then rerun markduplicates.
