### ISSUE TITLE
Feature rquest: CollectMultipleMetrics

### ISSUE THREAD

**Issue by fgvieira** [broadinstitute/picard#1333]
### Tool(s) involved
CollectMultipleMetrics

### Description
Right now `CollectMultipleMetrics` assumes default parameters for all tools. It would be nice if we could specify parameters for each tool, for example `--MINIMUM_PCT` for `CollectInsertSizeMetrics`.

**Comment by kbergin** [comment]
This was implemented in #1337 , closing this issue now.
