### ISSUE TITLE
Duplicate definition

### ISSUE THREAD

**Issue by fxjonas** [broadinstitute/picard#1349]
Dear Picard team,

I am currently trying to quantify the number of PCR duplicates in our sequencing data. When running mark duplicates on paired-end sequencing, I noticed that it actually doesn't differ between R1 and R2, e.g. if the same DNA fragment is spanned it is counted no matter if the R1 is on Watson or on Crick. However, we only amplify after adapter attachment and a PCR duplicate should thus also have R1 in the same direction as its duplicate. Is there any way to change the duplicate definition in this respect or do you plan to incorporate something like this in the future?

Thanks,
Felix

P.S., for now, my best workaround is creating to separate alignment files (depending on if R1 is on Watson or on crick) and then mark the duplicates separately before fusing both files. If you have a more straight forward solution I would be grateful.

**Comment by yfarjoun** [comment]
You can add a "barcode tag" RX with value either "Watson" or "Crick" and
run MD with BARCODE_TAG=RX. That should keep the two sets of reads separate.

**Comment by fxjonas** [comment]
Dear Yossi,

thanks for your rapid reply. I am not quite sure what you mean by  'RX with value either "Watson" or "Crick" ', can you maybe elaborate how to actually do this (I tried to find some Infos in the manual https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.7.0/picard_sam_markduplicates_MarkDuplicates.php#--BARCODE_TAG but couldn't find any clue how to set the value or which options there are)? 

P.S. I tried just adding BARCODE_TAG=RX when starting MD but this didn't change anything. I noticed however that optical duplicates already distinguish between F1R2 and R1F2 (what I want to do), so I was wondering if it is possible to make sure the algorithm disregards the distance on the flowcell and gives all possible optical duplicates?

**Comment by fxjonas** [comment]
Dear Yossi,

after reading a little into it, I finally understood that setting the barcode is prior to running Picard, and then picard jsut looks up a Tag in the optional arguments in the BamFile. And it seems to work (at least I get lower number of duplicates). I currently use SamJS from the Jvarkit to edit the tags of the bam files... but it is really reall slow do you have a better solution. I basically just set the RX to R1 for Read 1 and R2 for read 2. but it still takes several minutes for 10 mio paired reads

samjs.jar -e 'if (record.getReadLength()>30){record.setAttribute("RX","R1")}else{record.setAttribute("RX","R2")};true' ~/outG/Enr4_11B_S82.bam -o ~/outG/test.bam

**Comment by yfarjoun** [comment]
I think that this is a reasonable optional way of running MarkDuplicates,
but I that is is somewhat niche and so I'm not sure I'll have the time to
make the changes to allow for it. I suspect that it would be not too much
work for you to add an option to use the sort-order used by the optical
duplicate marking for the regular duplicate marking. This should produce
the results you want.
