### ISSUE TITLE
MarkDuplicates CRAM output support?

### ISSUE THREAD

**Issue by Reedwarbler** [broadinstitute/picard#1352]
Hi, I am running `MarkDuplicates` (v 2.20.2) with cram as input, and run with command like:
```
java -jar ./tools/picard/picard.jar MarkDuplicates I=SS6004480.srt.aln.bam.cram O=test.cram R=./fasta/genome.fa M=md.txt
```

How to set option to generate a real cram file? Is it supported by the current version? Thank you!

**Comment by yfarjoun** [comment]
We don't fully support cram output at this point.  please use bam output and convert to cram using samtools.

**Comment by Reedwarbler** [comment]
Oh, ok. Thank you for your reply.

**Comment by y9c** [comment]
Hi, I would like to know if cram format has been supported or not? I added .cram file as output, but the file is bam format.
