### ISSUE TITLE
Picard 2.20.3 markduplicates error

### ISSUE THREAD

**Issue by willright28** [broadinstitute/picard#1360]
Hi, i have a problem with using the picard markduplicates in the supercomputer, and the command is:

#!/bin/sh
#PBS -N mdup_LS004
#PBS -l nodes=4:ppn=8
#PBS -V

cd /gpfs/home/chenyl/biodata/test_seq/LS004

time java -Dpicard.useLegacyParser=false -Xmx32G -jar /gpfs/home/chenyl/picard/picard.jar MarkDuplicates -REMOVE_DUPLICATES true -I LS004_trimmed/LS004.sorted.bam -O LS004_trimmed/LS004_markdup.bam -M LS004_trimmed/LS004_markdup_metrics.txt --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1024 --MAX_RECORDS_IN_RAM 300000 --TMP_DIR /TMP

and it turned out to be a failure, and report is:

10:30:33.121 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs/home/chenyl/picard/picard.jar!/com/intel/gkl/native/libgkl_compression.so
10:30:33.190 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
10:30:33.198 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs/home/chenyl/picard/picard.jar!/com/intel/gkl/native/libgkl_compression.so
10:30:33.198 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
[Thu Jul 18 10:30:33 CST 2019] MarkDuplicates  --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1024 --INPUT LS004_trimmed/LS004.sorted.bam --OUTPUT LS004_trimmed/LS004_markdup.bam --METRICS_FILE LS004_trimmed/LS004_markdup_metrics.txt --REMOVE_DUPLICATES true --TMP_DIR /TMP --MAX_RECORDS_IN_RAM 300000  --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --DUPLEX_UMI false --ADD_PG_TAG_TO_READS true --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --OPTICAL_DUPLICATE_PIXEL_DISTANCE 100 --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Thu Jul 18 10:30:33 CST 2019] Executing as chenyl@cu46 on Linux 3.10.0-862.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_161-b14; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: Version:2.20.3-SNAPSHOT
INFO	2019-07-18 10:30:33	MarkDuplicates	Start of doWork freeMemory: 2036390760; totalMemory: 2058354688; maxMemory: 30542397440
INFO	2019-07-18 10:30:33	MarkDuplicates	Reading input file and constructing read end information.
INFO	2019-07-18 10:30:33	MarkDuplicates	Will retain up to 110660860 data points before spilling to disk.
10:30:35.900 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
[Thu Jul 18 10:30:37 CST 2019] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.07 minutes.
Runtime.totalMemory()=2943877120
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Exception creating temporary directory.
	at htsjdk.samtools.util.IOUtil.createTempDir(IOUtil.java:903)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.<init>(CoordinateSortedPairInfoMap.java:59)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.<init>(DiskBasedReadEndsForMarkDuplicatesMap.java:57)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:531)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at htsjdk.samtools.util.IOUtil.createTempDir(IOUtil.java:894)
	... 7 more

real	0m9.969s
user	0m2.131s
sys	0m0.557s
Host key verification failed.

Does anyone could help me with that, thanks in advance!

**Comment by fleharty** [comment]
Picard is attempting to create a temp directory but cannot.
You can resolve this by setting TMP_DIR to an appropriate location.

For more information, see,
https://gatkforums.broadinstitute.org/gatk/discussion/6083/picard-tools-markduplicates-spilling-to-disk

**Comment by dcopetti** [comment]
Hi,
I also get a similar error from this command:
`(base) bash-4.2$ java -Xmx30G -XX:-UseGCOverheadLimit -jar /home/copettid/anaconda3/share/picard-2.21.2-0/picard.jar MarkDuplicates INPUT=/scratch/dario/Hi-C_data/paired_bams/20181207.A-Arima_Rabiosa.bam INPUT=/scratch/dario/Hi-C_data/paired_bams/20190125.A-Arima_Rabiosa.bam OUTPUT=deduplicated_bams/Arima_both_dedupl.bam METRICS_FILE=deduplicated_bams/metrics_Arima_both_dedupl.txt TMP_DIR=/scratch/dario/Hi-C_data/temp_outputs ASSUME_SORTED=TRUE VALIDATION_STRINGENCY=LENIENT REMOVE_DUPLICATES=TRUE`
with the following stdout:
```
INFO    2019-11-11 11:29:03     MarkDuplicates

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicates -INPUT /scratch/dario/Hi-C_data/paired_bams/20181207.A-Arima_Rabiosa.bam -INPUT /scratch/dario/Hi-C_data/paired_bams/20190125.A-Arima_Rabiosa.bam -OUTPUT deduplicated_bams/Arima_both_dedupl.bam -METRICS_FILE deduplicated_bams/metrics_Arima_both_dedupl.txt -TMP_DIR /scratch/dario/Hi-C_data/temp_outputs -ASSUME_SORTED TRUE -VALIDATION_STRINGENCY LENIENT -REMOVE_DUPLICATES TRUE
**********


11:29:04.236 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/copettid/anaconda3/share/picard-2.21.2-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Nov 11 11:29:04 CET 2019] MarkDuplicates INPUT=[/scratch/dario/Hi-C_data/paired_bams/20181207.A-Arima_Rabiosa.bam, /scratch/dario/Hi-C_data/paired_bams/20190125.A-Arima_Rabiosa.bam] OUTPUT=deduplicated_bams/Arima_both_dedupl.bam METRICS_FILE=deduplicated_bams/metrics_Arima_both_dedupl.txt REMOVE_DUPLICATES=true ASSUME_SORTED=true TMP_DIR=[/scratch/dario/Hi-C_data/temp_outputs] VALIDATION_STRINGENCY=LENIENT    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Nov 11 11:29:04 CET 2019] Executing as copettid@g-wst-mpb-gabrieha on Linux 3.10.0-1062.4.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.2-SNAPSHOT
INFO    2019-11-11 11:29:04     MarkDuplicates  Start of doWork freeMemory: 2037526696; totalMemory: 2058354688; maxMemory: 28633464832
INFO    2019-11-11 11:29:04     MarkDuplicates  Reading input file and constructing read end information.
INFO    2019-11-11 11:29:04     MarkDuplicates  Will retain up to 103744437 data points before spilling to disk.
[Mon Nov 11 11:30:01 CET 2019] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.96 minutes.
Runtime.totalMemory()=6728187904
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: /scratch/dario/Hi-C_data/temp_outputs/CSPI.7674682554450186461.tmp/8929.tmpnot found
        at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:64)
        at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:49)
        at htsjdk.samtools.util.ResourceLimitedMap.get(ResourceLimitedMap.java:76)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.getOutputStreamForSequence(CoordinateSortedPairInfoMap.java:180)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.put(CoordinateSortedPairInfoMap.java:164)
        at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.put(DiskBasedReadEndsForMarkDuplicatesMap.java:65)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:591)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Caused by: java.io.FileNotFoundException: /scratch/dario/Hi-C_data/temp_outputs/CSPI.7674682554450186461.tmp/8929.tmp (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:61)
        ... 10 more
```

I wonder how else I should specify the temporary directory.
Thanks,

Dario

**Comment by fleharty** [comment]
The error that you are getting 

`java.io.FileNotFoundException: /scratch/dario/Hi-C_data/temp_outputs/CSPI.7674682554450186461.tmp/8929.tmp (Too many open files)`

appears to be a problem with either your file system or the path you are providing to Picard.  I don't think this is a problem with Picard.

 
Check to see that the directory /scratch/dario/Hi-C_data/temp_outputs
exists on your machine, and also be sure that there is enough disk space in that drive.

Also, I happened to notice you are using quite a bit of ram with `-Xmx30G`.  It's unlikely (thought possible) you actually need that much RAM.  You may be able to free up some resources by reducing that number.

**Comment by dcopetti** [comment]
Thank you for the hints,
I just realized that before marking the duplicates, there is another step 
`picard AddOrReplaceReadGroups`
that successfully completed, in two different machines (Fedora and Ubuntu).

I am checking about the file system, but can the issue be given by the java/JDK confusion?
These are the two versions I have:
```
(base) bash-4.2$ java -version
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
```
and
```
(hic_env) [copettid@kp141-242 ~]$ java -version
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.1-internal+0-adhoc..src, mixed mode)
```

Thanks!

**Comment by fleharty** [comment]
@dcopetti 
At the moment Picard only supports Java 8.

The binary file that you see show up and then get deleted is correct behavior.

**Comment by dcopetti** [comment]
Update:
a colleague suggested me to add
`-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000`
and it (magically!?) works!

**Comment by Bin-Xia** [comment]
> Picard is attempting to create a temp directory but cannot. You can resolve this by setting TMP_DIR to an appropriate location.
> 
> For more information, see, https://gatkforums.broadinstitute.org/gatk/discussion/6083/picard-tools-markduplicates-spilling-to-disk

**Hi fleharty, I also get a similar error from this command:**

> INPUT=/workspace/hrabxx/RNA_SNV_FPKM/3.mapping/add_RG.bam
> OUTPUT=/workspace/hrabxx/RNA_SNV_FPKM/3.mapping/Markduplicates.bam
> 
> mkdir -p $OUTPUT
> 
> module load picard-tools/2.10.1
> 
> for i in T64_01
> do
>     echo java -jar -Xmx12g -Xms1g /software/bioinformatics/picard-tools-2.10.1/picard.jar MarkDuplicates I=$INPUT/${i}.bam O=$OUTPUT/${i}_mark_dup.bam CREATE_INDEX=True VALIDATION_STRINGENCY=SILENT M=${i}_markd_dup_metrics.txt  
> done


**and it turned out to be a failure, and report is:**

> [Tue Dec 06 16:37:06 NZDT 2022] picard.sam.markduplicates.MarkDuplicates INPUT=[/workspace/hrabxx/RNA_SNV_FPKM/3.mapping/add_RG.bam/T64_01.bam] OUTPUT=/workspace/hrabxx/RNA_SNV_FPKM/3.mapping/Markduplicates.bam/T64_01_mark_dup.bam METRICS_FILE=T64_01_markd_dup_metrics.txt VALIDATION_STRINGENCY=SILENT CREATE_INDEX=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
> [Tue Dec 06 16:37:06 NZDT 2022] Executing as hrabxx@aklppb30.pfr.co.nz on Linux 3.10.0-1160.76.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_345-b01; Picard version: 2.10.1-SNAPSHOT
> INFO	2022-12-06 16:37:06	MarkDuplicates	Start of doWork freeMemory: 2042304024; totalMemory: 2058354688; maxMemory: 7635730432
> INFO	2022-12-06 16:37:06	MarkDuplicates	Reading input file and constructing read end information.
> INFO	2022-12-06 16:37:06	MarkDuplicates	Will retain up to 27665689 data points before spilling to disk.
> [Tue Dec 06 16:37:06 NZDT 2022] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.00 minutes.
> Runtime.totalMemory()=2058354688
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
> Exception in thread "main" htsjdk.samtools.SAMException: Exception creating temporary directory.
> 	at htsjdk.samtools.util.IOUtil.createTempDir(IOUtil.java:775)
> 	at htsjdk.samtools.CoordinateSortedPairInfoMap.<init>(CoordinateSortedPairInfoMap.java:59)
> 	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.<init>(DiskBasedReadEndsForMarkDuplicatesMap.java:57)
> 	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:473)
> 	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:228)
> 	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
> 	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
> 	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
> Caused by: java.io.IOException: Permission denied
> 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
> 	at java.io.File.createTempFile(File.java:2063)
> 	at java.io.File.createTempFile(File.java:2109)
> 	at htsjdk.samtools.util.IOUtil.createTempDir(IOUtil.java:766)
> 	... 7 more
> 

**I have set TMP_DIR to an appropriate location. it didn't work, the error report is below.  I don't know what I can do next. Looking for your help, thank you in advance.**

> [Wed Dec 07 11:27:25 NZDT 2022] picard.sam.markduplicates.MarkDuplicates INPUT=[/workspace/hrabxx/RNA_SNV_FPKM/3.mapping/add_RG.bam/T64_01.bam] OUTPUT=/workspace/hrabxx/RNA_SNV_FPKM/3.mapping/Markduplicates.bam/T64_01_mark_dup.bam METRICS_FILE=T64_01_markd_dup_metrics.txt VALIDATION_STRINGENCY=SILENT CREATE_INDEX=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
> [Wed Dec 07 11:27:25 NZDT 2022] Executing as hrabxx@wkoppb40.pfr.co.nz on Linux 3.10.0-1160.76.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_345-b01; Picard version: 2.10.1-SNAPSHOT
> INFO	2022-12-07 11:27:25	MarkDuplicates	Start of doWork freeMemory: 1018509952; totalMemory: 1029177344; maxMemory: 11453595648
> INFO	2022-12-07 11:27:25	MarkDuplicates	Reading input file and constructing read end information.
> INFO	2022-12-07 11:27:25	MarkDuplicates	Will retain up to 41498534 data points before spilling to disk.
> [Wed Dec 07 11:27:25 NZDT 2022] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.00 minutes.
> Runtime.totalMemory()=1029177344
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
> Exception in thread "main" htsjdk.samtools.SAMException: Exception creating temporary directory.
> 	at htsjdk.samtools.util.IOUtil.createTempDir(IOUtil.java:775)
> 	at htsjdk.samtools.CoordinateSortedPairInfoMap.<init>(CoordinateSortedPairInfoMap.java:59)
> 	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.<init>(DiskBasedReadEndsForMarkDuplicatesMap.java:57)
> 	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:473)
> 	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:228)
> 	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
> 	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
> 	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
> Caused by: java.io.IOException: Permission denied
> 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
> 	at java.io.File.createTempFile(File.java:2063)
> 	at java.io.File.createTempFile(File.java:2109)
> 	at htsjdk.samtools.util.IOUtil.createTempDir(IOUtil.java:766)
> 	... 7 more
>
