### ISSUE TITLE
Clearing COVERAGE_CAP default value in Picard CollectHsMetrics

### ISSUE THREAD

**Issue by asmoe4** [broadinstitute/picard#1361]
Hi

I am trying to remove the default value of 200x in `COVERAGE_CAP` of Picard's CollectHsMetrics by assigning NULL value.  I get the following error message:

`Exception in thread "main" java.lang.IllegalArgumentException: Can not set int field picard.analysis.directed.CollectTargetedMetrics.COVERAGE_CAP to null value`

Can you please advise?

**Comment by yfarjoun** [comment]
Yes, the cap needs to exist (due to how the code is written), but you can set it to be arbitrarily high. I've run it set to 100,000 without problems.
