### ISSUE TITLE
CollectAlignmentSummaryMetrics is not providing read group info

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/picard#1372]
-METRIC_ACCUMULATION_LEVEL  ALL_READS gives Sample and Library level information but not read group level information. It is not described in the documentation what are the different "levels" in METRIC_ACCUMULATION_LEVEL argument.

Please find below the user report:

Dear GATK team,
I have a bam file (merged using markduplicates after bwa mem)  with the following RG tags:

`view -H file.bam | grep '^@RG'`

    @RG	ID:FLOWCELL1.LANE1	PL:ILLUMINA	LB:Lib1	SM:Sample1
    @RG	ID:FLOWCELL1.LANE2	PL:ILLUMINA	LB:Lib1	SM:Sample1
    @RG	ID:FLOWCELL1.LANE3	PL:ILLUMINA	LB:Lib1	SM:Sample1

`ValidateSamFile` in summary mode reports no errors.
`HaplotypeCaller` and other gatk tools report no errors.

However, using `CollectAlignmentSummaryMetrics` with `METRIC_ACCUMULATION_LEVEL=READ_GROUP` (Version:4.1.2.0) produces this: 

    CATEGORY			…	SAMPLE	LIBRARY	READ_GROUP
    FIRST_OF_PAIR		…			
    SECOND_OF_PAIR		…			
    PAIR				…			
    UNPAIRED			…	Sample1	Lib1	
    FIRST_OF_PAIR		…	unknown	unknown	unknown
    SECOND_OF_PAIR		…	unknown	unknown	unknown
    PAIR				…	unknown	unknown	unknown

However, `samtools stats --split RG file.bam | grep '^SN' ` gives me bamstat files for all three read groups with the proper number of reads. 

    file.bam_FLOWCELL1.LANE1.bamstat
    file.bam_FLOWCELL1.LANE2.bamstat
    file.bam_FLOWCELL1.LANE3.bamstat

I would have expected something similar from the CollectAlignmentSummaryMetrics output. 

Did I miss something? How can I check that the read group information I've provided is valid and has been accordingly used by the gatk tools?
Could it have something to do with the fact that I did not state the PU field? Is this a problem? I thought gatk does not require it (see [here](https://gatkforums.broadinstitute.org/gatk/discussion/11015/read-groups "here")). 
Thank you very much for your help!

**UPDATE**

I re-ran `CollectAlignmentSummaryMetrics` with all possible values for `METRIC_ACCUMULATION_LEVEL` so : `{ALL_READS, SAMPLE, LIBRARY, READ_GROUP}`, which produces this: 

    CATEGORY			…	SAMPLE	LIBRARY	READ_GROUP
    FIRST_OF_PAIR		…			
    SECOND_OF_PAIR		…			
    PAIR				…			
    FIRST_OF_PAIR		…	Sample1		
    SECOND_OF_PAIR		…	Sample1		
    PAIR				…	Sample1		
    FIRST_OF_PAIR		…	Sample1	Lib1	
    SECOND_OF_PAIR		…	Sample1	Lib1	
    PAIR				…	Sample1	Lib1	
    UNPAIRED			…	Sample1	Lib1	
    FIRST_OF_PAIR		…	unknown	unknown	unknown
    SECOND_OF_PAIR		…	unknown	unknown	unknown
    PAIR				…	unknown	unknown	unknown

So Sample and Library are recognised just not the RG...

Thx!

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/24239/how-to-check-if-the-rg-information-is-valid/p1

**Comment by yfarjoun** [comment]
1. does the file validate by picard?
2. do the _reads_ not the header) have a RG tag?

**Comment by bhanugandham** [comment]
@yfarjoun  closing this issue as it looks like it was a user error. The user was missing the PU field that lead to the error. I will make a note to add this to the documentation.
