### ISSUE TITLE
UMI-aware markduplicates (considering only 5'-end and UMI)

### ISSUE THREAD

**Issue by vivekbhr** [broadinstitute/picard#1400]
### Tool(s) involved
markDuplicates / UMIawareMarkDuplicatesWithMateCigar
 
### Description

Hi. Is there any way for markduplicates to handle both cell barcodes (BC) and UMI (RX) tags? I know about UMIawareMarkDuplicatesWithMateCigar, but this one also considers the end of the fragments, along with start and UMI. I only want the start (of R1) and UMI to be considered. 

Thanks,
Vivek

**Comment by fleharty** [comment]
@vivekbhr 
It's not clear to me what you mean by "handle both cell barcodes and UMI tags".

My understanding of the way sequencing works, we want to deduplicate at the fragment level, so it isn't clear to me why you would want to deduplicate only by the start.  I don't think this is possible without making significant changes to the code.

**Comment by yfarjoun** [comment]
I believe that the @vivekbhr would like to treat the CB and the RX as two different barcodes and that two reads are duplicates of each other if they have the same coordinate, same RX **and also** same CB. This way you cannot have duplicates reads where one read came from one cell and the other from another cell.

**Comment by fleharty** [comment]
@vivekbhr @yfarjoun 
I see.  The request to treat CB as if it were another UMI has come up before.  I think the idea is so that fragments with the same start-stop positions, but different cell were treated as independent observations.

In principle this can certainly be done.  At the moment I don't have time available to work on this though, it could be a while before I can get to this.

**Comment by vivekbhr** [comment]
yes, the idea is same as @yfarjoun suggested, but I want to add that I want to use the CB and RX tags together with 5'-position of the fragment (which is 5'-pos of the R1 in the pair, for most illumina libraries). 

To use the CB and RX tag together, currently I am re-constructing a new tag in the sam file by concatenating the CB and RX and then specify that tag as the "barcode" tag to picard. However there seems to be no workaround to use the 5'-end of fragment only.

I want to use only the 5'-end as in the CelSeq2 library, the 3'-end of the same original molecule can map to multiple positions, so using both 5'-end and 3'-end would not collapse all true duplicates properly.

**Comment by yfarjoun** [comment]
I think you might need to write a new DuplicateMarker. using the DuplicateSetIterator, this should be relatively easy.....

**Comment by yfarjoun** [comment]
As a model you can look at `SimpleMarkDuplicateWithMateCigar`

**Comment by vivekbhr** [comment]
Thanks @yfarjoun. I'll check that out..
