### ISSUE TITLE
Number of sequences in text header (34216887) != number of sequences in binary header (182084669)

### ISSUE THREAD

**Issue by shimingtan** [broadinstitute/picard#1408]
Dear All,

I am trying to remove duplicates, but came across the following error:

`java -jar /gpfs1/scratch/shiming/tools/Picard/picard.jar MarkDuplicates M=1B131118A.marked_dup_metrics.txt REMOVE_DUPLICATES=true I=1B131118A.sorted.bam  O=1B131118A.bwa.dedupe.bam TMP_DIR=/gpfs1/scratch/shiming/tmp`

`htsjdk.samtools.SAMFormatException: Number of sequences in text header (34216887) != number of sequences in binary header (182084669) for file /gpfs1/scratch/shiming/April-Oct/Bowtie2/sam/sorted-bam/1B131118A.sorted.bam`

How do I overcome this error?

Thank You!

### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_Tool name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by yfarjoun** [comment]
it seems that your file is not self consistent. Not sure how you got into this state. I'd recommend passing your file through samtools view and create a new, valid bam before marking duplicates.

**Comment by shimingtan** [comment]
@yfarjoun, how do I verify is there is either a problem with my sam or bam file?

Thanks
