### ISSUE TITLE
CollectWgsMetrics per chromosome merge

### ISSUE THREAD

**Issue by Stikus** [broadinstitute/picard#1409]
Hello, thanks for great tools.
Recently we started to use Picard's CollectWgsMetrics tool, but due to it's single thread nature it's take too much time for run.
I tried to write simple code for xargs run using interval_list files for each chromosome and combine them after.
All good except that I don't fully understand to combine results - or maybe there are already any alternative to my approach?
CollectWgsMetrics result contains one line with 29 fields and 3 columns (`coverage	high_quality_coverage_count	unfiltered_baseq_count`).
These 3 columns combines easily - it is simple sum of all chromosomes results.
But for 29 fields I have some questions:
Header:

```
GENOME_TERRITORY | MEAN_COVERAGE | SD_COVERAGE | MEDIAN_COVERAGE | MAD_COVERAGE | PCT_EXC_ADAPTER | PCT_EXC_MAPQ | PCT_EXC_DUPE | PCT_EXC_UNPAIRED | PCT_EXC_BASEQ | PCT_EXC_OVERLAP | PCT_EXC_CAPPED | PCT_EXC_TOTAL | PCT_1X | PCT_5X | PCT_10X | PCT_15X | PCT_20X | PCT_25X | PCT_30X | PCT_40X | PCT_50X | PCT_60X | PCT_70X | PCT_80X | PCT_90X | PCT_100X | HET_SNP_SENSITIVITY | HET_SNP_Q
```
CHR10 Metrics
```
131314738 | 0,000001 | 0,000911 | 0 | 0 | 0 | 0,405512 | 0 | 0 | 0,165354 | 0 | 0 | 0,570866 | 0,000001 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
```
CHR17 Metrics
```
77795210 | 0,005583 | 0,390973 | 0 | 0 | 0 | 0,00075 | 0,10339 | 0 | 0,092142 | 0,197036 | 0 | 0,393318 | 0,000854 | 0,000214 | 0,000158 | 0,000125 | 0,000097 | 0,000075 | 0,000054 | 0,000023 | 0,000013 | 0,000008 | 0,000005 | 0,000001 | 0 | 0 | 0,000373 | 0
```
CHR10+CHR17 Metrics
```
209109948 | 0,002078 | 0,238487 | 0 | 0 | 0 | 0,000894 | 0,103354 | 0 | 0,092168 | 0,196966 | 0 | 0,393381 | 0,000318 | 0,000079 | 0,000059 | 0,000046 | 0,000036 | 0,000028 | 0,00002 | 0,000008 | 0,000005 | 0,000003 | 0,000002 | 0 | 0 | 0 | 0,000139 | 0
```
Fields:
* `GENOME_TERRITORY` is sum of all CHR## `GENOME_TERRITORY`.
* `MEAN_COVERAGE | SD_COVERAGE | MEDIAN_COVERAGE | MAD_COVERAGE` - I dont know how to merge.
* `PCT_EXC_ADAPTER | PCT_EXC_MAPQ | PCT_EXC_DUPE | PCT_EXC_UNPAIRED | PCT_EXC_BASEQ | PCT_EXC_OVERLAP | PCT_EXC_CAPPED` - [Description](https://broadinstitute.github.io/picard/picard-metric-definitions.html#CollectWgsMetrics.WgsMetrics) says that there are fractions but I cannot normalize them.
* `PCT_EXC_TOTAL ` - Sum of previous fields.
* `PCT_1X | PCT_5X | PCT_10X | PCT_15X | PCT_20X | PCT_25X | PCT_30X | PCT_40X | PCT_50X | PCT_60X | PCT_70X | PCT_80X | PCT_90X | PCT_100X` - these fields I can normalize: `PCT_1X _SUM=(SUM(PCT_1X _CHR##*GENOME_TERRITORY_CHR##))/GENOME_TERRITORY_SUM`.
* `HET_SNP_SENSITIVITY | HET_SNP_Q` - I dont know how to merge.

Can you give me any advices or links maybe?

**Comment by yfarjoun** [comment]
If you look at the code, you'll see that there's a .merge method that is
already implemented and knows how to merge results collected over
non-intersecting regions. The code is set-up to merge the metrics, so you
should be able to scatter the collection (using spark or regular multi
threading) and then pass the metric object and use the .merge() method to
combine various metrics.

Alternatively, you could write a MergeWGSMetrics command that will load up
the metrics files and call .merge() on them.

Or you could read the code and reimplement.

**Comment by Stikus** [comment]
Thank you for fast answer. I dont really know java but I'll look into code and check it.
`MergeWGSMetrics` is just suggested name for command, correct?

Can you point part oа code with merge method?
Do you talking about part, beginning here: [WgsMetrics.java#L216](https://github.com/broadinstitute/picard/blob/f64a8b980c623e8cfb640ecefbbfffa4070670a1/src/main/java/picard/analysis/WgsMetrics.java#L216).

I dont see anything about merge in [CollectWgsMetrics.java](https://github.com/broadinstitute/picard/blob/f64a8b980c623e8cfb640ecefbbfffa4070670a1/src/main/java/picard/analysis/CollectWgsMetrics.java), thats why I'm asking.

**Comment by yfarjoun** [comment]
`MergeWGSMetrics is just suggested name for command, correct?` Yes.
`Do you talking about part, beginning here: WgsMetrics.java#L216.` Yes.
