### ISSUE TITLE
picard CalculateHsMetrics not working with me

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#141]
Please help with this error! 
my lists start with the matchong .dict content followed by bed rows from SeqCapEZ_Exome_v3

java -jar /opt/biotools/picard/picard.jar CalculateHsMetrics BI=/opt/biodata/SeqCapEZ_Exome_v3/bait.list TI=/opt/biodata/SeqCapEZ_Exome_v3/target.list I=Patient1_results/Patient1_gatk.bam R=/opt/biodata/reference/human/GRCh37.73.fa O=test
[Mon Dec 22 22:11:52 CET 2014] picard.analysis.directed.CalculateHsMetrics BAIT_INTERVALS=[/opt/biodata/SeqCapEZ_Exome_v3/bait.list] TARGET_INTERVALS=[/opt/biodata/SeqCapEZ_Exome_v3/target.list] INPUT=Patient1_results/Patient1_gatk.bam OUTPUT=test REFERENCE_SEQUENCE=/opt/biodata/reference/human/GRCh37.73.fa    METRIC_ACCUMULATION_LEVEL=[ALL_READS] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Mon Dec 22 22:11:52 CET 2014] Executing as splaisan@r710bits on Linux 3.10.0-123.13.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.7.0_71-mockbuild_2014_10_03_09_36-b00; Picard version: 1.126(4691ee611ac205d4afe2a1b7a2ea975a6f997426_1417447214) IntelDeflater
[Mon Dec 22 22:11:53 CET 2014] picard.analysis.directed.CalculateHsMetrics done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=1515716608
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Invalid interval record contains 1 fields: track name=target_region description="Target Regions"
        at htsjdk.samtools.util.IntervalList.fromReader(IntervalList.java:367)
        at htsjdk.samtools.util.IntervalList.fromFile(IntervalList.java:293)
        at htsjdk.samtools.util.IntervalList.fromFiles(IntervalList.java:322)
        at picard.analysis.directed.CollectTargetedMetrics.doWork(CollectTargetedMetrics.java:87)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)

**Comment by splaisan** [comment]
Is there a picard equivalent to 
samtools view -h $bam chrN:from-to

apparently the (broad)picard samtools does not handle the region arguments

thanks!

Stephane Plaisance
stephane.plaisance@vib.be

**Comment by yfarjoun** [comment]
Please open a new ticket if you have another question.

Y.

On Tue, Jan 6, 2015 at 5:03 AM, Stephane Plaisance <notifications@github.com

**Comment by Rahel14350** [comment]
@splaisan @yfarjoun 
I did try to build the bait and target interval (using one time the headers from .bam file and one time with headers from mm10.dict) like this: 
m=0
for i in 'cat mm10_list.interval_list'   ;   \
do echo "$i"; echo "MPMPMP$m"; m=$(($m + 1)) ;  \
done > mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/\nMPMPMP/\ttarget_/g" mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/\r\t/\t/g" mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/:/\t/g" mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/-/\t/g" mm10_list.interval_list.tmp2
cat header.txt mm10_list.interval_list.tmp2 > mm10_list.interval_list.picard

 but I have still error while running calculateHSmetrics. Would you please let me know if the way I am building the bait and target files is correct? and I am using the same file for bait_interval and also target_interval, is this also correct?
Many thanks in advance,
Rahel

**Comment by yfarjoun** [comment]
please ask this question on the forum here: https://software.broadinstitute.org/gatk
