### ISSUE TITLE
paths continaing odd charaters not properly escaped in call to R

### ISSUE THREAD

**Issue by bwlang** [broadinstitute/picard#1412]
### Affected tool(s)
CollectMultipleMetrics (base_distribution_by_cycle maybe others too)

### Affected version(s)
- [x] Latest public release version [2.20.6]
- [ ] Latest development/master branch as of [date of test?]

### Description 
I see this error when I try to run   
```
picard -Xmx16g CollectMultipleMetrics     PROGRAM=CollectInsertSizeMetrics     PROGRAM=CollectGcBiasMetrics     PROGRAM=CollectSequencingArtifactMetrics      I='05-1%-1.md.bam' O='05-1%-1.md.bam' R='/mnt/galaxy/data/genome/grch38_full/bwa/GRCh38_full_analysis_set_plus_decoy_hla.fa'     VALIDATION_STRINGENCY=LENIENT
```

```
INFO  2019-10-15 13:11:35     RExecutor       Executing R script via command: Rscript /tmp/langhorst/script17683804813828027089.R 05-1%-1.md.bam.base_
distribution_by_cycle_metrics 05-1%-1.md.bam.base_distribution_by_cycle.pdf 05-1%-1.md.bam
  ERROR 2019-10-15 13:11:36     ProcessExecutor Error in pdf(outputFile) :
  ERROR 2019-10-15 13:11:36     ProcessExecutor   invalid 'file' argument '05-1%-1.md.bam.base_distribution_by_cycle.pdf'
  ERROR 2019-10-15 13:11:36     ProcessExecutor Execution halted
  [Tue Oct 15 13:11:36 EDT 2019] picard.analysis.CollectMultipleMetrics done. Elapsed time: 3.45 minutes.
  Runtime.totalMemory()=1342177280
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  Exception in thread "main" picard.PicardException: R script nucleotideDistributionByCycle.R failed with return code 1
        at picard.analysis.CollectBaseDistributionByCycle.finish(CollectBaseDistributionByCycle.java:139)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:164)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:597)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

note that running 
```
picard -Xmx16g CollectMultipleMetrics     PROGRAM=CollectInsertSizeMetrics     PROGRAM=CollectGcBiasMetrics     PROGRAM=CollectSequencingArtifactMetrics      I='05-1%-1.md.bam' O='05-1pct-1.md.bam' R='/mnt/galaxy/data/genome/grch38_full/bwa/GRCh38_full_analysis_set_plus_decoy_hla.fa'     VALIDATION_STRINGENCY=LENIENT
```
DOES work, so the problem is in the output file not the input file.

I think that path should be properly handled.

#### Steps to reproduce
name an output file with the % character

#### Expected behavior
should produce the file instead of the error.
All other tools in this pipeline handled the % character properly

#### Actual behavior
picard reports the error above

**Comment by yfarjoun** [comment]
nice find.....

**Comment by alanhoyle** [comment]
I'm getting this because our investigators want to name their samples with unusual characters (think slashes, parentheses, pipes, etc), and I thought it might be a good idea to use URLencoding to escape those characters, e.g. "hello (world)" would become "hello+%28world%29".  

WORKAROUND:  For the Output Filename, replace "%" with "%%" and it works!

**Comment by alanhoyle** [comment]
The underlying issue is that R's `pdf()` function must be doing something like a `printf()` on the filename, and `%` is a special character that needs to be escaped to output by a `printf()`/`sprintf()`/etc.  That's why the `%` to `%%` translation allows it to work.

**Comment by alanhoyle** [comment]
I did a bit of a deeper dive into this.  The issue is definitely in the R pdf() function and it's there by design there.  

``` R
$ R
R version 4.0.4 (2021-02-15) -- "Lost Library Book"
[...snip...]
> pdf ('hello%world.pdf')
Error in pdf("hello%world.pdf") :
  invalid 'file' argument 'hello%world.pdf'
> pdf ('hello%%world.pdf')
> dev.off()
null device
          1
> q('no')
$  ~ ls hello*.pdf
hello%world.pdf
```

The help for `pdf()` in R reads in part:  

> For use with ‘onefile = FALSE’ give a C integer format such
> as ‘"Rplot%03d.pdf"’ (the default in that case).

That is, `pdf()` is doing a `sprintf()` along the way to allow auto-enumeration for output PDF filenames.

**Comment by alanhoyle** [comment]
Would it be possible for someone at Broad to fix this?  I think it might require a "% -> %%" filter everywhere CHART_OUTPUT is used.

**Comment by alanhoyle** [comment]
I'm not much of a Java developer, but we would need to augment instances where we're requesting an R chart with a method that replaces of `%` with `%%`.

For example, most instances seem to have it this way:
    `CHART_OUTPUT.getAbsolutePath()` 
with
    `CHART_OUTPUT.getAbsolutePath().replace('%', '%%')`

That exists in six files in the Picard source tree that have that exact example:  

``` shell
$ find . -name *java |xargs grep "CHART_OUTPUT.getAbsolutePath()" 2>/dev/null | cut -f 1 -d :
./picard/src/main/java/picard/analysis/CollectGcBiasMetrics.java
./picard/src/main/java/picard/analysis/MeanQualityByCycle.java
./picard/src/main/java/picard/analysis/CollectBaseDistributionByCycle.java
./picard/src/main/java/picard/analysis/CollectRnaSeqMetrics.java
./picard/src/main/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverage.java
./picard/src/main/java/picard/analysis/QualityScoreDistribution.java
```

There are a few others places with RExecutor that appear to generate plots, but use different nomenclature:

* `./picard/src/main/java/picard/analysis/CollectRrbsMetrics.java` 
     `PLOTS_OUT.getAbsolutePath()`
* `./picard/src/main/java/picard/analysis/CollectInsertSizeMetrics.java`
     `Histogram_FILE.getAbsolutePath()`
* ./picard/src/main/java/picard/analysis/CollectAlignmentSummaryMetrics.java
     `HISTOGRAM_FILE.getAbsolutePath()`
