### ISSUE TITLE
Encountered a contig, chr1_gl000192_random that is not part of the target reference

### ISSUE THREAD

**Issue by jefferyUstc** [broadinstitute/picard#1416]
Hello,
I have download Bam files from TCGA,  and call sniffer using GATK，then I want to lift the VCF from hg38 to hg19 with code below:

```
java -XX:+UseSerialGC -Xmx20g -jar $PICARD LiftoverVcf \
   I="$file" \
   O="${file%%.*}_liftOver.vcf" \
   CHAIN=$liftOver_file \
   REJECT="${file%%.*}_rejected.vcf" \
   R=$hg19_fasta
```
and encountered an ERROR(similar but not the same as [#471):](https://github.com/broadinstitute/picard/issues/471):
```
ERROR	2019-10-23 **	LiftoverVcf	Encountered a contig, chr1_gl000192_random that is not part of the target reference.
```

And, when I check the VCF file with command `cat $file | grep chr1_gl000192_random`, There are nothing found! So, I do not know how can I solve this problem, hope your help, thank you in advance.

**Comment by jefferyUstc** [comment]
Some metadata in VCF shows below:
```
...
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
##contig=<ID=chrM,length=16569>
##contig=<ID=chr1_KI270706v1_random,length=175055>
##contig=<ID=chr1_KI270707v1_random,length=32032>
##contig=<ID=chr1_KI270708v1_random,length=127682>
##contig=<ID=chr1_KI270709v1_random,length=66860>
##contig=<ID=chr1_KI270710v1_random,length=40176>
##contig=<ID=chr1_KI270711v1_random,length=42210>
##contig=<ID=chr1_KI270712v1_random,length=176043>
##contig=<ID=chr1_KI270713v1_random,length=40745>
##contig=<ID=chr1_KI270714v1_random,length=41717>
##contig=<ID=chr2_KI270715v1_random,length=161471>
##contig=<ID=chr2_KI270716v1_random,length=153799>
...
##contig=<ID=chrUn_KN707724v1_decoy,length=1454>
##contig=<ID=chrUn_KN707725v1_decoy,length=2565>
##contig=<ID=chrUn_KN707726v1_decoy,length=2149>
##contig=<ID=chrUn_KN707727v1_decoy,length=2630>
##contig=<ID=chrUn_KN707728v1_decoy,length=14625>
##contig=<ID=chrUn_KN707729v1_decoy,length=7431>
##contig=<ID=chrUn_KN707730v1_decoy,length=5776>
##contig=<ID=chrUn_KN707731v1_decoy,length=4820>
##contig=<ID=chrUn_KN707732v1_decoy,length=1227>
##contig=<ID=chrUn_KN707733v1_decoy,length=7503>
##contig=<ID=chrUn_KN707734v1_decoy,length=9652>
...
```

**Comment by yfarjoun** [comment]
This seems to be a user-error, not a bug. could you post this on the GATK forum for a response that it more visible to others?

https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum

**Comment by rocreguant** [comment]
Encountered the same random error
`ERROR	2023-06-26 16:27:41	LiftoverVcf	Encountered a contig, chr11_KI270927v1_alt that is not part of the target reference.`

and when I grep the input file with that string (or even only the KI270927 nothing is found)

**Comment by timslittle** [comment]
Did you check the liftover/chain file for that string?

**Comment by valderpan** [comment]
Got the same error, `chr1_gl000192_random` is a contig in UCSC hg19 genome, you need to replace $hg19_fasta with UCSC hg19 fasta, which can be downloaded from the link below:
https://hgdownload.cse.ucsc.edu/goldenpath/hg19/bigZips/
