### ISSUE TITLE
liftover failed to recognize the swapped alleles

### ISSUE THREAD

**Issue by chenwenan** [broadinstitute/picard#1418]
### Affected tool(s)
picard LiftoverVcf

### Affected version(s)
2.21.2

### Description 
The input vcf variant:
chr18   63712604        TOPMed_freeze_5?chr18:63,712,604'03     G       T       255     PASS    VRT=1;NS=62784;AN=125568;AC=77256;AF=0.615252;Het=27816;Hom=24720 NA:FRQ  125568:0.615252

The failed vcf variant:
chr18   63712604        TOPMed_freeze_5?chr18:63,712,604'03     G       T       255     MismatchedRefAllele     AC=77256;AF=0.615252;AN=125568;AttemptedAlleles=G*->T;AttemptedLocus=chr18:61379838-61379838;Het=27816;Hom=24720;NS=62784;VRT=1   NA:FRQ  125568:0.615252

The chain file: hg38ToHg19.over.chain.gz

I think it finds the correct position, but somehow did not do the swap. 
Here is the snp info from dbsnp: https://www.ncbi.nlm.nih.gov/snp/rs4940595

Thanks

**Comment by yfarjoun** [comment]
Liftover doesn't swap REF and ALT alleles, there are too many annotations that would need to be updated for that to be done automatically. For example, in your provided variant, what the new AC be? what about Hom and in the format field NA & FRQ?

These need to be modified in a non-standard way.

**Comment by chenwenan** [comment]
Thanks for your quick reply. 

I am confused by this following document: 
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.0.0/picard_vcf_LiftoverVcf.php

for each variant, the tool will look for the target coordinate, reverse-complement and left-align the variant if needed, and, **in the case that the reference and alternate alleles of a SNP have been swapped in the new genome build, it will adjust the SNP, and correct AF-like INFO fields and the relevant genotypes.**

Is picard in GATK different from the picard here?

Thanks

**Comment by yfarjoun** [comment]
Hmmm. I guess I forgot about that functionality, but be careful with it due to the issues I mentioned. 

let me see what's going on.

**Comment by yfarjoun** [comment]
ah, I see did you run the tool with "RECOVER_SWAPPED_REF_ALT=true" ?

**Comment by chenwenan** [comment]
Yes, now it works. Can it set to be the default as explained in the GATK documentation?

Thanks.

**Comment by yfarjoun** [comment]
hmmm. the reason that it isn't the default is that it strongly depends on
the annotations that you have in your VCF. some of these would need to be
reversed and some become incorrect. To avoid *creating* bad data, we
decided to make this opt-in so that the user would know that they need to
do something in order to get the annotation modification. If you find the
documentation confusing or incorrect, please note this on the gatk forum.
