### ISSUE TITLE
MarkDuplicatesWithMateCigar crashes with >2B reads

### ISSUE THREAD

**Issue by leecbaker** [broadinstitute/picard#1426]
## Bug Report
When marking duplicates in a large file, a crash occurs after exactly 2,147,000,000 reads have been processed.

### Affected tool(s)
MarkDuplicatesWithMateCigar

### Affected version(s)
- [x] Latest public release version 2.21.3 downloaded from Github
- [ ] Latest development/master branch as of [date of test?]

### Description 
I'm processing a ~200GB sorted BAM. I've included relevant parts of the log inline below. The BAM is known to have been correctly sorted by samtools.

This looks suspiciously like an integer overflow of a signed 32 bit integer (e.g. Java's `int` type) when a 64 bit integer probably should have been used.

I can't upload the entire logfile as it's almost a gigabyte by itself. Some excerpts from the log file follow. Here is the command line given in the log file header:
`MarkDuplicatesWithMateCigar -I sorted_bams/<...>.bam.sorted.bam -M sorted_bams/<...>.metrics -O sorted_bams/<...>.mdup.bam -MAX_RECORDS_IN_RAM 1000000 -MINIMUM_DISTANCE 300 -TMP_DIR /mnt/temp/<...>`

Thousands of places in the log file, the following error is repeated. I have no idea if this is relevant to the crash. It looks like this may also be a bug as well, having to do with (perhaps) not handling paths correctly.

```
Could not delete file mnt
Could not delete file temp
Could not delete file diskbackedqueue.3514163575735271331.tmp
```

Just before the crash happens, here are the last status messages printed: 
```
INFO    2019-11-13 07:19:37     MarkDuplicatesWithMateCigar     Read 2,146,000,000 records.  Elapsed time: 15:35:46s.  Time for last 1,000,000:   21s.  Last read position: chr12:3,133,872
INFO    2019-11-13 07:19:38     MarkDuplicatesWithMateCigar     freeMemory: 63319838888; totalMemory: 66805825536; maxMemory: 66811068416; output buffer size: 178; duplicate queue size: 43
INFO    2019-11-13 07:19:58     MarkDuplicatesWithMateCigar     Read 2,147,000,000 records.  Elapsed time: 15:36:07s.  Time for last 1,000,000:   21s.  Last read position: chr12:4,269,685
INFO    2019-11-13 07:19:59     MarkDuplicatesWithMateCigar     freeMemory: 63265002544; totalMemory: 66793766912; maxMemory: 66811068416; output buffer size: 239; duplicate queue size: 76
```

At the end of the log file, here's the backtrace for the crash itself.
 
```
[Wed Nov 13 07:20:09 CST 2019] picard.sam.markduplicates.MarkDuplicatesWithMateCigar done. Elapsed time: 936.52 minutes.
Runtime.totalMemory()=66793766912
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: The records were added out of order
        at htsjdk.samtools.util.SamRecordTrackingBuffer.add(SamRecordTrackingBuffer.java:103)
        at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.addRecordToTheOutputBuffer(MarkDuplicatesWithMateCigarIterator.java:560)
        at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.markDuplicatesAndGetTheNextAvailable(MarkDuplicatesWithMateCigarIterator.java:435)
        at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.next(MarkDuplicatesWithMateCigarIterator.java:219)
        at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.next(MarkDuplicatesWithMateCigarIterator.java:47)
        at picard.sam.markduplicates.MarkDuplicatesWithMateCigar.doWork(MarkDuplicatesWithMateCigar.java:163)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

#### Steps to reproduce
Try running mark duplicates in a file with more than 2.2 billion reads. Here is the command line I am using:
`MarkDuplicatesWithMateCigar -I sorted_bams/<...>.bam.sorted.bam -M sorted_bams/<...>.metrics -O sorted_bams/<...>.mdup.bam -MAX_RECORDS_IN_RAM 1000000 -MINIMUM_DISTANCE 300 -TMP_DIR /mnt/temp/<...>`
Unfortunately the minimal test case is >100GB, so I can't easily send that, nor do I have authorization to distribute this data.

#### Expected behavior
No crash should occur.

#### Actual behavior
MarkDuplicatesWithMateCigar crashes after 15 hours processing a large input file. The error message states that the input BAM is not sorted properly, but the BAM is sorted correctly using Samtools.

**Comment by yfarjoun** [comment]
indeed it looks like an integer overflow bug. Any particular reason you are using this version of the tool and not the "regular" MarkDuplicates?

**Comment by yfarjoun** [comment]
hi @leecbaker Thanks for this report. 

I put in a possible fix in #1427, but I don't know how to test it since I'm not going to put a test that uses >2B reads and takes 17 hours to run.....

Would you be able to test this branch on your data and report back? You'll have to pull the branch and build picard on your own. If you have trouble with that, let me know and I can send you a compiled jar.

**Comment by leecbaker** [comment]
Thanks for changing this so quickly. We are using MarkDuplicatesWithMateCigar because it's believed to identify duplicates in more situations than MarkDuplicates, but I don't know how true that is. How mature is MarkDuplicatesWithMateCigar?

I can test it on the data that we have, but I don't have the time to build a jar. Can you email the jar to me? lee@leecbaker.com

**Comment by lbergelson** [comment]
@leecbaker If you have a very large bam file like this, you might want to look into using MarkDuplicatesSpark in GATK.  It should let you scale the job onto many cores to run in a more reasonable amount of time.

**Comment by yfarjoun** [comment]
I just shared the jar via dropbox.

Feel free to delete your email from the comment to avoid spam-bots from
picking it up.

As far as I know the results of the various markDuplicates variants should
be identical (the testing suite is essentially the same, for example), so
you should choose the version that fits your needs in terms of runtime,
cost, streaming ability, etc.

We'd love to hear back once you know more.

**Comment by leecbaker** [comment]
Hi @yfarjoun , Sorry for taking so long to get back to you- I'll test it out over the next 24h and let you know how it works.

**Comment by yfarjoun** [comment]
thanks!

**Comment by leecbaker** [comment]
Looks like it finished successfully with 4.15B reads. Took 1650 minutes. I think this means the fix worked.

**Comment by yfarjoun** [comment]
Great. Thanks for checking.
