### ISSUE TITLE
Correct  command line syntax help

### ISSUE THREAD

**Issue by xiucz** [broadinstitute/picard#1432]
Hi, what is the correct command line for picard's MarkDuplicates?
```
java -jar ~/picard/2.21.3/picard.jar MarkDuplicates I=sample.bam  M=sample.mkdp.bam.metrics.txt O=sample.mkdp.bam
INFO    2019-11-22 11:08:42     MarkDuplicates

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicates -I sample.bam -M sample.mkdp.bam.metrics.txt -O sample.mkdp.bam
**********
```
Thank you.

**Comment by xiucz** [comment]
And one more question I cannot find the TMP-DIR option now, was it removed ?

**Comment by cmnbroad** [comment]
@xiucz If you're asking about which syntax to use, the one you used above is fine. The message you see being output is just a warning that an alternative syntax that will become the default in the future. The `TMP_DIR` option has an underscore, not a hyphen. Hope that helps.
