### ISSUE TITLE
CrossCheck fingerprint is not symmetric (A vs. B != B vs. A)

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#1437]
## Bug Report
It has been reported to me (and I've confirmed) that CrosscheckFingerprints is not symmetric when comparing A to B and B to A. This seems to be due to two separate issues:

1. There's a bug that was introduced during refactoring whereby the prior isn't applied correctly 
2. The abundance of applications of the log function seems to cause floating point errors which depend on the order of operations and therefore are not symmetric.

While 1. is relatively easy to fix (I have a fix on a branch) the tests are failing due to 2. which I do not plan to fix. I will likely need to introduce some leniency in the test due to 2.

**Comment by dmcmanam** [comment]
With Picard 2.21.3, for one example I see a A->B LOD of -2.73 and B->A LOD of -2.11 so users should be prepared for rather large differences in LOD scores.

**Comment by yfarjoun** [comment]
The PR that fixes this is ready...I just need a code review.... #1455 @pshapiro4broad ?
