### ISSUE TITLE
Liftover Issue for HGDP panel

### ISSUE THREAD

**Issue by Anahit19** [broadinstitute/picard#1452]
**Tool(s) involved** 

Picard LiftoverVcf

**Affected version(s)**
Picard 2.21.6; Picard 2.21.4

**Description** 

I`ve run the following code with the HGDP panel vcf files: (ftp://ngs.sanger.ac.uk/production/hgdp/hgdp_wgs.20190516/). 

java -jar /storage/software/picard/picard.jar LiftoverVcf I=HGDP_CHR21.vcf O=LIFTOVER_CHR21.vcf CHAIN=/HGDP/vcf/hg38ToHg19.over.chain REJECT=rejected_variants.vcf R=/HGDP/vcf/GRCh38_full_analysis_set_plus_decoy_hla.fa

Reference: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa

**ERROR**

INFO    2020-01-16 17:20:57     LiftOver        Interval chr21:5033837-5033966 failed to match chain 210 because intersection length 4 < minMatchSize 130.0 (0.03076923 < 1.0)
INFO    2020-01-16 17:20:57     LiftOver        Interval chr21:5033929-5033972 failed to match chain 210 because intersection length 3 < minMatchSize 44.0 (0.06818182 < 1.0)
INFO    2020-01-16 17:20:57     LiftOver        Interval chr21:5049396-5049400 failed to match chain 210 because intersection length 4 < minMatchSize 5.0 (0.8 < 1.0)
INFO    2020-01-16 17:20:57     LiftOver        Interval chr21:5051123-5051124 failed to match chain 210 because intersection length 1 < minMatchSize 2.0 (0.5 < 1.0)
INFO    2020-01-16 17:20:57     LiftOver        Interval chr21:5051464-5051518 failed to match chain 210 because intersection length 51 < minMatchSize 55.0 (0.92727274 < 1.0)
INFO    2020-01-16 17:20:58     LiftOver        Interval chr21:5066673-5066675 failed to match chain 210 because intersection length 2 < minMatchSize 3.0 (0.6666667 < 1.0)
INFO    2020-01-16 17:20:58     LiftOver        Interval chr21:5067051-5067054 failed to match chain 210 because intersection length 3 < minMatchSize 4.0 (0.75 < 1.0)
INFO    2020-01-16 17:20:58     LiftOver        Interval chr21:5101922-5101924 failed to match chain 210 because intersection length 1 < minMatchSize 3.0 (0.33333334 < 1.0)
INFO    2020-01-16 17:20:58     LiftOver        Interval chr21:5103758-5103766 failed to match chain 210 because intersection length 1 < minMatchSize 9.0 (0.11111111 < 1.0)
INFO    2020-01-16 17:20:58     LiftOver        Interval chr21:5114110-5114310 failed to match chain 210 because intersection length 157 < minMatchSize 201.0 (0.78109455 < 1.0)
INFO    2020-01-16 17:20:58     LiftOver        Interval chr21:5114302-5114422 failed to match chain 210 because intersection length 70 < minMatchSize 121.0 (0.5785124 < 1.0)
INFO    2020-01-16 17:20:58     LiftOver        Interval chr21:5134181-5134182 failed to match chain 210 because intersection length 1 < minMatchSize 2.0 (0.5 < 1.0)
ERROR   2020-01-16 17:20:58     LiftoverVcf     Encountered a contig, chr9_gl000198_random that is not part of the target reference.

Thanks!

**Comment by chengdai** [comment]
Stumbled upon this while trying to find the answer to a separate unrelated issue with LiftOverVCF, but I want to point out that your reference file is incorrect. Your reference genome (R=reference.fa) should be the _target_ build you want to convert to, not your original one. That is, a command should be like `java -jar picard.jar LiftoverVcf I=input_original_build.vcf O=output_target_build.vcf CHAIN=original_to_target.over.chain REJECT=target_reject.vcf R=target_reference.fa`

See: https://gatk.broadinstitute.org/hc/en-us/articles/360037060932-LiftoverVcf-Picard-
