### ISSUE TITLE
Memory Issues with VcfToIntervalList

### ISSUE THREAD

**Issue by skwalker** [broadinstitute/picard#1454]
### Affected tool(s)
VcfToIntervalList

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest development/master branch as of [date of test?]

### Description 
Need a ridiculous amount of memory to run VcfToIntervalList because it's holding all of the intervals in memory.

#### Steps to reproduce
Run `VcfToIntervalList` on a large vcf (ex: 5G gzipped vcf), requires >30G of memory
`java -jar picard.jar VcfToIntervalList I=${large_vcf} O=${smaller}.interval_list`

#### Expected behavior
Shouldn't use this much memory 

#### Actual behavior
Uses a ton of memory because it's storing all the intervals in memory. Yossi says "You need to do the sorting and merging in the CLP itself using a disk-backed sorting collection and then merge the intervals as you write them... avoid using the IntervalList object"

**Comment by lbergelson** [comment]
Isn't a vcf pre-sorted by definition?

**Comment by yfarjoun** [comment]
besides the point...the intervals need to be joined and the Object that
does that in htsjdk wants all the intervals to be in memory...
