### ISSUE TITLE
UmiAwareMarkDuplicatesWithMateCigar random error 

### ISSUE THREAD

**Issue by sybrohee** [broadinstitute/picard#1459]
----

### Affected tool(s) 
UmiAwareMarkDuplicatesWithMateCigar

### Affected version(s)
- [ ] picard/2.18.16
- [ ] picard/2.27.7

### Description 
When running the UmiAwareMarkDuplicatesWithMateCigar tool, it sometimes produces the following error.

`java -jar picard.java UmiAwareMarkDuplicatesWithMateCigar I=input.bam CREATE_INDEX=true UMI_METRICS=md_metrics M=output.txt OUTPUT=test.bam ASSUME_SORT_ORDER=coordinate TAG_DUPLICATE_SET_MEMBERS=true MAX_RECORDS_IN_RAM=400000`

```
Exception in thread "main" htsjdk.samtools.SAMException: The input records were not sorted in duplicate order:
MN00975:67:000H2WVYG:1:21110:2374:3570  147     chr3    128485830       60      151M    =       128485833       -148       AGTCGCCGGCACTTAGGAGGGGTAGGTGGGGATGGGGTGGTGTGTAGCAGGCTGGGTGCCCATAGTAGCTAGGCCTGGGCGCAGGGGACTGCCACTTTCCATCTTCATGCTCTCCGTCAGTGACACCTGGTACTTGACGCCGTCCTTGTCC    //FF/A/FF6/=////F/A6=F//FFFFFF=FFFA/=/FFF/F/FFF/FFF//FFFFAFFFFFFFFFF/FFFF/AAFAF/AFFFF/AAFFF//FFF6FFF6F6FFF/FFFFFF//F/FA/FFAAF//F/FFFFFFFF/FFA/6F6AAF//A    MC:Z:13S130M    MD:Z:2C9A138       RG:Z:000H2WVYG.AE4441.L001      NM:i:2  MQ:i:60 AS:i:143        XS:i:0  QX:Z:FFFFFFFF   RX:Z:ACCCTATA
MN00975:67:000H2WVYG:1:11107:15346:8737 163     chr1    153346  0       10S40M21S       =       153346  40      AGCACCATCACCACTTACCTTGTCCTGTGCATCTCTTTCATTGGCTGTTCACTCCTGGCGGTTATCGGTAA    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFFFFFFFFFFFFAF    MC:Z:10S40M13S  MD:Z:40 RG:Z:000H2WVYG.AE4441.L001      NM:i:0  MQ:i:0  AS:i:40 XS:i:40    QX:Z:FFFFFFFA   RX:Z:ATCGGTAA

        at htsjdk.samtools.DuplicateSetIterator.next(DuplicateSetIterator.java:152)
        at picard.sam.markduplicates.UmiAwareDuplicateSetIterator.next(UmiAwareDuplicateSetIterator.java:119)
        at picard.sam.markduplicates.UmiAwareDuplicateSetIterator.next(UmiAwareDuplicateSetIterator.java:53)
        at picard.sam.markduplicates.SimpleMarkDuplicatesWithMateCigar.doWork(SimpleMarkDuplicatesWithMateCigar.java:126)
        at picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar.doWork(UmiAwareMarkDuplicatesWithMateCigar.java:138)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

#### Steps to reproduce
This error does not appear only on this file nor it happens every time I run the command, it happens from time to times. I ran a lot of tests and it generally happens every 10 tests iteration of the tool.

#### Expected behavior

A bam file with marked umi-duplicated reads

#### Actual behavior

An empty bam file and a java exception.

Thank you all for your help and for the great work you've been doing developing Picard.
----

**Comment by fleharty** [comment]
@sybrohee 
Are you claiming this is an intermittent error?  How is your bam sorted?

Could you make a small version of your input.bam that exhibits this issue and make it available to me somewhere?

**Comment by sybrohee** [comment]
@fleharty 
Thank you for your fast answer considering my issue. Indeed, I think this is an intermittent error, i.e, I tested 50 times the same command on the same input files and I got this error 3 to 4 times. This is why I think it does not have anything to do with the type of sort (but I tested it both with `picard SortSam` as well as `samtools sort`).

I hereby attach a file on which the following command generally works but also fails a few time.
`
java -jar picard.java UmiAwareMarkDuplicatesWithMateCigar I=umi_sample.bam CREATE_INDEX=true UMI_METRICS=md_metrics M=umi_sample_mdmetrics.txt OUTPUT=umi_sample_md.bam  ASSUME_SORT_ORDER=coordinate TAG_DUPLICATE_SET_MEMBERS=true MAX_RECORDS_IN_RAM=400000`

https://www.dropbox.com/s/i01231jvqgcnyxz/umi_sample.bam?dl=0

Note that (as these are private data), I took the liberty to randomize the sequence (so the sequence and the position do not correspond to actual position in the hg38 genomic build).

Again, many thanks for your help.

**Comment by abolia** [comment]
Hi, 
We are getting same errors on our bam file that it coordinate sorted and we are providing the parameter "ASSUME_SORT_ORDER=coordinate " while running picard UmiAwareMarkDuplicatesWithMateCigar. Did you find what was causing the issue and how this can be resolved. Thank you.

**Comment by fleharty** [comment]
@abolia @sybrohee Sorry for not getting back to this earlier.  I'm trying to understand the cause.  I've done a few preliminary checks, and it's not obvious to me what the problem is yet.

**Comment by abolia** [comment]
@fleharty Based on what we found out so far, this seems to be an issue with more recent versions (we used 2.21.4). We have been running 2.11 earlier on the same bam files and never had an issue. Also, I thought sorting with Picard sortsam will fix the issue but that didn't seem to solve the problem either. Its an intermittent issue. Doesnt happen every time on each case but its just random as @sybrohee mentioned as well.

**Comment by yfarjoun** [comment]
random indicates to me that it might be machine-dependent….are you running
this in the cloud, or on your own computer?

**Comment by fleharty** [comment]
@abolia Thanks.  It's strange that it is intermittent.  On my machine it happens everytime.

**Comment by abolia** [comment]
@yfarjoun We have tried running it on both cloud and locally. It throws error on both. @fleharty What I meant to say was it doesnt happen on each and every sample, it just happened in few samples out of a bunch that we ran. But they were all processed exactly same, so not sure why its happening on those and not the others.

**Comment by sybrohee** [comment]
I would add that we encountered this issue with older version of Picard as well (2.18). Moreover, I tested both versions on very different machines : my laptop and our HPC cluster that run different JVM, so it does not seem to be linked to the machine.

**Comment by fleharty** [comment]
@sybrohee Thanks.  I don't think this has anything to do with hardware.  I suspect that there is a bug, and I'm trying to figure out where it is.

**Comment by fleharty** [comment]
@sybrohee @abolia I have been investigating this a bit, and the issue is in fact intermittent.  While debugging, I noticed that the error occurs in different parts of the bam.  I'm not sure why yet, but I'll keep you updated as I understand more.

**Comment by fleharty** [comment]
Per @yfarjoun 's comment on another thread.

It seems that this bug is related to multithreading race condition in samtools/htsjdk#1516. Now that this has been identified, I think a fix will be forthcoming.

**Comment by abolia** [comment]
Thanks for the update @fleharty

**Comment by fleharty** [comment]
@abolia An update has been made to HTSJDK that resolves this bug.  We are just waiting for a release of htsjdk and then a subsequent release of Picard to get a working version for you.

**Comment by sybrohee** [comment]
> @abolia An update has been made to HTSJDK that resolves this bug. We are just waiting for a release of htsjdk and then a subsequent release of Picard to get a working version for you.

Great. Thank you.
Will you tell us when this new Picard version will be available?
Thank you again.

**Comment by fleharty** [comment]
@sybrohee yes, I'll be sure to update this issue when it becomes available.

**Comment by sybrohee** [comment]
Great... many thanks

**Comment by kockan** [comment]
Should be long resolved at this point by https://github.com/samtools/htsjdk/issues/1516
