### ISSUE TITLE
extract one chromosome from a BAM

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#146]
Hi,
Is there a picard equivalent to 
samtools view -h $bam chrN:from-to
apparently the (broad)picard ''ViewSam'' command does not handle the region arguments commonly used with samtools view

thanks!

**Comment by vdauwera** [comment]
AFAICT from the documentation, Picard does not seem to provide the capability to run on restricted regions like samtools or GATK. Some tools can take an intervals file but that's not the same thing. 

@nh13 Can you please confirm or provide a correction?

**Comment by nh13** [comment]
You are correct that this functionality does not exist in ```ViewSam``` and not all tools take interval lists.  It would not be hard to add a command line option to ```ViewSam``` to subset to a specific region.

**Comment by vdauwera** [comment]
I'll put in a feature request for this.
