### ISSUE TITLE
Bug Report: MergeBamAlignment Error: "String tag does not have length() == 2: Cross-species contamination | CO"

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/picard#1462]
User Report:

Hi,

I ran the GATK4 genome analysis pipeline on a uBam (H06HDADXX130110.1.ATCACGAT.20k_reads.bam) available from the broad public data sets.

The pipeline ran successfully producing vcfs, aligned BQSR bams and cram.

I converted the resulting cram file to ubam using samtools and RevertSam as follows:

samtools view -h ${cram} -T ${ref_fasta} -o /dev/stdout | \
java -Xms4000m -jar /usr/gitc/picard.jar RevertSam \
I=/dev/stdin \
O=${ius}.unmapped.bam \
MAX_DISCARD_FRACTION=0.005 \
ATTRIBUTE_TO_CLEAR=XT \
ATTRIBUTE_TO_CLEAR=XN \
ATTRIBUTE_TO_CLEAR=AS \
ATTRIBUTE_TO_CLEAR=OC \
ATTRIBUTE_TO_CLEAR=OP \
RESTORE_ORIGINAL_QUALITIES=true \
REMOVE_DUPLICATE_INFORMATION=true \
REMOVE_ALIGNMENT_INFORMATION=true
The options for RevertSam were chosen as specified in https://gatkforums.broadinstitute.org/gatk/discussion/6484 

I ran this new uBam through the GATK4 pipeline again but during the MergeBamAlignment step, in 'SamToFastqAndBwaMemAndMba' I get this error:

Exception in thread "main" java.lang.IllegalArgumentException: String tag does not have length() == 2: Cross-species contamination | CO
I couldn't find any information regarding this error. I assumed it had to do something with the read group information in the uBam. So I had a look at the read group information of the uBam that was converted from cram and the original ubam. There were the same. 

Can someone please explain what the "String tag does not have length() == 2: Cross-species contamination | CO" error means?

Is there also a better way to go from cram to ubam?

My goal is to process cram files, that were aligned to hg19, with the GATK4 hg38 pipeline.

Thanks in advance for your help.

----

In reference to forum thread: https://gatk.broadinstitute.org/hc/en-us/community/posts/360056504312-MergeBamAlignment-Error-String-tag-does-not-have-length-2-Cross-species-contamination-CO-

----

Discussed this at the GATK office hrs and this seems to be a bug in the Picard code. 

@lbergelson would you like to add to this?

**Comment by lbergelson** [comment]
#1461 is a fix for this issue.

**Comment by bioinfo-fiend** [comment]
@lbergelson was this issue resolved, as I am coming across the same error as user @bhanugandham after RevertSam has been implemented

**Comment by lbergelson** [comment]
Hi @bioinfo-fiend.  The fix I implemented stopped us from continuing to write corrupt data in this case.  If you're seeing the exact same issue is it possible your data has been processed with a version of picard from before the fix went in?

If you're seeing a similar but not identical error message, could you post the exact error message you're getting?  It's possible something else has a similar bug that is triggering the same error condition.

**Comment by bioinfo-fiend** [comment]
Thank you for the response, I've realized that I was running an older version of Picard. Have run with updated fix. Thanks for the response

**Comment by lbergelson** [comment]
👍 My favorite type of issue, one that's already solved :)
