### ISSUE TITLE
MarkDuplicates should check for @RG header

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/picard#1488]
### Tool(s) involved
MarkDuplicates

### Description
If an input bam/cram is provided to MarkDuplicates that does not contain a `@RG` header line, then MarkDuplicates should log a warning or throw an error.

See also https://github.com/broadinstitute/gatk/issues/6501

**Comment by yfarjoun** [comment]
Given that the RG requirement is a GATK BestPractices, not in the Sam-Spec, I hesitate to add this requirement here. 
ValidateSamFile will (by default) Error out if there are no read groups, and additionally, if a record doesn't contain an RG tag pointing to a valid readgroup....so a simpler solution would be to add ValidateSamFile to the beginning of the pipeline. I don't think that going down the path of adding all the validation checks and error messages to all the tools makes sense.

**Comment by ldgauthier** [comment]
I thought the spec said RG was required. Does it mean that if RG is present
then it must have an ID field?

**Comment by yfarjoun** [comment]
No it isn't required...technically it seems that even the @HD line is not required.... :-/
