### ISSUE TITLE
CollectHSMetrics - does the Bait interval is the Covered file of Agilent?

### ISSUE THREAD

**Issue by adily777** [broadinstitute/picard#1490]
### Tool(s) involved
CollectHsMetrics, according to BAIT_INTERVALS

### Description 
The BAIT_INTERVALS is an interval list file that contains the locations of the baits used, as explined here: https://gatk.broadinstitute.org/hc/en-us/articles/360036856051-CollectHsMetrics-Picard-

So this argument should get the Covered.bed file of Agilent? or it can get the Target.bed? 
And the TARGET_INTERVALS, should it get the Regions.bed or it can also get the Covered.bed?

Description by Agilent:
[design ID]_Regions.bed - This BED file contains a single track of the target regions of interest that SureDesign used to select the probes.
[design ID]_Covered.bed - This BED file contains a single track of the genomic regions that are covered by one or more probes in the design

If I give both of them the Covered.bed the results (hsmetrics and pertarget files) will be unreliable?

Thank you,
Adily

**Comment by yfarjoun** [comment]
since "Probes" and "Baits" are efectively the same thing, I would conclude,
from Agilent's description that you want to use  _Covered for BAITS and
_Covered for TARGETS.

**Comment by adily777** [comment]
But why _Covered for TARGETS? 
At the description of the TARGET_INTERVALS argument it says: An interval list file that contains the locations of the **targets**. Not what covered, the targets regions are included inside what covered

**Comment by yfarjoun** [comment]
Yes. you are right. that's what I meant, but wrote it incorrectly. editing it directly.

**Comment by adily777** [comment]
Thank you!
