### ISSUE TITLE
failed to filter reads using filterreads from a cram file

### ISSUE THREAD

**Issue by jainy** [broadinstitute/picard#1498]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_FilterSamReads, special parameters?FILTER=includeReadList INPUT=XYZ.cram_

### Affected version(s)
- [2.22.3 ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_ERROR	2020-04-16 16:07:05	FilterSamReads	Failed to filter XYZ.cram
htsjdk.samtools.cram.CRAMException: Contig chr1 not found in the reference file.
	at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:174)
	at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:258)
	at htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:591)
	at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:70)
	at htsjdk.samtools.util.PeekableIterator.<init>(PeekableIterator.java:38)
	at htsjdk.samtools.filter.FilteringSamIterator.<init>(FilteringSamIterator.java:80)
	at picard.sam.FilterSamReads.doWork(FilterSamReads.java:316)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
[Thu Apr 16 16:07:05 MDT 2020] picard.sam.FilterSamReads done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2058354688
._

#### Steps to reproduce
_/home/jainy/software/picard-2.22.3/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Apr 16 16:07:04 MDT 2020] FilterSamReads INPUT=PISI.cram FILTER=includeReadList READ_LIST_FILE=processcramtest/Allreadsforbam/sample_non-reference_file/PPMISI4110.allreadIDs.txt OUTPUT=processcramtest/Allreadsforbam/sample_non-reference_file/PPMISI4110.allreadIDs.bam WRITE_READS_FILES=false VALIDATION_STRINGENCY=LENIENT    VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false._

#### Expected behavior
_should extracts reads listed in the readlistfile from cram file and output to bam_

#### Actual behavior
_Instead it gives the error mentioned above,

Few lines from cram:
MG01HX02:466:H7HLGALXX:4:2213:31538:9185	99	chr1	64946	25	151M	=	65202	407	AACACAACTGAGACATCACTTGGATGTATTCCTATGACTATTTTAAGAAACATAAATTGTGGTGACTCACTCAGCTCACTTTTAACTACTGCATGGTAATTAAAGATGCAAAATAAAATAAGTTACAAGAAGTGAGGTTTTTTATTGGTTA	????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????5???+??????????????????	MC:Z:151M	MQ:i:25	AS:i:151	MD:Z:151	NM:i:0	RG:Z:PPMISI4110_H7HLG_L004
MG01HX02:466:H7HLGALXX:3:1101:15564:1731	147	chr1	64971	45	151M	=	64635	-487	GTATTCCTATGACTATTTTAAGAAACATAAATAGTGGTGACTCACTCAGCTCACTTTTAACTACTGCATGGTAATTAAAGATGCAAAATAAAATAAGTTACAAGAAGTGAGGTTTTTTATTGGTTAAAGCAATTTTTCTATATTTTCTCCG	???????5??+???????????????+555+55??????????5'5???????5?5?????????????+????????????5?????+????????????+????55????5???????????????????????????????55???5?	MC:Z:151M	MQ:i:57	AS:i:146	MD:Z:32T118	NM:i:1	RG:Z:PPMISI4110_H7HLG_L003
MG01HX02:466:H7HLGALXX:2:1213:19187:47105	147	chr1	64974	7	151M	=	64760	-365	TTTCTATGACTATTTTAAGAAACATAAATTGTGGTGACTCACTCAGCTCACTTTTAACTACTGCATGGTAATTAAAGATGCAAAATAAAATAAGTTACAAGAAGTGAGGTTTTTTATTGGTTAAAGCAATTTTTCTATATTTTCTCCGCAA	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:151M	MQ:i:7	AS:i:148	MD:Z:2C148	NM:i:1	RG:Z:PPMISI4110_H7HLG_L002

 _

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by yfarjoun** [comment]
The error is a little cryptic...did you give it the reference? there's a
REFERENCE_SEQUENCE argument you should probably use when using cram files.

**Comment by jainy** [comment]
Thank you! it worked when I gave the REFERENCE_SEQUENCE argument
