### ISSUE TITLE
Where do I find CreateSequenceDictionary.jar?

### ISSUE THREAD

**Issue by ginarific** [broadinstitute/picard#152]
Hi,

I've installed picard and have picard.jar in my dist/ directory. However, I'm trying to find CreateSequenceDictionary.jar and cannot locate it.

I can find CreateSequenceDictionary.java in src/java/picard/sam but not the .jar file. Am I supposed to manually compress it myself? Or are there additional installation procedures for creating the .jar file?

Finally, I'd like to express my frustration for how ridiculously little information I've been able to find in the documentation. I'm really unfamiliar with Java, and I'm not sure why it's assumed that we'd be familiar with it when working with Picard.

Thanks.

**Comment by geoffjentry** [comment]
Hi -

There's not a separate CreateSequenceDictionary.jar although it exists in
the picard fat jar. To run it from the command line, run "java -jar
/path/to/picard.jar CreateSequenceDictionary".

On the latter point, I don't think it's asking too much to assume that
someone using a library is at least somewhat familiar with the language the
library is for. If there are specific bits of doc which you think would be
helpful either ask here or if you already know the answer submit a pull
request w/ the extra doc.

J

**Comment by vdauwera** [comment]
Ginarific: For future reference, the doc page that answers your usage
question is here:

http://broadinstitute.github.io/picard/command-line-overview.html#Overview

With that, you can run any Picard command, and there is no need for you to
know anything about the Java language.

Best,
Geraldine

On Mon, Jan 19, 2015 at 2:46 PM, Jeff Gentry <notifications@github.com>
wrote:

> Hi -
>
> There's not a separate CreateSequenceDictionary.jar although it exists in
> the picard fat jar. To run it from the command line, run "java -jar
> /path/to/picard.jar CreateSequenceDictionary".
>
> On the latter point, I don't think it's asking too much to assume that
> someone using a library is at least somewhat familiar with the language
> the
> library is for. If there are specific bits of doc which you think would be
> helpful either ask here or if you already know the answer submit a pull
> request w/ the extra doc.
>
> J
>
> On Mon, Jan 19, 2015 at 1:03 PM, ginarific <notifications@github.com>
> wrote:
>
> > Hi,
> >
> > I've installed picard and have picard.jar in my dist/ directory.
> However,
> > I'm trying to find CreateSequenceDictionary.jar and cannot locate it.
> >
> > I can find CreateSequenceDictionary.java in src/java/picard/sam but this
> > not the .jar file. Am I supposed to manually compress it myself? Or are
> > there additional installation procedures for creating the .jar file?
> >
> > Finally, I'd like to express my frustration for how ridiculously little
> > information I've been able to find in the documentation. I'm really
> > unfamiliar with Java, and I'm not sure why it's assumed that we'd be
> > familiar with it when working with Picard.
> >
> > Thanks.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/broadinstitute/picard/issues/152>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/picard/issues/152#issuecomment-70549700>
> .
>



-- 
Geraldine A. Van der Auwera, Ph.D.
Bioinformatics Scientist II
GATK Support & Outreach
Broad Institute

**Comment by materechm** [comment]
Was having the same problem and found that if you download the latest Picard version from sourceforge, it actually contains CreateSequenceDictionary.jar

**Comment by nh13** [comment]
Sourceforge contains previous releases.  The latest releases can be found
on github: http://broadinstitute.github.io/picard/

N
