### ISSUE TITLE
ValidateSamFile

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/picard#1533]
I run : 
java -jar /Users/mac/Downloads/picard-2.jar ValidateSamFile \   I=/Users/mac/Desktop/NGS/SRR639642.bam \ MODE=SUMMARY
I got : The command line looks like this in the new syntax:
**********
**********    ValidateSamFile   -I /Users/mac/Desktop/NGS/SRR639642.bam - MODE SUMMARY
**********

ERROR: Invalid argument ' '.

**Comment by yfarjoun** [comment]
extra space?

**Comment by elbakrifz** [comment]
I run this java -jar /Users/mac/Downloads/picard-2.jar ValidateSamFile \   I=/Users/mac/Desktop/NGS/SRR639642.bam \ MODE=SUMMARY
 but still the same error

**Comment by elbakrifz** [comment]
the problem is also with AddOrReplaceReadGroups andCollectAlignmentSummaryMetrics, and it was working create sequence dictionary, what should I do ?!

**Comment by cmnbroad** [comment]
@elbakrifz If you use the line continuation character ("\"), it must have a space before it, and a newline immediately following it.

**Comment by cmnbroad** [comment]
Closing as user error. See the suggested fix in  https://github.com/broadinstitute/picard/issues/1544.
