### ISSUE TITLE
AddOrReplaceReadGroup

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/picard#1534]
I run :    java -jar /Users/mac/Downloads/picard-2.jar  AddOrReplaceReadGroups\                                           I=/Users/mac/Desktop/SRR639642.bam  \          
 O=SRR63964RG.bam \                                                                                  
    RGID=FLOWCELL1 \                                                                                             
  RGLB=lib1 \                                                                                                
    RGPL=ILLUMINA \                                                                                                
RGPU=unit1 \ 
I got: AddOrReplaceReadGroups ' is not a valid command. See PicardCommandLine -h for more information.
Did you mean this?
        AddOrReplaceReadGroups

**Comment by yfarjoun** [comment]
the slash is too close to the AddOrReplaceReadGroups and there's a space after it.

try
```
java -jar /Users/mac/Downloads/picard-2.jar AddOrReplaceReadGroups \ 
I=/Users/mac/Desktop/SRR639642.bam \
O=SRR63964RG.bam \
RGID=FLOWCELL1 \
RGLB=lib1 \
RGPL=ILLUMINA \
RGPU=unit1 
```

**Comment by elbakrifz** [comment]
I'm trying to follow your advise , I hope that's gonna be workable

**Comment by elbakrifz** [comment]
I had the same PROB              (base) Air-de-mac:NGS mac$ java -jar /Users/mac/Downloads/picard-2.jar AddOrReplaceReadGroups \                                   I=/Users/mac/Desktop/NGS/SRR6369659.bam \                                                              O=SRR6369659RG.bam \                                                                                   RGID=4 \                                                                                               RGLB=lib1 \                                                                                            RGPL=ILLUMINA \                                                                                        RGPU=unit1 \                                                                                           RGSM=20

**Comment by yfarjoun** [comment]
please run without any slashs and report back.

**Comment by elbakrifz** [comment]
I run it like the answers ask for The command line looks like this in the new syntax:
**********
**********    AddOrReplaceReadGroups   -I /Users/mac/Desktop/NGS/SRR6369659.bam   -O /Users/mac/Desktop/NGS/SRR6369659RG.bam   -RGID C7BDWACXX.7   -RGLB lmj_1948_EP_run1   -RGPL illumina   -RGPU C7BDWACXX.7   -RGSM N08162939
**********

 the commande’s running :java -jar /Users/mac/Downloads/picard-2.jar AddOrReplaceReadGroups  -I /Users/mac/Desktop/NGS/SRR6369659.bam   -O /Users/mac/Desktop/NGS/SRR6369659RG.bam   -RGID C7BDWACXX.7   -RGLB lmj_1948_EP_run1   -RGPL illumina   -RGPU C7BDWACXX.7  -RGSM N08162939

ERROR: Invalid argument '-I'.
