### ISSUE TITLE
BuildBamIndex error

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/picard#1544]
Hello, 
I run this CL : java -jar /Users/mac/Downloads/picard-2.jar BuildBamIndex \                                                   I=/Users/mac/Desktop/NGS/ERR439247_sorted.bam \

and I get : INFO	2020-07-13 02:15:41	BuildBamIndex	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    BuildBamIndex   -I /Users/mac/Desktop/NGS/ERR439247_sorted.bam
**********

ERROR: Invalid argument ' '.

USAGE: BuildBamIndex [options]

Documentation: http://broadinstitute.github.io/picard/command-line-overview.html#BuildBamIndex

Generates a BAM index ".bai" file.  This tool creates an index file for the input BAM that allows fast look-up of data
in a BAM file, lke an index on a database. Note that this tool cannot be run on SAM files, and that the input BAM file
must be sorted in coordinate order.
Usage example:

java -jar picard.jar BuildBamIndex \
I=input.bam

**Comment by cmnbroad** [comment]
@elbakrifz This appears to be another instance of the same issue you reported [here](https://github.com/broadinstitute/picard/issues/1533) and [here](https://github.com/broadinstitute/picard/issues/1534), which is incorrect use of the line continuation character. The line continuation character `\` is to be used when the command continues on the next line. Your command line includes two `\` characters, but in both cases the command does NOT continue on the next line:

`java -jar /Users/mac/Downloads/picard-2.jar BuildBamIndex \ I=/Users/mac/Desktop/NGS/ERR439247_sorted.bam \`

You need to either drop the `\` chars completely, and put the entire command on a single line:

`java -jar /Users/mac/Downloads/picard-2.jar BuildBamIndex  I=/Users/mac/Desktop/NGS/ERR439247_sorted.bam`

or use them as a separator between lines, as they are shown in the doc examples:

```
java -jar /Users/mac/Downloads/picard-2.jar BuildBamIndex \
I=/Users/mac/Desktop/NGS/ERR439247_sorted.bam
```
