### ISSUE TITLE
LiftoverVcf mapped to wrong location for dbsnp

### ISSUE THREAD

**Issue by yancylo** [broadinstitute/picard#1548]
### Affected tool(s)
LiftoverVcf

### Affected version(s)
- [x ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
I ran LiftoverVcf on a set of test variants from dbSNP 153 from GRCh37 to GRCh38 where there's a known strand flip. While most of these variants were lifted over correctly, some of them are not.

Example of a correctly lifted over location (the "b37" tag in the INFO field denote the original position on GRCh37, and the "b38" tag in the INFO field denote the expected new position on GRCh38, according to dbSNP lookup by rs ID):
(CHROM, POS, REF, ALT are the outputs of the lift over)
chr15   22728064      rs914331592       A       T       .       PASS    ReverseComplementedAlleles;b37=chr15:23145037:T>A;b38=chr15:22728064:A>T

Example of an incorrectly lifted over location (the "b37" tag in the INFO field denote the original position on GRCh37, and the "b38" tag in the INFO field denote the expected new position on GRCh38, according to dbSNP lookup by rs ID):
(CHROM, POS, REF, ALT are the outputs of the lift over)
chr9    41421417      rs918107926       C       G       .       PASS    ReverseComplementedAlleles;b37=chr9:70583572:G>C;b38=chr9:66332936:C>G

The incorrectly lifted over positions are not flagged as wrong in the output, but because these are from dbSNP with known coordinates, I was able to find out that they were not lifted over correctly. I used the chain file and GRCh38 reference downloaded from UCSC. The fact that most of the variants were lifted correctly seems to suggest that the issue is not coming from the reference file or the chain file, but the Liftover algorithm.

**Comment by yfarjoun** [comment]
Can you please help us by providing a vcf with the single variant that is not being LiftedOver correctly, and by providing a URL to the chain-file you used?

**Comment by yancylo** [comment]
Here's one vcf line:
chr19   11425401        rs912872624      G       A       .       PASS    b37=chr19:11536230:G>A;b38=chr19:11425469:A>G;id=
I listed the original b37 position and the expected b38 position in the info field. The chrom/pos fields are the coordinates returned by Picard.

Chainfile: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz

Thank you for your help!

**Comment by yfarjoun** [comment]
Hello,

I lifted-over your site using the UCSC tool (https://genome.ucsc.edu/cgi-bin/hgLiftOver) and got the same location as found by Picard.

This leads me to believe that the identity/location of rs912872624 is wrong in dbSNP. Alternatively, the chainfile provided by UCSC could be wrong, but since Picards implementation agrees with the reference (UCSC) implementation, I do not know how this can be fixed.
