### ISSUE TITLE
Please generate the extended manifest for me? Thanks!

### ISSUE THREAD

**Issue by wangfan860** [broadinstitute/picard#1553]
Hi,

I'm using the gtc2vcf function and I don't have the Extended Illumina manifest, which is one of the required inputs. I heard that the tool to do that hasn't been published and is still private now. Could you please generate it for me?  

Please go to the below Box folder to get the `egt` and `bpm` and `csv` files: https://uchicago.box.com/s/wrw3aipzj9q1cn9w5ck62imv7a3gikxc

And maybe put the output in the same folder please? I really appreciate your help!

Thanks very much!! 🙏
Fan

**Comment by gbggrant** [comment]
I sent the extended manifest to Fan this morning.
