### ISSUE TITLE
Provider GCS is not available

### ISSUE THREAD

**Issue by jwdy** [broadinstitute/picard#1557]
Hello, when I use picard.jar, there is always a warning (maybe, I'm not sure) "Provider GCS is not available".

### Bug Report
For example, I run:
java -jar /path/picard.jar CreateSequenceDictionary REFERENCE=$INDEX/${ref_version}.fa OUTPUT=$INDEX/${ref_version}.dict SPECIES=Homo_sapiens

I got:
22:18:28.720 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/export/home/daijiawei/software/picard/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat Aug 08 22:18:28 CST 2020] CreateSequenceDictionary OUTPUT=/export/home/daijiawei/project/lung_hospital/process/single_cell/INDEX/hg19/hg19.dict SPECIES=Homo_sapiens REFERENCE=/export/home/daijiawei/project/lung_hospital/process/single_cell/INDEX/hg19/hg19.fa    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sat Aug 08 22:18:28 CST 2020] Executing as daijiawei@CPU-4 on Linux 3.10.0-693.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_222-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.3-3-gbd603aa-SNAPSHOT
[Sat Aug 08 22:18:45 CST 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.28 minutes.
Runtime.totalMemory()=5290590208
(base) [daijiawei@CPU-4 process]$ java -jar /export/home/daijiawei/software/picard/picard/build/libs/picard.jar CreateSequenceDictionary -REFERENCE $INDEX/${ref_version}.fa -OUTPUT $INDEX/${ref_version}.dict -SPECIES Homo_sapiens
22:20:59.980 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/export/home/daijiawei/software/picard/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat Aug 08 22:20:59 CST 2020] CreateSequenceDictionary --OUTPUT /export/home/daijiawei/project/lung_hospital/process/single_cell/INDEX/hg19/hg19.dict --SPECIES Homo_sapiens --REFERENCE /export/home/daijiawei/project/lung_hospital/process/single_cell/INDEX/hg19/hg19.fa --TRUNCATE_NAMES_AT_WHITESPACE true --NUM_SEQUENCES 2147483647 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Sat Aug 08 22:20:59 CST 2020] Executing as daijiawei@CPU-4 on Linux 3.10.0-693.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_222-b10; Deflater: Intel; Inflater: Intel; **Provider GCS is not available**; Picard version: Version:2.23.3-3-gbd603aa-SNAPSHOT
[Sat Aug 08 22:21:17 CST 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.29 minutes.

### Affected tool(s)
All tools

### Affected version(s)
picard-2.23.2 and picard-2.23.3 (latest)

Everything seems to be going well except "Provider GCS is not available". Will this affect my result?

**Comment by lbergelson** [comment]
@jwdy It won't affect your results.  It's telling you that the libraries to provide support for reading from google cloud (gs://) paths isn't available.  So you won't be able to read data directly from google.  If you want to do that you can use the picardcloud jar.

**Comment by jwdy** [comment]
@lbergelson  Thank you so much for your quick reply.
