### ISSUE TITLE
ZERO_CVG_TARGETS_PCT vs. 1-PCT_TARGET_BASES_1X

### ISSUE THREAD

**Issue by kkruglyak** [broadinstitute/picard#1562]
### Tool(s) involved
CollectHsMetrics

### Description 
I cannot understand from the documentation description how ZERO_CVG_TARGETS_PCT differs from a theoretical PCT_TARGET_BASES_0X (which would be the same as 1-PCT_TARGET_BASES_1X). Sometimes ZERO_CVG_TARGETS_PCT + PCT_TARGETS_BASES_1X sum above 1, sometimes below (though always very close), which seems unintuitive. Would it be possible to flesh out the definitions to explain the subtleties of the calculations?

----

**Comment by yfarjoun** [comment]
the documentation says: 
```
The fraction of targets that did not reach coverage=1 over any base.
```
meaning that this metric is looking at target intervals, not bases. so it is effectively asking the question what percent of target intervals, got no reads at all over them. (this is usually an indication of a complete assay failure for that target)

**Comment by kkruglyak** [comment]
Thank you for your fast response. That was my intuition, but shouldn't this imply that ZERO_CVG_TARGETS_PCT + PCT_TARGET_BASES_1X is always less than or equal to 1? ZERO_CVG_TARGETS_PCT defines full target intervals at 0x, but there may also be other bases at 0x that are within covered target intervals. I'm unclear why the sum can be greater than 1.

**Comment by yfarjoun** [comment]
well, some of the targets could be small….some large. they all get counted
the same way…so comparing with bases is no so straightforward.

example: you could have lots of tiny targets that are not covered, so 90%
ZERO_CVG_TARGETS_PCT but that only accounts for 1% of the bases since the
remaining 10% are huge and have many bases….
