### ISSUE TITLE
MarkDuplicates gets killed immediately after launching

### ISSUE THREAD

**Issue by DanCag** [broadinstitute/picard#1564]
### Affected tool(s)
MarkDuplicates, version 1.62(1113)

### Description 
Hello, 

I would like to remove duplicates from a sorted bam file. 
However, when I run MarkDuplicates, the program gets killed immediatley. 
The input is a sorted bam file of roughly 2.5 GB.

#### Steps to reproduce
Command line: 
`java -jar MarkDuplicates.jar INPUT=path_input/sorted.bam OUTPUT=path_output/sorted_noduplicates.bam REMOVE_DUPLICATES=true METRICS_FILE=path_output/sorted_noduplicates_metrics`

#### Expected behavior
Return a new bam file without duplicates

#### Actual behavior
_[Tue Aug 18 16:35:51 CEST 2020] Executing as ieo5059@cn08.cluster.loc on Linux 3.10.0-514.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_102-b14; Picard version: 1.62(1113)
INFO	2020-08-18 16:35:52	MarkDuplicates	Start of doWork freeMemory: 2008412856; totalMemory: 2020081664; maxMemory: 28631367680
INFO	2020-08-18 16:35:52	MarkDuplicates	Reading input file and constructing read end information.
INFO	2020-08-18 16:35:52	MarkDuplicates	Will retain up to 113616538 data points before spilling to disk.
Killed

----

**Comment by yfarjoun** [comment]
looks like you are running this in a container, or vm, and it was using more memory than the machine has, so the kernel killed it. I suggest running it on a beefier machine…or limiting the memory that the tool has.

**Comment by DanCag** [comment]
Yes, actually I am running MarkDuplicates on a cluster. I will try to ask for more memory in the batch job.

Are there options that limit the amount of memory used by the tool? 
I have found the `--SORTING_COLLECTION_SIZE_RATIO ` option that seem to be useful in case you run out of memory. 

Thanks, 
Danilo

**Comment by gbggrant** [comment]
Hi @DanCag I'm assuming you were able to run the tool using more memory for the job.  Please re-open if you need more help on this specific issue.

One easy way to limit the memory usage for a java program is to use the '-Xmx' option.  So `java -Xmx8g -jar MarkDuplicates.jar` limits the process to no more than 8G of memory
