### ISSUE TITLE
PERCENT_DUPLICATION Calculation Bug

### ISSUE THREAD

**Issue by nathanhaigh** [broadinstitute/picard#157]
The `METRICS_FILE` generated by `MarkDuplicates` does not show the `PERCENT_DUPLICATION` as expected. It is in fact a fraction and not a percentage. i.e. it is 2-orders of magnitude less than one might expect given the column name.

**Comment by nh13** [comment]
Unfortunately this is a bug that we will not fix but it is documented in the FAQ: http://broadinstitute.github.io/picard/faq.html

Many folks including ourselves rely on the names and changing that would affect other systems.  My apologies in advance.
