### ISSUE TITLE
How to use multi threads with picard MarkDuplicates???

### ISSUE THREAD

**Issue by Sherry520** [broadinstitute/picard#1594]
how to use multi threads with picard MarkDuplicates???
I am using picard-2.23.4-0, I have thounds of bam files to deal, how to use muti threads to remove Duplicates more quickly?

**Comment by yfarjoun** [comment]
The process itself isn't multithereaded (though you probably already have
asynchronous reading and / or writing) . you can explore using
gatk's MarkDuplicatesSpark, but if you really have thousands of files to
mark, wouldn't you prefer to increase throughput/cpu rather than shorten
wall-clock time?

**Comment by Sherry520** [comment]
Thank you .I will have a try
