### ISSUE TITLE
Attempt to unmapped with non zero alignment start (0) or span

### ISSUE THREAD

**Issue by xtmgah** [broadinstitute/picard#1624]
### Instructions
----

### Affected tool(s)
java -Xmx4g -jar /data/zhangt8/Ref/picard/picard-tools-2.23.3/picard.jar ValidateSamFile I=/data/ITEB_Lung_WGS/FireCloud_downloads/Paper3/13Nov_835samples/NSLC-AKV2-TTP1-A-1-1-D-A81K-36/v1/NSLC-AKV2-TTP1-A-1-1-D-A81K-36.cram MODE=SUMMARY

### Description 

See the error bellow. Any idea or suggestion? Thanks. 

INFO	2021-01-06 11:25:06	ValidateSamFile

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    ValidateSamFile -I /data/ITEB_Lung_WGS/FireCloud_downloads/Paper3/13Nov_835samples/NSLC-AKV2-TTP1-A-1-1-D-A81K-36/v1/NSLC-AKV2-TTP1-A-1-1-D-A81K-36.cram -MODE SUMMARY
**********

11:25:06.839 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gpfs/gsfs7/users/zhangt8/Ref/picard/picard-tools-2.23.3/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jan 06 11:25:06 EST 2021] ValidateSamFile INPUT=/data/ITEB_Lung_WGS/FireCloud_downloads/Paper3/13Nov_835samples/NSLC-AKV2-TTP1-A-1-1-D-A81K-36/v1/NSLC-AKV2-TTP1-A-1-1-D-A81K-36.cram MODE=SUMMARY    MAX_OUTPUT=100 IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 SKIP_MATE_VALIDATION=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jan 06 11:25:06 EST 2021] Executing as zhangt8@cn0861 on Linux 3.10.0-862.14.4.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 12.0.1+12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.3
WARNING	2021-01-06 11:25:06	ValidateSamFile	NM validation cannot be performed without the reference. All other validations will still occur.
ERROR	2021-01-06 11:25:07	**ValidateSamFile	Attempt to unmapped with non zero alignment start (0) or span (-2147483647)**
[Wed Jan 06 11:25:07 EST 2021] picard.sam.ValidateSamFile done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=421527552
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp

**Comment by yfarjoun** [comment]
@cmnbroad could you look at this? the error comes from the Cram/Bai code in htsjdk. The message isn't properly worded and so I"m not actually sure what the problem is....but if we could make sure to catch this exception in the validator we could also provide a better error message to the user.

@xtmgah it looks like your index file is screwed up, but the error message isn't clear enough and so I can tell you much more. Can you rename (move) your index and reindex your cram file and see if this error persists?

**Comment by cmnbroad** [comment]
@xtmgah As suggested above, I recreate the index file, or at least temporarily remove/rename it to see if that eliminates the error.

The error message is malformed, but it indicates that either the cram file itself, or the index, has an entry for an unmapped/placed slice (a slice containing only unmapped but placed records) that has invalid alignment span values.

There certainly are older versions of cram implementations around that created such invalid slices. Do you have any idea what software was used to create the cram/index ?

**Comment by cmnbroad** [comment]
Also @xtmgah please do let us know if recreating the index resolves the issue.

**Comment by xtmgah** [comment]
Thanks. I will try and let you know soon how it goes.

**Comment by xtmgah** [comment]
Hello @cmnbroad Just let you know, I created a new index files and Picard work fine. Thanks for your help.

**Comment by cmnbroad** [comment]
@xtmgah Great, thanks for the followup. One last question - do you by any chance know how the original (bad) index was created (i.e., if it was created by Picard/GATK/samtools or some other software, and if so what version) ? If you happen to know the answer it might help us figure out if there is still a bug somewhere. Thanks.
