### ISSUE TITLE
Feature: Parametrize CollectRNASeqMetrics 3'/5' Bias Length

### ISSUE THREAD

**Issue by ramsey-watchmaker** [broadinstitute/picard#1625]
### Tool(s) involved
Picard CollectRnaSeqMetrics

### Description
Currently CollectRnaSeqMetrics has a fixed value of 100 for the 3'/5' end bias length.  

https://github.com/broadinstitute/picard/blob/74a85aba04d2283928dc8e88e43f02775cc29aac/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L379-L386

It may be helpful to parametrize this.  Also some additional constraints to this may need to work with around the minimum transcript length:

https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/CollectRnaSeqMetrics.java#L120

PR would require those changes and also small update to the documentation.  I would be happy to take this on.

**Comment by kbergin** [comment]
Hi @ramsey-watchmaker, we would be happy to see this feature added to CollectRnaSeqMetrics if you are still willing to make a PR. Please tag me when you do so I can help make sure you get a reviewer quickly.

**Comment by ramsey-watchmaker** [comment]
Hey @kbergin .  I got this all made and am ready to open a PR.  I do not have sufficient permissions to create a new branch though.

**Comment by jessicaway** [comment]
@ramsey-watchmaker you should be able to make a PR from a fork. Documentation on forks, including creating a PR from a fork, can be found here: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by kbergin** [comment]
Thanks to @ramsey-watchmaker for the contribution for this feature request! Closing this issue now.
