### ISSUE TITLE
Picard tools showing high CPU and RAM on a large cluster

### ISSUE THREAD

**Issue by OgnjenMilicevic** [broadinstitute/picard#1629]
Hi, 

I have a question about your Metrics collection tools used in https://github.com/gatk-workflows/gatk4-genome-processing-pipeline (I know it is archived, but I use these tools locally so I cannot easily move away). When using these tools in concurrence with other tools from the pipeline on the same cluster (~100CPU 500G RAM) they tend to show spikes in RAM and CPU - for example CollectMultipleMetrics can easily take 60 cores and 15G as viewed by top. The data passes all the QC in the end.

Is this an artefact or real usage? Can this be avoided by proper specification?
If I put hard limits on the container thus simulating the cloud instance, would this go away or would the program be killed due to the lack of resources?

I understand this seems very general, but I need someone to kickstart me in the right direction to explore this phenomenon.

**Comment by gbggrant** [comment]
Hi @OgnjenMilicevic in our usage (in a cloud-based WDL that's based on the one you referenced, but newer) we do not see the sort of resource usage that you describe.  In our case, we are requesting a cloud VM and it is provisioned with only 2 CPUs and 7 GiB of RAM.  It's possible that in an on-prem cluster that you are using CollectMultipleMetrics might use significantly more than that, but I'd be surprised about it using 60 cores.

I'd start by putting the hard limits on the container you suggest and seeing how that affects the time / resource usage of metrics collection.

**Comment by kedduck** [comment]
> Hi @OgnjenMilicevic in our usage (in a cloud-based WDL that's based on the one you referenced, but newer) we do not see the sort of resource usage that you describe. In our case, we are requesting a cloud VM and it is provisioned with only 2 CPUs and 7 GiB of RAM. It's possible that in an on-prem cluster that you are using CollectMultipleMetrics might use significantly more than that, but I'd be surprised about it using 60 cores.
> 
> I'd start by putting the hard limits on the container you suggest and seeing how that affects the time / resource usage of metrics collection.

Hello. I have this problem also. It's not allways using high number cores. I find that before the result print to screen, the using cores is high to 40. For example, 
INFO	2021-01-28 09:43:53	MarkDuplicates	Read    71,000,000 records.  Elapsed time: 00:11:00s.  Time for last 1,000,000:   27s.  Last read position: chromosome03_33792694bp:14,872,632
INFO	2021-01-28 09:43:53	MarkDuplicates	Tracking 3288091 as yet unmatched pairs. 366874 records in RAM.

before this print to screen the using core is high. I use a cluster.

I want to ask you that if you know how to limit the core?

Thanks !

**Comment by OgnjenMilicevic** [comment]
Hi,

Just to say that limiting the resources at the cluster does solve the problem.

For @kedduck and all cluster users,
I activated cgroups and limit the resources at the docker level. I use cromwell, but my docker submit is done like this:

"docker run -v ${cwd}:${docker_cwd} --cpus=${cpu} --memory=${memory_mb}m ${docker} ${job_shell} ${docker_cwd}/execution/script"

**Comment by kedduck** [comment]
@OgnjenMilicevic 

Thanks!

**Comment by kbergin** [comment]
Thanks, all.
