### ISSUE TITLE
CollectVariantCallingMetrics throws NullPointerException

### ISSUE THREAD

**Issue by jezkoski** [broadinstitute/picard#1631]
### Tool 

I'm trying to run CollectVariantCallingMetrics on my dataset.
I have tried to run anaconda installation of picard-2.23.8 and also the latest picard from github (downloaded this month), but I have the same problem with both. (the installations are on different servers so they won't be mixed)

My command.
` java -jar ./picard/build/libs/picard.jar CollectVariantCallingMetrics \
--INPUT germline_variants.vcf.gz \
--OUTPUT germ_raw_picardmetrics \
--DBSNP /data/ref_genomes/GRCh37/dbSNP154_UCSCnames.hg19.vcf.gz`

 ### Error description

I get this error, I assume there's a problem with loading my dbSNP file?

`07:55:32.308 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file: /home/jkoski/picard/build/libs/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Jan 14 07:55:32 UTC 2021] CollectVariantCallingMetrics INPUT=germline_variants.vcf.gz OUTPUT=germ_raw_picardmetrics DBSNP=/data/ref_genomes/GRCh37/dbSNP154_UCSCnames.hg19.vcf.gz    GVCF_INPUT=false THREAD_COUNT=1 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Jan 14 07:55:32 UTC 2021] Executing as jkoski@a2 on Linux 3.10.0-1062.4.3.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_232-b09; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.24.0-1-g74a85ab-SNAPSHOT`

The tool still goes through all the chromosomes and lists the process. Time for last 100,000 is 0s for all the INFO lines

`INFO    2021-01-14 09:05:17     CollectVariantCallingMetrics    Read     5,100,000 variants.  Elapsed time: 00:00:19s.  Time for last 100,000:    0s.  Last read position: chr1:20,452,846
INFO    2021-01-14 09:05:18     CollectVariantCallingMetrics    Read     5,200,000 variants.  Elapsed time: 00:00:20s.  Time for last 100,000:    0s.  Last read position: chr1:20,877,054`

`[Thu Jan 14 08:49:56 UTC 2021] picard.vcf.CollectVariantCallingMetrics done. Elapsed time: 54.40 minutes.
Runtime.totalMemory()=2624061440
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
        at picard.util.DbSnpBitSetUtil.loadVcf(DbSnpBitSetUtil.java:163)
        at picard.util.DbSnpBitSetUtil.createSnpAndIndelBitSets(DbSnpBitSetUtil.java:131)
        at picard.vcf.CollectVariantCallingMetrics.doWork(CollectVariantCallingMetrics.java:101)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:304)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)`

My VCF file works just fine with other tools so there shouldn't be huge problems with that. 

I downloaded the dbSNP file from https://ftp.ncbi.nih.gov/snp/redesign/latest_release/VCF/GCF_000001405.25.gz and changed the NCBI notation to UCSC one with 
`bcftools annotate --rename-chrs NCBI_to_UCSC.txt dbSNP154.hg19.vcf.gz -Oz -o dbSNP154_UCSCnames.hg19.vcf.gz`

I have tried to include --SEQUENCE_DICTIONARY /data/ref_genomes/GRCh37/hg19.dict but it doesn't change anything. Any suggestions on how I could troubleshoot?

**Comment by nh13** [comment]
@jezkoski could this be due to the VCF having variants on contigs not found in the `.dict` file?

**Comment by kockan** [comment]
I believe #1889 should address this, throwing an exception if the sequence dictionaries are not equal and informing the user.

Keeping the issue open for the time being to see whether @jezkoski can verify.
