### ISSUE TITLE
How can I use CollectRnaSeqMetrics with an ENSEMBL annotated BAM file?

### ISSUE THREAD

**Issue by rpauly** [broadinstitute/picard#1632]
How can I use CollectRnaSeqMetrics with an ENSEMBL annotated BAM file? Is there a refFLat equivalent in FRCh37 specifically?
Thanks,
Rini

**Comment by kockan** [comment]
Well, this is an old one and not sure if still relevant but I pretty much convert my GTFs to refflat with something like:
`gtfToGenePred -genePredExt -geneNameAsName2 gencode.v43.primary_assembly.annotation.gtf /dev/stdout | awk 'BEGIN { OFS="\t"} {print $12, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}' > gencode.v43.primary_assembly.refflat`

Closing for now, feel free to reopen if still relevant,
