### ISSUE TITLE
building picard against existing htsjdk

### ISSUE THREAD

**Issue by rekado** [broadinstitute/picard#165]
I'm packaging htsjdk and picard as separate libraries for GNU Guix.  In the build environment it is not possible and not desirable to download dependencies during the build process.  It would be preferable to build picard against an existing installation of htsjdk.

Is it possible to add an option to build.xml that would allow one to not compile htsjdk when building picard but to specify the path to already built htsjdk libraries?

A similar issue has previously been raised [here](https://github.com/broadinstitute/picard/issues/8).

**Comment by rekado** [comment]
A workaround is to remove the "compile-htsjdk" dependency from the compile task, and to symlink the htsjdk libraries to "htsjdk/lib", which has the effect of pacifying Ant, but it would be nicer if there was a less hackish way to accomplish this.

**Comment by nh13** [comment]
@vdauwera anyone taking a look at this?  I can't un-assign myself :/

**Comment by vdauwera** [comment]
@lbergelson any opinions about this?

**Comment by lbergelson** [comment]
I just saw that I was tagged in this several months ago... If anyone is still interested now that we've gone to gradle... Htsjdk is no longer built as part of picard, it's pulled in from maven central.  If you are running in an offline mode, you can install htsjdk into the local maven repository and picard will look for it there first.
