### ISSUE TITLE
ValidateSamFile diverges from SAM/BAM specification for read-group PL attribute

### ISSUE THREAD

**Issue by MikkelSchubert** [broadinstitute/picard#1661]
### Affected tool(s)
 - ValidateSamFile

### Affected version(s)
- [x] Latest public release version [2.25.1]

### Description 

ValidateSamFile appears to diverge from the SAM/BAM specification on a couple of points when it comes to the platform (`PL`) read-group attribute:

* The SAM/BAM specification lists `DNBSEQ` as a `PL` value for MGI/BGI platforms, while ValidateSamFile expects the non-standard value `BGI` and raises an `INVALID_PLATFORM_VALUE` if the value `DNBSEQ` is used.
* The specification states that `[the PL attribute] should be omitted when the technology is not in [the list of defined technologies] or is unknown.`, but ValidateSamFile raises an `MISSING_PLATFORM_VALUE` error if the `PL` attribute is omitted. Instead, ValidateSamFile seems to expect the non-standard value `OTHER`.

**Comment by jessicaway** [comment]
@MikkelSchubert Thank you for pointing out this inconsistency. A PR (linked above) has been opened in samtools/htsjdk to address the issue
