### ISSUE TITLE
IlluminaBasecallsToSam and IlluminaBasecallsToFastq do not demultiplex NovaSeq barcoded reads

### ISSUE THREAD

**Issue by myourshaw** [broadinstitute/picard#1679]
### Affected tool(s)
_Tool name(s), special parameters?_
IlluminaBasecallsToSam and IlluminaBasecallsToFastq

### Affected version(s)
- [X ] Latest public release version [GATK 4.2.0.0]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._
For **NovaSeq** 6000 data (v1.5 reagent kit; IDT xGen Dual Index UMI barcodes), neither of the tools successfully demultiplexes **NovaSeq** barcoded reads. All reads are assigned to the UNKNOWN uBAM or fastq files.

  - IlluminaBarcodesMetrics successfully recognizes the barcodes and counts the expected large number of reads for each.

  - Inspection of barcodes (BC tag) on reads in the UNKNOWN uBAM file shows the correct expected barcodes.

  - LIBRARY_PARAMS has the correct barcodes.

  - IlluminaBasecallsToSam with **NextSeq** data successfully demultiplexes when using a subset of the the same barcodes.

  - The current version of **bcl2fastq** successfully demultiplexes the **NovaSeq** data by barcode.

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._
Command used:
`
gatk --java-options -Xmx26g \
IlluminaBasecallsToSam \
--BASECALLS_DIR /home/dnanexus/210323_A00886_0062_BH5JM3DRXY/Data/Intensities/BaseCalls \
--LANE 1 \
--LIBRARY_PARAMS /home/dnanexus/210323_A00886_0062_BH5JM3DRXY.1.LibraryParams.txt \
--READ_STRUCTURE 151T8B9M8B151T \
--RUN_BARCODE 210323_A00886_0062_BH5JM3DRXY \
--ADAPTERS_TO_CHECK PAIRED_END \
--ADAPTERS_TO_CHECK INDEXED \
--ADAPTERS_TO_CHECK DUAL_INDEXED \
--APPLY_EAMSS_FILTER false \
--BARCODES_DIR /home/dnanexus/barcodes \
--IGNORE_UNEXPECTED_BARCODES false \
--INCLUDE_NON_PF_READS false \
--PLATFORM ILLUMINA \
--READ_GROUP_ID 210323_A00886_0062_BH5JM3DRXY.1 \
--RUN_START_DATE 2021/03/23 \
--SEQUENCING_CENTER cmoco@cuanschutz.edu \
--NUM_PROCESSORS 1 \
;
`
Log has no errors, app returns 0.

#### Expected behavior
_Tell us what should happen_
Reads having each of the 42 dual index barcodes should be demultiplexed to separate files.

#### Actual behavior
_Tell us what happens instead_
Reads having each of the 42 dual index barcodes are all in the UNKNOWN files.
----

**Comment by gbggrant** [comment]
This bug has been fixed in Picard release https://github.com/broadinstitute/picard/releases/tag/2.25.4 - The version of gatk that you are using (4.2.0.0) was packaged with Picard https://github.com/broadinstitute/picard/releases/tag/2.25.0 in it (which has the bug).

**Comment by myourshaw** [comment]
I noticed that Picard 2.25.4 seemed to differ from 2.25.0 in that the writing of output was postponed until all reading was done. This put a lot of pressure on the size of /tmp:
`ERROR 2021-05-12 18:11:35     ThreadPoolExecutorWithExceptions    A thread failed:
htsjdk.samtools.util.RuntimeIOException: Problem writing temporary file file:///tmp/myourshaw/sortingcollection.8534269494662177452.tmp.  Try setting TMP_DIR to a file system with lots of space.`
I fixed this with `-Djava.io.tmpdir=`pwd`/tmp` to a larger disk.

And then on memory:
`WARNING	2021-05-12 22:44:43	SortingCollection	There is not enough memory per file for buffering. Reading will be unbuffered.`
where I used `-Xmx26g` for a NovaSeq S2 run.

Am I correct? Do you have any recommendations regarding the size of disk space and memory?

**Comment by gbggrant** [comment]
Hi @myourshaw, in picard 2.25.x, the algorithm is now using a sorted collection, so it will use a lot of memory or disk to manage that.  If you don't need the output sorted by read name, you can try setting `SORT = false` and that should ease up a lot on the memory and disk requirements.

As for the memory issue, I believe you are getting the error about not enough memory available for buffering because there are too many files opened by the sorting collection.  If you increase the parameter `MAX_RECORDS_IN_RAM` that should decrease the number of files opened and hopefully allow for buffering.  Memory and disk tuning is difficult without knowing your situation.

**Comment by gbggrant** [comment]
Closing issue as the original bug has been resolved.
