### ISSUE TITLE
IlluminaBasecallsToSam doesn't assign Reads to expected Barcode

### ISSUE THREAD

**Issue by MaxiDoe** [broadinstitute/picard#1685]
### Affected tool(s)
_Tool name(s), special parameters?_
picard IlluminaBasecallsToSam

### Affected version(s)
Version: 2.25.2

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

I have a NovaSeq Output Folder and wanted to start my analysis. 
I started with "ExtractIlluminaBarcodes" and everything worked fine.
Then I wanted to run "IlluminaBasecallsToSam", which also worked fine without an error. But I realised that all my reads were assigned to the unassigned BAM file. I looked at the first few reads of this unassigned.bam and wondered why these reads were not assigned to the right BAM file since the barcodes matched exactly with the barcodes provided in my library_params.txt. So, here I am and ask you why all of my reads are assigned to the unassigned.bam file.

**Library_Params.txt**

OUTPUT  SAMPLE_ALIAS    LIBRARY_NAME    BARCODE_1       BARCODE_2
picard_illuminaBasecallsToSam/lane1/M70.bam      M70     M70     CGGCTAATNNNNNNNNN       CTCGTTCT
picard_illuminaBasecallsToSam/lane1/M75.bam      M75     M75     ATCGATCGNNNNNNNNN       TGGAAGCA
picard_illuminaBasecallsToSam/lane1/M76.bam      M76     M76     AACTGAGCNNNNNNNNN       CAATCAGG
picard_illuminaBasecallsToSam/lane1/HL1046.bam   HL1046  HL1046  CTTGTCGANNNNNNNNN       CGATGTTC
picard_illuminaBasecallsToSam/lane1/HL2426.bam   HL2426  HL2426  TGAGCTAGNNNNNNNNN       GAACGGTT
picard_illuminaBasecallsToSam/lane1/HL2440.bam   HL2440  HL2440  ACCACGATNNNNNNNNN       GTCTGCAA
picard_illuminaBasecallsToSam/lane1/unassigned.bam       unassigned      unassigned      N

**Read Structure**

142T8B9M8B151T

**Command-line** 

java -Xmx40g -jar /usr/bin/picard.jar IlluminaBasecallsToSam -BASECALLS_DIR ./Data/Intensities/BaseCalls/ -LANE 1 -READ_STRUCTURE 142T8B9M8B151T -LIBRARY_PARAMS lib_params.txt -TMP_DIR /tmp_dir/ -SEQUENCING_CENTER PATHO -TAG_PER_MOLECULAR_INDEX ZA -BARCODES_DIR /picard_extractIlluminaBarcodes/extracted_barcodes/lane1/ -RUN_BARCODE run21 -MAX_READS_IN_RAM_PER_TILE 100000 -MAX_RECORDS_IN_RAM 100000 -NUM_PROCESSORS 12 -MOLECULAR_INDEX_TAG RX

**Beginning of the unassigned BAM file where every read was put into.**

@HD     VN:1.6  SO:queryname
@RG     ID:run21.1      SM:unassigned   LB:unassigned   PL:ILLUMINA     PU:run21.1.N-null       CN:PATHO
@PG     ID:samtools     PN:samtools     VN:1.10 CL:samtools view -h unassigned.bam
run21:1:2101:10004:1000 77      *       0       0       *       *       0       0       NCGGAGTTATGACAAGCTTTCCAAATATTTTGCTTTATCAGCCGATATCAACACTTGTATCTGGCCTCTGTGCCCCAGCAGTGCCTTGTGCAATGTGAATGTGCGCGTCTCTGCTAAACCACCATTTTATTTGGTTTTTGTT  #FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFF,F,FFFFFFFFFF  ZA:Z:CCGATCTAA  BC:Z:CGGCTAAT-CTCGTTCT  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:CCGATCTAA
run21:1:2101:10004:1000 141     *       0       0       *       *       0       0       GCAAGTATCCGAGCAAAACCAAAACAAAACAAAAACCAAATAAAATGGTGGTTTAGCAGAGACGCGCACATTCACATTGCACAAGGCACTGCTGGGGCACAGAGGCCAGATACAAGTGTTGATATCGGCTGATAAAGCAAAATATTTGGAA FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF:FFFFFFF ZA:Z:CCGATCTAA  BC:Z:CGGCTAAT-CTCGTTCT  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:CCGATCTAA
run21:1:2101:10004:10019        77      *       0       0       *       *       0       0       TGTCTCTATGATAAAATAGGGTTTCTTGGGTAGAAATCAGGGCCTCGGGGCCTAGAAATGGGGTGAGGGACTCAGGGGAGACTTACCCACATGAGAAGCCAAGAAGAGGATGGGGAGCAAGAAAGGGGGCACCCGCCAGACC  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:FFFF  ZA:Z:CTCTTTGGT  BC:Z:ATCGATCG-TGGAAGCA  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:CTCTTTGGT
run21:1:2101:10004:10019        141     *       0       0       *       *       0       0       GCCTGGGTCGGCCTCTGGAGTATGGTCTGGCGGGTGCCCCCTTTCTTGCTCCCCATCCTCTTCTTGGCTTCTCATGTGGGTAAGTCTCCCCTGAGTCCCTCACCCCATTTCTAGGCCCCGAGGCCCTGATTTCTACCCAAGAAACCCTATT FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF ZA:Z:CTCTTTGGT  BC:Z:ATCGATCG-TGGAAGCA  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:CTCTTTGGT
run21:1:2101:10004:10050        77      *       0       0       *       *       0       0       GCCTACACTGCCTGCTCCCAGGAGGGGACTTTTGGAAAGCTGTCCATCCCCGGCATTGGCCTCTTATATGTGTGTGTGATATATCACCCACCATCTTCAGTGTGGTGTGTGGCCTCATCTCCAGCCAGGCTGTGGGGGATAT  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:F  ZA:Z:GGGGGGGGG  BC:Z:GGGGGGGG-TGGAAGCA  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:GGGGGGGGG
run21:1:2101:10004:10050        141     *       0       0       *       *       0       0       GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG FFFFFFF:FFFFFFFFFFFFFFF:FF:FFFFFFFF,FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFF,FFFFFFFFFFFF,FFFFFFFFFFFFF:FF,FFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFF:FFFF:F ZA:Z:GGGGGGGGG  BC:Z:GGGGGGGG-TGGAAGCA  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:GGGGGGGGG
run21:1:2101:10004:10081        77      *       0       0       *       *       0       0       CCCAAACATGCCCTTGTAGTTTCACACCCGACACTCAGCATCACCTCCATTTTGCCTAACCCTGGCACCCACCAGCCACATGCAGATGGAAGGAGAGCCGCTGGCCCCCAGCCTCGCAGCTGTACTCCCCGGCGTCCGCCAG  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F  ZA:Z:AAATGCTCA  BC:Z:TGAGCTAG-GAACGGTT  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:AAATGCTCA
run21:1:2101:10004:10081        141     *       0       0       *       *       0       0       GGCGGACGCCGGGGAGTACAGCTGCGAGGCTGGGGGCCAGCGGCTCTCCTTCCATCTGCATGTGGCTGGTGGGTGCCAGGGTTAGGCAAAATGGAGGTGATGCTGAGTGTCGGGTGTGAAACTACAAGGGCATGTTTGGGAGATCGGAAGA FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF::FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ZA:Z:AAATGCTCA  BC:Z:TGAGCTAG-GAACGGTT  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:AAATGCTCA
run21:1:2101:10004:10144        77      *       0       0       *       *       0       0       CCCTGAGATCTCCAAAACTTCTTCAAATTTATTCTTCAATTTAGTTGCTTTCCACTCAGCCAGTCTCTGCTGTCTGTACATTTCAATAGCACATTCATCCTCCTCATTAAACTTGTCTTCACGATCCTCCAGCTCTTCCAAA  FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF  ZA:Z:CGCCGAAGA  BC:Z:CTTGTCGA-CGATGTTC  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:CGCCGAAGA
run21:1:2101:10004:10144        141     *       0       0       *       *       0       0       TCCAGCAGTCAGTCGTGACAACATAGGAAGATATGACTTTGGAAGAGCTGGAGGATCGTGAAGACAAGTTTAATGAGGAGGATGAATGTGCTATTGAAATGTACAGACAGCAGAGACTGGCTGAGTGGAAAGCAACTAAATTGAAGAATAA FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF,FF::FFF ZA:Z:CGCCGAAGA  BC:Z:CTTGTCGA-CGATGTTC  RG:Z:run21.1    QX:Z:FFFFFFFFF  RX:Z:CGCCGAAGA

As you can see some of the first ten reads provided for you should be sorted into other BAM files like the library_params.txt suggests. 

#### Expected behavior
The reads should be sorted into the right BAM files like the barcodes in the library_params.txt suggest.

#### Actual behavior
All reads are assigned to the unassigned.bam file.

----

**Comment by gbggrant** [comment]
HI @MaxiDoe - I saw that you just closed this ticket.  I'm assuming that you have closed it because you found that the issue has been fixed in Picard release 2.25.4?  Please let me know if this is not the case (that is, if the bug is still an issue for you and that you have closed this for other reasons).

Sorry to not get back to you sooner.

**Comment by MaxiDoe** [comment]
Hi @gbggrant - I closed this ticket because the provider of the data just emailed me that something went wrong with the samplesheet and therefore I wanted to try the new approach since this is crucial for these steps. 

And no reason to be sorry. I appreciate your response. Have a great day!
