### ISSUE TITLE
Can't find picard-tools-x.y.z.zip at Latest Release project page.

### ISSUE THREAD

**Issue by rsharris** [broadinstitute/picard#1692]
### Entire package
picard-tools-x.y.z.zip

### Description 
The quick start at https://broadinstitute.github.io/picard tells me to "download a zipped package containing the jar file from the Latest Release project page on Github. The file name will be of the format picard-tools-x.y.z.zip."

But the "latest release" link takes me to https://github.com/broadinstitute/picard/releases/tag/2.25.6, and there is no file there with a name matching that format. All I see are picard.jar, picardcloud.jar, and two source code tarballs.

Is this an example of outdated documentation (in the quick start instructions), or am I looking in the wrong place?

----

**Comment by rsharris** [comment]
Looking through the older tagged releases, I find that prior to 2.6.0 the releases *do* have such a file, e.g. picard-tools-2.5.0.zip.  2.5.0 is dated Jun/23/2016. So the quick start at https://broadinstitute.github.io/picard is at least five years out of date.

Where *should* I be looking for installation instructions?

Thanks

**Comment by jessicaway** [comment]
Hi @rsharris, 

Apologies for the out of date installation instructions! Unfortunately the Picard documentation is currently broken and cannot be updated in its current state (this is a known issue). For more up to date documentation on Picard tools you can search the [GATK documentation](https://gatk.broadinstitute.org/hc/en-us/).

As you mentioned there is a picard.jar and a picardcloud.jar with each release, either of these can be downloaded and used to run picard. Unfortunately there is not a current equivalent of the `Quick Start` guide that you mentioned with installation instructions. 

Please let us know if you have additional issues or questions.

**Comment by rsharris** [comment]
OK. Thanks. I did eventually figure out that I could use picard.jar.

IIRC this was the first hit google gave me when I was trying to install picard. Since you can't easily change what google reports, it seems like it would be a good idea to remove the outdated documentation. Or at least make a BIG note in it to let users know it is incorrect.

**Comment by kockan** [comment]
Update(s) from the future:
- As of version 3.1.0, there is no separate `picardcloud.jar` anymore. All cloud functionality has been merged into `picard.jar`
- I seemed to be able to manually update https://broadinstitute.github.io/picard via pushing to the `gh-pages` branch, so hopefully people won't be looking for a `picard-tools-x.y.z.zip` anymore
