### ISSUE TITLE
Documentation request: speeding up IlluminaBaseCallsToSam

### ISSUE THREAD

**Issue by matthdsm** [broadinstitute/picard#1699]
### Tool(s) involved
IlluminaBaseCallsToSam

### Description 
Hi,

I'm looking for a way to optimize the speed of IlluminaBaseCallsToSam. At the moment, this step is a serious bottleneck in our workflow. Resources are not being used at all.

version: `picard-2.24.2`, installed by conda (later versions seem to have issues with sam output)
command:
```wdl
        picard -Xmx~{memory_mb}m IlluminaBasecallsToSam \
        --BASECALLS_DIR ~{basecalls_dir} \
        --BARCODES_DIR . \
        --LANE ~{lane} \
        --READ_STRUCTURE ~{read_structure} \
        --RUN_BARCODE ~{run_barcode} \
        --SEQUENCING_CENTER CMGG \
        --LIBRARY_PARAMS ~{library_params} \
        --IGNORE_UNEXPECTED_BARCODES false \
        --NUM_PROCESSORS ~{num_cpu}
```

Are there any option I could tweak to speed up the process? 
Thanks

----

**Comment by tomiles** [comment]
With current mostly default parameters and setting a high MAX_RECORDS_IN_RAM limit, its seems almost impossible to run IlluminaBasecallsToSam successfully without hitting `too many open files` limit for bigger NovaSeq runs (S3/S4).

If it doesn't crash the WRITE records stage seems very slow. So any tips to optimize this would be welcome.

**Comment by mjhipp** [comment]
To avoid crashing in this step, I run `IlluminaBasecallsToSam` with `SORT=false`, then sort individual BAMs downstream if needed.

**Comment by matthdsm** [comment]
Hi @mjhipp,

Thanks for the suggestion! Sadly, when using the `--SORT false` option, we're getting a different error.
```
Exception in thread "main" java.lang.NullPointerException
        at picard.illumina.UnsortedBasecallsConverter.processTilesAndWritePerSampleOutputs(UnsortedBasecallsConverter.java:93)
        at picard.illumina.IlluminaBasecallsToSam.doWork(IlluminaBasecallsToSam.java:267)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

**Comment by matthdsm** [comment]
seems related to #1696

**Comment by matthdsm** [comment]
Update: this issue was not fixed in v2.26.0. 
To make it worse, the issue now is now thrown when using `ExtractIlluminaBarcodes` too.

@mjhipp, you seem to have had success with the updated demultiplexing strategy from #1649 (included in 2.26.0), got any more tips?

Thanks
M

**Comment by gbggrant** [comment]
@matthdsm can you make another issue for the error you are seeing in `ExtractIlluminaBarcodes`?  We didn't see the issue buried in this thread.

**Comment by matthdsm** [comment]
It seems the underlying filesystem had a lot to do with the speed. Recent updates have alleviated a lot of the issues.
Runtimes have improved, but still no match with bcl2fastq/bclconvert. I suppose this also has something to do with java vs C.

Anyway, we're happy with the improved runtimes!
M
