### ISSUE TITLE
Picard from Bionconda 2.26 can not read BARCODE_FILE

### ISSUE THREAD

**Issue by crossz** [broadinstitute/picard#1709]
### Affected tool(s)
_Tool name(s), special parameters?_

Picard installed from bioconda. The command related is ExtractIlluminaBarcodes.

### Affected version(s)
- [x] Latest public release version [version?]

2.26

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

Barcode file which works fine for previous versions, such as 2.25.*, are not parsed properly. And don't know how to adjust it to make 2.26 work.

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

1. upgrade picard to 2.26,
2. run ```picard  ExtractIlluminaBarcodes READ_STRUCTURE=32T1S8B9M8B32T1S LANE=1 BASECALLS_DIR=<PATH TO 
 RUN>/Data/Intensities/BaseCalls/ BARCODE_FILE=barcodefile.txt```

#### Expected behavior
_Tell us what should happen_

Start to work to Extract Illumina Barcodes into L001, L002, L003, and L004.

#### Actual behavior
_Tell us what happens instead_

got:

```
<docs of ExtractIlluminaBarcodes>
...
...

No barcodes have been specified.
No barcodes have been specified.

```

**Comment by gbggrant** [comment]
Hi @crossz we haven't heard of any issues with ExtracIlluminaBarcodes on release 2.26.0, but we will test this on our data sets.

**Comment by matthdsm** [comment]
I've noticed the same issue where "ExtractIlluminaBarcodes"  complained the `barcode_sequence_2` columns was absent in a single end run.

M

**Comment by myourshaw** [comment]
See my issue #1728 with same problem using docker images.

**Comment by crossz** [comment]
> See my issue #1728 with same problem using docker images.

@gbggrant please refer to #1728, which works for me. And also hope to enhance the doc and error message. Thanks.
