### ISSUE TITLE
MergeBamAlignment needlessly requires input BAMs to be sorted by queryname

### ISSUE THREAD

**Issue by freeseek** [broadinstitute/picard#1710]
Generate a toy fastq dataset:
```
(echo "@NB500989:333:HKYJNAFX2:1:11101:24447:1024"
echo "CNGAAAGAAACTAGAGGGGGCCAGGTGCAGTAGCTCACACCTGTAATCTTAGCACTTTGGGAGGCCAAGGCGGGTGGATCATCTGAGGTCAGGAGTTCAAGACCAGCCTGGCCAACATGTTGAAACCCCGTCTCTATTAAAAATACAAAA"
echo "+"
echo "6#A/AEEEEEEEAEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEE<EEEEEEEEAEEEEEEEEEEEEEAEEEAEEEAEEEEEE/EEEEEEEEE/E/E<AEEEEE/6A/<<<EE/AEE/E"
echo "@NB500989:333:HKYJNAFX2:1:11101:10000:1915"
echo "AGACACATGGCGTTTATCCAGAATTAGCAAATTTATCTTCAGATATGGGATTTTCCTTCTTTTTTTAAATCTTGAGTCTGGCAGCAATTTGTAAAGGCTCATAAAAATCTGAAGCTTACATTTTTTGTCAAGTTACCGATGCTTGTGTCT"
echo "+"
echo "AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEAEEEEEEEEEAEEEEEEEEEAEEEEEEEEEEEAAAEAAAEEE/A<AEEEEEEEEEEAA") | \
  gzip > R1.fastq.gz

(echo "@NB500989:333:HKYJNAFX2:1:11101:24447:1024"
echo "NNNNTTGTATTTTTAATAGAGACGGGGTTTCAACATGTTGGCCAGGCTGGTCTTGAACTCCTGACCTCAGATGATCCACCCGCCTTGGCCTCCCAAAGTGCTAAGATTACAGGTGTGAGCTACTGCACCTGGCCCCCTCTAGTTTCTTTC"
echo "+"
echo "####AEEEEEEEEEEEEEEEE/EEEEEEEEEE6EEEEEEEEEEEEA<EEEEEEEEE/<EEEEEEE/EEEEEEEEEEE/EEEEEAEEEEEAEAEEEE/EEEEE/EEEEEEEEEEEEEAEEEEEEEEAE/<AAAA/<A<EE<<EA<A/AAE<"
echo "@NB500989:333:HKYJNAFX2:1:11101:10000:1915"
echo "TTACAGGATCTGAAGAGAGGGAAAAATAAACATGCACGATTATTTAATTCTTTTGGAAAAACTGCATGTAAGTGAAGTTCTCTTTCACAAGACACAAGCATCGGTAACTTGACAAAAAATGTAAGCTTCAGATTTTTATGAGCCTTTACA"
echo "+"
echo "AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEE6EEEEEEEEEEEEAEEEEEE/EEEAEEEEEEEEEEEEEAEEAE/EEEEEEEEEAEEEEEEA<EEEEEE<AAEEEEEEEEEEAEEEEEAEAAEAE/AAEAEAA<E") | \
  gzip > R2.fastq.gz
```

Install bwa and GATK resources:
```
sudo apt install java11-runtime bwa samtools
wget https://github.com/broadinstitute/gatk/releases/download/4.2.1.0/gatk-4.2.1.0.zip
unzip gatk-4.2.1.0.zip
echo dict fasta fasta.fai fasta.64.alt fasta.64.sa fasta.64.amb fasta.64.bwt fasta.64.ann fasta.64.pac | \
  tr ' ' '\n' | xargs -i echo gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.{} | \
  gsutil -m cp -I .
```

Run FastqToSam with the -SORT_ORDER "unsorted" option:
```
gatk-4.2.1.0/gatk \
  FastqToSam \
  -FASTQ R1.fastq.gz \
  -FASTQ2 R2.fastq.gz \
  -OUTPUT unmapped.bam \
  -SAMPLE_NAME SM \
  -SORT_ORDER "unsorted"
```
Notice the option -SORT_ORDER "unsorted" which prevents the tool from resorting the reads which can add both computational and storage requirements.

Aligned the data with bwa:
```
gatk-4.2.1.0/gatk \
  SamToFastq \
  -INPUT unmapped.bam \
  -FASTQ /dev/stdout \
  -INTERLEAVE true | \
  bwa mem -K 100000000 -p -v 3 -t 16 -Y Homo_sapiens_assembly38.fasta /dev/stdin | \
  samtools view -1 - > aligned.unmerged.bam
```

Merge unmapped and aligned BAMs:
```
gatk-4.2.1.0/gatk \
  MergeBamAlignment \
  -ALIGNED_BAM aligned.unmerged.bam \
  -UNMAPPED_BAM unmapped.bam \
  -OUTPUT aligned.unsorted.bam \
  -SORT_ORDER "unsorted" \
  -REFERENCE_SEQUENCE \
  Homo_sapiens_assembly38.fasta
```

This produces the error:
```
java.lang.IllegalStateException: Aligned record iterator (NB500989:333:HKYJNAFX2:1:11101:10000:1915) is behind the unmapped reads (NB500989:333:HKYJNAFX2:1:11101:24447:1024)
	at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:557)
	at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:186)
	at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:368)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

Despite the fact that option -SORT_ORDER "unsorted" is being used and the two BAM files have the reads in the same order:
```
$ samtools view unmapped.bam | cut -f1
NB500989:333:HKYJNAFX2:1:11101:24447:1024
NB500989:333:HKYJNAFX2:1:11101:24447:1024
NB500989:333:HKYJNAFX2:1:11101:10000:1915
NB500989:333:HKYJNAFX2:1:11101:10000:1915

$ samtools view aligned.unmerged.bam | cut -f1
NB500989:333:HKYJNAFX2:1:11101:24447:1024
NB500989:333:HKYJNAFX2:1:11101:24447:1024
NB500989:333:HKYJNAFX2:1:11101:10000:1915
NB500989:333:HKYJNAFX2:1:11101:10000:1915
```

Is there a way to run `MergeBamAlignment` letting the tool know that the order of the reads in the input BAMs is the same?

It seems then that the only workaround is to let `FastqToSam` sort the reads, which seems an unnecessary computational step since eventually the reads will be sorted by coordinate anyway.

This problem was observed when running together the WDL pipelines [paired-fastq-to-unmapped-bam.wdl](https://github.com/gatk-workflows/seq-format-conversion/blob/master/paired-fastq-to-unmapped-bam.wdl) and [processing-for-variant-discovery-gatk4.wdl](https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.wdl) where the former runs `FastqToSam` and the latter runs `SamToFastq` and `MergeBamAlignment`.

**Comment by gbggrant** [comment]
Hi @freeseek I know of no way to have MergeBamAlignment operate in the way you suggest.  To do what you suggest, the tool would still need to open both unsorted bams and compare their order, which, while not as expensive as a sort, would still be time consuming. If you are interested in having MBA support this behavior, you could contribute a pull request.

**Comment by gbggrant** [comment]
Closing this for now.  Happy to re-open if you want to discuss further.

**Comment by freeseek** [comment]
There are probably things that I don't understand about the internal workings of MergeBamAlignment, but if the two BAM files (unmapped and mapped) have the reads exactly in the same order (regardless of what that order is), it would be helpful to have a way to let MergeBamAlignment know and avoid an order check. Maybe this would better not be the default behavior, but it would be helpful to have an option to perform such an informed merge and save the computational cost of sorting when MergeBamAlignment is used in large pipelines.

**Comment by ruolin** [comment]
@freeseek I totally agree with you. This sorting behavior is totally unnecessary in some cases. It will be good to have an opt to skip this step.

**Comment by kachulis** [comment]
@freeseek @ruolin I think I agree with you both in theory, though I don't think this option should be on by default.  

Without having thought much at all about implementation, my initial concern is that there may be some brittleness in picard that makes implementing this much more complex than it _should_ be.  But if anyone wants to look into it more in depth, could be a nice addition.

**Comment by tfenne** [comment]
There's a tool in fgbio (see https://github.com/fulcrumgenomics/fgbio/pull/778) that is a new lightweight alternative to MergeBamAlignment.  It has a lot of the same functionality, but not all, but requires no sorting.

**Comment by yfarjoun** [comment]
hmmm. the have to be at least queryname _grouped_ though, right? I mean how
will you check the mate information otherwise?

Y.
