### ISSUE TITLE
Picard setlocale error with conda picard

### ISSUE THREAD

**Issue by isinaltinkaya** [broadinstitute/picard#1712]
Hi,

I get this warning (below) even though my run was finished successfully. 
`/opt/conda/bin/picard: line 5: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory`
My question is: Can such an error be important for how picard works, thus leading to incorrect results or bad file formats?

Thank you.

**Comment by gbggrant** [comment]
Hi @isinaltinkaya we have never seen this error and don't think it should affect Picard's operation. It looks like a conda installation issue (or other problem with your environment).  You might try something like this: https://snippets.aktagon.com/snippets/614-how-to-fix-bash-warning-setlocale-lc-all-cannot-change-locale-en-us-

**Comment by tolot27** [comment]
The reason for this error is that the picard wrapper script executes `export LC_ALL=en_US.UTF-8` and often the default locale is `C` and on non-english systems the locale `en_US.UTF-8` is not installed.
