### ISSUE TITLE
Error during IlluminaBaseCallsToSam when SORT=false

### ISSUE THREAD

**Issue by matthdsm** [broadinstitute/picard#1713]
### Affected tool(s)
IlluminaBaseCallsToSam --SORT false

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
When using IlluminaBaseCallsToSam with the `--sort`option set to false, the programs exits with an error.

#### Steps to reproduce
Any `IlluminaBaseCallsToSam` command with the `--sort` option set to `false`

#### Expected behavior
Tool should output unsorted unaligned bam files

#### Actual behavior
Tool fails with following error.

```bash
Exception in thread "main" java.lang.NullPointerException
        at picard.illumina.UnsortedBasecallsConverter.processTilesAndWritePerSampleOutputs(UnsortedBasecallsConverter.java:93)
        at picard.illumina.IlluminaBasecallsToSam.doWork(IlluminaBasecallsToSam.java:267)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

ping @gbggrant
first mentioned in https://github.com/broadinstitute/picard/issues/1699#issuecomment-900194298_

**Comment by gbggrant** [comment]
Hi @matthdsm - what version of picard was this from?  We believe this was fixed in 2.26.0, but the stack trace you have provided is not from 2.26.0.  If you are seeing it in 2.26.0 could you provide that stack trace?

Thanks.

George

**Comment by matthdsm** [comment]
Seems to be fixed in v2.26.0 😃 
Apologies for the unneeded issue!

Thanks for commenting.
Matthias

**Comment by gbggrant** [comment]
Thanks @matthdsm

**Comment by matthdsm** [comment]
Hi @gbggrant,

Sorry to bother you with this, but is the `UnsortedBasecallsConverter` supposed to be faster than the `SortedBasecallsConverter` or does it only have an effect on the resources needed?
Using the `--SORT` option doesn't seem to yield any performance gains. In fact, a lot of threads just seem to be idle.

I'm currently using v2.26.1

Thanks for the info, and again, sorry to bother
Matthias

**Comment by gbggrant** [comment]
Hi @matthdsm - Not sorting is an IO/Memory enhancement. The performance gain should be across both methods.  If you have other issues, can you open a different issue?

**Comment by matthdsm** [comment]
Thanks for the info! I'll make sure to open another issue if more questions arise.

M
