### ISSUE TITLE
READ_PAIR_DUPLICATES from picard EstimateLibraryComplexity

### ISSUE THREAD

**Issue by akk01** [broadinstitute/picard#1719]
Picard calculates PCR duplication rates as:  

`PERCENT_DUPLICATION = READ_PAIR_DUPLICATES / READ_PAIRS_EXAMINED`

How `READ_PAIR_DUPLICATES` is counted for secondary alignment (multimapping read pairs)? 

For examples, if a read pair appears 10 times in BAM file because it mapped to 10 positions in genome due to multimapping, and that read pair is marked as  PCR duplicate, will `Picard `count that as 1 `READ_PAIR_DUPLICATES` or 10 `READ_PAIR_DUPLICATES`? Please clarify my doubt. Thanks!

**Comment by yfarjoun** [comment]
"These are not the duplications you are looking for..." 

Duplicates in picard pertain to primary alignments. And have nothing to do with multiple mappings. There are two (main) modalities:

1. A DNA strand was duplicated during library construction and two (or more) sequence-ready reads were created from it and sequenced
2. A single DNA strand was placed on the flow-cell but for some reason two (or more) distinct reads (i.e. with different record names) were generated. 

When picard finds two read (pairs) that align to the same place, it chooses one pair as non-duplicate, and the other as duplicate. if there are 10 copied, there will be 9 duplicates and 1 non-duplicate and the rate will be 90% (9/10)

I hope this answers your question. 

In the future, please ask questions like this on the GATK forum: https://gatk.broadinstitute.org/hc/en-us/community/topics

**Comment by akk01** [comment]
Thanks for replying. I have a situation where `samtools flagstats` for a BAM file which is already marked with duplicate with Picard produces the following:
```
253552402 + 0 in total (QC-passed reads + QC-failed reads)
132897348 + 0 secondary
0 + 0 supplementary
71809672 + 0 duplicates
247864536 + 0 mapped (97.76% : N/A)
120655054 + 0 paired in sequencing
60327527 + 0 read1
60327527 + 0 read2
114967188 + 0 properly paired (95.29% : N/A)
114967188 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)```

To determine PCR duplication rate
