### ISSUE TITLE
Documentation for CollectHsMetrics PER_TARGET_COVERAGE?

### ISSUE THREAD

**Issue by clintval** [broadinstitute/picard#1742]
### Tool(s) involved

- `CollectHsMetrics` metric file [`PER_TARGET_COVERAGE`](https://github.com/broadinstitute/picard/blob/e44b2688552e8ea860ae5dc595444d1550d5272f/src/main/java/picard/analysis/directed/CollectTargetedMetrics.java#L76-L77)

### Description 

The hosted metrics documentation does not seem to have this metric class listed:

- https://broadinstitute.github.io/picard/picard-metric-definitions.html#HsMetrics

Would it be possible to host this?

I am most curious about "mean coverage" vs "normalized coverage" and what "normalized" means with regard to per-target coverage statistics.

**Comment by gbggrant** [comment]
Hi @clintval - the metrics documentation for Picard is well out of date - we are working on a fix for that. 

For the tool documentation, you can find it on gatk's web site at:
https://gatk.broadinstitute.org/hc/en-us/articles/360036856051-CollectHsMetrics-Picard- 
This describes the `PER_TARGET_COVERAGE` parameter that you are interested in.

I've looked at the code that generates those metrics, and it appears that the `mean_coverage` is the mean coverage for all the intervals in a specific gc percentage bin (0-100), while the `normalized_coverage` is the mean_coverage divided by the overall MEAN_TARGET_COVERAGE (across all intervals).

https://github.com/broadinstitute/picard/blob/959411f3a97e979c406cc068ca9200ff4e2bf6bf/src/main/java/picard/analysis/directed/TargetMetricsCollector.java#L903
