### ISSUE TITLE
Data provider mismatch in src/test/java/picard/illumina/IlluminaBasecallsToSamTest.java

### ISSUE THREAD

**Issue by pgrt** [broadinstitute/picard#1751]
Hello,

I am one of the Debian packagers of picard. During the tests of version 2.26.5, I got a failure of test variousConfigurationsData because of a mismatch between the expectations of the test and its data provider. Indeed, the last-but-one argument of the test should be of type long, and the data provider gives int.

The enclosed patch fixes the issue.

Best,
Pierre

[illumina_data_provider.txt](https://github.com/broadinstitute/picard/files/7591067/illumina_data_provider.txt)

**Comment by gbggrant** [comment]
Thanks very much Pierre! We have merged your fix and it is now released in Picard 2.26.6
