### ISSUE TITLE
remove duplication error in vcf result

### ISSUE THREAD

**Issue by Frank1219** [broadinstitute/picard#1756]
Hello, can you tell me how mark duplication in bam file or give me some materials. Does it take into account base variation at a particular location, or just the quality of the base like the picture?
![image](https://user-images.githubusercontent.com/14830635/144163283-a7baabf5-d10c-4df7-81c1-d308f30ab4b5.png)

**Comment by gbggrant** [comment]
Hi Frank1219, Picard issues is for specific issues with Picard tools. Your question seems to be a more general issue for support.  Please try the GATK forum: https://gatk.broadinstitute.org/hc/en-us/community/topics
