### ISSUE TITLE
Picard IntervalListTool java memory heap not recognised

### ISSUE THREAD

**Issue by BaylieRW** [broadinstitute/picard#1757]
Hi,

I get an error of java heap memory not enough when trying to create my interval list. Ive tried increasing the java memory using various options I've found by google searching, including:
1.
Module Load /PATH/TO/PICARD/ON/HPC

Picard --java options -Xmx40g -Xms40g IntervalListTools \   
SCRIPT ....

2.
Module Load /PATH/TO/PICARD/ON/HPC
Picard IntervalListTools \
JVM -Xmx40g -Xms40g \
SCRIPT ....

and also 3.
Module Load /PATH/TO/PICARD/ON/HPC

picard -Xmx40g -Xms40g IntervalListTools \
SCRIPT ....

But I just get my script terminated as they are all flagged as not recognised valid picard commands. How can I solve this please? Where in the picard script can java memory allocation be increased?

**Comment by gbggrant** [comment]
Hi @BaylieRW I'm not sure how the `Picard` script that you are invoking is defined,
but one way to define java options is this:

`java -Xmx1g -Xms1g -jar /PATH/TO/PICARD.jar IntervalListTools`

**Comment by bounlu** [comment]
This issue happens when `picard` is invoked from conda environment. You need to modify the wrapper script in conda environment like this:

`vim $(which picard)`
