### ISSUE TITLE
How to keep "duplicates" from different cells in single-cell sequencing data

### ISSUE THREAD

**Issue by Yydtqqqg** [broadinstitute/picard#1799]
Hi! I am considering Picard to remove duplicates from snATAC-seq data. For single-cell sequencing data, we want to remove duplicates from each individual cell, but fragments with identical start/end positions from different cells should not be marked as duplicates. The barcode (cell identification) information is contained in each record in the bam files. Can Picard somehow achieve this goal?

**Comment by kachulis** [comment]
Yes, you can use the `BARCODE_TAG`, `READ_ONE_BARCODE_TAG`, or `READ_TWO_BARCODE_TAG` options to tell picard where to not mark fragments with different cell barcodes as duplicates.
