### ISSUE TITLE
Picard CollectAlignmentSummaryMetrics/CollectMultipleMetrics finds no aligned reads in bam

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#180]
From a user in the McCarroll lab; summary metrics show unexpected zero counts. Data available locally on Broad servers.

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/discussion/5342/picard-collectalignmentsummarymetrics-collectmultiplemetrics-finds-no-aligned-reads-in-bam/p1

**Comment by dekling** [comment]
Confirmed that REFERENCE_SEQUENCE is required to obtain complete metrics.

**Comment by tfenne** [comment]
One change that would be nice to make in Picard that would avoid this kind of confusion is to make it easy for sub-classes (e.g. CollectAlignmentSummaryMetrics) to make global parameters like REFERENCE_SEQUENCE required, so that this kind of confusion can't happen.

**Comment by vdauwera** [comment]
@tfenne I agree, just not sure how much work that would entail. 
@nh13 Is Tim's suggestion something you think we can aim for, or should we solve this with better documentation for now?

**Comment by yfarjoun** [comment]
https://github.com/broadinstitute/picard/pull/188
