### ISSUE TITLE
Question about HsMetrics PCT_SELECTED_BASES

### ISSUE THREAD

**Issue by kkamii** [broadinstitute/picard#1807]
Hello, I got the hsmetrics file using picard CollectHsMetrics function.

Among several columns, I want to use PCT_SELECTED_BASES column for my QC metrics.

Is the PCT_SELECTED_BASES calculated  after removing duplicate reads? or include duplicate reads?

plz answer me.

thank you :)

----

**Comment by kachulis** [comment]
PCT_SELECTED_BASES is calculated including duplicate reads.
