### ISSUE TITLE
LiftoverVCF: "chain line has wrong number of fields in chain file" when 3 or more newlines are found after a chain entry block.osomal renaming

### ISSUE THREAD

**Issue by ghuls** [broadinstitute/picard#1809]
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)

LiftoverVcf

### Affected version(s)

- [ x] Latest public release version [version?]: 2.27.1

### Description

LiftoverVcf crashes when provided chain file contains 3 newlines (or more) after a chain entry block.

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._
```
[Mon May 23 15:20:05 CEST 2022] LiftoverVcf  --INPUT input.vcf.gz --OUTPUT output.vcf.gz --CHAIN hap1_with_3newlines_at_end.chain --REJECT output.rejected.vcf.gz --WARN_ON_MISSING_CONTIG true --LOG_FAILED_INTERVALS true --WRITE_ORIGINAL_POSITION true --WRITE_ORIGINAL_ALLELES true --LIFTOVER_MIN_MATCH 1.0 --ALLOW_MISSING_FIELDS_IN_HEADER false --RECOVER_SWAPPED_REF_ALT true --REFERENCE_SEQUENCE hap1.fa  --TAGS_TO_REVERSE AF --TAGS_TO_DROP MAX_AF --DISABLE_SORT false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Mon May 23 15:20:05 CEST 2022] Executing as user@hostname on Linux 3.10.0-1160.42.2.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_221-b11; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.20.5-SNAPSHOT
[Mon May 23 15:20:05 CEST 2022] picard.vcf.LiftoverVcf done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: chain line has wrong number of fields in chain file hap1_with_3newlines_at_end.chain at line 7
        at htsjdk.samtools.liftover.Chain.throwChainFileParseException(Chain.java:412)
        at htsjdk.samtools.liftover.Chain.loadChain(Chain.java:345)
        at htsjdk.samtools.liftover.Chain.loadChains(Chain.java:318)
        at htsjdk.samtools.liftover.LiftOver.<init>(LiftOver.java:89)
        at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:298)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

# Chain file with 3 newlines at the end.
$ cat -n hap1_with_3newlines_at_end.chain 
     1  chain 16569 chrM 16569 + 0 16569 chrM_hap1 16569 + 0 16569 25
     2  16569
     3
     4  chain 16569 chrM2 16569 + 0 16569 chrM2_hap1 16569 + 0 16569 25
     5  16569
     6
     7
     8

# Chain file with 3 newlines after an entry (complains about line 4).
$ cat -n hap1_with_3newlines_after an_entry.chain
     1  chain 16569 chrM 16569 + 0 16569 chrM_hap1 16569 + 0 16569 25
     2  16569
     3
     4
     5  chain 16569 chrM2 16569 + 0 16569 chrM2_hap1 16569 + 0 16569 25
     6  16569
     7
     8

```

#### Expected behavior

Ignore extra empty newline.

chainSort of Kent tools does not complain about this file (it will remove the extra empty line when sorting the output).

#### Actual behavior

Complains about wrong number of fields.

`htsjdk.samtools.SAMException: chain line has wrong number of fields in chain file hap1_with_3newlines_at_end.chain at line 7`

**Comment by kockan** [comment]
I believe we actually shouldn't allow an arbitrary number of empty lines after each chain due to the file format description: `Each set of chain alignments starts with a header line, contains one or more alignment data lines, and terminates with a blank line` (https://genome.ucsc.edu/goldenPath/help/chain.html).

If somehow such files are generated by some third-party software, users should preprocess them to remove extra newlines.

Closing for now, might reopen if it turns out there is a good reason to allow multiple blank lines after chains.
