### ISSUE TITLE
Problem with picard MarkDuplicates --version

### ISSUE THREAD

**Issue by SenseeraMachine** [broadinstitute/picard#1816]
After the new release yesterday, when I install Picard with bioconda, I have 2 options:

- conda install -c bioconda/label/cf201901 picard; picard MarkDuplicates --version
**output** - 2.18.23-SNAPSHOT
-  conda install -c bioconda/label/main picard; picard MarkDuplicates --version
**output** - 2.20.4-SNAPSHOT

Why do I get this SNAPSHOT? it wasn't like this up until the latest release, until now I got a normal version number. looks like a problem

**Comment by lbergelson** [comment]
This is happening because the version conda is using is built without specifying the `-Drelease=true` flag.  It's a packaging mistake but won't cause any issues analysis issues.
