### ISSUE TITLE
No output generated for MarkDuplicatesWithMateCigar Picard tool

### ISSUE THREAD

**Issue by Pravithaks** [broadinstitute/picard#1817]
### Instructions

- I'm working on MarkDuplicatesWithMateCigar Picard tool and no output was not generated.
-This is my code:
CLASSPATH=/usr/share/java/picard.jar java picard.cmdline.PicardCommandLine MarkDuplicatesWithMateCigar \
I=/home/mvrccri/Desktop/GLDS374/Alignmnet_out.bam \
O=/home/mvrccri/Desktop/GLDS374/mark_dups_w_mate_cig.bam \
M=/home/mvrccri/Desktop/GLDS374/mark_dups_w_mate_cig_metrics.txt 

---------
After running this command, it shows:

INFO	2022-07-01 12:39:21	MarkDuplicatesWithMateCigar	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MarkDuplicatesWithMateCigar -I /home/mvrccri/Desktop/GLDS374/Alignmnet_out.bam -O /home/mvrccri/Desktop/GLDS374/mark_dups_w_mate_cig.bam -M /home/mvrccri/Desktop/GLDS374/mark_dups_w_mate_cig_metrics.txt
**********

12:39:21.966 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/share/java/gkl.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Jul 01 12:39:21 IST 2022] MarkDuplicatesWithMateCigar INPUT=[/home/mvrccri/Desktop/GLDS374/Alignmnet_out.bam] OUTPUT=/home/mvrccri/Desktop/GLDS374/mark_dups_w_mate_cig.bam METRICS_FILE=/home/mvrccri/Desktop/GLDS374/mark_dups_w_mate_cig_metrics.txt    MINIMUM_DISTANCE=-1 SKIP_PAIRS_WITH_NO_MATE_CIGAR=true BLOCK_SIZE=100000 ADD_PG_TAG_TO_READS=true REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=TOTAL_MAPPED_REFERENCE_LENGTH PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicatesWithMateCigar READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Jul 01 12:39:21 IST 2022] Executing as mvrccri@administrator on Linux 5.15.0-25-generic amd64; OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.22.04.1; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: 2.26.10
[Fri Jul 01 12:39:21 IST 2022] picard.sam.markduplicates.MarkDuplicatesWithMateCigar done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=260046848
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: This program requires inputs in coordinate SortOrder
	at picard.sam.markduplicates.MarkDuplicatesWithMateCigar.doWork(MarkDuplicatesWithMateCigar.java:130)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

Kindly help. I'm using Ubuntu 22.04

**Comment by kachulis** [comment]
`Exception in thread "main" picard.PicardException: This program requires inputs in coordinate SortOrder`

Your input bam needs to be coordinate sorted for this tool.  MarkDuplicates (as opposed to MarkDuplicatesWithMateCigar) can take either coordinate or query-name sorted input.
