### ISSUE TITLE
mark duplicates according to the tag of Optional Fields in BAM file

### ISSUE THREAD

**Issue by HengkuanLi** [broadinstitute/picard#1822]
### Tool(s) involved
picard MarkDuplicates

### Description
Could you please tell me how to mark duplicates according to the tag of Optional Fields in BAM file?

----

**Comment by lbergelson** [comment]
This question is more appropriate for the [GATK forums](https://gatk.broadinstitute.org/hc/en-us/community/topics).   If you reopen it there please include more information about what you're trying to achieve because it is not clear here.
