### ISSUE TITLE
UmiAwareMarkDuplicatesWithMateCigar (no duplex). How to use it correctly?

### ISSUE THREAD

**Issue by migrau** [broadinstitute/picard#1824]
From a bam file (generated with bwa), can I use UmiAwareMarkDuplicatesWithMateCigar directly? e.g.

```picard UmiAwareMarkDuplicatesWithMateCigar I={input.bam} O={output.bamdup} M={output.dupmetrics} UMI_METRICS={output.umimetrics}```

I have used another tools in the past (`UMI-tools`), where the UMI has to be attached to the fastq reads prior to map/deduplicate. It's not clear for me how should I do it with `UmiAwareMarkDuplicatesWithMateCigar`. Is the `FixMateInformation` step, recommended?

After  `UmiAwareMarkDuplicatesWithMateCigar`, can I use `BaseRecalibrator/ApplyBQSR` as usual, before the mutect2 variant calling?

**Comment by kachulis** [comment]
If you're bam does not already include the MC tag, then yes you should run `FixMateInformation` first.  You will also need to make sure that the UMIs are stored in a tag for each read.  By default, UmiAwareMarkDuplicatesWithMateCigar expects this tag to be `RX`, but this can be changed with the `UMI_TAG_NAME` flag.
