### ISSUE TITLE
picard MarkDuplicates takes more than a day

### ISSUE THREAD

**Issue by xl5525** [broadinstitute/picard#1828]
10:05:33.997 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/picard-2.27.4-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Sep 13 10:05:34 EDT 2022] MarkDuplicates --INPUT ta_ctrl_R3.target.sorted.bam --OUTPUT ta_ctrl_R3.target.markdup.bam --METRICS_FILE ta_ctrl_R3.target.markdup.MarkDuplicates.metrics.txt --REMOVE_DUPLICATES false --ASSUME_SORT_ORDER coordinate --TMP_DIR tmp --VALIDATION_STRINGENCY LENIENT --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --DUPLEX_UMI false --FLOW_MODE false --FLOW_QUALITY_SUM_STRATEGY false --USE_END_IN_UNPAIRED_READS false --USE_UNPAIRED_CLIPPED_END false --UNPAIRED_END_UNCERTAINTY 0 --FLOW_SKIP_FIRST_N_FLOWS 0 --FLOW_Q_IS_KNOWN_END false --FLOW_EFFECTIVE_QUALITY_THRESHOLD 15 --ADD_PG_TAG_TO_READS true --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --OPTICAL_DUPLICATE_PIXEL_DISTANCE 100 --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Tue Sep 13 10:05:34 EDT 2022] Executing as xl5525@cetus-c1-04 on Linux 3.10.0-1160.59.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 17.0.3-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.27.4-SNAPSHOT
INFO	2022-09-13 10:05:34	MarkDuplicates	Start of doWork freeMemory: 529967672; totalMemory: 536870912; maxMemory: 2147483648
INFO	2022-09-13 10:05:34	MarkDuplicates	Reading input file and constructing read end information.
INFO	2022-09-13 10:05:34	MarkDuplicates	Will retain up to 7780737 data points before spilling to disk.
INFO	2022-09-13 10:05:38	MarkDuplicates	Read     1,000,000 records.  Elapsed time: 00:00:04s.  Time for last 1,000,000:    4s.  Last read position: chr2R:12,896,708
INFO	2022-09-13 10:05:38	MarkDuplicates	Tracking 40482 as yet unmatched pairs. 40482 records in RAM.
INFO	2022-09-13 10:05:43	MarkDuplicates	Read     2,000,000 records.  Elapsed time: 00:00:09s.  Time for last 1,000,000:    4s.  Last read position: chr3R:5,425,188
INFO	2022-09-13 10:05:43	MarkDuplicates	Tracking 4 as yet unmatched pairs. 4 records in RAM.
INFO	2022-09-13 10:05:47	MarkDuplicates	Read     3,000,000 records.  Elapsed time: 00:00:13s.  Time for last 1,000,000:    4s.  Last read position: chrX:15,502,997
INFO	2022-09-13 10:05:47	MarkDuplicates	Tracking 0 as yet unmatched pairs. 0 records in RAM.
INFO	2022-09-13 10:05:48	MarkDuplicates	Read 3205738 records. 0 pairs never matched.
INFO	2022-09-13 10:05:48	MarkDuplicates	After buildSortedReadEndLists freeMemory: 472495584; totalMemory: 890241024; maxMemory: 2147483648
INFO	2022-09-13 10:05:48	MarkDuplicates	Will retain up to 67108864 duplicate indices before spilling to disk.
INFO	2022-09-13 10:05:48	MarkDuplicates	Traversing read pair information and detecting duplicates.
INFO	2022-09-13 10:05:55	OpticalDuplicateFinder	Large duplicate set. size = 3819
INFO	2022-09-13 10:11:29	OpticalDuplicateFinder	compared         1,000 ReadEnds to others.  Elapsed time: 00:05:34s.  Time for last 1,000:    0s.  Last read position: 0:0
INFO	2022-09-13 10:11:29	OpticalDuplicateFinder	compared         2,000 ReadEnds to others.  Elapsed time: 00:05:34s.  Time for last 1,000:    0s.  Last read position: 0:0
INFO	2022-09-13 10:11:29	OpticalDuplicateFinder	compared         3,000 ReadEnds to others.  Elapsed time: 00:05:34s.  Time for last 1,000:    0s.  Last read position: 0:0
INFO	2022-09-13 10:11:34	OpticalDuplicateFinder	Large duplicate set. size = 32910

And it stuck for 16h without any progress.

**Comment by kachulis** [comment]
large duplicate sets can cause optical duplicate finding to be very slow.  You can tell MarkDuplicates not to try to find optical duplicates in duplicate sets over a certain size using the `MAX_OPTICAL_DUPLICATE_SET_SIZE` command line option (try setting it to, for example 10000 to start.  You can also turn off optical duplicate finding completely by setting `READ_NAME_REGEX` to null.  Note that these suggestions will slightly reduce the accuracy of library complexity calculations, but duplicate marking should be otherwise still accurate.
