### ISSUE TITLE
Update request to SamToFastq documentation

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/picard#1834]
We would like the SamToFastq tool doc page to be more clear that this tool can take both coordinate and name sorted inputs. There should also be a description that the order of the fastq pairs will be different depending on your input sam sort order. This description is in the GATK forum thread.

This request was created from a contribution made by Jakub Savara on July 24, 2022 10:48 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/7568071901083-SamToFastq-bam-order](https://gatk.broadinstitute.org/hc/en-us/community/posts/7568071901083-SamToFastq-bam-order)

\--

SamToFastq tool:

Can we use as input coordinate and also name sorted bam?

Thanks.<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/291776'>Zendesk ticket #291776</a>)<br> gz#291776</i>

**Comment by droazen** [comment]
@GATKSupportTeam Looking at the code for this tool, it's not clear that it will produce correct output when given coordinate-sorted input -- someone should test to make sure.

**Comment by kockan** [comment]
It should work with a coordinate sorted sam/bam. We still might want to add a test for completeness.

**Comment by kockan** [comment]
Closed by #1920
