### ISSUE TITLE
testBamToBfq output changed when switching from OpenJDK11 to OpenJDK17

### ISSUE THREAD

**Issue by pgrt** [broadinstitute/picard#1840]
Hello,

I am the Debian maintainer of picard.

I have recently built picard against htsjdk 3.0.2, no problem.

When additionally using OpenJDK17 (which is now the default JDK in Debian) instead of OpenJDK11, I got failures in testBamToBfq because the 5th byte in the generated file is 0x00FF instead of 0x0000 in the reference, see enclosed zip file.

[orig_and_generated.zip](https://github.com/broadinstitute/picard/files/9922443/orig_and_generated.zip)

My intuition is that we should not care, but please tell me if we should?

Warm thanks,

Pierre

**Comment by cmnbroad** [comment]
@pgrt Yes, this is due to a valid change in the header produced by the Java gzip implementation, and the failure is harmless. It is fixed in https://github.com/broadinstitute/picard/pull/1833.

**Comment by pgrt** [comment]
Hello @cmnbroad , thank you so much for looking at my issue and solving it, and also for the other pointers you provided me with!

Best regards,
Pierre
