### ISSUE TITLE
Thresholds for AT_DROPOUT and GC_DROPOUT

### ISSUE THREAD

**Issue by Newbee-glitch** [broadinstitute/picard#1845]
**documentation request**

### Description
Both CollectGcBiasMetrics and CollectHSMetrics will generate AT_DROPOUT and GC_DROPOUT.

Is there any threshold for AT_DROPOUT and GC_DROPOUT ? Like a bad-range and a good-range ?

**Comment by lbergelson** [comment]
The metrics are described [here](https://broadinstitute.github.io/picard/picard-metric-definitions.html).   I don't know what ranges are used in practice.  You could try asking on the gatk forums.
