### ISSUE TITLE
Picard MergeBamAlignment issue

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#186]
Exception merging bam alignment due to sort error. User has provided snippets for debugging.

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/discussion/5335/picard-mergebamalignment-issue/p1

**Comment by vdauwera** [comment]
@chandrans Would you be able to process this bug report?

**Comment by chandrans** [comment]
Yes, I think I can handle it.

**Comment by chandrans** [comment]
It looks like his ALIGNED_BAM input is missing read group information. When I run Validate Sam File, it gives a long list of reads missing read group information.

**Comment by vdauwera** [comment]
@chandrans Please post a representative section of the validation error output.

**Comment by chandrans** [comment]
The error message I get from MergeBamAlignment is:
Exception in thread "main" java.lang.IllegalStateException: Aligned record iterator (HS3:608:C6LNLACXX:7:1101:10082:8616) is behind the unmapped reads (HS3:608:C6LNLACXX:7:1101:10083:36394)
	
The error message from ValidateSamFile:
ERROR: Read groups is empty
WARNING: Read name HS3:608:C6LNLACXX:7:1316:15889:69616, A record is missing a read group
WARNING: Read name HS3:608:C6LNLACXX:7:1107:13342:90541, A record is missing a read group
WARNING: Read name HS3:608:C6LNLACXX:7:2208:4239:16257, A record is missing a read group
WARNING: Read name HS3:608:C6LNLACXX:7:2303:18152:26068, A record is missing a read group
WARNING: Read name HS3:608:C6LNLACXX:7:1209:14098:5489, A record is missing a read group
WARNING: Read name HS3:608:C6LNLACXX:7:2105:15796:95595, A record is missing a read group
.
.
.
up to 100 (max) errors for record missing read group. This is for the ALIGNED_BAM that goes into MergeBamAlignment.

**Comment by sooheelee** [comment]
I've seen this MergeBamAlignment error. If this is not resolved, let me know and I can dig through my notes on what this was about.

**Comment by chandrans** [comment]
OOh it looks like your suggestion resolved the latest user's error @sooheelee 👍
