### ISSUE TITLE
Picard new release

### ISSUE THREAD

**Issue by lappazos** [broadinstitute/picard#1863]
Error: LinkageError occurred while loading main class picard.cmdline.PicardCommandLine
java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by cmnbroad** [comment]
@lappazos What Java version are you using ? The latest Picard release requires [Java 17](https://github.com/broadinstitute/picard/releases/tag/3.0.0).

**Comment by lappazos** [comment]
@cmnbroad i'm installing it using 
`ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda && rm -rf ~/miniconda.sh
RUN conda install -c bioconda/label/main picard -y
RUN conda update -c bioconda/label/main picard -y`

**Comment by lappazos** [comment]
From some reason, in conda it think its requirement is Java11 instead of Java17

**Comment by cmnbroad** [comment]
I suspect thats because the bioconda recipe for the new release wasn't updated in time (the bioconda recipe is maintained separately from Picard itself). It looks like it's been [done now](https://github.com/bioconda/bioconda-recipes/pull/39644) though.

**Comment by connorrogerson** [comment]
@desmodus1984 easier solve here is to downgrade picard to 2.27.5 and should work.
