### ISSUE TITLE
SamToFastq

### ISSUE THREAD

**Issue by ruinw** [broadinstitute/picard#1864]
**SRR*.recal.bam is caused by gatk
then i run
#extract
samtools view -h -b SRR3270834.recal.bam chr6:28510120-33480577 > SRR3270834.mhc.bam
#Extract unmap reads
samtools view -b -f 4 SRR3270834.recal.bam > sample.unmap.bam
#Merge bam files
samtools merge -o SRR3270834.merge.bam SRR3270834.unmap.bam SRR3270834.mhc.bam
#Create fastq
java -jar /mydata/software/PICARD/picard.jar SamToFastq I=SRR3270834.merge.bam F=SRR3270834.hlatmp.1.fastq F2=SRR3270834.hlatmp.2.fastq
There will be:**

(hla-hd)[root@localhost testhla]$java -jar /mydata/software/PICARD/picard.jar SamToFastq I=SRR3270834.merge.bam F=SRR3270834.hlatmp.1.fastq F2=SRR3270834.hlatmp.2.fastq
INFO	2023-03-09 02:55:40	SamToFastq	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** 
https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    SamToFastq -I SRR3270834.merge.bam -F SRR3270834.hlatmp.1.fastq -F2 SRR3270834.hlatmp.2.fastq
**********

02:55:41.022 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mydata/software/PICARD/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Mar 09 02:55:41 EST 2023] SamToFastq INPUT=SRR3270834.merge.bam FASTQ=SRR3270834.hlatmp.1.fastq SECOND_END_FASTQ=SRR3270834.hlatmp.2.fastq    OUTPUT_PER_RG=false COMPRESS_OUTPUTS_PER_RG=false RG_TAG=PU RE_REVERSE=true INTERLEAVE=false INCLUDE_NON_PF_READS=false CLIPPING_MIN_LENGTH=0 READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Mar 09 02:55:41 EST 2023] Executing as root@localhost.localdomain on Linux 3.10.0-957.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_181-b13; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.27.5
[Thu Mar 09 02:55:41 EST 2023] picard.sam.SamToFastq done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: Illegal mate state: SRR3270834.49902681
	at picard.sam.SamToFastq.assertPairedMates(SamToFastq.java:438)
	at picard.sam.SamToFastq.handleRecord(SamToFastq.java:309)
	at picard.sam.SamToFastq.doWork(SamToFastq.java:205)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:309)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

**Then i use new version picard,there will be:**
(hla-hd)[root@localhost testhla]$java -jar /mydata/software/PICARD/new/picard.jar SamToFastq I=SRR3270834.merge.bam F=SRR3270834.hlatmp.1.fastq F2=SRR3270834.hlatmp.2.fastq
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**I also use jsd17 rerun,but the similar result.**

**what is this mean?Then i use output**
#Change fastq ID
cat SRR3270834.hlatmp.1.fastq |awk '{if(NR%4 == 1){O=$0;gsub("/1"," 1",O);print O}else{print $0}}' > SRR3270834.hla.1.fastq
cat SRR3270834.hlatmp.2.fastq |awk '{if(NR%4 == 1){O=$0;gsub("/2"," 2",O);print O}else{print $0}}' > SRR3270834.hla.2.fastq

**then i run hla-hd**
**the header is this**

HLA-HD version 1.7.0
Error: Read SRR3270834.366135751 has more read characters than quality values.
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134
Error: Read SRR3270834.366135752 has more read characters than quality values.
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134
Error: Read SRR3270834.366135751 has more read characters than quality values.
Aborted (core dumped)
(ERR): bowtie2-align exited with value 134
Error: Read SRR3270834.366135752 has more read characters than quality values.
Aborted (core dumped)
...

So,is my fq  wrong?I don't know which step i am wrong.
Thanks!

**Comment by ruinw** [comment]
**I run ValidateSamFile,and try solve this question.I fail to resolve it.
This is my pipe:
bwa→SortSam→samtools flagstat→samtools stats→MarkDuplicates→BuildBamIndex→BaseRecalibrator→ApplyBQSR**
_I want use bam from ApplyBQSR to get hla type,so I run code as shown
samtools view -h -b SRR3270834.recal.bam chr6:28510120-33480577 > SRR3270834.mhc.bam
#Extract unmap reads
samtools view -b -f 4 sample.sorted.bam > sample.unmap.bam
#Merge bam files
samtools merge -o SRR3270834.merge.bam SRR3270834.unmap.bam SRR3270834.mhc.bam
#Create fastq
java -jar /mydata/software/PICARD/picard.jar SamToFastq I=SRR3270834.merge.bam F=SRR3270834.hlatmp.1.fastq F2=SRR3270834.hlatmp.2.fastq_

**This is result of ValidateSamFile.**
**java -jar /mydata/software/PICARD/picard.jar ValidateSamFile I=SRR3270834.merge.bam MODE=SUMMARY**

INFO	2023-03-09 20:47:32	ValidateSamFile	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** 
https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    ValidateSamFile -I SRR3270834.merge.bam -MODE SUMMARY
**********


20:47:32.948 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mydata/software/PICARD/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Mar 09 20:47:32 EST 2023] ValidateSamFile INPUT=SRR3270834.merge.bam MODE=SUMMARY    MAX_OUTPUT=100 IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 SKIP_MATE_VALIDATION=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Mar 09 20:47:32 EST 2023] Executing as root@localhost.localdomain on Linux 3.10.0-957.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_181-b13; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.27.5
WARNING	2023-03-09 20:47:32	ValidateSamFile	NM validation cannot be performed without the reference. All other validations will still occur.


## HISTOGRAM	java.lang.String
Error Type	Count
ERROR:INVALID_PLATFORM_VALUE	2
ERROR:MATE_NOT_FOUND	1

[Thu Mar 09 20:47:34 EST 2023] picard.sam.ValidateSamFile done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2058354688
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp

**Comment by cmnbroad** [comment]
@ruinw Your original error indicates that there are reads named `SRR3270834.49902681` that appear to be paired, but that have SAMFlags that are not congruous with them being paired (specifically, one should have the `0x40` flag set and one should have the `0x80` flag set), but they don't meet that condition. I'm not sure why that is - one suggestion would be to try extracting those reads and looking at their flag values (you can use https://broadinstitute.github.io/picard/explain-flags.html to interpret the values) at each step in your pipeline to see if the values are being changed along the way, or if they were always like that.

The second error you reported is because the newest version of Picard requires Java 17 - the error message indicates that you were running an older version of Java for that.

**Comment by kachulis** [comment]
@ruinw I suspect the issue may be due to selecting reads from the bam without guaranteeing that you also select their mates.  For example, if a read is in the mhc region, but its mate is not, your resulting bam will have a read which is marked as being in a pair, but the bam will not include its mate.  You can adjust your commands as follows to also include mates of selected reads:
```shell
# select reads in mhc region, and their mates
samtools view -h -b --fetch-pairs SRR3270834.recal.bam chr6:28510120-33480577 > SRR3270834.mhc.bam

# select reads which are unmapped or have an unmapped mate
samtools view -b --include-flags 12 SRR3270834.recal.bam > sample.unmap.bam
```

**Comment by ruinw** [comment]
> @ruinw I suspect the issue may be due to selecting reads from the bam without guaranteeing that you also select their mates. For example, if a read is in the mhc region, but its mate is not, your resulting bam will have a read which is marked as being in a pair, but the bam will not include its mate. You can adjust your commands as follows to also include mates of selected reads:
> 
> ```shell
> # select reads in mhc region, and their mates
> samtools view -h -b --fetch-pairs SRR3270834.recal.bam chr6:28510120-33480577 > SRR3270834.mhc.bam
> 
> # select reads which are unmapped or have an unmapped mate
> samtools view -b --include-flags 12 SRR3270834.recal.bam > sample.unmap.bam
> ```

thank you!I will try

**Comment by xmy1990** [comment]
hello @https://github.com/ruinw
I also meet the sam error as your above:
Exception in thread "main" picard.PicardException: Illegal mate state: SRR3270834.49902681

I also use hla-hd.
Have you solved the error?

Thank you!
