### ISSUE TITLE
GENOTYPING_ERROR_RATE doesn't do anything in CrosscheckFingerprints

### ISSUE THREAD

**Issue by kachulis** [broadinstitute/picard#1865]
Since #1455, GENOTYPING_ERROR_RATE hasn't actually done anything in CrosscheckFingperints, due to `minPExpected` being unused in `FingerprintChecker.calculateMatchResults` after that PR.  Should it still be used?  Should we just remove it?

@yfarjoun do you have any memory of deciding that wasn't necessary anymore?

**Comment by yfarjoun** [comment]
I remember discussions with @tfenne about this....but not an actual conclusion... I also seem to remember that it's more of a hack to avoid infinities than the results of a rigorous mathematical derivation....

**Comment by cmnbroad** [comment]
I will mark the arg as deprecated and then have Louis re-review so we close this.
