### ISSUE TITLE
Question about Depth 

### ISSUE THREAD

**Issue by Nour-EddineS** [broadinstitute/picard#1867]
Dear All,
How can i calculate depth of my BAM/fastq file.
Thanks in advance for your help.

Best,

**Comment by droazen** [comment]
Hi @Nour-EddineS ,

You likely want to run `CollectWgsMetrics`. Instructions for running it can be found here: https://gatk.broadinstitute.org/hc/en-us/articles/13832707851035-CollectWgsMetrics-Picard-
