### ISSUE TITLE
CollectSamErrorMetrics overlap total bases

### ISSUE THREAD

**Issue by kachulis** [broadinstitute/picard#1873]
When calculating an OVERLAPPING_ERROR metrics, it would seem that NUM_BASES_WITH_OVERLAPPING_READS should be identical for FIRST and SECOND reads.  However, this does not seem to be true.  It is unclear why this is the case.

@fleharty

**Comment by fleharty** [comment]
@kachulis @yfarjoun 
This turns out not to be a bug, the data we were looking at had variable length reads which is what caused the confusion.
