### ISSUE TITLE
BUILD FAILED  error 

### ISSUE THREAD

**Issue by HK0911** [broadinstitute/picard#1874]
$     ./gradlew shadowJar
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Warning: using Java 11 but only Java 17 has been tested.

FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/d/wgs/raw/picard/build.gradle' line: 48

* What went wrong:
A problem occurred evaluating root project 'picard'.
> A Java 17 compatible (Java 17 or later) version is required to build GATK, but 11 was found. See https://github.com/broadinstitute/picard/blob/master/README.md#building-picard for information on how to build picard.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

**Comment by cmnbroad** [comment]
@HK0911 As the error message states, you need  to use Java 17 to run the latest Picard. You're using Java 11.
