### ISSUE TITLE
Picard Cloud

### ISSUE THREAD

**Issue by lappazos** [broadinstitute/picard#1898]
what is picard Cloud?

**Comment by cmnbroad** [comment]
@lappazos There is an effort under way to enable Picard to more generally support reading from and writing to cloud file stores such as Google Cloud Storage (the immediate target), or Azure or AWS. "picard Cloud" may refer to that effort, but without more context about where you saw this term, its hard to say.

**Comment by lbergelson** [comment]
I think this is referring to the picard-cloud.jar vs the normal picard.jar.  The current releases of picard do not have a hard dependency on google cloud libraries and cannot natively access data on google cloud.  The picard-cloud build includes the  necessary libraries at the cost of increased filesize.  We are currently removing this distinction and making the google libraries core picard dependencies so in the future all jars will effectively be cloud jars.
