### ISSUE TITLE
Creating 

### ISSUE THREAD

**Issue by kibanez** [broadinstitute/picard#1899]
## ***This issue tracker is for bug reports only. Before opening a new issue here, please make a post on our [support forum](https://gatk.broadinstitute.org/hc/en-us/community/topics) so that our support team can look at your issue and determine whether it needs to be escalated into a bug report.***

----

### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_picard-tools LiftoverVcf_

### Affected version(s)
- Latest v3.0.0 version
- v2.27.4

### Unffected version
- v2.18.25

### Description 
_This issue is an edge case, but it happens with latest Picard-tools releases. With the release we started using picard-tools LiftoverVcf (v2.18.25) does not happen, but it does with >=v2.27.4. Affected VCF files are those processed by GATK with an Indel shown with `*` 

Example: 
chr21   10569528        .       AG      *       221.62  ExcessHet       AC=1;AF=0.5;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;QD=0.03;ReadPosRankSum=-0.662;SOR=0.795    GT:AD:DP:GQ:PL  0/1:73,16:89:99:441,0,2975
chr21   10569528        .       AG      A       221.62  ExcessHet       AC=0;AF=0;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;QD=0.03;ReadPosRankSum=-0.662;SOR=0.795      GT:AD:DP:GQ:PL  0/0:73,0:89:99:441,660,3683

with (unaffected) v2.18.25 we get

chr21 10942927 . TC T 221.62 ExcessHet AC=1;AF=0.5;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;OriginalContig=chr21;OriginalStart=10569528;QD=0.03;ReadPosRankSum=-0.662;ReverseComplementedAlleles;SOR=0.795 GT:AD:DP:GQ:P0/1:73,16:89:99:441,0,2975

chr21 10942927 . TC T 221.62 ExcessHet AC=0;AF=0;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;OriginalContig=chr21;OriginalStart=10569528;QD=0.03;ReadPosRankSum=-0.662;ReverseComplementedAlleles;SOR=0.795 GT:AD:DP:GQ:P0/0:73,0:89:99:441,660,3683

but with (affected) latest (v3.3.0) and v2.27.4 releases we get:

proband_b37_picard_2.27.vcf:chr21   1       .       N       *       221.62  ExcessHet       AC=1;AF=0.5;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;OriginalContig=chr21;OriginalStart=10569528;QD=0.03;ReadPosRankSum=-0.662;ReverseComplementedAlleles;SOR=0.795     GT:AD:DP:GQ:PL  0/1:73,16:89:99:441,0,2975
chr21	10942927	.	TC	T	221.62	ExcessHet	AC=0;AF=0;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;OriginalContig=chr21;OriginalStart=10569528;QD=0.03;ReadPosRankSum=-0.662;ReverseComplementedAlleles;SOR=0.795	GT:AD:DP:GQ:PL	0/0:73,0:89:99:441,660,3683

proband_b37_picard_2.27.vcf:

proband_b37_picard_2.27.vcf:chr21   1       .       N       *       221.62  ExcessHet       AC=1;AF=0.5;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;OriginalContig=chr21;OriginalStart=10569528;QD=0.03;ReadPosRankSum=-0.662;ReverseComplementedAlleles;SOR=0.795     GT:AD:DP:GQ:PL  0/1:73,16:89:99:441,0,2975
proband_b37_picard_2.27.vcf:chr21	10942927	.	TC	T	221.62	ExcessHet	AC=0;AF=0;AN=2;BaseQRankSum=2.45;DP=89;ExcessHet=62.0242;FS=1.366;InbreedingCoeff=-0.5844;MQ=59.68;MQRankSum=0.757;OriginalContig=chr21;OriginalStart=10569528;QD=0.03;ReadPosRankSum=-0.662;ReverseComplementedAlleles;SOR=0.795	GT:AD:DP:GQ:PL	0/0:73,0:89:99:441,660,3683

Please, note that the original `chr21:10569528:AG>*` may cause picard-tools LiftoverVcf creating `chr21:1:N>*` ??
_

#### Steps to reproduce
_picard-tools LiftoverVcf 
I=proband.vcf 
O=proband_b37.vcf 
CHAIN=/home/data/template/chain/hg38ToHg19.over.chain.gz 
REJECT=proband_rejected.vcf 
R=/home/data/fasta/hg19/hg19.fa 
WRITE_ORIGINAL_POSITION=true

with any version >= v2.27.4
_

#### Expected behavior
_Expected output should be similar to what v2.18.25 generates_

#### Actual behavior
_The new output creates (we think this is an edge case) POS == 1 in that chromosome. Only seen in one INDEL so far_

**Comment by kachulis** [comment]
@kibanez thanks for the heads up about this!  This should be fixed now if you want to build from source.  Or the fix should be available in the next release.
