### ISSUE TITLE
Installation problem of v3.1.0

### ISSUE THREAD

**Issue by FionaMoon** [broadinstitute/picard#1905]
Hi Picard developer,
I got this error when installing new version of Picard:
```
$ ./gradlew shadowJar
-bash: ./gradlew: /bin/sh^M: bad interpreter: No such file or directory
```
Any advice for solving this problem?

Thank you in advance.

**Comment by kockan** [comment]
Hi @FionaMoon , I just built the new version of Picard with that command so I believe this issue might have to do with your system.

A quick google search highly suggests that your problem has to do with unix/dos line endings so it depends on your OS/system. Could you take a look at the following and see if any of it helps/makes sense?

https://stackoverflow.com/questions/23097528/bin-shm-bad-interpreter-no-such-file-or-directory
https://stackoverflow.com/questions/14219092/bash-script-bin-bashm-bad-interpreter-no-such-file-or-directory
https://askubuntu.com/questions/1158577/bin-bash-bad-interpreter-no-such-file-or-directory
https://askubuntu.com/questions/304999/not-able-to-execute-a-sh-file-bin-bashm-bad-interpreter

**Comment by lbergelson** [comment]
@FionaMoon A few questions.

1.  Do previous versions work?
2. What is the result of running `./gradlew` alone or `./gradlew tasks` ?

We did just update the various gradle scripts so it's possible it's a result of the changes.  It could also be a configuration issue on your system.  

One possible workaround would be to install gradle (8.2.1) on your system and invoke it directly with `gradle shadowJar` instead of using the wrapper script

**Comment by FionaMoon** [comment]
> @FionaMoon A few questions.
> 
> 1. Do previous versions work?
> 2. What is the result of running `./gradlew` alone or `./gradlew tasks` ?
> 
> We did just update the various gradle scripts so it's possible it's a result of the changes. It could also be a configuration issue on your system.
> 
> One possible workaround would be to install gradle (8.2.1) on your system and invoke it directly with `gradle shadowJar` instead of using the wrapper script

1. I used to install picard 3.0.0 by conda and it works well.
2. when I run `./gradlew ` , I got same error
> -bash: ./gradlew: /bin/sh^M: bad interpreter: No such file or directory

**Comment by kockan** [comment]
I would also double check this (an answer from someone in one of the links above) to make sure:

`For people using Intellij, open the gradlew file of your project. In the lower right corner of the IDE there will be one element written CRLF or LF or CR. Changed it to LF and it worked. (I'm using Windows+WSL)`

At least with that we can eliminate line-endings as a potential cause.
