### ISSUE TITLE
Question marks in output of Picard tools

### ISSUE THREAD

**Issue by Yu-jinKim** [broadinstitute/picard#1906]
Hello,

Do you have documentation about when the tools in Picard output question marks?

I have this thread for HSMetrics: https://sourceforge.net/p/samtools/mailman/samtools-help/thread/CAEwHMLEAdhWd-C+ELWHZ00NQ5B=UbpK-0DLD21EZjvNL7WOSPQ@mail.gmail.com/

But i have found question marks in InsertSizeMetrics standard deviation.
Do you have a list of the tools that can output question marks?

Thanks

**Comment by kockan** [comment]
Looks like any metric that _can_ have the values "NaN" or "Infinity" will be printed as such if they _do_ get assigned any of those values, based on this snippet I found:
```
decimalFormatSymbols.setNaN("?");
decimalFormatSymbols.setInfinity("?");
```

**Comment by Yu-jinKim** [comment]
Is there any indication on why question marks can be assigned?

**Comment by Yu-jinKim** [comment]
What about all the other metrics? My end goal is having QC trend monitoring so I want to know how to deal with those question marks when plotting.

**Comment by kockan** [comment]
I believe you could deal with any question mark symbols reported for any metrics the same way you would for any other missing data (e.g. N/A) in some other analysis.
