### ISSUE TITLE
--TMP_DIR parameter is ignored and tmp dir defaults to /tmp for CollectInsertSizeMetrics (and possibly more picard tools))

### ISSUE THREAD

**Issue by gokalpcelik** [broadinstitute/picard#1907]
Hi. 

Latest version of picard (3.10) standalone and picard in gatk 4.4.0.0 seems to ignore the `--TMP_DIR` switch and defaults to using /tmp for temporary files. 

The command line used for the program (Tried both legacy and new style parameters.)

```
java -jar picard.jar CollectInsertSizeMetrics -I bamfile.bam -O picard2.txt -H hist4.pdf --TMP_DIR /path/to/tmp

java -jar picard.jar CollectInsertSizeMetrics I=bamfile.bam O=picard2.txt H=hist4.pdf TMP_DIR=/path/to/tmp
```

In both cases the log starts with 

```
INFO	2023-08-04 18:41:26	RExecutor	Executing R script via command: Rscript /tmp/script838653579436375814.R
INFO	2023-08-04 18:41:26	ProcessExecutor	[1] "Checking if R is installed"
```

Desired behavior should be 

```
INFO	2023-08-04 18:41:26	RExecutor	Executing R script via command: Rscript /path/to/tmp/script838653579436375814.R
INFO	2023-08-04 18:41:26	ProcessExecutor	[1] "Checking if R is installed"
```

When javaVM is modified by `-Djava.io.tmpdir=/path/to/tmp` resulting output is 

```
INFO	2023-08-04 18:41:26	RExecutor	Executing R script via command: Rscript /path/to/tmp/script838653579436375814.R
INFO	2023-08-04 18:41:26	ProcessExecutor	[1] "Checking if R is installed"
```

Similar behavior is present with picard running from gatk 4.4.0.0. I have not checked other standalone picard tools or picard tools inside gatk but they might be affected as well. 

Both @droazen and @lbergelson also think this is bug. 

Regards

**Comment by kockan** [comment]
Should be fixed by #1908
