### ISSUE TITLE
 INVALID_ALIGNMENT_START

### ISSUE THREAD

**Issue by miderxi** [broadinstitute/picard#1912]
picard.jar CollectRnaSeqMetrics  \
 I=FFPE-breast_Aligned.sortedByCoord.sub.out.bam \
 O=FFPE-breast.SPLiT.RNA_Metrics \
 STRAND_SPECIFICITY=NONE \
 REF_FLAT=/Human_noncoding/refFlat.txt \
 RIBOSOMAL_INTERVALS=/Human_noncoding/rRNA.interval_list

Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 75887530, Read name A00582:989:H72GCDSX3:3:2362:1542:35383, Alignment start (262141) must be <= reference sequence length (441) on reference NONHSAT148573.1

#way of build reference.
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/GRCh38.primary_assembly.genome.fa.gz
wget http://www.noncode.org/datadownload/NONCODEv6_human.fa.gz
wget http://www.noncode.org/datadownload/NONCODEv6_human_hg38_lncRNA.gtf.gz
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.primary_assembly.annotation.gtf.gz

zless GRCh38.primary_assembly.genome.fa.gz NONCODEv6_human.fa.gz > genome.fa
zless gencode.v43.primary_assembly.annotation.gtf.gz NONCODEv6_human_hg38_lncRNA.gtf.gz > genome.gtf
#!STAR version ==2.7.10b
STAR --runThreadN 20 \
 --runMode genomeGenerate \
 --genomeDir STAR_index \
 --genomeFastaFiles genome.fa \
 --sjdbGTFfile genome.gtf \
 --sjdbOverhang 100 \
 --limitGenomeGenerateRAM 129386589109

**Comment by kockan** [comment]
I suspect this either has something to do with your input data or how STAR behaves on it. If we look at the line: `Alignment start (262141) must be <= reference sequence length (441) on reference NONHSAT148573.1` it seems that the alignment start is longer than that reference sequence. Could you check this alignment: `A00582:989:H72GCDSX3:3:2362:1542:35383` and make sure that the start/end coordinates are within the range of the reference sequence length?

**Comment by miderxi** [comment]
我已收到邮件，会尽快处理。

**Comment by miderxi** [comment]
i had fix this problem，input data problem，\r in my data.



发自我的iPhone


------------------ Original ------------------
From: Can Kockan ***@***.***&gt;
Date: Wed,Sep 13,2023 1:48 AM
To: broadinstitute/picard ***@***.***&gt;
Cc: string ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [broadinstitute/picard]  INVALID_ALIGNMENT_START (Issue #1912)





 
I suspect this either has something to do with your input data or how STAR behaves on it. If we look at the line: Alignment start (262141) must be <= reference sequence length (441) on reference NONHSAT148573.1 it seems that the alignment start is longer than that reference sequence. Could you check this alignment: A00582:989:H72GCDSX3:3:2362:1542:35383 and make sure that the start/end coordinates are within the range of the reference sequence length?

**Comment by kockan** [comment]
Great, thanks for the update!
