### ISSUE TITLE
java.io.FileNotFoundException: /tmp/CSPI.tmp15948393444880722616/7573.tmp (Too many open files)

### ISSUE THREAD

**Issue by poojancf** [broadinstitute/picard#1915]
## ***This issue tracker is for bug reports only. Before opening a new issue here, please make a post on our [support forum](https://gatk.broadinstitute.org/hc/en-us/community/topics) so that our support team can look at your issue and determine whether it needs to be escalated into a bug report.***
I am trying to use MarkDuplicates 
here is the code I am using 
java -jar .~/picard.jar MarkDuplicates
 INPUT=input.bam \ 
OUTPUT=ouput.bam \
METRICS_FILE=output.metrics.txt CREATE_INDEX=true         

The error is in find a tmp file. 
Please let me know how to troubleshoot this error. 

Thanks
### Instructions

- Use a **concise** yet **descriptive** title;
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request**;
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate;
- Delete the other template blocks and this header.

----

### Affected tool(s)
_Tool name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem and provide a minimal test case._

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) involved
_Tool name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) involved
_Tool name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by kockan** [comment]
This looks like the same issue with this: https://github.com/broadinstitute/picard/issues/1911

The most likely scenario is that you need to increase your "maximum open file" limit defined by your operating system.
For example, on my machine this would be `ulimit -a 10000` if I wanted to set this limit to 10000.
