### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by pk-zhu** [broadinstitute/picard#1941]
Hello,

I am currently working on creating a reference genome index for a species with a reference genome of approximately 10GB, most of which is hard-masked. I used the command: 

`picard CreateSequenceDictionary -R genome.fa`

However, I've encountered a technical issue, as detailed below:

However, I encountered the following error:

> Exception in thread "main" java.lang.NegativeArraySizeException: -2147483648
>         at htsjdk.samtools.reference.FastaSequenceFile.readSequence(FastaSequenceFile.java:177)
>         at htsjdk.samtools.reference.FastaSequenceFile.nextSequence(FastaSequenceFile.java:99)
>         at picard.util.SequenceDictionaryUtils$SamSequenceRecordsIterator.<init>(SequenceDictionaryUtils.java:86)
>         at picard.sam.CreateSequenceDictionary.lambda$getSamSequenceRecordsIterable$0(CreateSequenceDictionary.java:169)
>         at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:234)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:280)
>         at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:105)
>         at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:115)

Interestingly, this problem did not occur when indexing an unmasked genome. Could you please advise on how to successfully index a hard-masked genome? Any guidance or suggestions you could provide would be immensely appreciated.

Thank you for your time and assistance. I look forward to your valuable input.

**Comment by kockan** [comment]
I don't believe it should matter whether the reference is masked or unmasked. Looks like an overflow. Could you point to the unmasked/masked genomes if possible?

**Comment by kockan** [comment]
Closing for the time being. Will reopen/investigate if we receive the problematic hard-masked genome FASTA.
