### ISSUE TITLE
Picard Build Failure

### ISSUE THREAD

**Issue by n-belle** [broadinstitute/picard#1946]
## Bug Report
I am having trouble building Picard on my Linux software, and getting the following error
"Could not resolve org.ajoberstar.grgit:grgit-gradle:5.2.0"

### Affected tool(s)
./gradlew shadowJar

### Affected version(s)
I am using Java 21.0 

### Description 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'picard'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.ajoberstar.grgit:grgit-gradle:5.2.0.
     Required by:
         project : > org.ajoberstar.grgit:org.ajoberstar.grgit.gradle.plugin:5.2.0
      > No matching variant of org.ajoberstar.grgit:grgit-gradle:5.2.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.5' but:
          - Variant 'apiElements' capability org.ajoberstar.grgit:grgit-gradle:5.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')
          - Variant 'javadocElements' capability org.ajoberstar.grgit:grgit-gradle:5.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')
          - Variant 'runtimeElements' capability org.ajoberstar.grgit:grgit-gradle:5.2.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')
          - Variant 'sourcesElements' capability org.ajoberstar.grgit:grgit-gradle:5.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

#### Steps to reproduce
./gradlew shadowJar

**Comment by lbergelson** [comment]
Huh, that's strange. 
I'm not able to reproduce it yet.  It doesn't happen on my system, and I tried in a clean docker which also didn't hit that error. 
 
Are you sure java 8 isn't sneaking in somewhere?  Just to be clear, `which java`, `echo $JAVA_HOME` and `java -version` are all consistent with 21?

**Comment by cmnbroad** [comment]
If you want to build with Java 21, you'll need to change the language version to 21 in build.gradle. Note that we don't technically support Java 21 yet.

**Comment by lbergelson** [comment]
@himanshisyadav The error you're seeing makes sense to me.  We specify 17 as our java toolchain version.

Specifically in this line:

```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withJavadocJar()
    withSourcesJar()
}
```

Change the toolchain from 17 to 21 and it should work. (or add a second language version line with 21).
We don't regularly test with 21 but I wouldn't expect any  particular issues.

**Comment by himanshisyadav** [comment]
@lbergelson Thank you! I'll try that! We have recommended our users use Java 17 as it has developer support!

**Comment by lbergelson** [comment]
We'd like to move to officially support java 21 soon but there's no specific timeline.
