### ISSUE TITLE
Issue Running Picard MarkDuplicates: File Compression Error with Snappy

### ISSUE THREAD

**Issue by VPatel294** [broadinstitute/picard#1953]
Bug Report

Affected tool
Picard MarkDuplicates, SortSam, Snappy

Affected version
- Picard 3.1.1 running with openJDK 17.0

Description 
Hello, I am having an issue running any command with Picard that required file compression with snappy after finishing running. Below is a screenshot of my error report, it seems that the snappy module cannot be accessed correctly. I am running this on a SLURM computing cluster. 
![Screen Shot 2024-03-19 at 10 29 39 AM](https://github.com/broadinstitute/picard/assets/61365026/c2aab3da-131c-4086-9a0c-a3201b579ad5)

 Steps to reproduce
I have tried to run the command normally on a series of bam files with the code below. 

module load gatk/4.4.0.0-gdwu64w
module load openjdk
module load picard/3.1.1-vqrqbn
module load snappy

cd /data/niams_fis/NIH/IDX_VP/LFATMM/Bowtie2/noMit_Bam

for file in *woMit.bam; do
picard SortSam  -I $file -O ${file%.bam*}.sorted.bam -SO coordinate
done

Expected behavior
Typically, this would finish and output a sorted bam file that has been compressed or even a full bam file. 

Actual behavior
The job ends up being killed due to the error message displayed in the screenshot.

**Comment by kockan** [comment]
Being followed-up on this thread: https://gatk.broadinstitute.org/hc/en-us/community/posts/24382500795547-GATK-Picard-SortSam-MarkDups-Error-with-Snappy-Loading
