### ISSUE TITLE
about MarkDuplicates

### ISSUE THREAD

**Issue by cnxiaobo94** [broadinstitute/picard#1954]
Hi picard team,

I would like to ask a question about the duplication of sequencing data. I sequenced several libraries for a sample, and I used the MarkDuplicates function when processing each library. At last, after the MergeSamFiles were used to merge bam files of multiple libraries into one bam, do I need to use MarkDuplicates again?

Best,
Bo Xiao

**Comment by kachulis** [comment]
No, you do not need to mark duplicates across different libraries.  

In general, scientific questions like this are better suited to the [GATK forum](https://gatk.broadinstitute.org/hc/en-us/community/topics), where they can be answered more quickly.
