### ISSUE TITLE
MarkDuplicates SAM validation error

### ISSUE THREAD

**Issue by vivekbibs** [broadinstitute/picard#1961]
jdk-11.0.8_10
picard=2.6.
        {java} -jar {gatk} MarkDuplicates -I {input} \
        -O {output.marked} -M {output.metrics} \
        -R {human_ref} \
        --REMOVE_DUPLICATES true \
        --TMP_DIR $TMPDIR
Thanks in advance, please tell me if you need more info
htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 50598509, Read name HWI-D00810:720:HTL7MBCXY:1:2215:4305:54977, Mate Alignment start should be 0 because reference name = *.
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:458)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:849)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:591)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:570)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:524)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by kockan** [comment]
Could you try running `ValidateSamFile` (https://gatk.broadinstitute.org/hc/en-us/articles/21905113856795-ValidateSamFile-Picard) on your input SAM/BAM/CRAM? Looks like the problematic read is unmapped but it's mate somehow has an alignment start position other than 0. The diagnostics might tell us more.

**Comment by vivekbibs** [comment]
Many thanks for your quick response !
Here is the output for one of my problematic bams (I have around 20 bams that have the same problem). 
They are all coming from PDX samples (patient's tumors graffed into a mouse), that i need to run Variant calling on. But for that i needed to filter-out some of the reads coming from the host (the mouse), and maybe the source of the problem is mouse reads not perfectly filtered-out. 
I would be pleased if you could help me with analysing this output.
Many thanks again ! 
## HISTOGRAM	java.lang.String
Error Type	Count
ERROR:INVALID_ALIGNMENT_START	819606
ERROR:INVALID_FLAG_MATE_UNMAPPED	409803
ERROR:INVALID_MAPPING_QUALITY	389111
ERROR:INVALID_TAG_NM	103
ERROR:INVALID_UNALIGNED_MATE_START	409803
ERROR:MATE_NOT_FOUND	3694963
ERROR:MISMATCH_FLAG_MATE_UNMAPPED	378752
ERROR:MISSING_READ_GROUP	1
WARNING:RECORD_MISSING_READ_GROUP	146524865

Tool returned:
2

**Comment by meganshand** [comment]
@vivekbibs It looks like it might be that some of the mates of the mouse reads you filtered out are still in the file. If you filtered out the mouse reads by filtering over a certain interval list, then I'd recommend that you instead try this tool:

```
java -jar picard.jar FilterSamReads \
  I=input.bam \
   O=output.bam \
   INTERVAL_LIST=regions.interval_list \
   FILTER=includePairedIntervals
```

This will filter out regions in the interval list and their mates which will hopefully produce a valid bam.

**Comment by vivekbibs** [comment]
Thank you for quick response. Unfortunately I don't have a regions.interval_list. In fact, the method we use in our lab to filter the mouse reads is to map the fastq file to a concatenated reference file (mouse reference fasta file and human reference fasta file, concatenated in series). In the mouse reference the chromosomes are referred to as, e.g "chr2" for the chromosome 2, and on the contrary the human chromosomes are referred to as "2", e.g for the human chromosome 2.
Is there a way to filter-out the reads that are aligned to the mouse genome, using FilterSamReads, using the "chr" prefix ?
Many thanks in advance,
Vivek

**Comment by meganshand** [comment]
Yes, but you'll have to generate your own interval list file. Just make an interval list that contains the full length of the chromosomes you want to filter.

**Comment by rickymagner** [comment]
If you have any more questions, feel free to post on the [GATK forums](https://gatk.broadinstitute.org/hc/en-us/community/topics).
