### ISSUE TITLE
Add .fna to the list of recognized extensions

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#199]
Picard .dict file creation doesn’t recognize the FASTA file extension .fna. This needs to be added to the list of recognized extensions (check for .fasta, .fa, .fsa, or .fna).

**Comment by vdauwera** [comment]
@nh13 Do you have a pointer to where the list lives by any chance?

**Comment by vdauwera** [comment]
Well, found out two things. 

1. This is defined in htsjdk's [ReferenceSequenceFileFactory.java](https://github.com/samtools/htsjdk/blob/a30bc12df2aeb3b4312a9c236c6a639025d5b596/src/java/htsjdk/samtools/reference/ReferenceSequenceFileFactory.java), not Picard itself. 

2. The .fna extension is included in there, and accordingly, the latest version of Picard happily creates a dict file for a reference provided with .fna extension.

So it looks like there's nothing to do.

**Comment by vdauwera** [comment]
Actually, funny thing -- while .fna (which is what was originally requested)  is in there, .fsa is not, nor is .fas, which is another common one I remember from bygone days. We also don't include .seq, which is listed on the wikipedia page referred to in the original request. 

![uploads/547b19ef-5c42-4fbb-a7a2-cf8885bf9c2b/Screenshot 2015-04-27 01.09.59.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F547b19ef-5c42-4fbb-a7a2-cf8885bf9c2b%2FScreenshot+2015-04-27+01.09.59.png)

So, how far we want to go to accommodate the wildtype fastas out there?

**Comment by nh13** [comment]
No need to overgeneralize unless users want it.
