### ISSUE TITLE
Negative values in "reads processed" count for BuildBamIndex

### ISSUE THREAD

**Issue by oleraj** [broadinstitute/picard#206]
Hi, not sure if this is a bug, but it seems odd to me and I wanted to know if there is something wrong with my BAM file.  I noticed when indexing a large BAM file (341GB) that after about 2.1 billion reads, the numbers in the tally switch to _negative_, and then the tally continues in a positive direction towards zero. 

Here's a snippet of the screen output:
```
INFO	2015-05-04 18:29:46	BuildBamIndex	2138000000 reads processed ...
INFO	2015-05-04 18:29:51	BuildBamIndex	2139000000 reads processed ...
INFO	2015-05-04 18:29:55	BuildBamIndex	2140000000 reads processed ...
INFO	2015-05-04 18:30:00	BuildBamIndex	2141000000 reads processed ...
INFO	2015-05-04 18:30:05	BuildBamIndex	2142000000 reads processed ...
INFO	2015-05-04 18:30:09	BuildBamIndex	2143000000 reads processed ...
INFO	2015-05-04 18:30:14	BuildBamIndex	2144000000 reads processed ...
INFO	2015-05-04 18:30:19	BuildBamIndex	2145000000 reads processed ...
INFO	2015-05-04 18:30:23	BuildBamIndex	2146000000 reads processed ...
INFO	2015-05-04 18:30:28	BuildBamIndex	2147000000 reads processed ...
INFO	2015-05-04 18:30:32	BuildBamIndex	-2147000000 reads processed ...
INFO	2015-05-04 18:30:37	BuildBamIndex	-2146000000 reads processed ...
INFO	2015-05-04 18:30:43	BuildBamIndex	-2145000000 reads processed ...
INFO	2015-05-04 18:30:48	BuildBamIndex	-2144000000 reads processed ...
INFO	2015-05-04 18:30:53	BuildBamIndex	-2143000000 reads processed ...
INFO	2015-05-04 18:30:58	BuildBamIndex	-2142000000 reads processed ...
INFO	2015-05-04 18:31:03	BuildBamIndex	-2141000000 reads processed ...
INFO	2015-05-04 18:31:08	BuildBamIndex	-2140000000 reads processed ...
INFO	2015-05-04 18:31:13	BuildBamIndex	-2139000000 reads processed ...
INFO	2015-05-04 18:31:18	BuildBamIndex	-2138000000 reads processed ...
INFO	2015-05-04 18:31:23	BuildBamIndex	-2137000000 reads processed ...
```
Everything ran fine at the end (except for this little detail) -- i.e., no error messages:
```
INFO	2015-05-04 18:44:08	BuildBamIndex	-1982000000 reads processed ...
INFO	2015-05-04 18:44:11	BuildBamIndex	-1981000000 reads processed ...
INFO	2015-05-04 18:44:14	BuildBamIndex	-1980000000 reads processed ...
INFO	2015-05-04 18:44:17	BuildBamIndex	Successfully wrote bam index file /hpcdata/pid/aws/bam_files/new_files2/849NIH.bai
[Mon May 04 18:44:17 EDT 2015] net.sf.picard.sam.BuildBamIndex done. Elapsed time: 291.94 minutes.
Runtime.totalMemory()=257097728
```
At first glance, it appears that the index is okay.  I.e., when I run samtools idxstats, I see for chr22: 
```
22	51304566	29566913	142722
```
And when I run samtools view, I get the sum of the last two columns from above (mapped + unmapped):
```
samtools view 849NIH.bam 22 | wc
29709635
```

Do you think this output from BuildBamIndex is normal? Or, should I be worried about the BAM file and/or the index file?

Let me know if you need any more information.

Thanks,

Andrew

**Comment by oleraj** [comment]
Update: I was using an older version of picard... I'm going to retry with the latest release (1.130) and will report back whether I get the same result.

**Comment by vdauwera** [comment]
@oleraj OK, let us know how it goes with the newer version -- but please post in the [GATK forum](http://gatkforums.broadinstitute.org/) instead, as that's where we have moved general support. If something is a bug, we'll enter issue tickets ourselves. This makes managing support easier for us on our end. Thanks!

**Comment by yfarjoun** [comment]
Found the bug. fixing it.

**Comment by yfarjoun** [comment]
fixed. will be in the next version of picard.
