### ISSUE TITLE
MEAN_TARGET_COVERAGE underestimated in v1.124

### ISSUE THREAD

**Issue by hyjkim** [broadinstitute/picard#207]
When running calculateHsMetrics using the same interval file for baits and targets, I am getting two different numbers for MEAN_TARGET_COVERAGE and MEAN_BAIT_COVERAGE when coverage levels are very high (> 30,000x). When compared to coverage calculated using samtools mpileup, I see coverage levels more similar to MEAN_BAIT_COVERAGE.

Any idea why this might be occuring? 

Some example numbers are below:

Sample	MEAN_TARGET_COVERAGE 	MEAN_BAIT_COVERAGE	Calculated from samtools (>Q30)
A	28775	42528	38479
B	29396	59039	52709
C	30117	68338	61293

**Comment by yfarjoun** [comment]
HsMetrics (and TargetedPcrMetrics) use a *short* array  (as in short [] ) to calculate coverage metrics. This means that at each locus the coverage is limited by java MAX_SHORT which is ~32K...

There is currently no way to modify the behavior you are seeing.

**Comment by vdauwera** [comment]
We'll add this information to the docs if it's not already in there.

**Comment by dekling** [comment]
Incorporated explanation in to docs.

**Comment by dekling** [comment]
Incorporated explanation in to docs.
