### ISSUE TITLE
CollectGcBiasMetrics java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by slowkow** [broadinstitute/picard#212]
`CollectGcBiasMetrics` throws `java.lang.IndexOutOfBoundsException` and I don't see why.

At first, I thought this might be due difference in java versions. The same command worked on one system with java 1.6 and failed on a second system with java 1.7. On the second system, I changed to java 1.6 and the command still failed. So, it's not a java version issue.

Could you provide any clues about how I might fix or work around this error?

The log file for the failed run looks like this:

```
[Thu May 21 16:17:12 EDT 2015] picard.analysis.CollectGcBiasMetrics CHART_OUTPUT=sample1.gc_bias_metrics.pdf SUMMARY_OUTPUT=sample1.gc_bias_metrics_summary INPUT=sample1.bam OUTPUT=sample1.gc_bias_metrics VERBOSITY=DEBUG VALIDATION_STRINGENCY=LENIENT REFERENCE_SEQUENCE=/data/srlab/external-data/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa    WINDOW_SIZE=100 MINIMUM_GENOME_FRACTION=1.0E-5 IS_BISULFITE_SEQUENCED=false ASSUME_SORTED=true STOP_AFTER=0 QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Thu May 21 16:17:12 EDT 2015] Executing as ks38@rgs10.research.partners.org on Linux 2.6.32-431.29.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13; Picard version: 1.130(8b3e8abe25f920f5aa569db482bb999f29cc447b_1427207353) IntelDeflater
[Thu May 21 16:17:12 EDT 2015] picard.analysis.CollectGcBiasMetrics done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=5145362432
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at picard.analysis.CollectGcBiasMetrics.setup(CollectGcBiasMetrics.java:110)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:98)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:53)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

**Comment by yfarjoun** [comment]
hmmm. I'm not sure that this entirely java related. the line that fails is

saveHeader = header.getReadGroups().get(0).getLibrary();

And it's that get(0) that fails. This line is a recent change and so a
likely newly introduced bug.

It seems that your bam doesn't have readgroups and we didn't protect the
code against that case.
Can you post your header (or a minimal version that fails in the same way)?
(and state if we can use it in a unit test)

Your workaround (until bug is fixed): make sure your bams have readgroups.

Thanks!

Yossi.

On Thu, May 21, 2015 at 4:42 PM, Kamil Slowikowski <notifications@github.com>
wrote:
>
> CollectGcBiasMetrics completes successfully with this version of java:
>
> java -version
> java version "1.6.0_35"
> Java(TM) SE Runtime Environment (build 1.6.0_35-b10)
> Java HotSpot(TM) 64-Bit Server VM (build 20.10-b01, mixed mode)
>
> The same tool with the same inputs and arguments fails with this version
of java:
>
> java -version
> java version "1.7.0_51"
> Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
>
> The log file for the failed run looks like this:
>
> [Thu May 21 16:17:12 EDT 2015] picard.analysis.CollectGcBiasMetrics
CHART_OUTPUT=sample1.gc_bias_metrics.pdf
SUMMARY_OUTPUT=sample1.gc_bias_metrics_summary INPUT=sample1.bam
OUTPUT=sample1.gc_bias_metrics VERBOSITY=DEBUG
VALIDATION_STRINGENCY=LENIENT
REFERENCE_SEQUENCE=/data/srlab/external-data/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
   WINDOW_SIZE=100 MINIMUM_GENOME_FRACTION=1.0E-5
IS_BISULFITE_SEQUENCED=false ASSUME_SORTED=true STOP_AFTER=0 QUIET=false
COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false
CREATE_MD5_FILE=false
> [Thu May 21 16:17:12 EDT 2015] Executing as
ks38@rgs10.research.partners.org on Linux 2.6.32-431.29.2.el6.x86_64 amd64;
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13; Picard version:
1.130(8b3e8abe25f920f5aa569db482bb999f29cc447b_1427207353) IntelDeflater
> [Thu May 21 16:17:12 EDT 2015] picard.analysis.CollectGcBiasMetrics done.
Elapsed time: 0.00 minutes.
> Runtime.totalMemory()=5145362432
> To get help, see
http://broadinstitute.github.io/picard/index.html#GettingHelp
> Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0,
Size: 0
>     at java.util.ArrayList.rangeCheck(ArrayList.java:653)
>     at java.util.ArrayList.get(ArrayList.java:429)
>     at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
>     at
picard.analysis.CollectGcBiasMetrics.setup(CollectGcBiasMetrics.java:110)
>     at
picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:98)
>     at
picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:53)
>     at
picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
>     at
picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)

**Comment by slowkow** [comment]
Hi Yossi,

Indeed, Java version is not to blame. I got confused when I was testing the same command on two different systems. Picard 1.126 works and 1.130 fails.

This commit seems to introduce the line you mentioned:
https://github.com/broadinstitute/picard/commit/e0fbe398310f0fb4d223b2e932afef7a0ce8ac71#diff-2cfdc05396ec72fe66bb1536c182d031

Here's the header, and of course you may use it for unit tests. I used [subread] to generate the BAM file. Subread has an option called `--rg-id` to add a read group id, but I didn't use that option.

[subread]: http://subread.sourceforge.net/

```
@HD     VN:1.0  SO:unsorted
@SQ     SN:chrM LN:16571
@SQ     SN:chr1 LN:249250621
@SQ     SN:chr2 LN:243199373
@SQ     SN:chr3 LN:198022430
@SQ     SN:chr4 LN:191154276
@SQ     SN:chr5 LN:180915260
@SQ     SN:chr6 LN:171115067
@SQ     SN:chr7 LN:159138663
@SQ     SN:chr8 LN:146364022
@SQ     SN:chr9 LN:141213431
@SQ     SN:chr10        LN:135534747
@SQ     SN:chr11        LN:135006516
@SQ     SN:chr12        LN:133851895
@SQ     SN:chr13        LN:115169878
@SQ     SN:chr14        LN:107349540
@SQ     SN:chr15        LN:102531392
@SQ     SN:chr16        LN:90354753
@SQ     SN:chr17        LN:81195210
@SQ     SN:chr18        LN:78077248
@SQ     SN:chr19        LN:59128983
@SQ     SN:chr20        LN:63025520
@SQ     SN:chr21        LN:48129895
@SQ     SN:chr22        LN:51304566
@SQ     SN:chrX LN:155270560
@SQ     SN:chrY LN:59373566
@PG     ID:subread      PN:subread      VN:1.4.6
```

**Comment by yfarjoun** [comment]
Great. thanks Kamil.

if you can add the read-group, I predict the problem will go away. We
should at least fail more gracefully when there is no readgroup.

cheers.

On Thu, May 21, 2015 at 8:31 PM, Kamil Slowikowski <notifications@github.com

**Comment by slowkow** [comment]
If possible, I'd prefer that the tool successfully run with or without the read group. A warning would be fine, but a termination would not. Many other tools run successfully without a read group, so my expectation is that this one should run as well.

Thanks for the quick replies. I appreciate it!

**Comment by yfarjoun** [comment]
pull request is in.

On Fri, May 22, 2015 at 7:56 AM, Kamil Slowikowski <notifications@github.com
