### ISSUE TITLE
TMP_DIR is ignored or reset at some point

### ISSUE THREAD

**Issue by hammer** [broadinstitute/picard#215]
As reported elsewhere:
- https://bitbucket.org/galaxy/galaxy-central/pull-request/28/specify-java-temp-directory-for-picard/diff
- http://sourceforge.net/p/samtools/mailman/message/27300266/
- http://dev.list.galaxyproject.org/incorrect-tmp-dir-handling-in-picard-AddOrReplaceReadGroups-td4529840.html

**Comment by nh13** [comment]
@vdauwera can you take a look at this bug?

**Comment by vdauwera** [comment]
Will ask secons.

**Comment by vdauwera** [comment]
Oy, this is old. Sorry we never addressed this, @hammer. Is it still a problem?

**Comment by ronlevine** [comment]
@hammer Use the picard option `TMP_DIR=yourTmpDir`. Otherwise, TMP_DIR will be set to `java.io.tmpdir/user.name`

**Comment by ronlevine** [comment]
@vdauwera Can this be closed?
