### ISSUE TITLE
Genes get collapsed by RefFlatReader

### ISSUE THREAD

**Issue by alecw** [broadinstitute/picard#220]
RefFlatReader constructs Gene objects from all the transcript lines for a gene in the input refFlat file.  In some circumstances two different genes end up having Gene objects with the same Interval and strand.  RefFlatReader uses an OverlapDetector to hold the Gene objects, and the two Gene objects are considered to be equal because the have the same Interval, so only one of them survives RefFlatReader.

E.g. reading the following with RefFlatReader will result in only one Gene object:

GALNT4  GALNT4-001  12  -   89913184    89918583    89916592    89918326    1   89913184,   89918583,
GALNT4  GALNT4-201  12  -   89916431    89920039    89916592    89919932    3   89916431,89918896,89919657, 89917450,89918981,89920039,
POC1B-GALNT4    POC1B-GALNT4-001    12  -   89913184    89919975    89916592    89919672    3   89913184,89918896,89919657, 89918217,89918981,89919975,
POC1B-GALNT4    POC1B-GALNT4-002    12  -   89915710    89920039    89917424    89919672    3   89915710,89918896,89919657, 89917450,89918981,89920039,

I'm not sure what the right solution is -- should the two Genes resulting from the above transcripts not be considered equal?  Or should there be a way to use RefFlatReader without producing an OverlapDetector, so multiple Genes the are equal will survive?

**Comment by jamesnemesh** [comment]
This is a weird case of a fusion gene, where the transcript extents are the same, but exons in the middle change around.  It might be useful (if possible) to figure out how many of these cases exist in the hg19 meta data set, but my guess is this is extremely rare.

The key program that consumes the data from the RefFlatReader is TagReadWithGeneExon, which immediately creates an OverlapDetector<Gene>.  So unless we can change overlapdetector to not be fooled by this problem, any changes added to RefFlatReader will be reverted later on.

**Comment by vdauwera** [comment]
I'm going to close this given the age of the thread and the lack of concrete proposal; resurrect if needed/wanted.
