### ISSUE TITLE
Change ceiling of mean coverage values in picard pcr metrics data

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#232]
Both HsMetricsCollector and TargetedPcrMetricsCollector derive from TargetMetricsCollector, which, inturn uses a Coverage class to collect per-target coverage information. This little class uses a short[] to store the information. In targeted PCR we sometime have loci that have coverage greater than MAX_SHORT and while this doesn't overflow it maxes-out resulting in limited information. In dev experiments the actual value is important and so it would be nice to remove this cap.

Since most of the times the more important issue is run-time and memory usage, it might be foolish to simply replace the short[] with an int[], but perhaps a smarter object could be used. For example we could have a LowCoverage and a HighCoverage implementations of the Coverage class and if the coverage seems to be getting to high for an interval we replace it with with a HighCoverage object....

**Comment by tfenne** [comment]
Honesty it's probably fine to just shift this to an int[] these days.  If I've done my math right then an exome-sized array would be 120-150MB as an int[].  Even if you're collecting for several levels that's still only going to be 1-2GB of memory.  Given how much more memory machines tend to have nowadays I wouldn't sweat it.

**Comment by yfarjoun** [comment]
In that case, I'll ask @vdauwera if a secon could do that for us.

**Comment by yfarjoun** [comment]
As a test one could create a SamRecordSet using the SAMRecordSetBuilder with a target that gets more then MAX_SHORT reads and then run TargetedPcrMetricsCollector on it with per-target coverage, and see that that target gets more then MAX_SHORT reads in it.

**Comment by kbergin** [comment]
This has been addressed and merged!
