### ISSUE TITLE
InsertSizeMetricsCollector HistogramWidth width is not updated properly

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/picard#253]
`HistogramWidth` should be recalculated for each histogram if an explicit width isn't specified.

Instead it's being set by the first histogram and then never recalculated.  This means that a first histogram with a small stdev will cause the table to be trimmed to tightly.

**Comment by yfarjoun** [comment]
This is another good training bug for someone wanting to become familiar
with Picard.

Y.

**Comment by lbergelson** [comment]
I'll do this since I already have the fix in hellbender, just entered the issue to help me remember to do so.
