### ISSUE TITLE
ValidateSamFile should warn that NM validation cannot be done without REFERENCE_SEQUENCE

### ISSUE THREAD

**Issue by jmthibault79** [broadinstitute/picard#258]
I was unable to observe an error in NM tag calculation when running ValidateSamFile without setting the REFERENCE_SEQUENCE.  Adding that parameter solved my problem.

Was NM tag validation done differently, or not performed at all in the first case?  Either way, a warning or other notification is necessary to inform the user of this situation.

**Comment by yfarjoun** [comment]
NM validation cannot be performed without the reference. I guess an easy fix would be to add a warning if reference is null.

**Comment by yfarjoun** [comment]
fixed by https://github.com/broadinstitute/picard/pull/1220
