### ISSUE TITLE
MarkIlluminaAdapters histogram counts could be incorrect

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#264]
The histogram counts were being updated based on the first record of a pair, which is problematic when the second record is clipped at a different offset/index.

See proposed fix that needs tests here: https://github.com/broadinstitute/picard/pull/262

**Comment by yfarjoun** [comment]
Thank you very much for spotting this bug, and suggesting a fix. Would you be able to supply two reads that cause an error so that we could write a test for this? That would be very much appreciated!

**Comment by nh13** [comment]
I noticed this while trying to understand the code so I don't have two reads handy.  I observed that the clipping index can be set differently in the two ends of a read (see https://github.com/broadinstitute/picard/blob/95818b6e611725775e29d3b4acbaa23747eb3e94/src/java/picard/util/ClippingUtility.java#L164), and thus the histogram needs to consider each end rather than just the first twice.

**Comment by yfarjoun** [comment]
Got it. Thanks. This looks quite simple to test: a SAM file with one paired
read that has different read-lengths would do (it would seem)

**Comment by vdauwera** [comment]
Closing due to old age and inactivity.

**Comment by yfarjoun** [comment]
I think this should be opened...a test is needed here and this has an example of how to write such a test...

**Comment by nh13** [comment]
I think it's fixed in https://github.com/broadinstitute/picard/pull/341, closing.
