### ISSUE TITLE
Need to handle reverse-complemented indels in LiftoverVcf

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/picard#272]
Currently LiftoverVcf refuses to liftover indels or mixed records if they fall into a reverse complemented region in the target genome.  However, it is actually possible to liftover these records correctly with some changes to the code.
1. Check that the indel does not span over the boundary of a block in the chain file; if it does span then we should continue to fail to lift it over.
2. Multi-allelic records need to be split up into their component parts and lifted over (and output) as separate records.  This is necessary because indels are given a position which is the position before the event; in the original genome all of the indels in a multi-allelic record start at the same position but once the indels are reverse-complemented this no longer holds true.
3. Indels should be left-aligned if necessary based on the recommendations in the VCF specification. 

@tfenne said that he may one day take a shot at implementing this.

**Comment by yfarjoun** [comment]
Comment regarding 3 above: a mixed record might have snps and indels which would also need to be split (not only multi-indels)

4. Multiple records might end up in the same genomic position and so we should merge them in that case:
10 AGG->AG final G added to inform of the reference)
11 G->C
12 G->A

After liftover 10-12 -> 10-12 (NEGATIVE) should become

10 CCT->CT, TGT 
11 C->G

**Comment by yfarjoun** [comment]
Thinking about this more, we have a problem with genotypes....splitting/merging the variant is one thing, but if there are genotypes, these would need to be split up/merged, and with this come the splitting/merging of fields like PL, which would be quite horrendous (I think).

So, as a first pass, I'll take a crack at doing this for bi-allelic indels that will not require merging with neighboring variants.

**Comment by yfarjoun** [comment]
fixed by #836
