### ISSUE TITLE
FilterVcf IllegalArgumentException

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/picard#274]
When running FilterVcf, I get this error message: Exception in thread "main" java.lang.IllegalArgumentException: A reference dictionary is required for creating Tribble indices on the fly
The reference does have a .dict file accompanying it in the same folder.

The files are here: /humgen/gsa-scr1/schandra/GATK_basic

The command I ran:
java -jar /seq/software/picard/current/bin/picard.jar FilterVcf REFERENCE_SEQUENCE=human_b37_20.fasta INPUT=Sheila.HaplotypeCaller.vcf OUTPUT=Sheila.FilterVcf.vcf

This Issue was generated from your [forums](http://gatkforums.broadinstitute.org/discussion/comment/23868#Comment_23868)

**Comment by roozbeh73** [comment]
Any news on this bug? I have the same problem

**Comment by ktibbett** [comment]
Thus far we have determined that this works if you output a compressed vcf (.vcf.gz) but not if you try to output a vcf or bcf file.  We are working to determine the correct behavior/fix, but in the meantime outputting a compressed vcf will work around this.

**Comment by vdauwera** [comment]
Forum says a fix was put in, even though the PR isn't linked. Closing on the assumption that the forum is correct.
