### ISSUE TITLE
CompareSAMs reports file different from itself

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/picard#284]
picard 1.138
[ac12.sam | uploaded via ZenHub](https://files.zenhub.io/55f24bf2c633a8e0736339bc)

commandline:
`java -jar ~/bin/picard-tools-1.138/picard.jar CompareSAMs VALIDATION_STRINGENCY=SILENT ac12.sam ac12.sam`

result:
```
Executing as akiezun@wm494-874 on Mac OS X 10.9.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17; Picard version: 1.138(aa51703435dc6a423013e74e56b0b68405facd79_1439324166) JdkDeflater
Match	1
Differ	0
Unmapped_both	0
Unmapped_left	0
Unmapped_right	0
Missing_left	1
Missing_right	0
SAM files differ.
```

This is unexpected - files should be equal to themselves.

**Comment by mattsooknah** [comment]
Is this potentially related to https://github.com/broadinstitute/picard/issues/160 ?

**Comment by yfarjoun** [comment]
looks like the same issue from here. why was #160 closed? lack of interest?

**Comment by mattsooknah** [comment]
I remember fixing this in the Hellbender port of CompareSAMs (see https://github.com/broadinstitute/hellbender/pull/18) but I guess I forgot to copy the fix back into Picard. So it seems that ticket was closed prematurely.

Although https://github.com/broadinstitute/hellbender/pull/898 suggests that it's still broken in the Hellbender port as well ... @akiezun is that true?
