### ISSUE TITLE
add percent GQ0 to CollectVariantCallingMetrics

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#286]

**Comment by vdauwera** [comment]
Still a thing? This is way old...

**Comment by yfarjoun** [comment]
perhaps this should be merged with the other VCM issue...

**Comment by vdauwera** [comment]
You mean https://github.com/broadinstitute/picard/issues/555?

**Comment by yfarjoun** [comment]
yes.

**Comment by vdauwera** [comment]
Seems like very different work though. I'm not sure it's wise to tie this (possibly very straightforward) thing to that can of worms... I could see this being a training issue for a new dev.

**Comment by yfarjoun** [comment]
OK. sounds good.

**Comment by fleharty** [comment]
@yfarjoun @pjfan 
Yossi, do you think this would be a good feature for Peter to work on?

**Comment by yfarjoun** [comment]
sure.
