### ISSUE TITLE
Picard refers to undescribed SAM tags (BX etc)

### ISSUE THREAD

**Issue by jmarshall** [broadinstitute/picard#287]
The new "support for duplicate marking for individual barcodes (ex. 10X Genomics)" merged from PR #285 [refers to](https://github.com/broadinstitute/picard/blob/master/src/java/picard/sam/markduplicates/EstimateLibraryComplexity.java#L130-L137) barcode-related SAM record tags:

``` java
@Option(doc = "Barcode SAM tag (ex. BC for 10X Genomics)", optional = true)
public String BARCODE_TAG = null;

@Option(doc = "Read one barcode SAM tag (ex. BX for 10X Genomics)", optional = true)
public String READ_ONE_BARCODE_TAG = null;

@Option(doc = "Read two barcode SAM tag (ex. BX for 10X Genomics)", optional = true)
public String READ_TWO_BARCODE_TAG = null;
```

It appears that 10X Genomics plans for **BX** (et al) to be widespread tags therefore of general interest, and that Picard is supporting this in MarkDuplicates.  There was discussion on the pull request of getting 10X Genomics's tags into the SAM spec:

@wheaton5

> […] The BC field in our bams is the sample_index. The RX field is the raw barcode. BX is the corrected and validated (must be in barcode whitelist we expect) barcode as well as gem_group attached (if you do multiple library preps they cannot be dups of one another and did not come from the same long molecules).

@nh13

> I would also say that an email to `samtools-devel@lists.sourceforge.net` requesting that the new tags (`BX`, `RX`, etc.) be added to the spec early on will help avoid 10X Genomics data getting into the wild using non-standard non-local SAM tags. See footnote 3: https://samtools.github.io/hts-specs/SAMv1.pdf

@jmarshall

> +1 to Nils's suggestion about promulgating new tags sooner rather than later (though as these are alignment record tags, the plea to email samtools-devel is in §1.5 ¶2).
> 
> When someone does this, please also expand on @wheaton5's comment that _the BC field in our bams is the sample_index_. What is your _sample_index_? If this is not similar to
> 
> > Barcode **sequence**, with any quality scores stored in the QT tag
> 
> which is how the SAM spec describes the **BC:Z tag**, then there may be a problem.

I'm raising this issue to ensure that this conversation is not lost and these tags get added to the spec and any confusion around **BC:Z** is nipped in the bud, whether by discussion here or on samtools-devel.

**Comment by vdauwera** [comment]
Sounds like this has been/is being addressed in a variety of other threads.
