### ISSUE TITLE
CollectGcBiasMetrics requires a lot more memory

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#289]
Running the current version of CollectGcBiasMetrics requires a lot more memory to complete than the pre-SinglePassProgram version.  Old version is 46330cbbc330ce0925849a2aa2574d99d0cba727.  This is likely due to storing all the gc bias windows for every chromosome, instead of one at a time:  https://github.com/broadinstitute/picard/blob/da43b4f03cdc911f0708a9522516231da874bb86/src/java/picard/analysis/CollectGcBiasMetrics.java#L138

This is a big deal to use so much more memory, could you please fix this?

**Comment by kbergin** [comment]
Oh hey nils! I will look into it. I think there was a reason I had to put that calculation in setup all at once to be able to work with the multi level collector though..

**Comment by yfarjoun** [comment]
There are only 100 windows and about 100 references, so 10K...I doubt that
is the problem. more likely is that the loading of the whole reference at
setup time requires too much memory....would be nice if there were a way to
garbageCollect the unneeded references...

**Comment by kbergin** [comment]
Wouldn't most scenarios need all of the references though anyways? It seemed like it was mostly the smaller test files that didn't use all of them. Would it help to 'close' the ref file after it's read through?

**Comment by kbergin** [comment]
I think the pre-SPS version also loaded the whole reference

**Comment by yfarjoun** [comment]
Not  sure if it will help this issue, but it's probably a good idea.

**Comment by yfarjoun** [comment]
It went through the entire thing, but only as the reads came by, not at the
start. So perhaps there was more time to do garbage collection...

**Comment by kbergin** [comment]
Oh that makes sense. hmm

**Comment by tfenne** [comment]
@kbergin If you look at the old implementation it only ever kept everything in memory for a single chromosome at a time.  You can see the old version [here](https://github.com/broadinstitute/picard/blob/705f349fde4aa9a6ab4a0fcfedba102dcc080e6a/src/java/picard/analysis/CollectGcBiasMetrics.java).  It iterated over the sequences in the references, and then used a PeekableIterator to iterate over the reads, and roll onto the next chromosome when it needed to.

@yfarjoun Unless I've read it wrong, the `gcByRef` map contains an entry for each chromosome, and the byte array stored is the same length as the chromosome - holding the calculated GC for each window on the chromosome.

**Comment by kbergin** [comment]
You're right that it holds the gc for each window on the chromosome. I need to look more into how to avoid doing that with the multi level collector.

**Comment by yfarjoun** [comment]
sorry, my mistake.

**Comment by kbergin** [comment]
This has been addressed in PR #295.
