### ISSUE TITLE
Build docs for all tools automatically

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/picard#290]
Currently the `package-commands` Ant target contains a list of tools for which to build online docs. 

In order to keep the documentation at http://broadinstitute.github.io/picard complete and up-to-date, I suggest that we automatically build docs for all CLPs instead of maintaining an explicit list.

**Comment by vdauwera** [comment]
+1

**Comment by vdauwera** [comment]
Man, this is *so* annoying the way it's set up.
