### ISSUE TITLE
https://sourceforge.net/projects/picard/ still appears to be current

### ISSUE THREAD

**Issue by jmarshall** [broadinstitute/picard#294]
While http://picard.sourceforge.net/ redirects to http://broadinstitute.github.io/picard/, there is no indication on the [SourceForge project page](https://sourceforge.net/projects/picard/) that it is no longer current — and indeed people are still downloading Picard 1.119 or earlier from there.

See for example http://seqanswers.com/forums/showthread.php?p=181033#post181033

You might consider

* Adding a note to the project description (cf [samtools](http://sourceforge.net/projects/samtools/))
* Disabling file downloads from sourceforge, or adding a README to be displayed [there](http://sourceforge.net/projects/picard/files/)
* Changing the SF project status to "Moved" (though I don't know what the implications of this are)

**Comment by vdauwera** [comment]
Good point. I'm happy to take care of it as a support/doc task but one of @tfenne @nh13 @alecw @mccowan needs to grant me access.

**Comment by alecw** [comment]
Hi Geraldine, 

Please send me your SF username and I'll make you an administrator.

-Alec

**Comment by vdauwera** [comment]
Thanks Alec, it's vdauwera (same as on here)

**Comment by alecw** [comment]
OK, you are now an admin.  

-Alec

**Comment by vdauwera** [comment]
Cheers Alec

**Comment by vdauwera** [comment]
Done, thanks for reporting this @jmarshall
