### ISSUE TITLE
Adding Theoretical Het Sensitivity to CollectWGSMetrics and TargetedMetrics Collection

### ISSUE THREAD

**Issue by kbergin** [broadinstitute/picard#299]
David Benjamin has been working on a Theoretical Het Sensitivity metric and I will be implementing it in picard workflows.

- [x] Alter CollectWGSMetrics to send the base and quality distribution to HetSensitivity
- [x] Get Targeted Metrics Collection to calculate base and quality distributions and send to HetSens
- [x] Add HetSens ability to RapidQC - only collect histograms from sampling sites
- [x] Add output metric to both metrics files and change documentation accordingly
- [x] Test change in compute time from adding metric calculation and decide whether to make it optional or not.
- [x] Code review
- [x] Merge
- [x] Write up explanation of changes - get help from David or David's report to explain metric
- [x] Flyway script to update database
- [x] CRSP release so metrics can go into Tableau
- [x] Talk to tableau to get metrics in reports

**Comment by ktibbett** [comment]
@kbergin , it would also be helpful to know if this has a significant impact on the compute required for calculating these metrics.

**Comment by tfenne** [comment]
@ktibbett I totally agree!  If the cost is marginal to compute these new metrics, then that's great.  But if they are expensive to compute it might be better to have them as optional, controlled by a parameter.  After all, not everyone is doing germline sequencing of diploid organisms.

**Comment by yfarjoun** [comment]
I agree. the calculation is based on the distributions of coverage and
quality scores which are either already collected (in WGS metrics) or
partially collected (in hs_metrics). Once these distributions have been
collected, it is my understanding that the remaining calculation takes a
few seconds/minutes, which I think should be insignificant relative to the
traversal time.

**Comment by kbergin** [comment]
Thanks @ktibbett @tfenne @yfarjoun ! I will add in a task to check the compute changes and report back, then we can decide whether to make them optional or not.

**Comment by kbergin** [comment]
Initial PR is up #355
