### ISSUE TITLE
CollectGcBiasMetricsTest does not clean up some temp files

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/picard#302]
Running ```ant single-test -Dname=CollectGcBiasMetricsTest``` results in some temp files being created, e.g.
```
testdata/picard/sam/CollectGcBiasMetrics/CollectGcBias6501112568992755541.bam
testdata/picard/sam/CollectGcBiasMetrics/CollectGcBias7958623947061848645.bam
```

I'm guessing the test is missing a ```deleteOnExit``` somewhere.

**Comment by kbergin** [comment]
Addressed by PR 308.
