### ISSUE TITLE
Supporting METRICS_ACCUMULATION_LEVEL in CollectMultipleMetrics

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/picard#305]
@davidangb and I would like to support METRICS_ACCUMULTATION_LEVEL in CollectMultipleMetrics.  Not all SinglePassSam programs support this option, so our proposed approach is to add it as a parameter and, if it is specified, to validate that all arguments to PROGRAM support accumulation levels (and fail with an exception if they do not).  This will involve making METRICS_ACCUMULTATION_LEVEL, which is currently private, public on the command-line programs that do support it.

Questions, comments, or concerns (@tfenne/@nh13 )?

**Comment by tfenne** [comment]
Seems reasonable to me.  It might be nice to create a simple interface that all the relevant metrics collection programs can implement, which would a) enforce consistency around how it's handled and b) give you a clearer check than checking a parameter value.

**Comment by ktibbett** [comment]
There's actually a ProgramInterface in CollectMultipleMetrics (currently definesneedsReferenceSequence()) and we'll just add supportsMetricsAccumulationLevels, defaulting to true since most programs do, there.
