### ISSUE TITLE
Inject tool version

### ISSUE THREAD

**Issue by cgirardot** [broadinstitute/picard#310]
Hi all,

I am using Picard and htsjdk 1.135 to develop my own command line tools. In particular I am extending CommandLineProgram.java.
My problem is I can t get my own tool version properly injected. Looking at the code I thought I could do this by overwriting the getVersion() method, but this does not work. I am always getting "Version: null" in the usage printout.

From the code, I understand the tool version is somehow extracted from the Manifest file but I am not sure how to do this myself ?

PS: switching to 1.140 does not fix the issue

Hints welcome.

Best wishes

Charles

**Comment by rvalieris** [comment]
I was just looking into this same thing..
picard calls the package  getImplementationVersion() method, you can set it by modifing the manifest of your jar.
https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html

**Comment by cgirardot** [comment]
Thanks for the tip, it worked. 
Best Charles


> On 23 Oct 2015, at 00:04, rvalieris <notifications@github.com> wrote:
> 
> I was just looking into this same thing..
> picard calls the package getImplementationVersion() method, you can set it by modifing the manifest of your jar.
> https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html
> 
> —
> Reply to this email directly or view it on GitHub.
> 

=====================================
Charles Girardot
Head of Genome Biology Computational Support (GBCS)
European Molecular Biology Laboratory
Tel: +49 6221 387 -8585
Fax: +49-(0)6221-387-8166 
Email: charles.girardot@embl.de
Web : http://gbcs.embl.de
Room V205
Meyerhofstraße 1, 
69117 Heidelberg, Germany
=====================================

**Comment by yfarjoun** [comment]
this seems to have been resolved.
