### ISSUE TITLE
readme.md is confusing

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#320]
should have explanations about how to build picard, not how to build gatk-tools-java....

**Comment by cgirardot** [comment]
+1

**Comment by vdauwera** [comment]
Looks like this has been resolved, the readme is nice and straightforward now. @yfarjoun do you see anything else that needs doing?

**Comment by yfarjoun** [comment]
there's a space missing before the HTSJDK link. otherwise :+1:

I think that it would be good to include a howto for testing, and
developing using IntelliJ, but that might need a separate issue.

**Comment by vdauwera** [comment]
True, I'll fix the space here: https://github.com/broadinstitute/picard/pull/377 which add Java version requirement. 

Agreed, testing and dev guidelines should be new/separate issues (and I wouldn't hold my breath).
