### ISSUE TITLE
Controlling version print order when calling -h

### ISSUE THREAD

**Issue by cgirardot** [broadinstitute/picard#324]
Hi all, 

I am extending the CommandLineProgram to implement my own tools. But I have an Abstract class in between that declares common command line options i.e. :
**AbstractTool extends CommandLineProgram**
**Tool1 extends AbstractTool**
**Tool2 extends AbstractTool**

When I call -h on e.g. Tool2, options get printed following their declaration order in the classes (which is good), with all options from Tool2 first then those from AbstractTool. This is bad as the most important options are from AbstractTool and I'd like to get them first. Or best I d like to control option order altogether. Is this possible ?

Thanks for your help,

Charles

**Comment by yfarjoun** [comment]
There is a printOrder parameter now. does that help?
