### ISSUE TITLE
picard does not compile after cloning

### ISSUE THREAD

**Issue by cgirardot** [broadinstitute/picard#325]
Hi there, 
I am trying to build picard after cloning the repo. I am using eclipse. 

Here are the issues that I faced
0. I had to clone htsjdk and make picard depends on this project (could have build the jar and place it in lib folder too). I would have expected the htsjdk jar to be included in the lib folder. 
1. testng jar declared in not found because not available in the lib folder
2. compilation errors due to guava not being declared in the build path => fixed once added as the jar is in the lib folder 
3. MericsDoclet.java declares com.sun.javadoc.* imports. I am not sure where to get this jar.

Could someone commit the missing jar dependencies in the lib folder please?

thx

Charles

**Comment by cgirardot** [comment]
Ok, my bad. Point 3 is certainly an eclipse issue. Simply had to include tools.jar in my 'JRE' as described here : 
http://stackoverflow.com/questions/4797079/how-to-import-com-sun-javadoc-in-eclipse

**Comment by cgirardot** [comment]
and just solved the point 1 by copying lib/testing/testng-5.5-jdk15.jar from htsjdk repo into the picard one. 

but please make this easier for other people ...

**Comment by cgirardot** [comment]
but then, I was unable to ant build because htsjdk was not found by ant, here is how I could fix it : 

in build.xml:
1. change the <property name="htsjdk" value="htsjdk"/> to <property name="htsjdk" value="/absolute/path/to/git/htsjdk"/>

2. make sure 
<property name="htsjdk-classes" value="htsjdk/classes"/> 
now uses this variable as well i.e.
<property name="htsjdk-classes" value="${htsjdk}/classes"/>

ant now builds :-)

**Comment by vdauwera** [comment]
Sounds like this is resolved... and the instructions in the readme work out of the box now.
