### ISSUE TITLE
ValidateSamFile can take a really long time "validating" the index, especially on WGS data

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/picard#346]
@ktibbett mentioned a problem whereby `ValidateSamFile` goes silent and runs for a really long time after initially traversing and validating a BAM file.  It would appear that the quiet time is spent inside a call to `BamIndexValidator.exhaustivelyTestIndex()`.  This method iterates over every bin in the index and every entry in the linear index that has an entry, and then seeks to that position in the BAM file and pulls out a single record.

This is fairly horrendous.  Firstly it's massively IO intensive because it's random accessing to tens of thousands of locations within the input BAM.  Secondly it's not even, as far as I can tell, validating anything more than that the index entries contains valid virtual file offsets - there's no validation that the record found upon seeking is appropriate for the bin the vfo was pulled from.

There are a few ways this could be fixed:
1. Just don't bother validating the index (not great)
2. Add a `nonExhaustivelyTestIndex()` that perhaps tests the first, last, and a few random bins from each reference
3. Modify ValidateSamFile to create a new index in memory as it's traversing the file, and then compare the new index to the on-file index (more work, but perhaps a better test)

**Comment by eitanbanks** [comment]
Why validate the index?  Just to make sure that it's not truncated?  If so, then we really only need to test the last bin.
(As you can guess, I vote against option 3)

**Comment by tfenne** [comment]
I think also to check that the index isn't full of incorrect values; but this seems of limited use to me given that only a few programs create BAM indices, and they're all thoroughly tested at this point.  I'd vote for (2) but that seemed to make @ktibbett  a little nervous.

**Comment by eitanbanks** [comment]
I am cool with option 2.  But I wouldn't even bother with "a few random bins" - just first and last.

**Comment by ktibbett** [comment]
I am not THAT nervous and will look to implement option 2 with first and last.

**Comment by yfarjoun** [comment]
resolved by #397
