### ISSUE TITLE
Picard's travis builds will continue to fail until they are switched to Java 8 because of building htsjdk

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/picard#351]
@lbergelson @akiezun @nh13 @ktibbett @eitanbanks Given that we've now pushed HTSJDK up to Java 8, all Picard travis builds are going to fail until they are updated to also only build on Java 8 and ditch the Java 6 and 7 builds.

I'm happy to make the changes to the travis file and make a PR, but I figured this should probably get a quick discussion and thumbs up first.  

Anyone object to switching the Picard travis build to JDK 8 only?

**Comment by lbergelson** [comment]
:facepalm:  I didn't realize that picard travis just built on htjsdk master.  That's awful.  

I don't think picard passes java 8 tests yet so this may not work.

**Comment by tfenne** [comment]
@lbergelson I updated #350 to a) include testing on Java8 and b) fix one of the broken tests.

I'm fairly sure all the broken tests are just poorly written tests.  The remaining breaks are in `CollectSequencingArtifactMetricsTest`.   Calling @mattsooknah  and @yfarjoun...

Those tests are are very hard to debug because they basically just run the program and assert that the entire output files are equal - so there's no actual diagnosis of what's change, you have to go and look manually and try and figure it out.  I did some of that and at least in the first cases, it was that the `WORST_CXT` and `WORST_POST_CXT` were different on many rows.  I started looking through the code and gave up.  My expectation is that somewhere deep down there is code that loops over a `HashSet` or `HashMap` to find entry with `min` or `max` of some value, and when there are multiple equal values takes the first or last such one, such that it is prone to changes in iteration order.  (The failure in TestFilterVcf was a change of ordering in HashSet.iterator() problem).

**Comment by lbergelson** [comment]
@tfenne I suspect your correct about ordering issues being the root cause of the test failures.  We've had lots of issues with metrics file comparison in tests because of ordering issues.

**Comment by akiezun** [comment]
no objection here. +1 for Java 8 all the way

**Comment by yfarjoun** [comment]
Other tests seem to be failing as well...various IlluminaBasecallsToSam tests...I'll look into it but probably not today.

**Comment by yfarjoun** [comment]
This has been resolved.
