### ISSUE TITLE
Run picard offline

### ISSUE THREAD

**Issue by olingerc** [broadinstitute/picard#354]
Hi,
I followed the instructions on the github page to build using ant. When launching picard, I get:
```
java.net.ConnectException: Connection timed out
java.net.ConnectException: Connection timed out
java.net.ConnectException: Connection timed out
Failed to load ngs-sdk library
java.net.ConnectException: Connection timed out
java.net.ConnectException: Connection timed out
Cannot download library: -2
Failed to download ngs-sdk from NCBI
INFO	2015-12-07 12:13:13	SRAAccession	SRA is not supported. Will not be able to read from SRA
INFO	2015-12-07 12:13:13	AddOrReplaceReadGroups	Created read group ID=1 PL=Illumina LB=TODO SM=test-original_S1
```

I know picard wants to download something, but why? and how can I turn that off? I will run picard offline anyway and I do not need access to SRA or any other online database.

Best regards,

Christophe

**Comment by lbergelson** [comment]
Hi @olingerc, thanks for reporting this.  SRA support is a very new addition to htsjdk and we haven't noticed this before.  SRA support relies on a C library and it looks like it may be not finding that, and trying to download it, and then failing for some reason.  It's likely there may be a packaging issue with the c code that we'll need to correct.  In any case, it shouldn't be trying the download unless you're actually trying to read SRA. And the warning message is not particularly useful.  

I don't know if there is a way to turn it off at the moment.  I'll look into it.  Is it causing tools to fail? Or just producing a lot of error messages?  In either case we will correct this.

**Comment by olingerc** [comment]
Hi, thanks for you reply. I'm quite sure the fault is my very strict
company proxy configuration. I can only clone git repos via https adresses,
no git@... adresses and proxy configuration for JAVA is a hit and miss in
Linux.
It does not cause the tools to fail, they continue after a timeout. But
this timeout takes a long time. I have the same issue with GATK were I use
a local key obtained from them to "bypass" calling home.

Automatic downloading is a nice feature but I would prefer a dependency
list and the choice to install what I want. But maybe this is to be
considered an upstream problem?

**Comment by yfarjoun** [comment]
Hi @olingerc,
could you try running with `-Dvdb.System.loadLibrary=true` and see if that helps?

**Comment by olingerc** [comment]
Hey! That actually works!
```
Smart DLL search was disabled
Failed to load ngs-sdk library
```
but then my glorious picard output.

**Comment by yfarjoun** [comment]
@vdauwera FYI

**Comment by vdauwera** [comment]
To echo @lbergelson's comment:

> the warning message is not particularly useful.

Should we add the `-Dvdb.System.loadLibrary=true` tip to the error message?

**Comment by vdauwera** [comment]
And now I realize https://github.com/samtools/htsjdk/issues/407 addresses this. Nevermind.
