### ISSUE TITLE
Use https github links instead of public key 

### ISSUE THREAD

**Issue by JohnLonginotto** [broadinstitute/picard#362]
It would be a lot easier to clone the repos if https links were used instead of the ssh "git@github.com:..." in the build.xml of both picard and htsjdk.

The latter requires a github account, and the knowledge of how to create a public/private key, which may be out of the scope of what many of your users will know how to do :)

**Comment by vdauwera** [comment]
I don't disagree on replacing the ssh with https links, but I think anyone who's cloning the repo and compiling from source probably knows what they're doing. We expect end-users who don't understand github to just download the precompiled jar package. -- there's no need for them to bother with the source in the first place.

**Comment by JohnLonginotto** [comment]
Yes, that had crossed my mind - but perhaps it is a sort of self-fulfilling prophecy to assume that because people who don't know what they're doing don't use it, it doesn't need to be made usable by people who don't know what they're doing :)

I know what i'm doing in the bioinformatic sense, but I don't know much about Java or ant, so it still took me a few minutes to figure out what the error I was getting meant, and it was stressful to have to edit the install code manually since I don't know what problems that might cause downstream.
Also, i'd much rather have used the .jar, but openjre-7 was unable to run it. Using sun-oracle-cocacola Java seemed to fix everything, but I tried compiling from source first :) All i'm saying is some headaches are unavoidable, but some like this one are an easy fix :)

**Comment by vdauwera** [comment]
Totally fair point, I'm originally a wetlab microbiologist with zero formal informatics background so I understand completely what it can be like. The install and compile instructions could definitely use some love.
