### ISSUE TITLE
CollectWgsMetrics should double-check that sequence dictionaries match

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/picard#366]
It is possible for a user to pass in e.g. the hg19 reference for the REFERENCE_SEQUENCE argument with a bam aligned to hg38.  No error or warning is generated until/unless we hit a read that aligns off the end of the reference sequence (although it doesn't really; we're just using the wrong reference).
We should put in a super quick sanity check on the dictionaries to make sure they match (at least somewhat).

**Comment by akiezun** [comment]
see also https://github.com/broadinstitute/gatk/pull/1379

**Comment by nsoranzo** [comment]
:+1: The `ArrayIndexOutOfBoundsException` error is quite obscure for the user.

**Comment by golharam** [comment]
This also happens when using a BAM file aligned with GRCh37 (1000 Genomes), but REFERENCE_SEQUENCE is given hg19.  I don't think its obscure.   If the sequence dictionaries don't match, and error should be reported.

**Comment by kbergin** [comment]
@sophiacrennan has added a check for this in #1610 . Closing this issue!
