### ISSUE TITLE
LiftOverIntervalList

### ISSUE THREAD

**Issue by dekling** [broadinstitute/picard#371]
Running LiftOverIntervalList generates an output file AND the following error: "Could not find or load main class".  However, the output file seems fine and used it successfully as an input for CalculateHSMetrics.

**Comment by yfarjoun** [comment]
very difficult to understand the issue. could you provide small files that generate the problem?

**Comment by dekling** [comment]
OK.  Will do.

**Comment by dekling** [comment]
@yfarjoun 
Let me know if you need clarification or more info.

**Comment by dekling** [comment]
Sent test files to @yfarjoun via E-mail.

**Comment by yfarjoun** [comment]
@fleharty could you take a look at this please? I"ll forward you the test files.

**Comment by fleharty** [comment]
@dekling Could you send me the test files that generate this error?

**Comment by dekling** [comment]
Sent them to you via E-mail.

**Comment by fleharty** [comment]
@dekling Pinging you regarding our conversation last Friday.

**Comment by dekling** [comment]
Sorry.  Tied up with other issues.  Will get back to you shortly.

-D

> On Jan 11, 2016, at 2:19 PM, Mark Fleharty <notifications@github.com> wrote:
> 
> @dekling <https://github.com/dekling> Pinging you regarding our conversation last Friday.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/broadinstitute/picard/issues/371#issuecomment-170660342>.
> 

—
David E. Kling, Ph.D.
Senior Technical Writer
Broad Institute
75 Ames Street, #7003DC
Cambridge, MA 02142
O (617) 714 - 7351
C (617) 291 - 1617

**Comment by yfarjoun** [comment]
@dekling is this solved?

**Comment by dekling** [comment]
@yfarjoun:  I know Mark was able to reproduce the error.  @fleharty: do you know the status of this?

**Comment by fleharty** [comment]
@dekling @yfarjoun I was able to reproduce the error in some sense.  I was able to reproduce the error when I downloaded the jar off the website, but if I compiled a jar myself, the error does not happen.

I have been unable to determine what the cause is.

Mark

**Comment by yfarjoun** [comment]
could you debug the downloaded jar?

**Comment by vdauwera** [comment]
Do you know exactly what version was the compiled one? Would be great if
the bug was fixed automagically in latest master.
On Mon, Feb 1, 2016 at 10:29 AM Yossi Farjoun <notifications@github.com>
wrote:

> could you debug the downloaded jar?
>
> On Sun, Jan 31, 2016 at 6:10 PM, Mark Fleharty <notifications@github.com>
> wrote:
>
> > @dekling <https://github.com/dekling> @yfarjoun
> > <https://github.com/yfarjoun> I was able to reproduce the error in some
> > sense. I was able to reproduce the error when I downloaded the jar off
> the
> > website, but if I compiled a jar myself, the error does not happen.
> >
> > I have been unable to determine what the cause is.
> >
> > Mark
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/broadinstitute/picard/issues/371#issuecomment-177653950
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/picard/issues/371#issuecomment-177660480>
> .
>
-- 
Geraldine A. Van der Auwera, PhD
Manager of Outreach and Communications
Data Sciences and Data Engineering
Broad Institute

**Comment by yfarjoun** [comment]
@fleharty if you run the compiled jar, it might tell you what the version is...can you check for @vdauwera ?
