### ISSUE TITLE
Piccard tools error using CollectRnaSeqMetrics #461

### ISSUE THREAD

**Issue by dekling** [broadinstitute/picard#398]
User reports 0 genes loaded.  I used the tool with a different dataset and obtained the exact same results.  Tried several different REF_FLAT files.  Can someone have a look at this?  Thanks in advance.

**Comment by dekling** [comment]
Here is the script:
java -jar picard.jar CollectRnaSeqMetrics \
I=NA12878_rnaseq_20.bam \
O=NA12878_rna_seq_2.rna_metrics \
REF_FLAT=refFlat_b37_20_1.txt \
STRAND=SECOND_READ_TRANSCRIPTION_STRAND\
RIBOSOMAL_INTERVALS=ribo_20_a.txt

Will send the test files via E-mail.

**Comment by dekling** [comment]
May have nothing to do with this but I noticed that in the code, there is information indicating that if a base does not overlap with rRNA or a gene, it is considered "intergenic".  Does it designate the entire read as intergenic?  If so, this could explain why it thinks every read is intergenic.  Anybody have thoughts on this?

**Comment by sooheelee** [comment]
I was curious...

In the metrics file, only 4 of the metrics have non-zero values:

- PF_BASES | 3585300
- PF_ALIGNED_BASES | 3549492
- INTERGENIC_BASES | 3549492
- PCT_CORRECT_STRAND_READS | 1

Where intergenic_bases is defined as the number of bases in primary aligments that do not align to any gene.

**It appears the REF_FLAT file is ineffective in defining genic and intergenic regions.** I tried to look for more information on the REF_FLAT format from [the UCSC link](http://genome.ucsc.edu/goldenPath/gbdDescriptionsOld.html#RefFlat) provided in the documentation but found the descriptions confusing. Namely, when do you use and not use the quotes? The user's REF_FLAT uses quotes when defining exon starts and again in the next column to define exon ends.

> DEFB128	NM_001037732	20	-	168493	170322	168526	170264	2	"168493,170215,"	"168759,170322,"
C20orf96	NM_153269	20	-	251503	271419	251847	271251	11	"251503,256608,257433,257684,257866,258970,259812,264603,270199,270899,271231,"	"251908,256727,257520,257786,258024,259070,259971,264722,270317,270948,271419,"
C20orf96	NM_080571	20	-	251503	271419	251847	271244	11	"251503,256608,257433,257684,257866,258970,259812,264603,270199,270899,271227,"	"251908,256727,257520,257786,258024,259070,259971,264722,270317,270948,271419,"
NRSN2-AS1	NR_109990	20	-	300330	305896	305896	305896	3	"300330,303021,305785,"	"301425,303209,305896,"



**It would be helpful to see a REF_FLAT file we know produces correct metrics.** This way we could rule out file format errors.

I'm only familiar with gtf files for transcriptomics. Here's an example snippet:

> ##description: evidence-based annotation of the human genome (GRCh37), version 7 (Ensembl 62)
##provider: GENCODE
##contact: gencode@sanger.ac.uk
##format: gtf
##date: 2011-03-23
1	HAVANA	gene	11869	14409	.	+	.	gene_id "ENSG00000223972.3"; transcript_id "ENSG00000223972.3"; gene_type "pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; transcript_type "pseudogene"; transcript_status "KNOWN"; transcript_name "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2";
1	HAVANA	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972.3"; transcript_id "ENST00000456328.2"; gene_type "pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_status "KNOWN"; transcript_name "DDX11L1-002"; level 2; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";

**Comment by ktibbett** [comment]
@sooheelee , you win!  I tried this with the refFlat file we use in production and got 649 genes loaded.  I am looking into the provenance of that file, but will not likely have it until Monday.

**Comment by ktibbett** [comment]
Nope, I got it!  http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/refFlat.txt.gz.

**Comment by dekling** [comment]
This is still loading 0 genes (for me) with @ktibbett refFlat file.  @ktibbett can you send me your command line and a bam file?  Thanks.

**Comment by ashutosh-trehan** [comment]
Is there a way of coverting gtf file from Ensembl to refFlat files for using the tool?
I tried downloading refflat files from UCSC and it gave me all reads aligned to intergenic regions. I'm new to RNAseq analysis and any help would be greatly appreciated.
