### ISSUE TITLE
GatherVCFs fails if one of the files is empty

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#412]
Problem seems to be line picard/vcf/GatherVcfs.java:221 as the blockLength will indeed be 0.

I can easily remove the blockLength==0 predicate, but there are no tests so I'm resist doing it.. 

@nh13 do you remember why you put in that check?

**Comment by nh13** [comment]
It probably blames me since I made the switch from Svn to git. @tfenne who likely wrote this.

**Comment by yfarjoun** [comment]
@nh13 I seem to remember a recent PR of yours might have fixed this...am I correct?

**Comment by vdauwera** [comment]
@yfarjoun Were you ever able to determine whether this is still a thing?

**Comment by yfarjoun** [comment]
continuring this issue  here #755
