### ISSUE TITLE
Query on picard downsample

### ISSUE THREAD

**Issue by shrukane** [broadinstitute/picard#413]
Hi, I am currently trying to downsample multi-lane data using picard, will the downsampler serve the purpose ? 
When I run a t-test for correlation (to check the randomness) of the downsampled counts vs the original counts, I do not obtain a significance. Can you please clarify ?

Regards
Shruti

**Comment by yfarjoun** [comment]
What is the purpose? The downsampler will give you a fraction of the reads
while keeping paired reads together. It is based on the read-name and the
default strategy is to simply use a probability and so the accuracy is
binomial. if you want a greater accuracy, you can achieve that by using a
different STRATEGY (an input to the program). See the usage notes for
detailed description of the difference STRATEGYs.

Not sure if this is helpful.
