### ISSUE TITLE
Picard tools documentation test

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#415]
We have tools that lack documentation due to forgetting to modify the build.xml. I was wondering if a test could be written (or an ant-target?) that would check that all the tools are in the build.xml and then when someone adds a tool without modifying the build.xml the test would fail.

Does this sounds like a reasonable way to make sure that the online documentation matches the tools that are in the jar?

**Comment by vdauwera** [comment]
That would be very useful. This idiosyncrasy of the doc system has already bitten us, see https://github.com/broadinstitute/picard/pull/378.

@ktibbett Do you know how/who could set something like this up?

**Comment by yfarjoun** [comment]
This would be otherwise resolved by #290...so closing this.
