### ISSUE TITLE
Picard SortVcf not working

### ISSUE THREAD

**Issue by Shenglai** [broadinstitute/picard#419]
I'm using:
cmd = ['java', '-Djava.io.tmpdir=/tmp/job_tmp', '-d64', '-jar', os.path.join(home_dir, 'tools/picard-tools/picard.jar'), 'SortVcf', 'INPUT=' + vcf_path, 'OUTPUT=' + srt_vcf_path, 'SEQUENCE_DICTIONARY=' + reference_fasta_dict].
However, I notice by htop that the cmd is NOT running. I tested CreateSequenceDictionary, and it's working. Wondering if it's a bug. 

The version is Version: 2.0.1(fe51f432e4b918385037e6d15e958f0298203e28_1449251266).
Docker images is : https://quay.io/repository/jeremiahsavage/picard

**Comment by vdauwera** [comment]
Obviously this comes too late to help, but for the record, please post user questions in the GATK forum.
