### ISSUE TITLE
CreateSequenceDictionary stalls indefinitely with large genomes

### ISSUE THREAD

**Issue by cacampbell** [broadinstitute/picard#432]
Running create sequence dictionary results in an indefinitely running process (at 3 days now -- just to see how long it would go) with the following output:

[Thu Feb 04 10:10:14 PST 2016] picard.sam.CreateSequenceDictionary REFERENCE=[large conifer species] OUTPUT=[large conifer species].dict VERBOSITY=DEBUG QUIET=false MAX_RECORDS_IN_RAM=40000000    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Thu Feb 04 10:10:14 PST 2016] Executing as [user]@bigmem3 on Linux 3.13.0-36-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26; Picard version: 2.0.1() JdkDeflater

the fasta file for that genome is around 40GB

Using samtools 1.3 dict creates a sequence dictionary relatively quickly (about an hour)

Sorry if this has been discussed / resolved elsewhere

**Comment by tfenne** [comment]
FYI it's likely that this is less related to the raw size of the genome in bytes or bases, and more to the number of contigs in the genome.  Unless it has changed CreateSequenceDictionary caches all the `@SQ` records in memory before writing them to disk, and if there are hundreds of thousands, it will end up running low on memory and thrashing in garbage collection.

**Comment by yfarjoun** [comment]
if any of the contigs is greater in size than MAX_INT, there will be a
problem since we seem to be using int for iterating the reference.

**Comment by tfenne** [comment]
Though to be clear - a single sequence of length greater than max int will cause problems in many places, since the SAM spec defines position fields as ints.

**Comment by cacampbell** [comment]
Regarding contig count -- yeah this seems to be the case for me

**Comment by jmarshall** [comment]
See also [this samtools-help thread](https://sourceforge.net/p/samtools/mailman/message/31531210/) regarding 2<sup>31</sup>-1 vs. 2<sup>32</sup>-1 for maximum contig sizes.

**Comment by jabbarish** [comment]
@cacampbell  could you please clarify how many contigs your reference file contains? Do you allocate additional memory for the picard process or use the default value?

**Comment by cacampbell** [comment]
Not in the office atm, but the reference has something like 400,000 contigs

**Comment by cacampbell** [comment]
Hi -- just kidding about that... 

The actual number of contigs is 58,407,655

**Comment by cacampbell** [comment]
And to answer your question about memory -- yes, typically, I would run this with -Xms380g -Xmx400g (on the "to see how long it will go" task)

**Comment by jabbarish** [comment]
@cacampbell could we please have an access to the genome?  Is it available to download?

**Comment by cacampbell** [comment]
http://dendrome.ucdavis.edu/ftp/Genome_Data/genome/pinerefseq/Pila/v1.0/

pila.v1.0.scafSeq.gz is the compressed sugar pine genome (used here).

**Comment by jabbarish** [comment]
Thanks!

**Comment by zstudent** [comment]
@cacampbell 
Hi!  We have fixed the problem, see the pull requests mentioned above.  Now this tool takes 13 minutes on our test machine and fits within 1.5 Gb to process your 40Gb genome of sugar pine.

**Comment by ZLyanov** [comment]
@cacampbell 
Hi! We have fixed the problem, see the pull requests mentioned above. Now this tool takes 13 minutes on our test machine and fits within 1.5 Gb to process your 40Gb genome of sugar pine.

**Comment by cacampbell** [comment]
Thats awesome, thank you!

Regards,
    Chris Campbell

**Comment by vdauwera** [comment]
Closing this issue since it is presumptively resolved in htsjdk. 

When the next Picard version with upgraded htsjdk is released, please let us know how the tools perform on your genome.

**Comment by vdauwera** [comment]
Whoops, just realized we also need to take in the Picard PR, my bad.

**Comment by yfarjoun** [comment]
this should be fixed now thanks to @SilinPavel  #687
