### ISSUE TITLE
Improve CLI help formatting cleanup functions

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#439]
Follow-up on https://github.com/broadinstitute/picard/pull/437

As requested by @yfarjoun:
- Add a test for the results of the html parsing
- Add a test for non-ascii character check
- Rewrite the regexp using a stream/fold or forloop.

**Comment by nh13** [comment]
@vdauwera can this be completed before the next Picard release?

**Comment by vdauwera** [comment]
I won't have the time, I need to focus on the WDL docs. To be frank I don't think it's necessary, it's more of a nice-to-have.

**Comment by yfarjoun** [comment]
who are we kidding?
