### ISSUE TITLE
Picard github summary is inaccurate, needs to be updated

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#443]
Currently reads

> A set of tools (in Java) for working with next generation sequencing data in the BAM (http://samtools.github.io/hts-specs) format.

- "next generation sequencing" should be "high-throughput sequencing" (we're not in 1999 anymore)
- the tools are no longer limited to processing SAM/BAM; there's also VCF

A more accurate summary would be

> A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS) data and formats such as SAM/BAM/CRAM and VCF.

Happy to make the change myself if given admin powers.

**Comment by ktibbett** [comment]
Done.
