### ISSUE TITLE
ValidateSamFile crashing with various settings (GC overhead limit exceeded)

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#446]
I tried lowering the number of tmp files and files in RAM but it keeps crashing although I have 8GB RAM on my MBP.

Any idea?
# run1

`java -jar $PICARD/picard.jar ValidateSamFile I=${infolder}/${infile} M=SUMMARY         VALIDATION_STRINGENCY=LENIENT         IGNORE_WARNINGS=TRUE O=${infolder}/PE_ValidateSamFile_Summary.txt MAX_OPEN_TEMP_FILES=1000                                                                                                                     [Tue Feb 16 15:00:32 CET 2016] picard.sam.ValidateSamFile INPUT=ori-Illumina_hg18_mapping_results/PE_rg_nmsrt_fixmate_NA18507_GAIIx_100_chr21.bam OUTPUT=ori-Illumina_hg18_mapping_results/PE_ValidateSamFile_Summary.txt MODE=SUMMARY IGNORE_WARNINGS=true MAX_OPEN_TEMP_FILES=1000 VALIDATION_STRINGENCY=LENIENT    MAX_OUTPUT=100 VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json                                                                                                       [Tue Feb 16 15:00:32 CET 2016] Executing as splaisan@maf-wrk-0013.med.ad10.intern.kuleuven.ac.be on Mac OS X 10.10.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_71-b15; Picard version: 2.1.0(25ebc07f7fbaa7c1a4a8e6c130c88c1d10681802_1454776546) JdkDeflater         [Tue Feb 16 15:07:53 CET 2016] picard.sam.ValidateSamFile done. Elapsed time: 7.36 minutes.                                           Runtime.totalMemory()=1908932608                                                                                                      To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp                                                        Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded                                                             at java.util.ArrayList.iterator(ArrayList.java:834)                                                                                   at java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1039)                                                       at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038)                                                       at htsjdk.samtools.SAMUtils.getAlignmentBlocks(SAMUtils.java:687)                                                                     at htsjdk.samtools.SAMRecord.getAlignmentBlocks(SAMRecord.java:1757)                                                                  at htsjdk.samtools.SAMRecord.validateCigar(SAMRecord.java:1775)                                                                       at htsjdk.samtools.SamFileValidator.validateCigar(SamFileValidator.java:403)                                                          at htsjdk.samtools.SamFileValidator.validateCigar(SamFileValidator.java:393)                                                          at htsjdk.samtools.SamFileValidator.validateSamRecordsAndQualityFormat(SamFileValidator.java:285)                                     at htsjdk.samtools.SamFileValidator.validateSamFile(SamFileValidator.java:200)                                                        at htsjdk.samtools.SamFileValidator.validateSamFileSummary(SamFileValidator.java:128)                                                 at picard.sam.ValidateSamFile.doWork(ValidateSamFile.java:187)                                                                        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)                                                        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)                                                           at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)`
# run2

`java -jar $PICARD/picard.jar ValidateSamFile I=${infolder}/${infile} M=SUMMARY         VALIDATION_STRINGENCY=LENIENT         IGNORE_WARNINGS=TRUE O=${infolder}/PE_ValidateSamFile_Summary.txt MAX_OPEN_TEMP_FILES=1000 MAX_RECORDS_IN_RAM=100000                                                                                           [Tue Feb 16 15:12:32 CET 2016] picard.sam.ValidateSamFile INPUT=ori-Illumina_hg18_mapping_results/PE_rg_nmsrt_fixmate_NA18507_GAIIx_100_chr21.bam OUTPUT=ori-Illumina_hg18_mapping_results/PE_ValidateSamFile_Summary.txt MODE=SUMMARY IGNORE_WARNINGS=true MAX_OPEN_TEMP_FILES=1000 VALIDATION_STRINGENCY=LENIENT MAX_RECORDS_IN_RAM=100000    MAX_OUTPUT=100 VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json                                                                                                       [Tue Feb 16 15:12:32 CET 2016] Executing as splaisan@maf-wrk-0013.med.ad10.intern.kuleuven.ac.be on Mac OS X 10.10.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_71-b15; Picard version: 2.1.0(25ebc07f7fbaa7c1a4a8e6c130c88c1d10681802_1454776546) JdkDeflater         [Tue Feb 16 15:20:20 CET 2016] picard.sam.ValidateSamFile done. Elapsed time: 7.79 minutes.                                           Runtime.totalMemory()=1908932608                                                                                                      To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp                                                        Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded                                                             at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:397)                                  at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:384)                                     at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:127)                                     at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:252)                                          at java.io.DataInputStream.read(DataInputStream.java:149)                                                                             at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:404)                                                            at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)                                                                   at htsjdk.samtools.util.BinaryCodec.readByteBuffer(BinaryCodec.java:490)                                                              at htsjdk.samtools.util.BinaryCodec.readInt(BinaryCodec.java:501)                                                                     at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:177)                                                                     at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:661)                                                at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:635)                                                      at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:629)                                                         at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:599)                                                         at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:545)                                                               at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:519)                                                               at htsjdk.samtools.SamFileValidator.validateSamRecordsAndQualityFormat(SamFileValidator.java:269)                                     at htsjdk.samtools.SamFileValidator.validateSamFile(SamFileValidator.java:200)                                                        at htsjdk.samtools.SamFileValidator.validateSamFileSummary(SamFileValidator.java:128)                                                 at picard.sam.ValidateSamFile.doWork(ValidateSamFile.java:187)                                                                        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)                                                        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)                                                           at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)`

**Comment by jabbarish** [comment]
@splaisan  We have tried to reproduce the situation, but all the time the VM performed stably and GC was low loaded.

Could you please give more details about your machine configuration? What sort order has the file (coordinate, queryname, unsorted)?  It would be great also if you could share the data to help us reproduce the issue.

**Comment by splaisan** [comment]
Dear @jabbarish,

Thanks for answering this request. It has however been so much time since it happened that I do not have the corresponding data anymore.
I will recontact you when such issue happens again.

Best Regards,
Stephane
 <http://www.nucleomics.be/>      	Stephane Plaisance, Ph.D

Address: Herestraat 49, O&N4, Post Box 816, Room nr. 404-24 / 08.428, 3000 Leuven - Belgium
Tel: +32 (0)16 373126
Tel (lync): +32 (0)16 320060
Fax: +32 (0)16 373129
Web: www.nucleomics.be <http://www.nucleomics.be/>

**Comment by yfarjoun** [comment]
close? cannot reproduce... @jabbarish, your call.

**Comment by jabbarish** [comment]
@yfarjoun actually, we have created a number of test cases for this ticket, and increased the coverage, so we can make PR to include them into the project.

**Comment by yfarjoun** [comment]
Sure. tests are always welcome (as long as they are "well behaved") :-)
