### ISSUE TITLE
Build error: Could not find picard.cmdline.CreateHtmlDocForProgram

### ISSUE THREAD

**Issue by ndrubins** [broadinstitute/picard#450]
Hi,

I'm trying to build picard tools from broadinstitute-picard-a4d54b4.

I first successfully built htsjdk. Then running ant to build picard I get this error:

BUILD FAILED
build.xml:552: Could not find picard.cmdline.CreateHtmlDocForProgram. Make sure you have it in your classpath

Help would be appreciated.

**Comment by vdauwera** [comment]
Hmm Travis builds are failing with that same error. Including master builds that were previously ok (I reran the build from before I merged my PR).

@ktibbett @geoffjentry Any idea what's going on here?

**Comment by akiezun** [comment]
ugh, can it be the jacoco stuff again? Just in case I made a revert of the
last pull request in htsjdk https://github.com/samtools/htsjdk/pull/484
(can someone merge that and see what happens?)

(btw for stability picard master should not build off of live master of
htsjdk but off a tagged version)

**Comment by vdauwera** [comment]
Sounds like @tfenne fixed it.
