### ISSUE TITLE
Running CollectSequencingArtifactMetrics with CollectMultipleMetrics and a FILE_EXTENSION does not produce the correct file name

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#467]
It looks like the `OUTPUT` is not being set correctly here:
https://github.com/broadinstitute/picard/blob/master/src/java/picard/analysis/CollectMultipleMetrics.java#L277
@davidangb it looks like perhaps it was an addition you made.

**Comment by yfarjoun** [comment]
Are you seeing a problem with the output or just seeing it from the code?
CollectSequencingArtifactMetrics is supposed to take OUTPUT and generate 4
different output files with different extensions....


On Sun, Feb 28, 2016 at 1:00 PM, Nils Homer <notifications@github.com>
wrote:
>
> It looks like the OUTPUT is not being set correctly here:
>
https://github.com/broadinstitute/picard/blob/master/src/java/picard/analysis/CollectMultipleMetrics.java#L277

**Comment by nh13** [comment]
In the output.

**Comment by nh13** [comment]
@yfarjoun I am also seeing that `SUMMARY_OUTPUT` for `CollectGcBiasMetrics` is not updated as well: https://github.com/broadinstitute/picard/blob/master/src/java/picard/analysis/CollectMultipleMetrics.java#L226

I have to work around both issues in my use of `CollectMultipleMetrics`.

**Comment by yfarjoun** [comment]
Thanks @nh13! I'll add test for that and fix!

**Comment by yfarjoun** [comment]
oh, you're fixing it! thanks!

**Comment by yfarjoun** [comment]
this is fixed, right @nh13 ?

**Comment by nh13** [comment]
It is, closing.
