### ISSUE TITLE
MarkDuplicates dies a horrible death when large duplicates sets exists.

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#472]
The code for finding optical duplication is implemented as a n^2 code. We have seen a case when n is .5e6 and this breaks the code. While the data is dubious, it would be good to get an output from the program. I think that the "findOpticalDuplicates" code should be implemented using a kdtree rather than a brute force approach. 

Any thoughts?

pinging @nh13 @tfenne @davidbenjamin

**Comment by yfarjoun** [comment]
I am considering including the java-ml.sourceforge.net library...any objections?

**Comment by davidbenjamin** [comment]
@yfarjoun I was tempted to implement it via a k-d tree but realized the n^2 algorithm outperforms it for any reasonable amount of duplication.  But now that we have seen a case like this I don't object to a k-d tree.  The java-ml.sourceforge implementation has a clean and simple API, so code readability/maintainability shouldn't suffer.

**Comment by tfenne** [comment]
I do have thoughts on this, and an alternative suggestion but am mobile right now. Will try to reply later today.

**Comment by tfenne** [comment]
The solution that was there before was nice - it sorted the list by location and was then able to do a much more efficient than n^n comparison.  It was very efficient, but had the downsides of:
a) being somewhat complicated
b) re-ordering the input list, which had some nasty side-effects

This made it very hard to implement the optical duplicate _flagging_  - the first thing that cared that that input sort order and the returned `boolean[]` sort order matched other things it was tracking.  I think one option, and possibly the right one, is to restore the old behaviour, but change the API so that the `location` -> `is optical duplicate` isn't maintained by a position in an array, but something that is ordering independent (e.g. a flag on the input physical location?).  I didn't want to change the API at the time, but perhaps that is the best approach?

I'd be concerned that building a whole other data structure would cost a lot in both memory and runtime.

**Comment by yfarjoun** [comment]
Another alternative would be to only use the kd tree when N>>1

**Comment by tfenne** [comment]
Agreed @yfarjoun - though if it's memory usage is not very light it is likely to cause other problems with N >> 1.

**Comment by yfarjoun** [comment]
I've started looking into using the kd-tree implementation. I don't think
that there will be much overhead beyond N * 2 * double (since it uses
double for the positions).

**Comment by nh13** [comment]
I would definitely test a few different datasets to characterize the performance change.  This part of the code was highly optimized for a reason.

**Comment by yfarjoun** [comment]
well...right now it simply breaks for N=1e5....so I figured, if I can get
it to run correctly, and also run with reasonable time with N>50 I'll
switch on that since there shouldn't be that many sets of size greater than
50....but I'll make sure to discuss here the details.

**Comment by yfarjoun** [comment]
hmmm. So I have been playing around with my kdTree version of findOpticalDuplicates, and have run some timing experiments. I found that while it is _faster_ I can run both with 1e6 data points with no problem (n^2 takes 30 minutes, kdTree takes 10)...so I'm not sure **why** MD is dieing with 5e5 duplicates....until I figure this out, I will hold-off on adding complexity to an already complex algorithm.

**Comment by yfarjoun** [comment]
I'm starting to think that this is a JVM bug. the error is

``` 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:308), pid=30468, tid=47023495768384
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: Java(TM) SE Runtime Environment (8.0-b132) (build 1.8.0-b132)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.0-b70 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# READACTED/hs_err_pid30468.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
```
and in the hs_err_pid30468.log file I see that the thread is inside the keeperOrNull loop. From reading about errors in safepoint.cpp:308 it seems that there might be some java problem with tight long loops with respect to "safepoints". This is totally over my head...if someone has a clue as to a possible workaround, I'd be happy to hear.

**Comment by lbergelson** [comment]
@yfarjoun You might want to file a jvm bug.  If you can reproduce the error regularly on your dataset it might be a valuable test case to fix this.
