### ISSUE TITLE
INTERVALS option doesn't work in CollectMultipleMetrics

### ISSUE THREAD

**Issue by hurchu** [broadinstitute/picard#478]
Hi, 

I tried to run CollectMultipleMetrics and provide a target region file. But with or without the target region as input, the outputs are same.

I tried to add BAM file header to the target region, still no difference.

This is the command I used:

java -jar picard.jar CollectMultipleMetrics INPUT=sorted.bam ASSUME_SORTED=true STOP_AFTER=0 OUTPUT=01-BG PROGRAM=[CollectAlignmentSummaryMetrics, CollectBaseDistributionByCycle, CollectInsertSizeMetrics, MeanQualityByCycle, QualityScoreDistribution, CollectAlignmentSummaryMetrics, CollectInsertSizeMetrics, QualityScoreDistribution, MeanQualityByCycle] INTERVALS=target_region REFERENCE_SEQUENCE=genome.fa STOP_AFTER=0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false

The following are part of my target region file.

@HD	VN:1.3	SO:coordinate
@SQ	SN:chrM	LN:16571
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@SQ	SN:chr1_gl000191_random	LN:106433
@SQ	SN:chr1_gl000192_random	LN:547496
@SQ	SN:chr4_ctg9_hap1	LN:590426
@SQ	SN:chr4_gl000193_random	LN:189789
@SQ	SN:chr4_gl000194_random	LN:191469
@SQ	SN:chr6_apd_hap1	LN:4622290
@SQ	SN:chr6_cox_hap2	LN:4795371
@SQ	SN:chr6_dbb_hap3	LN:4610396
@SQ	SN:chr6_mann_hap4	LN:4683263
@SQ	SN:chr6_mcf_hap5	LN:4833398
@SQ	SN:chr6_qbl_hap6	LN:4611984
@SQ	SN:chr6_ssto_hap7	LN:4928567
@SQ	SN:chr7_gl000195_random	LN:182896
@SQ	SN:chr8_gl000196_random	LN:38914
@SQ	SN:chr8_gl000197_random	LN:37175
@SQ	SN:chr9_gl000198_random	LN:90085
@SQ	SN:chr9_gl000199_random	LN:169874
@SQ	SN:chr9_gl000200_random	LN:187035
@SQ	SN:chr9_gl000201_random	LN:36148
@SQ	SN:chr11_gl000202_random	LN:40103
@SQ	SN:chr17_ctg5_hap1	LN:1680828
@SQ	SN:chr17_gl000203_random	LN:37498
@SQ	SN:chr17_gl000204_random	LN:81310
@SQ	SN:chr17_gl000205_random	LN:174588
@SQ	SN:chr17_gl000206_random	LN:41001
@SQ	SN:chr18_gl000207_random	LN:4262
@SQ	SN:chr19_gl000208_random	LN:92689
@SQ	SN:chr19_gl000209_random	LN:159169
@SQ	SN:chr21_gl000210_random	LN:27682
@SQ	SN:chrUn_gl000211	LN:166566
@SQ	SN:chrUn_gl000212	LN:186858
@SQ	SN:chrUn_gl000213	LN:164239
@SQ	SN:chrUn_gl000214	LN:137718
@SQ	SN:chrUn_gl000215	LN:172545
@SQ	SN:chrUn_gl000216	LN:172294
@SQ	SN:chrUn_gl000217	LN:172149
@SQ	SN:chrUn_gl000218	LN:161147
@SQ	SN:chrUn_gl000219	LN:179198
@SQ	SN:chrUn_gl000220	LN:161802
@SQ	SN:chrUn_gl000221	LN:155397
@SQ	SN:chrUn_gl000222	LN:186861
@SQ	SN:chrUn_gl000223	LN:180455
@SQ	SN:chrUn_gl000224	LN:179693
@SQ	SN:chrUn_gl000225	LN:211173
@SQ	SN:chrUn_gl000226	LN:15008
@SQ	SN:chrUn_gl000227	LN:128374
@SQ	SN:chrUn_gl000228	LN:129120
@SQ	SN:chrUn_gl000229	LN:19913
@SQ	SN:chrUn_gl000230	LN:43691
@SQ	SN:chrUn_gl000231	LN:27386
@SQ	SN:chrUn_gl000232	LN:40652
@SQ	SN:chrUn_gl000233	LN:45941
@SQ	SN:chrUn_gl000234	LN:40531
@SQ	SN:chrUn_gl000235	LN:34474
@SQ	SN:chrUn_gl000236	LN:41934
@SQ	SN:chrUn_gl000237	LN:45867
@SQ	SN:chrUn_gl000238	LN:39939
@SQ	SN:chrUn_gl000239	LN:33824
@SQ	SN:chrUn_gl000240	LN:41933
@SQ	SN:chrUn_gl000241	LN:42152
@SQ	SN:chrUn_gl000242	LN:43523
@SQ	SN:chrUn_gl000243	LN:43341
@SQ	SN:chrUn_gl000244	LN:39929
@SQ	SN:chrUn_gl000245	LN:36651
@SQ	SN:chrUn_gl000246	LN:38154
@SQ	SN:chrUn_gl000247	LN:36422
@SQ	SN:chrUn_gl000248	LN:39786
@SQ	SN:chrUn_gl000249	LN:38502
@RG	ID:01-BG_S1_L001_R1_001	PL:ILLUMINA	PU:None	LB:1	SM:01-BG
@PG	ID:bwa	PN:bwa	VN:0.7.12-r1039	CL:bwa mem -t 2 genome.fa 01-BG_S1_L001_R1_001.fastq.gz 01-BG_S1_L001_R2_001.fastq.gz -M -R @RG\tID:01-BG_S1_L001_R1_001\tPL:ILLUMINA\tPU:None\tLB:1\tSM:01-BG
chr16	2093497	2093817	+	interval_1
chr16	2094572	2094878	+	interval_2
chr16	2096047	2096442	+	interval_3
chr16	2097637	2097947	+	interval_4
chr16	5606115	5606268	+	interval_5
chr16	8768372	8768641	+	interval_6
chr16	8806742	8807133	+	interval_7

Thanks!

**Comment by yfarjoun** [comment]
Hello,

I agree that the documentation is somewhat unclear about it, but the
INTERVALS argument only gets passed to programs that know how to use it. As
you may know, most Picard CLPs do not take an INTERVALS argument. In
particular, of the list of programs that can be run via collect multiple
metrics, only "CollectSequencingArtifactMetrics" can use it, the other
programs quietly ignore it. Since you are not collecting this metric, you
do not see any change in your output.

I hope this helps!

Yossi.

On Wed, Mar 9, 2016 at 5:39 PM, hurchu <notifications@github.com> wrote:
>
> Hi,
>
> I tried to run CollectMultipleMetrics and provide a target region file.
But with or without the target region as input, the outputs are same.
>
> I tried to add BAM file header to the target region, still no difference.
>
> This is the command I used:
>
> java -jar picard.jar CollectMultipleMetrics INPUT=sorted.bam
ASSUME_SORTED=true STOP_AFTER=0 OUTPUT=01-BG
PROGRAM=[CollectAlignmentSummaryMetrics, CollectBaseDistributionByCycle,
CollectInsertSizeMetrics, MeanQualityByCycle, QualityScoreDistribution,
CollectAlignmentSummaryMetrics, CollectInsertSizeMetrics,
QualityScoreDistribution, MeanQualityByCycle] INTERVALS=target_region
REFERENCE_SEQUENCE=genome.fa STOP_AFTER=0 VERBOSITY=INFO QUIET=false
VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000
CREATE_INDEX=false CREATE_MD5_FILE=false
>
> The following are part of my target region file.
>
> @HD VN:1.3 SO:coordinate
> @SQ SN:chrM LN:16571
> @SQ SN:chr1 LN:249250621
> @SQ SN:chr2 LN:243199373
> @SQ SN:chr3 LN:198022430
> @SQ SN:chr4 LN:191154276
> @SQ SN:chr5 LN:180915260
> @SQ SN:chr6 LN:171115067
> @SQ SN:chr7 LN:159138663
> @SQ SN:chr8 LN:146364022
> @SQ SN:chr9 LN:141213431
> @SQ SN:chr10 LN:135534747
> @SQ SN:chr11 LN:135006516
> @SQ SN:chr12 LN:133851895
> @SQ SN:chr13 LN:115169878
> @SQ SN:chr14 LN:107349540
> @SQ SN:chr15 LN:102531392
> @SQ SN:chr16 LN:90354753
> @SQ SN:chr17 LN:81195210
> @SQ SN:chr18 LN:78077248
> @SQ SN:chr19 LN:59128983
> @SQ SN:chr20 LN:63025520
> @SQ SN:chr21 LN:48129895
> @SQ SN:chr22 LN:51304566
> @SQ SN:chrX LN:155270560
> @SQ SN:chrY LN:59373566
> @SQ SN:chr1_gl000191_random LN:106433
> @SQ SN:chr1_gl000192_random LN:547496
> @SQ SN:chr4_ctg9_hap1 LN:590426
> @SQ SN:chr4_gl000193_random LN:189789
> @SQ SN:chr4_gl000194_random LN:191469
> @SQ SN:chr6_apd_hap1 LN:4622290
> @SQ SN:chr6_cox_hap2 LN:4795371
> @SQ SN:chr6_dbb_hap3 LN:4610396
> @SQ SN:chr6_mann_hap4 LN:4683263
> @SQ SN:chr6_mcf_hap5 LN:4833398
> @SQ SN:chr6_qbl_hap6 LN:4611984
> @SQ SN:chr6_ssto_hap7 LN:4928567
> @SQ SN:chr7_gl000195_random LN:182896
> @SQ SN:chr8_gl000196_random LN:38914
> @SQ SN:chr8_gl000197_random LN:37175
> @SQ SN:chr9_gl000198_random LN:90085
> @SQ SN:chr9_gl000199_random LN:169874
> @SQ SN:chr9_gl000200_random LN:187035
> @SQ SN:chr9_gl000201_random LN:36148
> @SQ SN:chr11_gl000202_random LN:40103
> @SQ SN:chr17_ctg5_hap1 LN:1680828
> @SQ SN:chr17_gl000203_random LN:37498
> @SQ SN:chr17_gl000204_random LN:81310
> @SQ SN:chr17_gl000205_random LN:174588
> @SQ SN:chr17_gl000206_random LN:41001
> @SQ SN:chr18_gl000207_random LN:4262
> @SQ SN:chr19_gl000208_random LN:92689
> @SQ SN:chr19_gl000209_random LN:159169
> @SQ SN:chr21_gl000210_random LN:27682
> @SQ SN:chrUn_gl000211 LN:166566
> @SQ SN:chrUn_gl000212 LN:186858
> @SQ SN:chrUn_gl000213 LN:164239
> @SQ SN:chrUn_gl000214 LN:137718
> @SQ SN:chrUn_gl000215 LN:172545
> @SQ SN:chrUn_gl000216 LN:172294
> @SQ SN:chrUn_gl000217 LN:172149
> @SQ SN:chrUn_gl000218 LN:161147
> @SQ SN:chrUn_gl000219 LN:179198
> @SQ SN:chrUn_gl000220 LN:161802
> @SQ SN:chrUn_gl000221 LN:155397
> @SQ SN:chrUn_gl000222 LN:186861
> @SQ SN:chrUn_gl000223 LN:180455
> @SQ SN:chrUn_gl000224 LN:179693
> @SQ SN:chrUn_gl000225 LN:211173
> @SQ SN:chrUn_gl000226 LN:15008
> @SQ SN:chrUn_gl000227 LN:128374
> @SQ SN:chrUn_gl000228 LN:129120
> @SQ SN:chrUn_gl000229 LN:19913
> @SQ SN:chrUn_gl000230 LN:43691
> @SQ SN:chrUn_gl000231 LN:27386
> @SQ SN:chrUn_gl000232 LN:40652
> @SQ SN:chrUn_gl000233 LN:45941
> @SQ SN:chrUn_gl000234 LN:40531
> @SQ SN:chrUn_gl000235 LN:34474
> @SQ SN:chrUn_gl000236 LN:41934
> @SQ SN:chrUn_gl000237 LN:45867
> @SQ SN:chrUn_gl000238 LN:39939
> @SQ SN:chrUn_gl000239 LN:33824
> @SQ SN:chrUn_gl000240 LN:41933
> @SQ SN:chrUn_gl000241 LN:42152
> @SQ SN:chrUn_gl000242 LN:43523
> @SQ SN:chrUn_gl000243 LN:43341
> @SQ SN:chrUn_gl000244 LN:39929
> @SQ SN:chrUn_gl000245 LN:36651
> @SQ SN:chrUn_gl000246 LN:38154
> @SQ SN:chrUn_gl000247 LN:36422
> @SQ SN:chrUn_gl000248 LN:39786
> @SQ SN:chrUn_gl000249 LN:38502
> @RG ID:01-BG_S1_L001_R1_001 PL:ILLUMINA PU:None LB:1 SM:01-BG
> @PG ID:bwa PN:bwa VN:0.7.12-r1039 CL:bwa mem -t 2 genome.fa
01-BG_S1_L001_R1_001.fastq.gz 01-BG_S1_L001_R2_001.fastq.gz -M -R
@RG\tID:01-BG_S1_L001_R1_001\tPL:ILLUMINA\tPU:None\tLB:1\tSM:01-BG

**Comment by hurchu** [comment]
Thank you very much!

On Wed, Mar 9, 2016 at 7:05 PM, Yossi Farjoun <notifications@github.com>
wrote:

> Hello,
>
> I agree that the documentation is somewhat unclear about it, but the
> INTERVALS argument only gets passed to programs that know how to use it. As
> you may know, most Picard CLPs do not take an INTERVALS argument. In
> particular, of the list of programs that can be run via collect multiple
> metrics, only "CollectSequencingArtifactMetrics" can use it, the other
> programs quietly ignore it. Since you are not collecting this metric, you
> do not see any change in your output.
>
> I hope this helps!
>
> Yossi.
>
> On Wed, Mar 9, 2016 at 5:39 PM, hurchu <notifications@github.com> wrote:
> >
> > Hi,
> >
> > I tried to run CollectMultipleMetrics and provide a target region file.
> But with or without the target region as input, the outputs are same.
> >
> > I tried to add BAM file header to the target region, still no difference.
> >
> > This is the command I used:
> >
> > java -jar picard.jar CollectMultipleMetrics INPUT=sorted.bam
> ASSUME_SORTED=true STOP_AFTER=0 OUTPUT=01-BG
> PROGRAM=[CollectAlignmentSummaryMetrics, CollectBaseDistributionByCycle,
> CollectInsertSizeMetrics, MeanQualityByCycle, QualityScoreDistribution,
> CollectAlignmentSummaryMetrics, CollectInsertSizeMetrics,
> QualityScoreDistribution, MeanQualityByCycle] INTERVALS=target_region
> REFERENCE_SEQUENCE=genome.fa STOP_AFTER=0 VERBOSITY=INFO QUIET=false
> VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000
> CREATE_INDEX=false CREATE_MD5_FILE=false
> >
> > The following are part of my target region file.
> >
> > @HD VN:1.3 SO:coordinate
> > @SQ SN:chrM LN:16571
> > @SQ SN:chr1 LN:249250621
> > @SQ SN:chr2 LN:243199373
> > @SQ SN:chr3 LN:198022430
> > @SQ SN:chr4 LN:191154276
> > @SQ SN:chr5 LN:180915260
> > @SQ SN:chr6 LN:171115067
> > @SQ SN:chr7 LN:159138663
> > @SQ SN:chr8 LN:146364022
> > @SQ SN:chr9 LN:141213431
> > @SQ SN:chr10 LN:135534747
> > @SQ SN:chr11 LN:135006516
> > @SQ SN:chr12 LN:133851895
> > @SQ SN:chr13 LN:115169878
> > @SQ SN:chr14 LN:107349540
> > @SQ SN:chr15 LN:102531392
> > @SQ SN:chr16 LN:90354753
> > @SQ SN:chr17 LN:81195210
> > @SQ SN:chr18 LN:78077248
> > @SQ SN:chr19 LN:59128983
> > @SQ SN:chr20 LN:63025520
> > @SQ SN:chr21 LN:48129895
> > @SQ SN:chr22 LN:51304566
> > @SQ SN:chrX LN:155270560
> > @SQ SN:chrY LN:59373566
> > @SQ SN:chr1_gl000191_random LN:106433
> > @SQ SN:chr1_gl000192_random LN:547496
> > @SQ SN:chr4_ctg9_hap1 LN:590426
> > @SQ SN:chr4_gl000193_random LN:189789
> > @SQ SN:chr4_gl000194_random LN:191469
> > @SQ SN:chr6_apd_hap1 LN:4622290
> > @SQ SN:chr6_cox_hap2 LN:4795371
> > @SQ SN:chr6_dbb_hap3 LN:4610396
> > @SQ SN:chr6_mann_hap4 LN:4683263
> > @SQ SN:chr6_mcf_hap5 LN:4833398
> > @SQ SN:chr6_qbl_hap6 LN:4611984
> > @SQ SN:chr6_ssto_hap7 LN:4928567
> > @SQ SN:chr7_gl000195_random LN:182896
> > @SQ SN:chr8_gl000196_random LN:38914
> > @SQ SN:chr8_gl000197_random LN:37175
> > @SQ SN:chr9_gl000198_random LN:90085
> > @SQ SN:chr9_gl000199_random LN:169874
> > @SQ SN:chr9_gl000200_random LN:187035
> > @SQ SN:chr9_gl000201_random LN:36148
> > @SQ SN:chr11_gl000202_random LN:40103
> > @SQ SN:chr17_ctg5_hap1 LN:1680828
> > @SQ SN:chr17_gl000203_random LN:37498
> > @SQ SN:chr17_gl000204_random LN:81310
> > @SQ SN:chr17_gl000205_random LN:174588
> > @SQ SN:chr17_gl000206_random LN:41001
> > @SQ SN:chr18_gl000207_random LN:4262
> > @SQ SN:chr19_gl000208_random LN:92689
> > @SQ SN:chr19_gl000209_random LN:159169
> > @SQ SN:chr21_gl000210_random LN:27682
> > @SQ SN:chrUn_gl000211 LN:166566
> > @SQ SN:chrUn_gl000212 LN:186858
> > @SQ SN:chrUn_gl000213 LN:164239
> > @SQ SN:chrUn_gl000214 LN:137718
> > @SQ SN:chrUn_gl000215 LN:172545
> > @SQ SN:chrUn_gl000216 LN:172294
> > @SQ SN:chrUn_gl000217 LN:172149
> > @SQ SN:chrUn_gl000218 LN:161147
> > @SQ SN:chrUn_gl000219 LN:179198
> > @SQ SN:chrUn_gl000220 LN:161802
> > @SQ SN:chrUn_gl000221 LN:155397
> > @SQ SN:chrUn_gl000222 LN:186861
> > @SQ SN:chrUn_gl000223 LN:180455
> > @SQ SN:chrUn_gl000224 LN:179693
> > @SQ SN:chrUn_gl000225 LN:211173
> > @SQ SN:chrUn_gl000226 LN:15008
> > @SQ SN:chrUn_gl000227 LN:128374
> > @SQ SN:chrUn_gl000228 LN:129120
> > @SQ SN:chrUn_gl000229 LN:19913
> > @SQ SN:chrUn_gl000230 LN:43691
> > @SQ SN:chrUn_gl000231 LN:27386
> > @SQ SN:chrUn_gl000232 LN:40652
> > @SQ SN:chrUn_gl000233 LN:45941
> > @SQ SN:chrUn_gl000234 LN:40531
> > @SQ SN:chrUn_gl000235 LN:34474
> > @SQ SN:chrUn_gl000236 LN:41934
> > @SQ SN:chrUn_gl000237 LN:45867
> > @SQ SN:chrUn_gl000238 LN:39939
> > @SQ SN:chrUn_gl000239 LN:33824
> > @SQ SN:chrUn_gl000240 LN:41933
> > @SQ SN:chrUn_gl000241 LN:42152
> > @SQ SN:chrUn_gl000242 LN:43523
> > @SQ SN:chrUn_gl000243 LN:43341
> > @SQ SN:chrUn_gl000244 LN:39929
> > @SQ SN:chrUn_gl000245 LN:36651
> > @SQ SN:chrUn_gl000246 LN:38154
> > @SQ SN:chrUn_gl000247 LN:36422
> > @SQ SN:chrUn_gl000248 LN:39786
> > @SQ SN:chrUn_gl000249 LN:38502
> > @RG ID:01-BG_S1_L001_R1_001 PL:ILLUMINA PU:None LB:1 SM:01-BG
> > @PG ID:bwa PN:bwa VN:0.7.12-r1039 CL:bwa mem -t 2 genome.fa
> 01-BG_S1_L001_R1_001.fastq.gz 01-BG_S1_L001_R2_001.fastq.gz -M -R
> @RG\tID:01-BG_S1_L001_R1_001\tPL:ILLUMINA\tPU:None\tLB:1\tSM:01-BG
> > chr16 2093497 2093817 + interval_1
> > chr16 2094572 2094878 + interval_2
> > chr16 2096047 2096442 + interval_3
> > chr16 2097637 2097947 + interval_4
> > chr16 5606115 5606268 + interval_5
> > chr16 8768372 8768641 + interval_6
> > chr16 8806742 8807133 + interval_7
> >
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/picard/issues/478#issuecomment-194618480>
> .
>



-- 
Junfei Zhu

**Comment by yfarjoun** [comment]
This seems to be resolved. feel free to reopen if I'm mistaken.
