### ISSUE TITLE
Help dialogue is broken

### ISSUE THREAD

**Issue by rleonid** [broadinstitute/picard#481]
```sh
$ java -jar picard.jar --help
USAGE: PicardCommandLine <program name> [-h]

Available Programs:
....
'--help' is not a valid command. See PicardCommandLine --help for more information.
$ echo $?
1
```

**Comment by rleonid** [comment]
Furthermore, if the help argument does succeed (ex. `java -jar picard.jar SortVcf --help`) the return value should not `1`.

**Comment by rleonid** [comment]
I guess addressing the return code is not a valid concern?

**Comment by yfarjoun** [comment]
If you'd like to fix the return code, you are welcome to do so. I didn't feel the need to impose it on this simple PR.
