### ISSUE TITLE
Is there a way to make MarkDuplicates less CPU-greedy? 

### ISSUE THREAD

**Issue by apredeus** [broadinstitute/picard#488]
I'm using MarkDuplicates on a 64-CPU server, and no matter what the current load is, Java seems to occupy all 64 cores when I run few jobs simultaneously. Is there a way to make it use less resources?

**Comment by yfarjoun** [comment]
have you tried adding `-XX:+UseSerialGC` (HT to @kcibul ) to your commandline?

**Comment by apredeus** [comment]
We did - this only limits what the garbage collector uses (I think). The jobs still occupy way too many cores.

**Comment by nh13** [comment]
`-XX:GCHeapFreeLimit=10` and `-XX:GCTimeLimit=50` can be helpful too.  

On Unix, another way to limit the JVM's resource usage is to use `taskset` (cores) or `cgroups` (all).
