### ISSUE TITLE
Remove deprecated classes

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/picard#510]
In particular, we should remove CollectWgsMetricsFromQuerySorted and CollectWgsMetricsFromSampledSites (and their respective test classes and files) in a few months from today (4/12/16).

**Comment by nh13** [comment]
@eitanbanks any reason for their removal?  Are they not useful?  I am more curious than anything since they seemed like tools to quickly compute WGS metrics that could be useful as WGS scales in the community.  Is there a preferred tool?

**Comment by eitanbanks** [comment]
Yeah, it's a fair question, @nh13.  @ktibbett pointed out (correctly IMO) that I probably shouldn't have put these classes into the repo in the first place.  They were used for some experimental development work and are unlikely to be useful to others.  They effectively do the same thing as CollectWgsMetrics (which is the preferred tool).  If you disagree though I'm happy to hear otherwise.

**Comment by vdauwera** [comment]
Has the relevant work been done / can this be closed?

**Comment by eitanbanks** [comment]
No, they still need to be removed.

**Comment by ronlevine** [comment]
Closing since #798 is merged.
