### ISSUE TITLE
VariantContext throws exception on getAltAlleleWithHighestAlleleCount()

### ISSUE THREAD

**Issue by jamesnemesh** [broadinstitute/picard#519]
When calling getAltAlleleWithHighestAlleleCount() on a variant that has no variation, class throws exception:

java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at htsjdk.variant.variantcontext.VariantContext.getAltAlleleWithHighestAlleleCount(VariantContext.java:1704)

This used to emit a null, which I'd grab and then work around appropriately.  I've attached a 1 line VCF (testVCF.vcf) file as an example for replication.  

As a further related question - is there a way to recover the alternate allele for this record if I've filtered the record to only look at sample a sample that doesn't have the alternate allele via subContextFromSamples()?  The list of the samples I care about for analysis changes the list of alternate alleles for the context, but I actually want all of the original alleles for reporting purposes.  See testVCF2.vcf.  Is my only recourse to get those alleles before filtering by samples?

[testVCFs.zip](https://github.com/broadinstitute/picard/files/226295/testVCFs.zip)

**Comment by kasont** [comment]
Could you add a test for this to come out null and one to not? @jamesnemesh
