### ISSUE TITLE
Review period for functionally equivalent PRs: 4/19 - 5/3

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/picard#520]
Some users have requested the opportunity to have more time to review functionally equivalent PRs.  As an attempt at implementing this, we've started by creating a "[functionally equivalent changes](https://github.com/broadinstitute/picard/pulls?q=is%3Apr+is%3Aopen+label%3A%22functionally+equivalent+changes%22)" label and grouped 3 issues under it.  We're asking for review and comment on these changes between now and May 3rd, at which time they will be resolved.

Suggestions for improving this process are welcome.

**Comment by yfarjoun** [comment]
I think we got these done and can close this issue.
