### ISSUE TITLE
MarkDuplicates, use UMI from read name instead of tag

### ISSUE THREAD

**Issue by mjafin** [broadinstitute/picard#539]
Hi there,
Thanks for all the fantastic work on Picard. I was wondering if you would consider using the read name as the source of UMI for marking duplicates, as an alternative to a separate BAM tag. If UMI is in the read name then any BAM-fastq conversions won't lose the information. It seems to be the direction Illumina are taking too; when delimiting the read name by `:` the last field is allowed to contain the UMI. If both indices have a UMI the separator is `+` as far as I can tell.

**Comment by yfarjoun** [comment]
This is an interesting idea but I see more cons than pros:

pro:
- no data loss when going from BAM to FASTQ

con:
- if you put sequence information in the read-name, you will not be able to
put quality scores (there)
- you will need to be careful about parsing a single string that already
has many fields (and a somewhat complicated parser)
- to do this the BCL processor might need to know about molecular barcodes,
which might be inline with the read, or the same barcodes, or out on their
own.
- It doesn't enable (simply) the error correction of barcodes
- if you want to strip out the barcode, you need to change the readname
- some people modify the read-names to improve compression (see CRAM), this
will not work here

For the benefit, the cost seems pretty high...given that there are many
other tags that are lost when going to FASTQ, why focus on this one in
particular?

**Comment by tfenne** [comment]
I completely agree with @yfarjoun .  I'll add to the con list that it becomes much more awkward to handle reads that have multiple UMIs (several systems using multiple UMIs have already been published/are in use).

**Comment by nh13** [comment]
There's no data loss going from BAM to FASTQ if you have the UMIs stored in the SAM tags and then have a tool re-create the FASTQ header.   Also, depending on what is shoved into the read name as part of the UMIs, read name sorting will fail since ends of a pair may have different UMIs and therefore have different read names.  Finally, I think adding more fields in the name for Illumina data will break the parsing of read name to obtain their physical location (tile, x, y)

**Comment by mjafin** [comment]
Thanks for the great discussion, you've certainly brought up some points I hadn't even considered, like losing the base qualities if putting the UMI in the read name. I've learned something new today so that's good!

To cut a long story short, we're tied to using Illumina's bcl2fastq and they are taking steps towards shoving the UMI into the read name (I like the idea - I might be the only one), see http://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-17-software-guide-15051736-g.pdf page 5. Read name sorting will not fail as both reads in a pair get the same UMI (if multiple UMIs are used in a read pair they are concatenated and separated by `+` symbols). 

The read name format, as specified by Illumina is:
```
@<instrument>:<run number>:<flowcell ID>:<lane>:<tile>:<xpos>:<y-pos>:<UMI> <read>:<is filtered>:<control number>:<index>
```
So, in the read name that eventually ends up in BAM, UMI will be the last string when delimited by `:`. 

For a bit more background, in the pipeline we use everything is piped from fastq all the way to duplicate marked and sorted bam (we prefer the intermediate data touching the disk as little as possible). At the moment it works somehow like
```
fastq | bwa | samblaster | samtools sort > bam
```
Since bwa doesn't (?) work off of bam/sam files, I can't think of another way of passing the UMIs to the duplicate marking tool except in the read name (samblaster doesn't support UMI duplicate marking but you get the gist). Would value your opinion here.

**Comment by yfarjoun** [comment]
I think that if you have UMIs in the readname, you should first move them to a tag. 👎

**Comment by jhl667** [comment]
I know this is closed, but thought I would throw my two cents in.  Illumina's demultiplexer bcl2fastq does indeed place UMI's in the read name, as described above.  I have written a very short Python utilizing pysam to modify the format and throw UMI's from the end of the read name in to the last field using RX:Z:<UMI>.  I would say that since bcl2fastq is such a standard Illumina tool, it would make sense to eventually have this functionality in Picard.  However, I certainly don't have time to contribute it, so I don't expect anyone else to either!! 😉 

Thanks for all the great work!

**Comment by mjafin** [comment]
I wanted to add that the umis repo https://github.com/vals/umis does the work of extracting UMIs from raw fastq files into the readname and also has a streaming module to extract the UMI from read name into a bam tag post alignment (in a streaming manner). @tfenne you may want to reconsider supporting UMIs in read names as reading all UMIs into memory in fgbio's AnnotateBamWithUmis doesn't scale for higher depth data.

**Comment by mjafin** [comment]
@nh13 no worries, this is all sorted in bcbio using `umis` to stream the UMI from the read name to a bam tag so that we can use the other fgbio tools downstream. Our fastq files can be arbitrarily large.

I believe it's standard practice especially in single-cell RNA-seq to use the read name for UMIs but I'm starting to sound like a broken record, apologies for that.

Often people realign other people's bam files and the bam tags have no place in fastq files so the UMIs would get lost but again this is an aside.

**Comment by nh13** [comment]
@mjafin that's why I recommend converting FASTQs to SAM ASAP, or not using FASTQs at all (i.e. use Picard's IlluminaBasecallsToSam, which can extract UMIs).  Thanks for giving feedback on how you are using the tools, it's really helpful!

**Comment by jhl667** [comment]
@nh13 If you convert to SAM via IlluminaBasecallsToSam, wouldn't you have to convert back to FASTQ to align your sequence (e.g. BWA)?

**Comment by nh13** [comment]
Yes you do, but the conventional way without writing the FASTQ to disk is `SamToFastq -> Bwa -> MergeBamAlignment`, so you never have a FASTQ available for any real amount of time.

**Comment by BigTA78** [comment]
You might want to check out Je. The markdupes command extends the popular Picard’s MarkDuplicates tool by adding support for UMIs embedded in read headers
