### ISSUE TITLE
Write error using /dev/stdout in MarkDuplicates

### ISSUE THREAD

**Issue by jma1991** [broadinstitute/picard#541]
I encounter an error when I pipe the output from MarkDuplicates through /dev/stdout to another command:

`Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; file: /dev/stdout`

The command I use is:

`java -Xmx2g -XX:ParallelGCThreads=1 -jar picard.jar MarkDuplicates QUIET=true VERBOSITY=ERROR INPUT=input.bam OUTPUT=/dev/stdout METRICS_FILE=/dev/null REMOVE_DUPLICATES=true`

If I put an actual filename as the output variable, I do not encounter this error. This behaviour is very similar to the [issue](https://github.com/arq5x/bedtools2/issues/229) I have been having with bedtools, when I try to intersect a BAM file with a BED file.

Both Picard (picard-2.3.0) and Bedtools (bedtools v2.25.0) are installed (using the bioconda channel) in my home directory on a server (CentOS release 6.7), and my files are on a storage array which I access using NFS. The UID/GID on both the server and storage array are an exact match.

I believe the error comes from the underlying BGZF library used to compress BAM files, because both the error from Picard and Bedtools seem to originate from that libraries use. What's interesting is that if I pipe the Picard output through `samtools view -b -` then I don't encounter any errors. I think Samtools uses the same BGZF library so I wonder if Samtools uses it differently to both Picard and Bedtools?

**Comment by jabbarish** [comment]
@s1437643!
We tried to reproduce your problem, but we couldn't.
In the course of work was taken steps:
1) Install VM CentOS 6.7
2) Install Picard 2.3.0 from bioconda 
3) Set up NFS connection between VM and physical machine, share bam file
4) Run command form your issue
It is work normally for us. Can you describe what happened with more details and give some file, where do you reproduced the problem and full log file. Also please check if the issue persists in the current version of the Picard.
Thank you!

**Comment by jabbarish** [comment]
@s1437643 s1437643

We tried to reproduce your problem, but we couldn't.

We used
1) VM CentOS 6.7
2) Picard 2.3.0 from bioconda 
3) NFS connection between VM and physical machine, shared bam file
4) command line options from your description

It worked normally for us. Could you describe what happened with more details and give us the file to reproduce the problem? Could you also provide us with full log file?  Please check if the issue still occurs using the latest version of the Picard.

Thank you!

**Comment by vdauwera** [comment]
Closing due to lack of response
