### ISSUE TITLE
Use maven version of htsjdk during releases, decouple htsjdk and picard releases, and simplify release process.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/picard#545]
As of https://github.com/broadinstitute/picard/pull/542, Picard fetches htsjdk from maven during normal builds, but the release script still clones the htsjdk repo and builds from source. Ideally we should use the same version of htsjdk in releases as we do in normal builds, travis, etc. If we need to release with a newer htsjdk than we're currently on, we can just do a PR to update `ivy.xml` just before a release. This will require some changes to the existing release process, however. @jacarey and I settled on the following plan during review of https://github.com/broadinstitute/picard/pull/542:

-Decouple htsjdk and picard releases so that we don't have to release both projects simultaneously. This will allow Picard to pull a tagged version of htsjdk from maven during release instead of building from source.

-Release to only one place (maven central) instead of both maven and github, and simplify the existing Picard release script into a documentation publisher.

-Write up instructions for a new, simplified release procedure for Picard along the lines of: "tag and update version number in build.sbt, release to maven, and publish documentation via the modified release script", and post the instructions to the wiki on github (minus passwords and other sensitive info).

-Include an easy way to substitute a locally-built htsjdk jar during development in place of the maven jar (for example, by installing an htsjdk snapshot to one's local maven repository in ~/.m2, or some other convenient mechanism).

@jacarey does the above adequately capture our discussion in https://github.com/broadinstitute/picard/pull/542? Anything I'm missing?

**Comment by jacarey** [comment]
https://github.com/broadinstitute/picard/pull/554

Gradle changes for picard. This includes a "build htsjdk from source" build file that can clone and build htsjdk from source instead of taking the released jar from maven.

**Comment by vdauwera** [comment]
Same question as the linked PR: is this still a thing or can I assume it's a relic?

**Comment by lbergelson** [comment]
Move to gradle is complete!
