### ISSUE TITLE
Picard build failing with the latest HTSJDK

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#563]
Also, the last build of the integration test was 84 on May 16th: https://gatk-jenkins.broadinstitute.org/job/picard-on-htsjdk-master/

@akiezun can you take a look or someone at Broad?

**Comment by nh13** [comment]
Also, the last build of gatk was a while ago: https://gatk-jenkins.broadinstitute.org/job/gatk-on-htsjdk-master/

**Comment by akiezun** [comment]
@nh13 is it now fixed after @tfenne's changes?

**Comment by nh13** [comment]
Why are there no jenkins builds between May 16 (`#84`) and June 15 (`#85`)?

**Comment by lbergelson** [comment]
@nh13 There should be jenkins builds again.  The downstream jenkins builds weren't getting started because the htsjdk one was failing due to a configuration issue.

**Comment by nh13** [comment]
That makes a lot of sense.  How were those builds intended to be used, since merges to master and releases still happened?

**Comment by lbergelson** [comment]
The builds were intended to be used to show that there weren't any newly introduced bugs that caused downstream failures before releasing.  (i.e. using the picard / gatk tests suites as auxiliary tests for htsjdk.  We had a number of bad bugs that we didn't find in htsjdk before release, but were immediately caught when we updated gatk. )  It's complicated by the fact that there may be breaking changes that are expected to cause failures.   The thought was that before an htsjdk release someone should make a branch in picard/ gatk that passes against the current htsjdk and do a manual green build to show that it's an api change that caused the problems and not a newly introduced bug.  

I was on vacation while the last release happened, so I'm not sure what tests were run then.  It's possible no one realized that the tests were outdated and didn't do the manual builds.

**Comment by yfarjoun** [comment]
This is fixed, right?

**Comment by lbergelson** [comment]
I've fixed the tests and this is working now.
