### ISSUE TITLE
Picard command line over page duplicates tools

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#564]
For example, `CollectSequencingArtifactMetrics` is listed six times  here: https://broadinstitute.github.io/picard/command-line-overview.html

@vdauwera can you take a look?

**Comment by vdauwera** [comment]
Sure, will take a look when I'm back from my GATK workshop away mission next week.

**Comment by vdauwera** [comment]
Huh. This is bizarre -- the entire set of tools is repeated end to end several times. We must have introduced a bug into the doc generation code. Will get this fixed asap.

**Comment by yfarjoun** [comment]
is this fixed?

**Comment by vdauwera** [comment]
Yeah it looks like it is. Must have been a glitch during release that one time. I did check and nothing looks amiss in the doc generation code.
