### ISSUE TITLE
Trouble excecuting

### ISSUE THREAD

**Issue by ksw9** [broadinstitute/picard#567]
Hi, I just cloned picard using the following:

git clone git@github.com:broadinstitute/picard.git
cd picard/
ant clone-htsjdk
ant

And I am now confused about where to find the executable picard.jar file?  Thank you for your help!

Best,

**Comment by yfarjoun** [comment]
Thanks for your question. 

in the dist/ directory:
```bash
$ ls dist
html                   htsjdk_lib_dir         picard-lib.jar         picard-tools-2.4.1.zip picard.jar
```

**Comment by ksw9** [comment]
Thank you for the reply.  I do not have a dist directory in the picard
version I downloaded.  Did I not clone correctly?  Thank you.

 ls ~/repos/picard/
.classpath         .gitignore         Dockerfile         Picard-public.ipr
 build.xml          lib/               testdata/
.dockerignore      .project           Picard-public.fbp  README.md
 etc/               project/
.git/              .travis.yml        Picard-public.iml  build.sbt
 htsjdk/            src/

**Comment by yfarjoun** [comment]
hmm. I ran the commands you listed and got the expected results:

```bash
git clone git@github.com:broadinstitute/picard.git
cd picard/
ant clone-htsjdk
ant
ls
ls dist
```

output 
```code
html                   htsjdk_lib_dir         picard-lib.jar         picard-tools-2.4.1.zip picard.jar
```

Did you check for errors in the compilation? what version of Ant do you have? 
```bash
 ant -version
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
```

**Comment by ksw9** [comment]
Thank you for your quick reply.
Yes, there is an error with the compilation.  I need to look into this
locally:
     [exec] * What went wrong:
     [exec] Execution failed for task ':compileJava'.
     [exec] > Could not find tools.jar. Please check that
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-2.b15.el7_2.x86_64/jre contains a
valid JDK installation.


Thanks again for the fast help!
Best,
