### ISSUE TITLE
Bug in MarkDuplicates when using ASSUME_SORT_ORDER

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#572]
In order to use Picard's Markduplicates in queryname mode (which marks supplementary reads and secondary reads like the canonical read) the input must be in "queryname" order, or the flag "ASSUME_SORT_ORDER=queryname" should be set (if the reads known to be query-name grouped, but not queryname sorted). The latter will fail if the reads are not actually **sorted** by queryname since the program uses that sort order in the output writer which then fails to write records that are out of order....

Thanks for the user for reporting. 

Working on fixing this.

**Comment by vdauwera** [comment]
@yfarjoun I see you closed your PR without merging. Does that mean this is no longer considered a bug, or it is but it needs a different approach for fixing?
