### ISSUE TITLE
ViewSam Performance

### ISSUE THREAD

**Issue by ayang99** [broadinstitute/picard#574]
(Posted originally to GATK forums and they recommended I open an issue here)

I have been playing around with the latest Picard Tools build (2.4.1) with the intention of eventually using HTSJDK directly to manipulate SAM/BAM/CRAM files. I've found that when I run the ViewSam Picard Tool on a CRAM, it takes a very long time to run. In this example, my "interval.txt" contains a single range 7:169000-170000 that has been converted from a Bed file into an Interval file with a SequenceDictionary I constructed from a FASTA file.

Running the same query in SamTools 1.3.1 View is extremely quick - a matter of seconds. The ViewSam Picard Tool takes 30+ minutes.

java -jar /picard-tools-2.4.1/picard.jar ViewSam INPUT=sample.cram INTERVAL_LIST=interval.txt REFERENCE_SEQUENCE=genome.fa VALIDATION_STRINGENCY=SILENT

[Wed Jun 22 20:41:31 UTC 2016] picard.sam.ViewSam INPUT=sample.cram INTERVAL_LIST=interval.txt REFERENCE_SEQUENCE=genome.fa ALIGNMENT_STATUS=All PF_STATUS=All HEADER_ONLY=false RECORDS_ONLY=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=SILENT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json

Running this on the BAM version of the file also takes a long time. The sample CRAM file I'm testing with is approximately 88 GB. Both my reference file and my CRAM file are indexed (I have genome.fa.fai and sample.cram.crai in the same directory as genome.fa and sample.cram)

I compared the code in ViewSam with a quick and dirty code spike I did (which runs as quickly as SamTools). The main material difference appears to be that ViewSam uses SamRecordIntervalIteratorFactory().makeSamRecordIntervalIterator() whereas I use SamReader.query().

What is the trade-off between these two approaches? Is this performance discrepancy expected?

Actually, just realized I am also doing a println of the SAMRecord.toString() whereas ViewSam is using SAMTextHeaderCodec().encode() - could this be the cause of the discrepancy?

Your environment

HTSJDK 2.4.1
Oracle Java 1.8.0_91
Ubuntu 14.04 LTS

**Comment by tfenne** [comment]
@ayang99 I took a quick peek at the code for `SamRecordIntervalIteratorFactory().makeSamRecordIntervalIterator()`, and so long as an index exists and is detected, then the invocation from `ViewSam` will also reduce down to the same call to `SamReader.query()`.  So I think one thing to check out be whether it's finding the index.  You could verify this by a) moving the index out of the way and b) writing an empty or invalid file with the same name - which _should_ cause an exception.

I would find it super surprising to find that `SAMRecord.toString()` would account for a difference of more than a few seconds per million records written.  Also, I'm wondering if maybe you meant `SAMRecord.getSAMString` since `toString()` doesn't produce SAM format (!).

**Comment by ayang99** [comment]
Thanks for looking into this. I do have an index file - it's naming convention is sample.cram.crai - is that what Picard would look for?

Also yes, I'm using toString() just for this research spike. I'm not outputting valid SAM, but just enough info to be recognizable.

**Comment by ayang99** [comment]
In htsjdk, the convention around using SamInputResources appears to be: SamReaderFactory.makeDefault().open(SamInputResource.of(bam).index(bai));

So, I'm inclined to think this should be fixed in ViewSam, unless you are suggesting that the logic for finding the index file should be exposed and re-usable. I can see that.

**Comment by tfenne** [comment]
That is what I'm suggesting.  I think that if using SamInputResource.of() with either `File` or `Path` it should probably attempt to find the index for you, as I think it's probably what most people would expect.  Wouldn't hurt to fix `ViewSam` in the mean time though.

**Comment by vdauwera** [comment]
Looks like this was fixed in htsjdk.
