### ISSUE TITLE
CleanSam configurable

### ISSUE THREAD

**Issue by apeltzer** [broadinstitute/picard#578]
Hi everyone!

It would be great to specify what CleanSam can do on your data on the command line. Currently, it fixes MAPQ>0 for unmapped reads and also fixes off-hanging reads and soft clips them. While the first is desirable in our application case, the second is not. Could we maybe add this as an option to configure what we would like to be done by CleanSam? It might be useful for others too, and not too complicated to be added to cleanSam. In case you're happy with it, I might even add it myself ;-)

**Comment by yfarjoun** [comment]
I think it would be fine to have a CLIP_OVERHANGING_READS (default = true)
in the commandline.

On Mon, Jun 27, 2016 at 5:08 AM, Alexander Peltzer <notifications@github.com

**Comment by tfenne** [comment]
FWIW It's invalid SAM to have reads that map beyond the end of a reference sequence, so this option would allow CleanSam to produce invalid BAM files.

**Comment by apeltzer** [comment]
You are right, we only produce inconsistent SAM/BAM files when applying our mapping method for circular genomes, which is then subsequently corrected using our tool, splitting these reads. As this produces coherent results again, I guess we are safe to use CleanSam in all cases, so I consider this as solved. Thanks for the input anyhow!
