### ISSUE TITLE
CollectInsertSizeMetricsTest is inconsistent/broken

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/picard#581]
CollectInsertSizeMetricsTest has a bunch of code that appears to [validate metrics collected at multiple levels](https://github.com/broadinstitute/picard/blob/6f1c99263c2b8f712f06a07b50d4db0550ed4885/src/tests/java/picard/analysis/CollectInsertSizeMetricsTest.java#L83), but most of the code never executes because the test doesn't any pass metric accumulation level arguments. Metrics are only collected at the ALL_READS level; if the args are passed, the validation code executes, but the tests fail. Its not clear if the failures indicate a bug in the collector or just bad test code.

**Comment by SHuang-Broad** [comment]
@cmnbroad, should this be closed now that #480 is in?

**Comment by cmnbroad** [comment]
Closed via #480.
