### ISSUE TITLE
RevertSam feature request to make RG-aware OR give error for mixed PE/SE BAMs

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#583]
This issue stems from answering a forum user question described in github issue https://github.com/broadinstitute/dsde-docs/issues/1010 and forum post http://gatkforums.broadinstitute.org/gatk/discussion/7814/error-mate-unmapped-flag-should-not-be-set-for-unpaired-reads-after-revertsam/p1.

Perhaps RevertSam could use an error message indicating mixed PE and SE reads and ask users to instead `OUTPUT_BY_READGROUP`. Alternatively, RevertSam could be made readgroup aware and handle each differently.

**Comment by jabbarish** [comment]
@sooheelee  We believe, your last proposed solution for the described error was already done in the following commit:
https://github.com/broadinstitute/picard/commit/b52e5ceede94903753c537db3123a7b95c7b773b

Please, check it.

**Comment by vdauwera** [comment]
@ZLyanov It looks like that commit does indeed address this request. Has the commit been pull-requested yet?

**Comment by ZLyanov** [comment]
@vdauwera  Yes, it was merged into the master earlier: https://github.com/broadinstitute/picard/pull/559

**Comment by sooheelee** [comment]
Thanks for letting us know @ZLyanov.

**Comment by vdauwera** [comment]
Great, thanks!

**Comment by sooheelee** [comment]
Update [doc](http://gatkforums.broadinstitute.org/gatk/discussion/6484/how-to-generate-an-unmapped-bam-from-fastq-or-aligned-bam#latest) to reflect change. Comment reads:

---
## Update to RevertSam

An issue described by [this forum question](http://gatkforums.broadinstitute.org/gatk/discussion/7814/error-mate-unmapped-flag-should-not-be-set-for-unpaired-reads-after-revertsam/p1) has been fixed by a Picard repo code change documented [here as a pull request](https://github.com/broadinstitute/picard/commit/b52e5ceede94903753c537db3123a7b95c7b773b) and [here as the related github issue](https://github.com/broadinstitute/picard/pull/559). The effect of this code change is that when encountering mate-missing reads in a PE data file, RevertSam will now remove all mate information and thereby effectively turn mate-missing records into SE reads.
