### ISSUE TITLE
CollectOxoGMetrics combined OXIDATION_Q score

### ISSUE THREAD

**Issue by dekling** [broadinstitute/picard#584]
One of our user's asked on the Forum whether it would be possible to merge the 16 CONTEXT-specific OXIDATION_Q scores into a single scalar score.  

Although I responded that I was not sure how valuable this would be, I defer to people that use this more than I to make that determination.

**Comment by meganshand** [comment]
Perhaps I don't understand what the user is asking for, but if you set CONTEXT_SIZE to 0 I would think that would result in a single score.

**Comment by dekling** [comment]
I could be wrong, but I think they are looking for an overall score for all of the different contexts, perhaps weighted by the frequencies of the different possible trinucleotide groups.

**Comment by dekling** [comment]
Yes.  The user has confirmed they are interested in a weighted average Q-score that sums over all of the different context-specific Q-scores.

**Comment by yfarjoun** [comment]
In that case Megan is correct...choose context size =0 and that's what
you'll get. but it's almost useless...

**Comment by dekling** [comment]
OK.  Thanks.
