### ISSUE TITLE
Update picard README for gradle

### ISSUE THREAD

**Issue by droazen** [broadinstitute/picard#590]
The Picard README needs instructions for building/testing using gradle, and setting up an IntelliJ project. The htsjdk README (https://github.com/samtools/htsjdk/) already has full instructions, and the relevant sections could probably be copied to the Picard README with slight modifications.

**Comment by droazen** [comment]
@jacarey Would you have time to do this, since you're most familiar with the new build system?

**Comment by droazen** [comment]
In response to a request from @kbergin

**Comment by droazen** [comment]
This is becoming urgent -- if I have time at the end of today I'll attempt it.

**Comment by jacarey** [comment]
@droazen Sorry I haven't had time to work on this. It is #3 on my priority list right now.

**Comment by nh13** [comment]
@jacarey any update on this?

**Comment by droazen** [comment]
@nh13 Full gradle instructions added to Picard README

**Comment by nh13** [comment]
👍 how about that picard.jar?
