### ISSUE TITLE
How to build the Picard JAR without running tests

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#601]
It is really useful to quickly build a picard jar while developing a new tool or feature.  Any idea with gradle how to do this?  Also the README needs an update as I keep using the ant build to figure out what gradle commands to use.

Thanks for any help you could offer @droazen @lbergelson @jacarey.

**Comment by fleharty** [comment]
I do
./gradlew shadowJar

**Comment by nh13** [comment]
`ant -lib lib/ant all` gives
```
     [echo]         build a jar that packages all of htsjdk's dependencies in a single jar
     [echo]         ./gradlew shadowJar
```
That should probably be updated as well as the README.  Can the person who moved us to the gradle build update the README?  It seems like it should have gone hand in hand.

**Comment by fleharty** [comment]
One thing that would be nice to have in the Picard build is a "current" jar.  It produces one that has a hash in the name.  It would be nice to have a constant place.

**Comment by nh13** [comment]
Or just `picard.jar` like it was previously.

**Comment by droazen** [comment]
https://github.com/broadinstitute/picard/issues/590

**Comment by nh13** [comment]
Closing in favor of #590, thanks @droazen for the link.
