### ISSUE TITLE
CollectMultipleMetrics needs a doc update 

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#609]
The list of available modules is hard-coded and out of date. It would be best to create it on the fly from the enum.

**Comment by yfarjoun** [comment]
take a look at the code. the USAGE string has the programs hard-coded and it should be build programmatically from the list of values in the ENUM.

**Comment by kasont** [comment]
The Usage string needs to be constant. Implementing this makes it inconstant requiring things to be brought in before the full text is created, subsequently errors appear.

**Comment by yfarjoun** [comment]
in that case, please simply update it to include all the PROGRAMS that currently exist...

**Comment by kasont** [comment]
This look good? https://github.com/broadinstitute/picard/pull/626 @yfarjoun
