### ISSUE TITLE
Build should produce a real file named picard.jar

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#617]
See requests on https://github.com/broadinstitute/picard/issues/601.

**Comment by droazen** [comment]
`./gradlew shadowJar` will build a Picard jar -- it gets put into `build/libs`. Is this not what you mean?

**Comment by droazen** [comment]
Ah I see -- you want a jar or link actually named `picard.jar`. Updated the title of the ticket to clarify this.

**Comment by nh13** [comment]
I don't want a symlink, I want a real file.

**Comment by droazen** [comment]
Having the version in the file name is very useful, however -- a symlink to the actual jar seems like a good compromise to make everyone happy, no? Or can you explain why a symlink wouldn't work for you?

**Comment by nh13** [comment]
Oh, definitely lets not get rid of the version in the file name for the versioned jar.  I frequently switch branches in development, or use various picard builds in different locations, and so I want a consistent name that I can rely upon when it is built, which is in some cases not done by me.  

Why not a symlink?  Since then copy utilities need to be given options to follow symlinks, which is a problem if we are batch copying in some cases. Why not have a versioned JAR and a picard-current.jar or picard.jar?
