### ISSUE TITLE
Reordersam bug?

### ISSUE THREAD

**Issue by dthach1** [broadinstitute/picard#619]
Hello,

```
When I ran ReorderSam to fix the header of my BAM file to that of the one for HG19 in GATK, I get error below.  I also attached an example BAM file.
```

[Wed Jul 13 20:52:15 UTC 2016] picard.sam.ReorderSam done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=760217600
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
    at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
    at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:503)
    at picard.sam.ReorderSam.doWork(ReorderSam.java:124)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
' returned non-zero exit status 1

My original BAM header looks like this:

@HD    VN:1.0    SO:coordinate
@SQ    SN:chr1    LN:249250621
@SQ    SN:chr2    LN:243199373
@SQ    SN:chr3    LN:198022430
@SQ    SN:chr4    LN:191154276
@SQ    SN:chr5    LN:180915260
@SQ    SN:chr6    LN:171115067
@SQ    SN:chr7    LN:159138663
@SQ    SN:chr8    LN:146364022
@SQ    SN:chr9    LN:141213431
@SQ    SN:chr10    LN:135534747
@SQ    SN:chr11    LN:135006516
@SQ    SN:chr12    LN:133851895
@SQ    SN:chr13    LN:115169878
@SQ    SN:chr14    LN:107349540
@SQ    SN:chr15    LN:102531392
@SQ    SN:chr16    LN:90354753
@SQ    SN:chr17    LN:81195210
@SQ    SN:chr18    LN:78077248
@SQ    SN:chr19    LN:59128983
@SQ    SN:chr20    LN:63025520
@SQ    SN:chr21    LN:48129895
@SQ    SN:chr22    LN:51304566
@SQ    SN:chrX    LN:155270560
@SQ    SN:chrY    LN:59373566
@SQ    SN:chrM    LN:16571
@PG    ID:bowtie2    PN:bowtie2    VN:2.2.5    CL:"/usr/local/bowtie2-2.2.5/bowtie2-align-s --wrapper basic-0 -p 20 --sensitive -x /lgenomes/hg19/hg19 -S /data/scratch/RPRxW5/R1_BC008_GAGTAGAG_trimmed.sam -U /data/scratch/RPRxW5/R1_BC008_GAGTAGAG_trimmed.fq"

Thanks!!

DT

[R1_BC008_GAGTAGAG_trimmed_hg19.sorted.markdup.bam.gz](https://github.com/broadinstitute/picard/files/404211/R1_BC008_GAGTAGAG_trimmed_hg19.sorted.markdup.bam.gz)

**Comment by yfarjoun** [comment]
please ask on the GATK forum http://gatkforums.broadinstitute.org/gatk/
