### ISSUE TITLE
MergeBamAlignment and its CLIP_OVERLAPPING_READS option

### ISSUE THREAD

**Issue by danielvo** [broadinstitute/picard#631]
Hello,

I have tested Picard versions 2.6.0 and 2.5.0 and I wonder whether the "CLIP_OVERLAPPING_READS" option of the "MergeBamAlignment" tool is taking effect. In the output BAM file, I am still seeing overlapping paired reads (with no clipping introduced). Are there some specific conditions at which the clipping is not applied even when enabled?

With best regards,
Daniel

**Comment by yfarjoun** [comment]
Can you give an example of a read pair you get in the output (position and
cigar only) that you think should be clipped but isn't?

**Comment by danielvo** [comment]
Thank you for the quick feedback!

Here is an example:

(...):8:2209:8184:46637      163     7       2566743 60      101M    =       2566783 141 (...)
(...):8:2209:8184:46637      83      7       2566783 60      101M    =       2566743 -141 (...)

**Comment by danielvo** [comment]
And here is the command that was used to generate my output:

${JAVA} -Xmx32G -Djava.io.tmpdir=./TMP -jar ${PICARD26} SamToFastq \
  I=./${F_NAME_BASE}_MarkIlluminaAdapters.bam \
  FASTQ=/dev/stdout \
  CLIPPING_ATTRIBUTE=XT \
  CLIPPING_ACTION=2 \
  INTERLEAVE=true \
  NON_PF=true | \
bwa mem -M -t 10 -p ${GENREF} /dev/stdin | \
${JAVA} -Xmx32G -jar -Djava.io.tmpdir=./TMP ${PICARD} MergeBamAlignment \
  R=${GENREF} \
  UNMAPPED_BAM=./${F_NAME_BASE}_FastqToSam.bam \
  ALIGNED_BAM=/dev/stdin \
  O=./${F_NAME_BASE}_MergeBamAlignment.bam \
  CREATE_INDEX=true \
  ADD_MATE_CIGAR=true \
  CLIP_ADAPTERS=false \
  CLIP_OVERLAPPING_READS=true \
  INCLUDE_SECONDARY_ALIGNMENTS=true \
  MAX_INSERTIONS_OR_DELETIONS=-1 \
  ATTRIBUTES_TO_RETAIN=XS

**Comment by vdauwera** [comment]
@danielvo I believe this may have been fixed by a recent PR (#709). Please try the latest version of Picard on your data and reopen this issue if the problem persists.
