### ISSUE TITLE
CollectWgsMetricsWithNonZeroCoverage plot not working

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/picard#632]
`wgsHistogram.R` assumes that the metrics file contains a histogram, but the histogram isn't there, so the R code throws an error and fails the program (it does create a metrics file, however). @nh13, if you could tell me what histogram format the R code expects (e.g. it seems to expect that histogram has third and forth columns named 'count_WHOLE_GENOME' and 'count_NON_ZERO_REGIONS.' ), I'd be happy to fix the java code.

Also, CollectWgsMetricsWithNonZeroCoverage in master branch throws a nullpointer early on. The fix is simple (call `super.doWork()` before getting `readGroups`) and is in my branch.

**Comment by vdauwera** [comment]
@takutosato Is this still a thing or has it been fixed?

**Comment by takutosato** [comment]
I think it's been fixed.
