### ISSUE TITLE
Picard CleanSAM memory issue (?)

### ISSUE THREAD

**Issue by cacampbell** [broadinstitute/picard#638]
Hello, 

This seems like such a simple issue to me, but it doesn't really make sense. I have been trying to run CleanSAM (Picard 2.5) on a SAM file ~3.5GB (one flowcell) and have continually run out of memory at increasingly implausible amounts. 

I have tried -Xmx64g, -Xmx100g, -Xmx200g, -Xmx300g, and even -Xmx400g for a few runs, and have gotten the same type of result each time:

```
[Thu Aug 25 12:30:21 PDT 2016] picard.sam.CleanSam INPUT=Mapped_Pila_Split/YD1/YD1_pe.split.ah.sam OUTPUT=Mapped_Pila_Split_CS/YD1/YD1_pe.split.ah.clean.sam TMP_DIR=[/home/cacampbe/tmp]    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Thu Aug 25 12:30:21 PDT 2016] Executing as [user]@[host] on Linux 3.13.0-36-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26; Picard version: 2.6.0-SNAPSHOT
[Thu Aug 25 13:06:30 PDT 2016] picard.sam.CleanSam done. Elapsed time: 36.15 minutes.
Runtime.totalMemory()=106121134080
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
       	at java.util.Arrays.copyOf(Arrays.java:3332)
       	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
       	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
       	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
       	at java.lang.StringBuilder.append(StringBuilder.java:136)
       	at htsjdk.samtools.SAMTextHeaderCodec.advanceLine(SAMTextHeaderCodec.java:131)
       	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:86)
       	at htsjdk.samtools.SAMTextReader.readHeader(SAMTextReader.java:200)
       	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:63)
       	at htsjdk.samtools.SAMTextReader.<init>(SAMTextReader.java:73)
       	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:319)
       	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:145)
       	at picard.sam.CleanSam.doWork(CleanSam.java:81)
       	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
       	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
       	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

The command used would be something like this (not exactly, but same parameters):

```
echo '#!/usr/bin/env bash
java -Xms108G -Xmx114G -Djava.io.tmpdir=~/tmp -jar ~/.prog/picard-tools-2.5.0/picard.jar CleanSam INPUT=Mapped_Pila_Split/YD1/YD1_pe.split.ae.sam TMP_DIR=~/tmp OUTPUT=Mapped_Pila_Split_CS/YD1/YD1_pe.split.ae.clean.sam && java -Djava.io.tmpdir=~/tmp -Xms108G -Xmx114G -jar ~/.prog/picard-tools-2.5.0/picard.jar FixMateInformation I=Mapped_Pila_Split_CS/YD1/YD1_pe.split.ae.clean.sam O=Mapped_Pila_Split_CS/YD1/YD1_pe.split.ae.clean.sort.sam TMP_DIR=~/tmp SO=coordinate && samtools view -@ 14 -m 8G -bS Mapped_Pila_Split_CS/YD1/YD1_pe.split.ae.clean.sort.sam > Mapped_Pila_Split_CS/YD1/YD1_pe.split.ae.clean.sort.bam' | sbatch --mem=120G --ntasks=1 --cpus-per-task=14 --partition=bigmemh --job-name=Pwal_CS_YD1_pe.split.ae.sam --mail-user=[email] --mail-type=BEGIN,FAIL,END --output=Pwal_CS_YD1_pe.split.ae.sam_output --error=Pwal_CS_YD1_pe.split.ae.sam_error
```

I have noticed that these same jobs work fine in other projects, using less memory. Could this mean that the SAM file is invalid somehow?

The reference genome used for mapping (if relevant) is ~40G, 50,000,000 scaffolds.

**Comment by cacampbell** [comment]
Any ideas? Anyone?

**Comment by nh13** [comment]
My guess is the number of contigs in the header is too large. Could you try ValidateSamFile to see if it makes it through? Could you post the SAM header plus a few reads somewhere?

**Comment by cacampbell** [comment]
Here is a Header:

[Link to EnCN_pe.header.sam](https://ucdavis365-my.sharepoint.com/personal/cacampbell_ucdavis_edu/_layouts/15/guestaccess.aspx?guestaccesstoken=0yU1CYWk9YuK8bnHRrCdYrwaDYGD6MbcARlRzsqoBiw%3d&docid=184b40c681d144633b576ffb369e52139&rev=1)

And here is 80 lines of the headerless sam file:

[Link to EnCN_pe.80_lines.sam](https://ucdavis365-my.sharepoint.com/personal/cacampbell_ucdavis_edu/_layouts/15/guestaccess.aspx?guestaccesstoken=HW6WonV%2b1slFaiTPmXLwbzNhU%2bwXO06GzyfTYvqKLpA%3d&docid=1e55db121b8414257ad1c128d34b952ec&rev=1)

At modest amounts of memory, ValidateSamFile also runs out of memory -- I am running it with a large amount of memory now to see what happens.

**Comment by nh13** [comment]
Thanks for uploading the data.  I can't even get `ViewSam` to load that many contigs (58M+), so unfortunately it looks like there are just too many contigs in that one file.  It will be difficult for you to use downstream tools (like Picard) to process this SAM file too.  Without understanding your application a little better, for example if there is a way to partition your data by contig/scaffold, I can't give you much more advice.

**Comment by cacampbell** [comment]
Thanks -- I will reassess. We will probably subset the genome into relevant scaffolds and then try again.
