### ISSUE TITLE
installing picard-2.6.0

### ISSUE THREAD

**Issue by peijiamail** [broadinstitute/picard#667]
Hi,

 I have a trouble with installing picard-2.6.0.
 When I execute the command ./gradlew, the result shows the below.

 FAILURE: Build failed with an exception.
- Where:
  Build file '/opt/broadinstitute-picard-679ea0d/build.gradle' line: 20
- What went wrong:
  An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version:
  
  > Failed to apply plugin [id 'org.ajoberstar.grgit']
  > One of setGitDir or setWorkTree must be called.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug opti
  
  BUILD FAILED
  
  How do I solve the problem?
  Thanks.

**Comment by maarten-k** [comment]
I advice if you want to **install** picard, just grab a copy from https://github.com/broadinstitute/picard/releases.

Without any technical background information it is impossible to sort this out.

**Comment by yfarjoun** [comment]
try asking for help on the GATK forum http://gatkforums.broadinstitute.org/gatk/
