### ISSUE TITLE
shallow copy of AbstractAlignmentMerger results in bugs

### ISSUE THREAD

**Issue by chetui** [broadinstitute/picard#668]
Hi all,

I suspect the following code in AbstractAlignmentMerger.java has a shallow copy bug:

```
    private SAMRecord clone(final SAMRecord rec) {
        try {
            return (SAMRecord) rec.clone();
        } catch (CloneNotSupportedException e) {
            throw new PicardException("Should never happen.");
        }
    }
```

AbstractAlignmentMerger.clone() is used for creating output buffers (firstToWrite, secondToWrite). After some changes on these buffers, they would be added into the output queue.  

While the AbstractAlignmentMerger.clone() function is actually a shallow copy. It would not copy bases (mReadBases) or qualities (mBaseQualities) data. If there are multiple alignments for a read (pair), they would share the same bases or qualities data. Later changes (such as reverse complement) on output buffer would affect the data which is already in the output queue.   

The SAMRecord structure actually has a deepCopy() function to do deep copy. I guess this function is actually the one that you guys want.  

A related issue I encounter is: I find the sam records have the illegal format sometimes. For example, in one sam record, its bases are not reverse complement while its qualities are reverse complement. It seems to be an illegal format of SAM. This bug may relate to the shallow copy bug described above. Because when I use SAMRecord.deepCopy() to replace SAMRecord.clone(), the illegal format would disappear.

Following is the code I use to fix above bugs. It works well in my dataset:

```
   private SAMRecord clone(final SAMRecord rec) {
        return (SAMRecord) rec.deepCopy();
   }
```

Thanks,
Xinjie Yu

Engineer
Ningbo Shufang Information Technology Co., Ltd.
http://shufangkeji.com/en/

**Comment by meganshand** [comment]
I believe this is the same thing that was observed in #518. There is an open PR to resolve this issue: #663

**Comment by chetui** [comment]
Yes. The commit (b78ca137e50e98a285a45c795299881ee4d9cfee) in #663 seems to resolve this issue.  
I will try that commit in my dataset to verify it later.

**Comment by meganshand** [comment]
@chetui The fix has been merged into master and should be included in the next release. Thanks for reporting this!
