### ISSUE TITLE
GAKT realigner

### ISSUE THREAD

**Issue by peijiamail** [broadinstitute/picard#672]
Hi,

I run rhino data according to the workflows ( http://www.htslib.org/workflow/ ).
I use the below command
 "java -Xmx2g -jar GenomeAnalysisTK.jar -T RealignerTargetCreator -R ref.fa -I lib_sorted.bam -o lib.intervals -nt INT"
 to run the data, but the program stop when running the step ( INFO 11:29:09,811 GenomeAnalysisEngine - Strictness is SILENT ).
But, I don't have the trouble when running spoonbill data.
Can anyone tell me how to solve the problem?
Thanks.

**Comment by vdauwera** [comment]
Cross-posted on the GATK forum; we'll answer there.
