### ISSUE TITLE
Command Line Overview repeated itself 4 times

### ISSUE THREAD

**Issue by JohnMCMa** [broadinstitute/picard#674]
I have noticed the tool-specific documentations in the [Command Line Overview](http://broadinstitute.github.io/picard/command-line-overview.html) seems to have repeated itself 4 times.

**Comment by vdauwera** [comment]
We've noticed that too -- this has appeared then gone away then reappeared depending on the release, with different repeat counts each time. I'm pretty sure it's a technical glitch in the generation of the documents but right now we don't have time to hunt down the cause.

**Comment by droazen** [comment]
I've fixed this -- closing.

**Comment by droazen** [comment]
(Fixed by following the official release instructions for Picard here: https://github.com/broadinstitute/picard/wiki/How-to-release-Picard)
