### ISSUE TITLE
Cannot Build Picard in Shared Cluster Computing Environment

### ISSUE THREAD

**Issue by jejacobs23** [broadinstitute/picard#677]
Hello,

I'm having trouble getting the build to run correctly on my institutions Cluster Computing Environment.  

Here is the error message I get when I attempt to build:

```
[jacojam@exalab3 picard]$ ./gradlew shadowJar

FAILURE: Build failed with an exception.

* Where:
Build file '/home/exacloud/lustre1/BioDSP/users/jacojam/programs/picard/build.gradle' line: 56

* What went wrong:
A problem occurred evaluating root project 'picard'.
> Cannot invoke method getURLs() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 35.05 secs
```

Our Service Desk did some testing with an expanded OpenJDK installation and with Oracle Java. The gradlew script went further, but it still failed:

```
Download ... [lots of stuff] ...
Download https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.3-rc3/snappy-java-1.0.3-rc3.jar
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Function not implemented
> Function not implemented
```

They told me that the failure comes by way of using gradle during the compile process, as far as they could tell:
- Exception is:

```
org.gradle.api.UncheckedIOException: java.io.IOException: Function not implemented
    at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
    at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:83)
    at org.gradle.cache.internal.DefaultCacheAccess.onStartWork(DefaultCacheAccess.java:349)
    at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:187)
    ...

```

You can get to the same point by changing your environment a bit:

```
# option one: use OpenJDK
export JAVA_HOME=/usr/lib/jvm/jre-1.8.0
export PATH=${JAVA_HOME}/bin:$PATH

# option two: use Oracle JDK
export JAVA_HOME=/opt/installed/jdk-1.8
export PATH=${JAVA_HOME}/bin:$PATH

```

We've reached the limit of what the Service Desk can do and they recommended that I contact you directly to see if there is any way to fix this issue.  

Thanks,

James E. Jacobs MD, MPH

**Comment by vdauwera** [comment]
@jejacobs23 Sorry for the late response. We typically respond faster if you post your issue in the GATK support forum at http://gatkforums.broadinstitute.org.

If you still need to be able to build Picard in your environment, make sure you're using the latest version of Java, and post in the forum linked above. However, be aware that if you just need a prebuilt jar of Picard, you can get it [here](https://github.com/broadinstitute/picard/releases). Unless your platform has exotic requirements, it should just work.
