### ISSUE TITLE
NestedOptions command line argument annotation usage

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/picard#678]
It looks like there are no references to the [NestedOptions](https://github.com/broadinstitute/picard/blob/e7d6c8f8cf110e6f74edefdef86fba64d01ad0fa/src/main/java/picard/cmdline/NestedOptions.java) command line argument annotation in the Picard code itself, so I'd like to propose it as a candidate for removal. Is anyone in the community aware of any downstream consumers that are dependent on this class/feature ?

**Comment by tfenne** [comment]
I had no idea this even existed!  👍

**Comment by vdauwera** [comment]
Is this still a thing, @cmnbroad ? It sounds like no one objected...

**Comment by cmnbroad** [comment]
Since there have been no objections, we'l remove this in a future release.
