### ISSUE TITLE
calculateHSmetrics picard

### ISSUE THREAD

**Issue by Rahel14350** [broadinstitute/picard#686]
@splaisan @yfarjoun 
I did try to build the bait and target interval (using one time the headers from .bam file and one time with headers from mm10.dict) like this: 
m=0
for i in 'cat mm10_list.interval_list' ; \
do echo "$i"; echo "MPMPMP$m"; m=$(($m + 1)) ; \
done > mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/\nMPMPMP/\ttarget_/g" mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/\r\t/\t/g" mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/:/\t/g" mm10_list.interval_list.tmp2
perl -0777 -i -pe "s/-/\t/g" mm10_list.interval_list.tmp2
cat header.txt mm10_list.interval_list.tmp2 > mm10_list.interval_list.picard

but I have still error while running calculateHSmetrics. Would you please let me know if the way I am building the bait and target files is correct? and I am using the same file for bait_interval and also target_interval, is this also correct?
Many thanks in advance,
Rahel

**Comment by yfarjoun** [comment]
This is the kind of problem that should be brought up in the GATK forum.
