### ISSUE TITLE
incorrect adapter sequences in IlluminaUtils.java?

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#691]
It seems that the DUAL_INDEX AdapterPair in IlluminaAdapterPair has a typo in it. as far as I can tell from the [documentation](http://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences_1000000002694-01.pdf) and from manually inspecting soft-clipped bases in short inserts the first sequence should be 

AATGATACGGCGACCACCGAGATCT**ACAC**NNNNNNNNACACTCTTTCCCTACACGACGCTCTTCCGATCT
not 
AATGATACGGCGACCACCGAGATCTNNNNNNNNACACTCTTTCCCTACACGACGCTCTTCCGATCT

These four missing bases are probably causing some trouble in evaluating PCT_ADAPTER (In AlignmentSummaryMetrics) and other output issues (though they do not seem to be affecting clipping).

My question is whether we should change the sequence to the correct one, or add it as another option?

If no-one cares, I would prefer to have the right sequence there.

**Comment by nh13** [comment]
Isn't `GATCT` the linker?  So we should start the Ns after?
http://benthamopen.com/contents/supplementary-material/TOMICROJ-6-29-SD1.pdf
Do you have a reference?

**Comment by yfarjoun** [comment]
I have documentation to the sequences included in the original post. I don't know about the "linker", but I thought that the point is to list the sequences of bases as they would be sequenced if one were to sequence into the adapter...and in that case after reading through the sample-barcode, you would reach the ACAC rather than the GATCT.

**Comment by yfarjoun** [comment]
No-one seems to care, so I'll fix the sequence. perhaps there will be more opinions with a PR...

**Comment by nh13** [comment]
👍

**Comment by nh13** [comment]
This should also be fixed in hellbender/gatk/etc. if needed.

**Comment by yfarjoun** [comment]
I don't think that these have specific sequences in them...but I'll check.
thanks.

**Comment by vdauwera** [comment]
@yfarjoun @nh13 Sounds like this has been addressed and can be closed?

**Comment by yfarjoun** [comment]
yes.

**Comment by init-js** [comment]
I think that illumina link could be updated to: the [Feb 2019 version](https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences-1000000002694-10.pdf ). 

I'm processing a mixture of fastqs produced with different versions of TruSeq kits, and I was trying to determine whether I should pass a custom adapter string to `MarkIlluminaAdapters`.

The illumina document gives adapter strings for Read1: `AGATCGGAAGAGCACACGTCTGAAC`, and Read2: `AGATCGGAAGAGCGTCGTGTAGGGA`, which don't seem to be featured, at least not verbatim, in the [picard utils adapters file](https://github.com/broadinstitute/picard/blob/1531278515aaf39c9049b5792ae569b92326dd90/src/main/java/picard/util/IlluminaUtil.java#L141 ). Is there something special about the way these constants are specified?

**Comment by yfarjoun** [comment]
I don't think that it's appropriate here. the original issue was about an error in the Adapter listed in the adapters file, while your issue is either about how to use a custom adapter, or about adding a new adapter...I suggest you open a new ticket.

**Comment by init-js** [comment]
My apologies.

moved to [Issue 1299](https://github.com/broadinstitute/picard/issues/1299 ) .
