### ISSUE TITLE
Usage example for SamToFastq has wrong case (SamToFASTQ instead of SamToFastq)

### ISSUE THREAD

**Issue by IleaHeft** [broadinstitute/picard#698]
### Tool(s) involved
picard SamToFastq 

### Description 
Usage example provided at (https://broadinstitute.github.io/picard/command-line-overview.html#SamToFastq) shows SamToFASTQ - which does not work, instead of SamToFastq, which does work.  Recommend updating usage example accordingly.  

----

**Comment by vdauwera** [comment]
Thanks for reporting this, we'll get it fixed for the next release.

**Comment by vdauwera** [comment]
Fixed in https://github.com/broadinstitute/picard/pull/736
