### ISSUE TITLE
Cannot index bam from reference with any contig > 512M

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#706]
### Affected tool(s)
BuildBamIndex, SortSam, Markduplicates

### Affected version(s)
Latest public release version

### Description 

Picard Tools fail to index bam files if reads were aligned with a start position > 512M. This is a known issue documented in the [FAQ](http://broadinstitute.github.io/picard/faq.html), which throws a java exception "java.lang.ArrayIndexOutOfBoundsException". 

The problem is that biology refuses to comply with this arbitrary limitation, especially plants. 

Also, samtools faidx can index these files just fine. So why can't we?

#### Steps to reproduce

Here's a wheat reference genome that has sufficiently large contigs to trigger the problem: ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/triticum_aestivum/dna/Triticum_aestivum.TGACv1.dna_sm.toplevel.fa.gz

There is short read data [here](https://trace.ddbj.nig.ac.jp/DRASearch/study?acc=SRP037990) but I couldn't find publicly shared bams. Will go back to the original user report in the GATK forum to ask if we can share their test bam.

**Comment by vdauwera** [comment]
@SilinPavel Here is the issue for the large contig problem. I'm still hunting down some appropriate test data.

**Comment by ZLyanov** [comment]
@vdauwera Thank you!  We will try to resolve it ASAP.

**Comment by SilinPavel** [comment]
@vdauwera Thank you! We hope that we can help with it.

**Comment by SilinPavel** [comment]
We have investigated the problem.
There is a constant in GenomicIndexUtils.java:
public static final int BIN_GENOMIC_SPAN = 512*1024*1024;

We think that increasing its value might be a solution (or a first step to a solution).
We are ready to try this change, however we need test BAM to check the effect.
@vdauwera could you provide us with test BAM?
Also it would be helpful if  the user(s) could share their logs with us.

**Comment by vdauwera** [comment]
@SilinPavel Sorry for the late response. The user hasn't got back to me with a test bam, so I'm going to try to find some public data (this is an organism we don't normally work with).

**Comment by wangguangya60** [comment]
Just to reflect that this issue still exists in picard and GATK4. Another thing is that sambamba now support to create .bai indexes for large chromosomes. Really hope for any progress in this field.

**Comment by yfarjoun** [comment]
I think that this is a htsjdk/hts-spec issue. please resolve there first.
