### ISSUE TITLE
Overlapping reads are not clipped in MergeBamAlignment if soft-clipping is present

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#708]
If a record (ex. 127M14S below) already has soft-clipping and needs to be further soft-clipped, the calculation for "from where" to soft-clip in the read does not take into account the already soft-clipped bases.  It calculates the amount one read goes past the other based on the soft-clipped ends (or starts), but uses the full read length (not the aligned portion of the read).

See:
https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/sam/AbstractAlignmentMerger.java#L608-L609
https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/sam/AbstractAlignmentMerger.java#L614-L615

genome: hg38DH
test SAM records:
```
READ    83  chr1    114713831   60  22S119M =   114713831   -119    NCTCTTCCGATCTGACCTCAATTATTATTGATGGCAAATACACAGAGGAAGCCTTCGCCTGTCCTCATGTATTGGTCTCTCATGGCACTGTACTCTTCTTGTCCAGCTGTATCCAGTATGTCCAACAAACAGGTTTCACCA   #{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{
READ    163 chr1    114713831   60  127M14S =   114713831   119 TATTATTGATGGCAAATACACAGAGGAAGCCTTCGCCTGTCCTCATGTATTGGTCTCTCATGGCACTGTACTCTTCTTGTCCAGCTGTATCCAGTATGTCCAACAAACAGGTTTCACCATATATAACTAGATCGGAAGAGC   {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{
```

**Comment by vdauwera** [comment]
Looks like this was fixed by #709. Reopen if I'm wrong.
