### ISSUE TITLE
Why I get insert size from CollectInsertSizeMetrics is less than read length?

### ISSUE THREAD

**Issue by AJ23ZX** [broadinstitute/picard#720]
Hi,

I used picard 2.8.1 to stat insert size in a bam file. The command I used is:
java -jar /programs/picard.jar CollectInsertSizeMetrics I=/workdir/xz235/3T/282BAM/A6_HA5R1ADXX.bam R=/workdir/xz235/ref.fa O=/workdir/xz235/bamInsertsize/bamInsertsizeDoc/A6_HA5R1ADXX.insertSize.txt H=/workdir/xz235/bamInsertsize/bamInsertsizePdf/A6_HA5R1ADXX.insertSize.pdf

The result of output metrics file is like below:
MEDIAN_INSERT_SIZE = 168
MEAN_INSERT_SIZE = 180.17965

Both of these results are much less than read depth:201.
I transformed to the format of Pindel, there is also an error occured:
Error: the insert size is only 180 while the read length is 201 201
in paired end sequencing, the insert size is the total size of the fragment to be sequenced, with a read length of 100 bp the entire fragment may for example look like

|----100 bp: first read of the read pair--|-------------------300 bp: unsequenced DNA---------------------|----100 bp: second read of the read pair--|
<-----------------------------------------------------------insert size=500 ------------------------------------------------------------------------->

Can you help me to solve it? Thank you.

Xiao

**Comment by yfarjoun** [comment]
Please post usage questions in the GATK forum as instructed in the "getting started" doc. Github Issues are reserved for discussions about the code and confirmed bug reports. Thank you.
