### ISSUE TITLE
Error installing picard-2.8.1

### ISSUE THREAD

**Issue by shlomita** [broadinstitute/picard#723]
Hi,
I need to install  picard-tools on CentOS 7.
When I run: ./gradlew shadowJar 
I got the error:
 ```
FAILURE: Build failed with an exception.

* Where:
Build file '/apps/src_7/shlomit/picard-tools/picard/build.gradle' line: 56

* What went wrong:
A problem occurred evaluating root project 'picard'.
> Cannot invoke method getURLs() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.736 secs

```

How can I install it?

**Comment by vdauwera** [comment]
Please post your issue in the GATK support forum here: http://gatkforums.broadinstitute.org/

**Comment by vdauwera** [comment]
Also, be aware you can get a prebuilt picard jar file [here](https://github.com/broadinstitute/picard/releases).
