### ISSUE TITLE
CollectMultipleMetrics does not work with RnaSeqMetrics

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#727]
... since `CollectRnaSeqMetrics` requires the `REF_FLAT` option which is not passed by `CollectMultipleMetrics`.  I am reporting this here in case others see the same issue.

**Comment by ale07alvarez** [comment]
Can CollectRnaSeqMetrics be used for RNAseq data?

**Comment by nh13** [comment]
@ale07alvarez yes it can.

From Broad support: "You can find answers to Picard tool error in the [GATK forum](http://gatkforums.broadinstitute.org/gatk). Please post your Picard usage questions to the GATK forum going forward."

**Comment by kbergin** [comment]
Didn't see this when I made the same bug ticket in late 2017, but that one (#999) has more discussion so I'll close this one in favor of that one.
