### ISSUE TITLE
BARCODE_TAG Mismatch Option

### ISSUE THREAD

**Issue by jhl667** [broadinstitute/picard#730]
### Tool(s) involved
_MarkDuplicates_

### Description
_Having the ability to mark as duplicate, molecular barcodes (as directed by BARCODE_TAG) that are attached to the same sequence but only differ by one (or any user-definable number) base, would reduce the reliance on external tools._

**Comment by fleharty** [comment]
This exists now in UmiAwareMarkDuplicatesWithMateCigar.
This tool has not been tested on RNA data, or other data where the paired ends are far apart.
Closing ticket until a more specific request is made.

**Comment by jhl667** [comment]
My apologies, I did not realize this tool existed!  I will perform some testing and reopen if necessary.
