### ISSUE TITLE
Minor but important ! - filenaming convention 

### ISSUE THREAD

**Issue by serine** [broadinstitute/picard#753]
Hi there, 

I noticed that you are keep switching betweem different file conventions for `.jar` file

It is either `picar-version.jar` or just `picard.jar`

Which ever way works best for you I'll adopt to that, but can you be consistent please?

It makes ansible deployment annoying, because I have edited ansible src everytime..

Thanks

**Comment by lbergelson** [comment]
Ah, sorry about that.  We'll try to stick to picard.jar I think unless anyone objects.

**Comment by serine** [comment]
That'll be great, Thanks heaps guys !

**Comment by lbergelson** [comment]
We'll try to keep it consistent.  It really should just be automated....  I've opened a ticket to track that  #754
