### ISSUE TITLE
GatherVCF crashes when a VCF to be gathered has no variants

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/picard#755]
### Affected tool(s)
GatherVCF

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest development/master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
Inputs attached.  some.vcf.gz has one variant, and none.vcf.gz has no variants

`java -Xmx1000m -jar ~/picard.jar GatherVcfs INPUT=some.vcf.gz INPUT=none.vcf.gz OUTPUT=boom.vcf.gz CREATE_INDEX=false`

#### Expected behavior
Should gather the VCFs without crashing ;)  Gathering a VCF that has no variants should just progress to the next VCF supplied

#### Actual behavior
`
[Fri Feb 17 12:19:34 EST 2017] picard.vcf.GatherVcfs INPUT=[some.vcf.gz, none.vcf.gz] OUTPUT=boom.vcf.gz CREATE_INDEX=false    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Fri Feb 17 12:19:34 EST 2017] Executing as kcibul@wm965-594 on Mac OS X 10.10.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14; Picard version: 1.137(c8c9f584d7042e98867ea3cfc355fb7b89acd2e6_1438018139) JdkDeflater
INFO	2017-02-17 12:19:34	GatherVcfs	Checking inputs.
INFO	2017-02-17 12:19:35	GatherVcfs	Checking file headers and first records to ensure compatibility.
INFO	2017-02-17 12:19:36	GatherVcfs	Gathering by copying gzip blocks. Will not be able to validate position non-overlap of files.
INFO	2017-02-17 12:19:36	GatherVcfs	Gathering /Users/kcibul/projects/dsde-p2/dsde-pipelines/genomes_in_the_cloud/joint_genotyping_workflow/some.vcf.gz
INFO	2017-02-17 12:19:36	GatherVcfs	Gathering /Users/kcibul/projects/dsde-p2/dsde-pipelines/genomes_in_the_cloud/joint_genotyping_workflow/none.vcf.gz
[Fri Feb 17 12:19:36 EST 2017] picard.vcf.GatherVcfs done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=257425408
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalStateException: Could not read available bytes from BlockCompressedInputStream.
	at picard.vcf.GatherVcfs.gatherWithBlockCopying(GatherVcfs.java:221)
	at picard.vcf.GatherVcfs.doWork(GatherVcfs.java:80)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
`

[some.vcf.gz](https://github.com/broadinstitute/picard/files/783881/some.vcf.gz)
[none.vcf.gz](https://github.com/broadinstitute/picard/files/784390/none.vcf.gz)

**Comment by kcibul** [comment]
Talking with @vdauwera , she said to "tag @ronlevine and say I asked if he could take a look".  Thanks!

**Comment by droazen** [comment]
As part of this, it would be good to determine whether this issue is specific to the Picard tool `GatherVcfs`, or whether a patch at the htsjdk level is required to, eg., `BlockCompressedInputStream`. It seems to me to depend on whether `BlockCompressedInputStream` is violating its contract in some way (eg., `available()` returning an incorrect value), or the tool just needs to do some additional special-casing.

**Comment by kcibul** [comment]
Good question David.  The error is thrown here:

https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/vcf/GatherVcfs.java#L225

On the condition

if (blockLength == 0 || read != blockLength)

So it might just be removing the requirement that the blockLength be non-zero (and understanding what the implications of that are!)

**Comment by yfarjoun** [comment]
https://github.com/broadinstitute/picard/issues/412

**Comment by nh13** [comment]
@kcibul looks like both VCFs you attached have variants.  Did you mean to attach `none.vcf.gz` vs `foo.vcf.gz`?  Also, did you check taht `none.vcf.gz` has a valid header but zero variant records?

**Comment by tfenne** [comment]
I think @nh13 is on the right track.  I just tried this locally with two bgzipped VCFs with records in them and two bgzipped VCFs that only contained the header and no variants, and it worked just fine.  Is it possible that one of the empty files is either not a valid gzip archive, or didn't contain a valid header?

**Comment by kcibul** [comment]
Damn, you're right nils.  I'm on a flight now but will attach the right ones as soon as I can

**Comment by kcibul** [comment]
They're definitely valid files from the test case.  Are you also requesting
a bgzipped file as the output so it invokes the block-copying logic?
Otherwise it does a standard copy, which works fine (but decompresses
everything and then we have to re-compress it)

- k

-------------------------------
Kristian Cibulskis
Engineering Director, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by kcibul** [comment]
btw -- i uploaded the examples here (some.vcf.gz and none.vcf.gz).  Can you repro with those?

**Comment by yfarjoun** [comment]
seem like this issue has more information, so I closed the other in favor of this one.

**Comment by tfenne** [comment]
@kcibul That's very strange.  Here's what I get with the files I've tested with:

```bash
tfenne@shinykat[20:28]:/tmp $ file ?.vcf.gz
1.vcf.gz: gzip compressed data, extra field
2.vcf.gz: gzip compressed data, extra field
3.vcf.gz: gzip compressed data, extra field
4.vcf.gz: gzip compressed data, extra field
tfenne@shinykat[20:28]:/tmp $ for file in ?.vcf.gz; do echo $file `gzcat $file | wc -l` `gzcat $file | egrep -v '^#' | wc -l`; done
1.vcf.gz 3520 95
2.vcf.gz 3489 64
3.vcf.gz 3425 0
4.vcf.gz 3425 0
tfenne@shinykat[20:28]:/tmp $ picard GatherVcfs I=1.vcf.gz I=2.vcf.gz I=3.vcf.gz I=4.vcf.gz O=gathered.vcf.gz
[Fri Feb 17 20:28:44 EST 2017] picard.vcf.GatherVcfs INPUT=[1.vcf.gz, 2.vcf.gz, 3.vcf.gz, 4.vcf.gz] OUTPUT=gathered.vcf.gz    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=true CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Fri Feb 17 20:28:44 EST 2017] Executing as tfenne@shinykat.local on Mac OS X 10.12.2 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_92-b14; Picard version: 2.8.3-2-gbce0086-SNAPSHOT
INFO	2017-02-17 20:28:44	GatherVcfs	Checking inputs.
INFO	2017-02-17 20:28:44	GatherVcfs	Checking file headers and first records to ensure compatibility.
INFO	2017-02-17 20:28:45	GatherVcfs	Gathering by copying gzip blocks. Will not be able to validate position non-overlap of files.
WARNING	2017-02-17 20:28:45	GatherVcfs	Index creation not currently supported when gathering block compressed VCFs.
INFO	2017-02-17 20:28:45	GatherVcfs	Gathering /private/tmp/1.vcf.gz
INFO	2017-02-17 20:28:45	GatherVcfs	Gathering /private/tmp/2.vcf.gz
INFO	2017-02-17 20:28:45	GatherVcfs	Gathering /private/tmp/3.vcf.gz
INFO	2017-02-17 20:28:45	GatherVcfs	Gathering /private/tmp/4.vcf.gz
[Fri Feb 17 20:28:45 EST 2017] picard.vcf.GatherVcfs done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=257425408
```

**Comment by kcibul** [comment]
Hey folks -- I think we can close this out.  I reran with the latest picard and it runs successfully.  I had been testing it with the production version of picard-private, which shows this problem... but since it's fixed in master... that ain't a Picard problem.

I would feel bad... but since this was a dupe of an open bug, I'll just view it as having helped Picard by closing that one ;)

**Comment by yfarjoun** [comment]
That's weird since picard and htsjdk are fairly uptodate in
picard-private...but perhaps you should open a ticket there...
