### ISSUE TITLE
HsMetrics Histogram for quality score bases count

### ISSUE THREAD

**Issue by renkyp** [broadinstitute/picard#769]
### Affected tool(s)
CollectHsMetrics

### Affected version(s)
picard-2.9.0-9-gb9978f5-SNAPSHOT-all

### Description 
 in TargetMetricsCollector.java, line 591, base quality of the base is reported as baseQualities[offset], but the "offset" does not take into account the start position of the alignment block. The actual value should be "qual". 

#### Expected behavior
 the quality score reported is not right and the histogram is skewed

**Comment by yfarjoun** [comment]
Thanks! I'm looking into it. This could definitely explain some interesting
behavior I saw....
