### ISSUE TITLE
SortSam hold output file and I can't delete it when exception is thrown

### ISSUE THREAD

**Issue by Fizol** [broadinstitute/picard#775]
### Affected tool(s)
picard.sam.SortSam

### Affected version(s)
Latest public release version 2.9.0

### Description 
Running the test:
```
    @Test
    public void bugTest() throws Exception {
        File input = temp.newFile();
        File output = temp.newFile("output");
        FileUtils.write(input, "not valid sam input");
        try {
            new SortSam().instanceMain(new String[]{
                    "I=" + input.getPath(),
                    "O=" + output.getPath(),
                    "SORT_ORDER=coordinate"});
        } catch (SAMFormatException ex) {}
        Files.delete(output.toPath());
    }
```
Last line throws:
```
java.nio.file.FileSystemException: AppData\Local\Temp\junit4286312902586687756\output: The process cannot access the file because it is being used by another process.
```

#### Steps to reproduce
It's given above.

#### Expected behavior
I should be able to delete the "output" file.

#### Actual behavior
the "output" file is used and I can't delete it.

As you can see I use your tool inside java application. 
**I suppose** that the problem is you don't close your writers if exception occurs. I don't know in how many places you don't call close() in the finally statement, I've tried only that one.

**Comment by yfarjoun** [comment]
cannot reproduce.
