### ISSUE TITLE
fastqtobam error

### ISSUE THREAD

**Issue by antoine4ucsd** [broadinstitute/picard#780]
Hi,

----

## Bug Report
I am facing problem with the fastqtosam tool. 
I used the following command:
**java -jar FastqToSam.jar F1=mydata.fastq O=mydata.bam SM=for_tool_testing** 

### Affected tool(s)
FastqToSam.jar

### Affected version(s)
- Latest public release version 

### Description 
I tried various quality format ('standard' or 'Illumina') but I still have the same following error message:

<img width="1274" alt="screen shot 2017-03-28 at 8 27 11 am" src="https://cloud.githubusercontent.com/assets/18502631/24413488/692f67d2-1390-11e7-94b3-82ba95660513.png">

----
## attachment
Input fastq file

[mydata.fastq.zip](https://github.com/broadinstitute/picard/files/876190/mydata.fastq.zip)

----
## Alternative
if it has to do with the fastq file input, is there a way to create bam file with artificial Qscore from fasta files?

----
thanks!

**Comment by nh13** [comment]
Your reads have leading and trailing dashes (`-`) along with bases.  That's whats causing the error.  You can convert them to "N" if you really want them there or remove them. 

Also, the Broad Institute's support says "You can find answers to Picard tool error in the [GATK forum](http://gatkforums.broadinstitute.org/gatk). Please post your Picard usage questions to the GATK forum going forward."

**Comment by antoine4ucsd** [comment]
thanks Nils,
I just tried with the attachment and the following command:

java -jar /Users/antoinechaillon/Documents/HIV/TOOLS/picard-tools-1.89/picard-tools-1.89/FastqToSam.jar F1=R1R2.fastq O=R1R2.bam SM=for_tool_testing QUALITY_FORMAT=Standard

I still get this error



I am trying to generate bam files from reads (originally in fasta format) with ‘artifical Q-score’ generated with my little script ‘fasta_to_fastq’
First step : create fastq file from source fasta file
Second step: convert fastq to bam file
Final step (my goal): use the bam file as input for haploclique (https://github.com/cbg-ethz/haploclique <https://github.com/cbg-ethz/haploclique>)

Would you suggest another way to do it?

thanks ++




Cheers,
antoine






Antoine Chaillon M.D., Ph.D.
Center For Aids Research (CFAR)
Division of Infectious Diseases,
UCSD & VA San Diego Healthcare System 
Stein Clinical Research Building #325
University of California San Diego 
9500 Gilman Drive
La Jolla CA, 92093-0679
(619) 928-1842

**Comment by vdauwera** [comment]
Antoine, you need to post your question in the GATK forum as Nils indicated.

**Comment by nh13** [comment]
Thanks Antoine in advance for posting it over at the GATK forum as my initial suggestion didn't work.

**Comment by antoine4ucsd** [comment]
I just did it
thanks again

a
