### ISSUE TITLE
FastqToSam error message needs to be more informative

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#781]
I've just answered this forum user about an error message in FastqToSam. The error message says `Exception in thread "main" java.lang.IllegalArgumentException: Bad  byte passed to charToCompressedBase: 62` and could be more informative by giving the line number of the data that is causing the error. In this user's case it is line 395ish.

---

Hi

I am trying to generate bam files from reads (originally in fasta format) with ‘artifical Q-score’ generated with the attached script ‘fasta_to_fastq’
First step : I created fastq file from source fasta file (R1R2.fasta attached)
Second step: I am trying to convert the R1R2.fastq file to bam file (here I am using FastqToSam command below)
Final step (my goal): use the bam file as input for haploclique (https://github.com/cbg-ethz/haploclique)

java -jar /Users/antoinechaillon/Documents/HIV/TOOLS/picard-tools-1.89/picard-tools-1.89/FastqToSam.jar F1=R1R2.fastq O=R1R2.bam SM=for_tool_testing 

I get this error (screenshot)

thoughts? alternative approach?
thanks for your help ++
a

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/9282/fastqtosam-error/p1

**Comment by ronlevine** [comment]
Yep, it's an bad base `<`, (ASCII 62) , line 200, in the input fasta. The read name is not followed by a carriage return. Besides the file line number, the ASCII representation would be nice too.

**Comment by sooheelee** [comment]
That's a great idea to include the offending character in the error message!

**Comment by ronlevine** [comment]
The exception originates from HTSJDK,from within `htsjdk.samtools.SamUtils.compressedBasesToBytes`.

**Comment by sooheelee** [comment]
Ron, does the htsjdk origin still allow us to get the line number and offending character in the error message?

**Comment by ronlevine** [comment]
@sooheelee That shouldn't be an issue.

**Comment by sooheelee** [comment]
Great.

**Comment by ronlevine** [comment]
It's a mess adding the line number. I plan to put the read name and the bad base in the exception message.

**Comment by sooheelee** [comment]
Alright. Just learned from an Agile games day how to be better about putting in my tickets. I need to be more open to allow our developers the freedom to make their best judgement calls.

**Comment by chandrans** [comment]
Can someone let the user know? @sooheelee @vdauwera ? Geraldine, I don't know about Picard changes and how they access them. I know you responded to a  user about this before, but I cannot find that thread.

**Comment by ronlevine** [comment]
@chandrans [Here](http://gatkforums.broadinstitute.org/gatk/discussion/9282/fastqtosam-error/p1) is the link to the forum thread. The code change adds the base and read name to the error message so that it's more informative. The user appears to be satisfied with @sooheelee's response.

**Comment by chandrans** [comment]
Thanks. It would be nice to let him/her know the better error message is in Picard now. I just don't know how they would access the change.

**Comment by ronlevine** [comment]
Soo Hee told the user what the problem is with their data and they are satisfied with her response. They will see the improved error message in the next Picard Release (unless want to clone and build picard from [GitHub](https://github.com/broadinstitute/picard).

**Comment by chandrans** [comment]
Perfect. I just wanted to know what to tell the user. I will tell them They will see the improved error message in the next Picard Release (unless want to clone and build picard from GitHub. Unless you want to tell them Ron?

**Comment by ronlevine** [comment]
@chandrans You can do it. You are the middle of a nice dialogue.
