### ISSUE TITLE
Documentation needs to describe Haploptype_map file better for Picard CrosscheckReadGroupFingerprints and CheckFingerprint

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#783]
Seems our current documentation does not describe acceptable input formats for this, e.g. VCF.

---

Hello,

In the picard CrosscheckReadGroupFingerprints command, it asks for a Haplotype_map file. What format does Haplotype_map file need to be in? If you have multiple BAM files with the same RG tag, would this command work?  If not, what is the best way to edit 6000+ BAM files to have unique RG tag names?  

Thank you.
Devin Porter

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/9289/picard-crosscheckreadgroupfingerprints/p1

**Comment by vdauwera** [comment]
Congratulations, it's all yours :)

**Comment by yfarjoun** [comment]
Sorry. I put the description in the private repository....here it is:

@Option(shortName = "H", doc = "Haplotype map to be used for
fingerprinting. FORMAT of Halotype map is, standard SAM header (with
one @HD and multiple @SQs) " +
        "followed by a tab-separated header line and lines describing
SNPs and Haplotype blocks. For example :" +
        "#CHROMOSOME    POSITION    NAME        MAJOR_ALLELE
MINOR_ALLELE    MAF         ANCHOR_SNP  PANELS" +
        "1              29478419    rs2503005   C               T
         0.483791    rs2230678   panel1" +
        "1              29497820    rs1994859   C               T
         0.483791    rs2230678   panel2" +
        "1              29500995    rs2486204   T               C
         0.484167    rs2230678         " +
        "1              29509603    rs2428556   C               T
         0.728976    rs2230679   panel1" +
        "" +
        "NOTE: SNPs listed with the same ANCHOR_SNP will be in the
same haplotype. In case of discrepancy between the MAFs within a
block, " +
        "the MAF of the first (smallest genomic position) SNP in the
block is considered the MAF of the block." +
        "NOTE: the PANEL field is optional (as a value, not in the header)")

**Comment by sooheelee** [comment]
Thanks Yossi. I will use this.

I was thinking that it would be good if Picard tools that require haplotype maps could accept the same information from a standardized file format, e.g. VCF. Or that we provide a means to create a haplotype map file using one of our tools, e.g. SelectVariants, and VCFs as input. 

The map resource as is matches VCF fields on:

1. CHROM
2. POS 
3. NAME
4. REF
5. ALT

and could use a population AF in column 6. The final two columns, (7) ANCHOR_SNP and (8) PANELS, would require addition.

**Comment by yfarjoun** [comment]
I agree 100%. Happy to advise whoever has time to do it.

**Comment by sooheelee** [comment]
I'm back from being away for 3 weeks and update this doc now.

**Comment by sooheelee** [comment]
In addition, I need to actually update the file descriptor in the code. Here is the discrepancy:

CheckFingerprint Javadoc says:
```
HAPLOTYPE_MAP=File
H=File                        A file of haplotype information produced by the CheckFingerprint program.  Required. 
```
CrosscheckReadGroupFingerprints Javadoc says:
```
HAPLOTYPE_MAP=File
H=File                        The file of haplotype data to use to pick SNPs to fingerprint  Required. 
```
---

Obviously, the tool does not produce the file, it requires it. Let's modify the descriptor:

```
File mapping SNPs to LD blocks used by Fingerprints tools. See XXX for details of the format. 
```

**Comment by sooheelee** [comment]
I've got a draft that describes the file format up in the GATK forum site: http://gatkforums.broadinstitute.org/dsde/discussion/9526/picard-haplotype-map-file-format/p1?new=1. 

It is in the Communications Drafts. I hope @yfarjoun has access to this for review. I will also modify the parameter description for two tools to include the URL to the GATK forum document (as shown above).

Also, @yfarjoun would it be okay if I posted your fingerprinting poster from AGBT? I think it would be good to point to it in the Picard tool docs for the CheckFingerprints tool.

**Comment by sooheelee** [comment]
Here is a question. What publicly available resource allows folks to reconstruct SNPs in high LD?

**Comment by yfarjoun** [comment]
Right now, none. However, I have a PR in place (
https://github.com/broadinstitute/picard/pull/793) which will make this
whole thing go away as you'll be able to use a phased VCF for this and
there are many tools for making vcfs.

Y.

**Comment by sooheelee** [comment]
@yfarjoun Does this PR mean that this will be in the next release of Picard? I have some questions then.

Will the tool still accept the Haplotype map format in addition to VCF?
Can I use the code change details in your PR to document the format of the VCF that the tools will accept?

> The VCF needs to have exactly one sample, HET for all the variants, and the phasing of haplotype blocks is done via phased genotypes (0|1, and 1|0) and the PS format field. The AF field is the AlternateAllele frequency, NOT the minor allele frequency, as it is in the HaplotypeDatabase file.

> The Constructor checks if the input file has the known vcf extensions (vcf, vcf.gz, bcf) and in that case opens the file as a vcf. otherwise it will attempt to open as a haplotype_database file.

**Comment by sooheelee** [comment]
Yossi answered in person. 

- I've changed the example haplotype map to remove identifying information. The draft is currently private and so no secret sauce was shared.
- I've permission to share the example VCF.
- I will also describe the VCF.

**Comment by sooheelee** [comment]
I think this is sufficient for now. We can change content later if needed. I will move the draft to the public forum.
