### ISSUE TITLE
custom adapters with IlluminaBasecallsToSam

### ISSUE THREAD

**Issue by jdc8890** [broadinstitute/picard#790]
### Tool(s) involved
_IlluminaBasecallsToSam_

### Description
_Unlike MarkIlluminaAdapters, IlluminaBasecallsToSam cannot mark custom adapter sequences.  For example, it would be useful if the THREE_PRIME_ADAPTER and FIVE_PRIME_ADAPTER parameters could be passed directly to IlluminaBasecallsToSam so that custom adapters can me marked directly during the BAM/SAM generation procedure._

**Comment by nh13** [comment]
@jdc8890 I see a number of other command line options in `MarkIlluminaAdapters`, like `ADAPTER_TRUNCATION_LENGTH`, `PRUNE_ADAPTER_LIST_AFTER_THIS_MANY_ADAPTERS_SEEN`, and `NUM_ADAPTERS_TO_KEEP`... I see seven in total actually.   Here's a PR with just the two options you are looking for, but I am worried that having the rest of the options may make `IlluminaBasecallsToSam` white large.
https://github.com/nh13/picard/pull/6

**Comment by nh13** [comment]
@jdc8890 do you want all the other options present in `MarkIlluminaAdapters` also included? I think if so, then `IlluminaBasecallsToSam` my get too cluttered, and so I would recommend just running `MarkIlluminaAdapters` on the de-multiplexed BAMs.  @yfarjoun, what do you think?

**Comment by yfarjoun** [comment]
I agree that adding all the options to IlluminaBasecallsToSam might make it too cluttered but think that just adding the custom adapter is OK. 

my 2cts

**Comment by yfarjoun** [comment]
fixed.
