### ISSUE TITLE
VariantCalling Metrics missing sample

### ISSUE THREAD

**Issue by renkyp** [broadinstitute/picard#797]
### Affected tool(s)
 CollectVariantCallingMetrics

### Affected version(s)
Current

### Description 

In same cases, variant calling output is missing samples in detail_metrics.  

In vcf/CallingMetricAccumulator.java, line 117, accumulate function, starting line 123, filters are applied before maps are created. So for example, in a vcf with Normal and Tumor data, if all Normal data have GT 0/0 (HOM_REF), then all records are filtered out before goes to sampleMetrcisMap. So in the final detail_metrics output, the Normal sample's record does not even show up.  

#### Expected behavior

If the sample's records are all with GT 0/0, the sample will be missed by Picard 

#### Actual behavior

INPUT a tumor/normal vcf, normal was ignored by Picard

**Comment by meganshand** [comment]
@renkyp This should be fixed in the next release, thanks for reporting it.
