### ISSUE TITLE
Make HTSJDK project a proper dependency

### ISSUE THREAD

**Issue by heuermh** [broadinstitute/picard#8]
The dependency between Picard and HTSJDK needs to be improved.

``` bash
$ git clone https://github.com/broadinstitute/picard.git
$ ant
Buildfile: /Users/xxx/working/picard/build.xml

set-htsjdk-version:

BUILD FAILED
/Users/xxx/working/picard/build.xml:108: Basedir /Users/xxx/working/picard/htsjdk does not exist

Total time: 0 seconds
```

There are many mechanisms for dependency resolution in java projects (e.g. Maven, Ivy, Gradle, etc.).

**Comment by apredeus** [comment]
clone-htsjdk fails with the following message:

Cloning into 'htsjdk'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

----------------

Any idea why this is?

**Comment by thomasyu888** [comment]
Thanks in advance for your time.  I am having the same problem as apredeus.  Please kindly advise me so I can clone htsjdk and install picard.

**Comment by xchrom** [comment]
I'd love to hear if apredeus resolved this as I'm getting the same error message:

ant clone-htsjdk
Buildfile: /home4/edarrow/software/broadinstitute-picard-e62cc4c/build.xml
     [exec] Result: 128

clone-htsjdk:
     [exec] Cloning into 'htsjdk'...
     [exec] Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
     [exec] Permission denied (publickey).
     [exec] fatal: The remote end hung up unexpectedly

BUILD FAILED
/home4/edarrow/software/broadinstitute-picard-e62cc4c/build.xml:130: exec returned: 128

Total time: 2 seconds

**Comment by apredeus** [comment]
Hello,

On Wed, Jan 20, 2016 at 11:01 PM, xchrom <notifications@github.com> wrote:

> I'd love to hear if apredeus resolved this as I'm getting the same error
> message:
>

This problem has something to do with accessing GitHub using ssh - the
suggested command

git clone git@github.com:samtools/htsjdk.git

never worked for me. Just use the usual

git clone https://github.com/samtools/htsjdk

instead, and then follow the building instructions.It will work fine.

-- apredeus

**Comment by albacrespi** [comment]
I can clone as apredeus said, but then the normal build instructions don't work.
The problem is that ant is depracated for building htsjdk. The help give some hints, however doesn't work.
Any suggestions?

**Comment by akiezun** [comment]
+1 from me on making htsjdk a proper dependency. Should we reopen this now that htsjdk uses gradle and is on maven central?

**Comment by droazen** [comment]
Re-opening -- Picard should pull htsjdk from maven like a modern, well-behaved project (with ability to optionally override using a locally-built htsjdk jar).

**Comment by jacarey** [comment]
PR here https://github.com/broadinstitute/picard/pull/542

**Comment by droazen** [comment]
Thanks @jacarey!

**Comment by yfarjoun** [comment]
this is done, right?!
