### ISSUE TITLE
Add link to example refflat file in CollectRnaSeqMetrics documentation

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#804]
### Tool(s) involved
CollectRnaSeqMetrics 

### Description 
_Describe what needs to be added or modified._

[Current doc](https://broadinstitute.github.io/picard/command-line-overview.html#CollectRnaSeqMetrics) reads:
> The sequence input must be a valid SAM/BAM file containing RNAseq data aligned by an RNAseq-aware genome aligner such a STAR or TopHat. The tool also requires a REF_FLAT file, a tab-delimited file containing information about the location of RNA transcripts, exon start and stop sites, etc. For more information on the REF_FLAT format, see the following [description](http://genome.ucsc.edu/goldenPath/gbdDescriptionsOld.html#RefFlat). Build-specific REF_FLAT files can be obtained [here](http://hgdownload.cse.ucsc.edu/downloads.html).

First link gives a 404 and second link gives the UCSC general downloads landing page. 

Update documentation to give an example file link: <http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/refFlat.txt.gz>.

as well as a snippet from the file:
```
DDX11L1 NR_046018   chr1    +   11873   14409   14409   14409   3   11873,12612,13220,  12227,12721,14409,
WASH7P  NR_024540   chr1    -   14361   29370   29370   29370   11  14361,14969,15795,16606,16857,17232,17605,17914,18267,24737,29320,  14829,15038,15947,16765,17055,17368,17742,18061,18366,24891,29370,
```

**Comment by nh13** [comment]
For build 38: http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database

**Comment by sooheelee** [comment]
Thank you @nh13! 

**Blurb for tool document**:
For an example refFlat file for GRCh38, see `refFlat.txt.gz` at [http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database](http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database). The first two lines of the tab-limited text file appear as follows.
```
DDX11L1	NR_046018	chr1	+	11873	14409	14409	14409	3	11873,12612,13220,	12227,12721,14409,
WASH7P	NR_024540	chr1	-	14361	29370	29370	29370	11	14361,14969,15795,16606,16857,17232,17605,17914,18267,24737,29320,	14829,15038,15947,16765,17055,17368,17742,18061,18366,24891,29370,
```
