### ISSUE TITLE
How to tell if VCFFileReader has an index?

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#814]
The VCFFileReader constructor has an argument `requireIndex`, which enables one to require that an index be present. It doesn't seem to enable one to query _whether_ the resulting reader has an index, and therefore whether you can query it, or only iterate over the entire collection. 

What is the right why to find out if a VCFFileReader has an index? If such a way doesn't exist (I guess one could always try and catch the exception...), should it?

**Comment by pshapiro4broad** [comment]
I don't see a way to do this either. For now a caller will have to try/catch around a call to `query()`.

It would be nice to update the javadoc for `VCFFileReader.query()` so it documents this requirement.

**Comment by ben10wald** [comment]
Hey guys I have updated the docs just like @pshapiro4broad recommended:
https://github.com/samtools/htsjdk/pull/954
Do you want to close out this ticket or is there more to do?
