### ISSUE TITLE
Are Illumina adapter sequences licensed? 

### ISSUE THREAD

**Issue by JohnLonginotto** [broadinstitute/picard#824]
More of a question than an issue, I am just curious to know if the Picard team required a license to include the adapter sequences used in MarkIlluminaAdapters, or if this was not needed.

From their docs: https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences_1000000002694-01.pdf

All the best!

EDIT: Perhaps it is not needed, since MarkIlluminaAdapters never prints adapter sequences?

**Comment by sooheelee** [comment]
@vdauwera have you any insight?

**Comment by vdauwera** [comment]
Hi @JohnLonginotto, we have interpreted the text to mean that the usage made in the Picard project is within scope of what is allowed. We're adding a copyright notice (see #828) to make sure others are aware that these sequences are Illumina's intellectual property.
