### ISSUE TITLE
Release 2.9.3?

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#825]
It looks like the last release was 26 days ago.  Any chance for a new release?  Also, is there a release schedule (every two weeks) that we could rely on?

**Comment by ktibbett** [comment]
@nh13 , we'll try to do a release later today (could fall to tomorrow).  We will also adopt your proposal of regular picard releases every two weeks on Mondays.  Thank you for the suggestion.

**Comment by nh13** [comment]
Thank-you!

**Comment by ktibbett** [comment]
2.9.1 went out last night (and 2.9.2 this AM).
