### ISSUE TITLE
Review automated release notes code and upgrade

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#826]
I'm studying v2.9.2 release notes and notice that Eric's new tool is not featured in the release notes.

From:
https://github.com/broadinstitute/picard/wiki/How-to-release-Picard

The release notes are automatically generated in this step:
```
git log --pretty=oneline PREVIOUS_VERSION..NEW_VERSION | grep -v "Merge pull request" | awk '{ $1=""; print "* " $0; }'
```

However, the 2.9.2 release notes exclude <https://github.com/broadinstitute/picard/commit/bfeb7f5da7c739108e5728cd5bfc7aea0a5ee18a> for new tool AccumulateVariantCallingMetrics. Checked and this is not intentional.

Could we please fix the code to not have such oversights? Thanks.

**Comment by droazen** [comment]
Discussed in person with @sooheelee -- her problem was that the new release hadn't happened yet, so she needed to run the command from the wiki with CURRENT_VERSION..HEAD instead of PREVIOUS_VERSION..NEW_VERSION. 

Closing as resolved.
