### ISSUE TITLE
UMI aware - Mate CIGAR (tag MC) not Found  -- Bug Report

### ISSUE THREAD

**Issue by ChristopheLegendre** [broadinstitute/picard#827]
### Affected tool(s)
_UmiAwareMarkDuplicatesWithMateCigar_

### Affected version(s)
- [ 2.9.2 ] Latest public release version [2.9.2]

### Description 
If I use the picard's Fixmate or the newest version of samtools 1.4's fixmate, I get the following Error if I try to use _UmiAwareMarkDuplicatesWithMateCigar_ module of picard.
Here is my steps to get to the coordinate-sorted BAM file that is used as input for _UmiAwareMarkDuplicatesWithMateCigar_ : 
1) BWA alignment 
2) Adding RX tag to alignment records in SAM format
3) convert SAM -> BAM  using samtools
4) sort by readname the newly formed BAM file using: samtools 1.4 sort -n 
3) Fixmate ( I tried the fixmate versions from samtools 1.4 or/and picard's 2.9.2)
4) sorting by coordinate the bam file obtained from step 3 using samtools sort
5) run UmiAwareMarkDuplicatesWithMateCigar
6) Exception raised ...
 
__Here the **stacktrace** of the Error:__

java -jar  picard_2.9.2.jar  UmiAwareMarkDuplicatesWithMateCigar ASSUME_SORT_ORDER=coordinate PROGRAM_RECORD_ID=umiAwareMarkDuplicate UMI_TAG_NAME=RX  MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=true CREATE_MD5_FILE=false I=mySimple.coord.bam  O=mySimple.coord.bam.md.bam METRICS_FILE=mySimple.coord.bam.md.metrics UMI_METRICS=mySimple.coord.bam.umi_metrics VALIDATION_STRINGENCY=SILENT

[Mon Jun 05 15:41:04 MST 2017] picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar UMI_METRICS_FILE=fixmate_with-p.bam.umi_metrics UMI_TAG_NAME=RX INPUT=[fixmate_with-p.bam] OUTPUT=fixmate_with-p.bam.md.bam METRICS_FILE=.md.metrics ASSUME_SORT_ORDER=coordinate PROGRAM_RECORD_ID=umiAwareMarkDuplicate VALIDATION_STRINGENCY=SILENT MAX_RECORDS_IN_RAM=5000000 CREATE_INDEX=true CREATE_MD5_FILE=false    MAX_EDIT_DISTANCE_TO_JOIN=1 ASSIGNED_UMI_TAG=MI ALLOW_MISSING_UMIS=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag REMOVE_DUPLICATES=false ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_GROUP_NAME=UmiAwareMarkDuplicatesWithMateCigar READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 GA4GH_CLIENT_SECRETS=client_secrets.json
[Mon Jun 05 15:41:04 MST 2017] Executing as clegendre@pnap-scalemp on Linux 2.6.32-220.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14; Picard version: 2.9.2-SNAPSHOT
[Mon Jun 05 15:42:06 MST 2017] picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar done. Elapsed time: 1.02 minutes.
Runtime.totalMemory()=11884036096
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Mate CIGAR (Tag MC) not found.
        at htsjdk.samtools.SAMUtils.getMateUnclippedEnd(SAMUtils.java:877)
        at htsjdk.samtools.SAMRecordDuplicateComparator.getMateCoordinate(SAMRecordDuplicateComparator.java:189)
        at htsjdk.samtools.SAMRecordDuplicateComparator.populateTransientAttributes(SAMRecordDuplicateComparator.java:85)
        at htsjdk.samtools.SAMRecordDuplicateComparator.compare(SAMRecordDuplicateComparator.java:224)
        at htsjdk.samtools.SAMRecordDuplicateComparator.compare(SAMRecordDuplicateComparator.java:43)
        at java.util.TimSort.binarySort(TimSort.java:296)
        at java.util.TimSort.sort(TimSort.java:239)
        at java.util.Arrays.sort(Arrays.java:1512)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:219)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:166)
        at htsjdk.samtools.DuplicateSetIterator.<init>(DuplicateSetIterator.java:99)
        at htsjdk.samtools.DuplicateSetIterator.<init>(DuplicateSetIterator.java:66)
        at picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar.getDuplicateSetIterator(UmiAwareMarkDuplicatesWithMateCigar.java:107)
        at picard.sam.markduplicates.SimpleMarkDuplicatesWithMateCigar.doWork(SimpleMarkDuplicatesWithMateCigar.java:120)
        at picard.sam.markduplicates.UmiAwareMarkDuplicatesWithMateCigar.doWork(UmiAwareMarkDuplicatesWithMateCigar.java:96)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
 

## Description ##
The MC tag is added to my alignment recoreds in the BAM file when using the fixmate modules from the two tools samtools and picard but despite it, _UmiAwareMarkDuplicatesWithMateCigar_ raises an exception. 

# Question/Request
Would it be possible to fix the Exception and make _UmiAwareMarkDuplicatesWithMateCigar_  module compatible with samtools fixmate or picard fixmate?

Let me know if you have questions

Thanks,
Best,
Chris

**Comment by yfarjoun** [comment]
the numbering of your steps got screwed up, and you seem to be referencing the wrong step when you say "sorting by coordinate the bam file obtained from step 3 using samtools sort".

Can you please do the following things for me:

1. Run validateSamFile on your BAM and see if it reports any errors
2. Run FixMateInformation with IGNORE_MISSING_MATES=false
3. I modified htsjdk to emit more informative exceptions in cases like this, can you build Picard with a custom htsjdk ? If so, please build against branch `yf_add_exception_information` in htsjdk  and rerun UmiAwareMarkDuplicatesWithMateCigar and post the exception here.

**Comment by yfarjoun** [comment]
The only reason you might be getting Missing MC (That I can think of) is that you have a mixture of mated reads and fragments in your file...could this be the case? 

If not, you should be able to run FixMateInformation with IGNORE_MISSING_MATE=false and that should run with no error. (please test) 

Regarding UmiAwareMarkDuplicatesWithMateCigar ignoring MC:Z:* that seems like a simple fix...should be able to get it done....though it seems like a hack.

**Comment by ChristopheLegendre** [comment]
1. Yes, this is the case; We are using "bwa mem" for aligning the reads; read names may appear more than once and also may be split (fragments).
2. I ran FixMateInformation with IGNORE_MISSING_MATE=false as mentioned in NOTE_3 but I ran it after having removed  ** MC:Z:* **  from my file and it worked ; But there is not point of running both samtools and picard's fixmate modules one after the other in my case.  
3. Ignoring MC:Z:* could be an option in UmiAwareMarkDuplicatesWithMateCigar; if possible great; Thanks.

**Comment by yfarjoun** [comment]
UmiAwareMarkDuplicatesWithMateCigar cannot (currently) work on files that do not contain MC tag. the MC tag doesn't have any meaning on unmated records...so the conclusion is that UmiAwareMarkDuplicatesWithMateCigar cannot work on unmated fragments. sorry.

**Comment by kongdeju** [comment]
what is the UMI_METRICS file like ?
