### ISSUE TITLE
RevertSam, when REMOVE_ALIGNMENT_INFORMATION=true, should not stall on sam validation errors

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#849]
E.g. `Read CIGAR M operator maps off end of reference`. The point of RevertSam afterall is to remove subpar alignment information to eventually obtain a fresh alignment. 

### Affected tool(s)
RevertSam, when REMOVE_ALIGNMENT_INFORMATION=true

### Affected version(s)
- [x] Latest public release version [2.9.4]

### Description 
- Original user post: <http://gatkforums.broadinstitute.org/gatk/discussion/comment/39949#Comment_39949>
- Recapitulate user error with test data:
<https://github.com/broadinstitute/dsde-docs/issues/2231>

#### Steps to reproduce
- Test data: 
```
/humgen/gsa-scr1/pub/incoming/jfiksel_revertsam_bug.zip
```
- Test command:
```
java -jar $PICARD RevertSam \
    I=PGDX8157T_Ex_snippet.bam \
    O=sandbox/PGDX8157T_Ex_u.bam
```
#### Expected behavior
Tool reverts reads to unaligned BAM

#### Actual behavior
Error message:
```
WMCF9-CB5:jfiksel_revertsam_error shlee$ java -jar $PICARD RevertSam I=PGDX8157T_Ex_snippet.bam O=sandbox/PGDX8157T_Ex_u.bam 
[Fri Jun 30 11:17:58 EDT 2017] picard.sam.RevertSam INPUT=PGDX8157T_Ex_snippet.bam OUTPUT=sandbox/PGDX8157T_Ex_u.bam    OUTPUT_BY_READGROUP=false OUTPUT_BY_READGROUP_FILE_FORMAT=dynamic SORT_ORDER=queryname RESTORE_ORIGINAL_QUALITIES=true REMOVE_DUPLICATE_INFORMATION=true REMOVE_ALIGNMENT_INFORMATION=true ATTRIBUTE_TO_CLEAR=[NM, UQ, PG, MD, MQ, SA, MC, AS] SANITIZE=false MAX_DISCARD_FRACTION=0.01 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Fri Jun 30 11:17:58 EDT 2017] Executing as shlee@WMCF9-CB5 on Mac OS X 10.11.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_111-b14; Picard version: 2.9.4-SNAPSHOT
INFO	2017-06-30 11:18:04	RevertSam	Reverted     1,000,000 records.  Elapsed time: 00:00:05s.  Time for last 1,000,000:    5s.  Last read position: chr17:61,684,897
INFO	2017-06-30 11:18:10	RevertSam	Reverted     2,000,000 records.  Elapsed time: 00:00:12s.  Time for last 1,000,000:    6s.  Last read position: chr17:72,477,335
INFO	2017-06-30 11:18:16	RevertSam	Reverted     3,000,000 records.  Elapsed time: 00:00:18s.  Time for last 1,000,000:    5s.  Last read position: chr17:76,120,913
INFO	2017-06-30 11:18:22	RevertSam	Reverted     4,000,000 records.  Elapsed time: 00:00:24s.  Time for last 1,000,000:    6s.  Last read position: chr17:80,046,790
[Fri Jun 30 11:18:24 EDT 2017] picard.sam.RevertSam done. Elapsed time: 0.44 minutes.
Runtime.totalMemory()=1670381568
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Read name HWI-D00743_115_5_2112_18001_6554_0:0:0:0:0, Read CIGAR M operator maps off end of reference
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:451)
	at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:253)
	at htsjdk.samtools.SAMRecord.getAlignmentEnd(SAMRecord.java:603)
	at htsjdk.samtools.SAMRecord.computeIndexingBin(SAMRecord.java:1547)
	at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:2054)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:811)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
	at picard.sam.RevertSam.doWork(RevertSam.java:246)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

**Comment by sooheelee** [comment]
Perhaps I can interest you @ronlevine?

**Comment by ronlevine** [comment]
On it.

**Comment by ronlevine** [comment]
@sooheelee After 2fa went into effect, I lost access to dsde-docs. Could you give me the location of the test data?

**Comment by sooheelee** [comment]
Sure. It's at /humgen/gsa-scr1/pub/incoming/jfiksel_revertsam_bug.zip

Soo Hee Lee, Ph.D.
Science Technical Writer

**Comment by ronlevine** [comment]
The error message is quite informative. The read:
`HWI-D00743_115_5_2112_18001_6554_0:0:0:0:0	73	chr17	81195137	12	100M	=	81195137	0	GTTAGGGTTAGGGTTAGGGTTAGGGGATGGGTTAGGGATAGGTCTGAACTTAAGTTACGCTAAAGGGTTTCGTATGCGGTCTTGTGCTTGGAAAGGAAAN	BBBBBFFFFFFFFFFFFFFFFFFF############################################################################	XD:Z:25TG5GT3TGT2GTGTGGG1GTG2GTGTGGGTGT2G1GT1GTNNNNNNNNNNNNNNNNNNNNNNNNN1	PG:Z:MarkDuplicates	SM:i:12	AS:i:0`
is off the end of `chr17`:
`@SQ	SN:chr17	LN:81195210	M5:351f64d4f4f9ddd45b35336ad97aa6de	UR:file:/dcl01/scharpf/data/reference/no_alternates/hg19/hg19.fa`
because:
```
alignment start on reference + alignment length - 1 > reference sequence length
81195137 + 100 - 1 > 81195210
```

**Comment by sooheelee** [comment]
Yes. The point is that we want to be able to revert reads without alignment related checks/errors. Presumably, we are reverting so we can realign the reads for better alignment. Hindering reversion with alignment filters is counter intuitive.

**Comment by sooheelee** [comment]
So, what are the alignment filters that are active when removealignmentonformation is set to true?

**Comment by ronlevine** [comment]
The command line from the user's script is:
```
java -Xmx8G -jar $PICARD RevertSam \
    I=PGDX8157T_Ex_snippet.bam \
    O=PGDX8157T_Ex_revertsam.bam \
    SANITIZE=true \
    MAX_DISCARD_FRACTION=0.005 \
    ATTRIBUTE_TO_CLEAR=XT \
    ATTRIBUTE_TO_CLEAR=XN \
    ATTRIBUTE_TO_CLEAR=AS \
    ATTRIBUTE_TO_CLEAR=OC \
    ATTRIBUTE_TO_CLEAR=OP \
    SORT_ORDER=queryname \
    RESTORE_ORIGINAL_QUALITIES=true \
    REMOVE_DUPLICATE_INFORMATION=true \
    REMOVE_ALIGNMENT_INFORMATION=true
```
By default, `VALIDATION_STRINGENCY=STRICT`, which throws an exception when encountering an error. Make `VALIDATION_STRINGENCY=LENIENT` logs the error message but does not throw an exception. But, it gives an NPE.
```
[Wed Jul 05 10:38:55 EDT 2017] picard.sam.RevertSam INPUT=PGDX8157T_Ex_snippet.bam OUTPUT=PGDX8157T_Ex_revertsam.bam SORT_ORDER=queryname RESTORE_ORIGINAL_QUALITIES=true REMOVE_DUPLICATE_INFORMATION=true REMOVE_ALIGNMENT_INFORMATION=true ATTRIBUTE_TO_CLEAR=[NM, UQ, PG, MD, MQ, SA, MC, AS, XT, XN, AS, OC, OP] SANITIZE=true MAX_DISCARD_FRACTION=0.005 VALIDATION_STRINGENCY=LENIENT    OUTPUT_BY_READGROUP=false OUTPUT_BY_READGROUP_FILE_FORMAT=dynamic VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Jul 05 10:38:55 EDT 2017] Executing as rlevine@gsa5.broadinstitute.org on Linux 2.6.32-642.15.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Picard version: 2.9.4-9-gb7996a6-SNAPSHOT
INFO	2017-07-05 10:39:15	RevertSam	Reverted     1,000,000 records.  Elapsed time: 00:00:19s.  Time for last 1,000,000:   18s.  Last read position: chr17:61,684,897
INFO	2017-07-05 10:39:24	RevertSam	Reverted     2,000,000 records.  Elapsed time: 00:00:28s.  Time for last 1,000,000:    9s.  Last read position: chr17:72,477,335
INFO	2017-07-05 10:39:36	RevertSam	Reverted     3,000,000 records.  Elapsed time: 00:00:40s.  Time for last 1,000,000:   11s.  Last read position: chr17:76,120,913
INFO	2017-07-05 10:39:47	RevertSam	Reverted     4,000,000 records.  Elapsed time: 00:00:50s.  Time for last 1,000,000:   10s.  Last read position: chr17:80,046,790
Ignoring SAM validation error: ERROR: Read name HWI-D00743_115_5_2112_18001_6554_0:0:0:0:0, Read CIGAR M operator maps off end of reference
[Wed Jul 05 10:39:50 EDT 2017] picard.sam.RevertSam done. Elapsed time: 0.94 minutes.
Runtime.totalMemory()=3599237120
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at picard.sam.RevertSam.sanitize(RevertSam.java:400)
	at picard.sam.RevertSam.doWork(RevertSam.java:274)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

**Comment by jfiksel** [comment]
Hi @ronlevine. I am the user who submitted the error. After using CleanSam, which got rid of the overhanging read, I still got a NPE. I found that this was fixed by first adding read group information to the BAM file. However, I'm not sure if read group information should also be required for RevertSam, since as @sooheelee said, I am doing this process to pretty much start over and not deal with my original BAM file not conforming to GATK standards.

**Comment by ronlevine** [comment]
With `VALIDATION_STRINGENCY=LENIENT` or `VALIDATION_STRINGENCY=SILENT`, the `NPE`,
`Exception in thread "main" java.lang.NullPointerException at picard.sam.RevertSam.sanitize(RevertSam.java:400)` is due to a `recordFormat == null` because the read groups (`RG`) are missing from the `SAMRecord`s.
```
for (final SAMRecord rec : recs) {
   // The only valid quality score encoding scheme is standard; if it's not standard, change it.
   final FastqQualityFormat recordFormat = readGroupToFormat.get(rec.getReadGroup());
   if (!recordFormat.equals(FastqQualityFormat.Standard)) {
       final byte[] quals = rec.getBaseQualities();
       for (int i = 0; i < quals.length; i++) {
           quals[i] -= SolexaQualityConverter.ILLUMINA_TO_PHRED_SUBTRAHEND;
       }
       rec.setBaseQualities(quals);
   }
   out.addAlignment(rec);
   sanitizerProgress.record(rec);
}
```

This can be fixed by changing:
`if (!recordFormat.equals(FastqQualityFormat.Standard)) {`
to
`if (recordFormat != null && !recordFormat.equals(FastqQualityFormat.Standard)) {`

**Comment by ronlevine** [comment]
@jfiksel Refer to my last post. The fix will remove the `RG` requirement.

**Comment by jfiksel** [comment]
Thanks for the quick fix @ronlevine ! Where/how would I make this fix?

**Comment by ronlevine** [comment]
I will create a pull request. BTW, did you run ValidateSamFile?

**Comment by jfiksel** [comment]
I did, the two errors I got were the overhanging read and the lack of read groups.

**Comment by sooheelee** [comment]
@ronlevine Are there other filters that kick in when REMOVE_ALIGNMENT_INFORMATION=true and/or when SANITIZE=true?

**Comment by ronlevine** [comment]
@jfiksel The fix has been merged to master.

**Comment by ronlevine** [comment]
Per discussion with @sooheelee, the alignment based validation should be removed from RevertSam.

**Comment by ronlevine** [comment]
On second thought, this would require some messy refactoring of SAMRecord/SamReader. Since VALIDATION_STRINGENCY=STRICT by default, I think the documentation should be updated to say that if there is a SAM validation error, set VALIDATION_STRINGENCY=LENIENTor SILENT.

**Comment by jfiksel** [comment]
After using VALIDATION_STRINGENCY=LENIENT, and then re-aligning with bwa mem, will this cause any problems with GATK/Picard validation? Or will bwa mem deal with the unmapped overhanging read appropriately, so that I don't have to run CleanSam?

**Comment by ronlevine** [comment]
@sooheelee, correct me if I am wrong. `bwa-mem` will soft clip overhanging reads but `CleanSam` is not required if VALIDATION_STRINGENCY=LENIENT. Whenever SAM file reads are processed, they are validated. If VALIDATION_STRINGENCY=LENIENT, the processing will continue and the validation error is logged.

**Comment by sooheelee** [comment]
I'm working on workshop materials--on a bit of a tight deadline. So I'll take a look at these questions next week.

**Comment by ronlevine** [comment]
Closing since #856 and #858 are merged.
