### ISSUE TITLE
User-defined coverage in CollectHsMetrics 

### ISSUE THREAD

**Issue by Anupriya014** [broadinstitute/picard#851]
Hello all!

Can anyone tell me how to get user-defined coverage from Picard? Right now, I am using CollectHsMetrics to get coverage like 1x, 2x, 10x - 50x, 100x. But what if I want to get coverage at 5x ?

Command used : `java -jar /home/packages/picard-tools-2.5.0/picard.jar CollectHsMetrics INPUT=/home/sorted.bam REFERENCE_SEQUENCE=/home/references/ref_fasta/grch37/ucsc.hg19.fasta TARGET_INTERVALS=/home/interval_list BAIT_INTERVALS=/home/interval_list OUTPUT=/home/hsmetrics.txt `

Please help me. Thank you in advance :)

**Comment by yfarjoun** [comment]
Currently CollectHsMetrics  doesn't calculate the Percent@5x. However, there
should be a histogram at the end of the metrics file (use the
high_quality_coverage_count column) that lists the number of bases (in the
target region) that were covered to at least each coverage value. From this
histogram it should be possible to calculate the desired Percent. The code
that does this is
here: picard/analysis/directed/TargetMetricsCollector.java:656 and in line
683.

I hope this helps.

**Comment by Anupriya014** [comment]
Thank you for the reply.
There is one more query. I ran CalculateHsMetrics too for the coverage. The results I got were quite different from CollectHsMetrics:

CalculateHsMetrics: 
`BAIT_SET	GENOME_SIZE	BAIT_TERRITORY	TARGET_TERRITORY	BAIT_DESIGN_EFFICIENCY	TOTAL_READS	PF_READS	PF_UNIQUE_READS	PCT_PF_READS	PCT_PF_UQ_READS	PF_UQ_READS_ALIGNED	PCT_PF_UQ_READS_ALIGNED	PF_BASES_ALIGNED	PF_UQ_BASES_ALIGNED	ON_BAIT_BASES	NEAR_BAIT_BASES	OFF_BAIT_BASES	ON_TARGET_BASES	PCT_SELECTED_BASES	PCT_OFF_BAIT	ON_BAIT_VS_SELECTED	MEAN_BAIT_COVERAGE	MEAN_TARGET_COVERAGE	MEDIAN_TARGET_COVERAGE	PCT_USABLE_BASES_ON_BAIT	PCT_USABLE_BASES_ON_TARGET	FOLD_ENRICHMENT	ZERO_CVG_TARGETS_PCT	PCT_EXC_DUPE	PCT_EXC_MAPQ	PCT_EXC_BASEQ	PCT_EXC_OVERLAP	PCT_EXC_OFF_TARGET	FOLD_80_BASE_PENALTY	PCT_TARGET_BASES_1X	PCT_TARGET_BASES_2X	PCT_TARGET_BASES_10X	PCT_TARGET_BASES_20X	PCT_TARGET_BASES_30X	PCT_TARGET_BASES_40X	PCT_TARGET_BASES_50X	PCT_TARGET_BASES_100X	HS_LIBRARY_SIZE	HS_PENALTY_10X	HS_PENALTY_20X	HS_PENALTY_30X	HS_PENALTY_40X	HS_PENALTY_50X	HS_PENALTY_100X	AT_DROPOUT	GC_DROPOUT	HET_SNP_SENSITIVITY	HET_SNP_Q	SAMPLE	LIBRARY	READ_GROUP
interval_list	3137161264	74569526	74569526	1	102824496	102824496	102824496	1	1	102784777	0.999614	10154706779	10154706779	6991599306	1285611474	1877495999	6991568964	0.815111	0.184889	0.844681	93.759471	93.759064	78	0.687497	0.687494	28.965738	0.002078	0	0.000116	0	0	0.311379	2.534029	0.996827	0.994848	0.969157	0.919166	0.854721	0.78146	0.704444	0.373226		0	0	0	0	0	0	9.77375	1.500733	0.990723	20`

CollectHsMetrics:
`BAIT_SET	GENOME_SIZE	BAIT_TERRITORY	TARGET_TERRITORY	BAIT_DESIGN_EFFICIENCY	TOTAL_READS	PF_READS	PF_UNIQUE_READS	PCT_PF_READS	PCT_PF_UQ_READS	PF_UQ_READS_ALIGNED	PCT_PF_UQ_READS_ALIGNED	PF_BASES_ALIGNED	PF_UQ_BASES_ALIGNED	ON_BAIT_BASES	NEAR_BAIT_BASES	OFF_BAIT_BASES	ON_TARGET_BASES	PCT_SELECTED_BASES	PCT_OFF_BAIT	ON_BAIT_VS_SELECTED	MEAN_BAIT_COVERAGE	MEAN_TARGET_COVERAGE	MEDIAN_TARGET_COVERAGE	PCT_USABLE_BASES_ON_BAIT	PCT_USABLE_BASES_ON_TARGET	FOLD_ENRICHMENT	ZERO_CVG_TARGETS_PCT	PCT_EXC_DUPE	PCT_EXC_MAPQ	PCT_EXC_BASEQ	PCT_EXC_OVERLAP	PCT_EXC_OFF_TARGET	FOLD_80_BASE_PENALTY	PCT_TARGET_BASES_1X	PCT_TARGET_BASES_2X	PCT_TARGET_BASES_10X	PCT_TARGET_BASES_20X	PCT_TARGET_BASES_30X	PCT_TARGET_BASES_40X	PCT_TARGET_BASES_50X	PCT_TARGET_BASES_100X	HS_LIBRARY_SIZE	HS_PENALTY_10X	HS_PENALTY_20X	HS_PENALTY_30X	HS_PENALTY_40X	HS_PENALTY_50X	HS_PENALTY_100X	AT_DROPOUT	GC_DROPOUT	HET_SNP_SENSITIVITY	HET_SNP_Q	SAMPLE	LIBRARY	READ_GROUP
interval_list	3137161264	74569526	74569526	1	102824496	102824496	102824496	1	1	102784777	0.999614	10154706779	10154706779	6991599306	1285611474	1877495999	5435804440	0.815111	0.184889	0.844681	93.759471	72.895789	61	0.687497	0.534513	28.965738	0.02522	0	0.065077	0.007651	0.159565	0.233912	2.603421	0.975861	0.972497	0.938605	0.872346	0.787044	0.693796	0.601437	0.252717		0	0	0	0	0	0	10.226132	1.393542	0.95063	13`


Out of curiosity, I even tried DepthOfCoverage (GATK3.6) ,the coverage I got was same as the CalculateHsMetrics results:
`	gte_0	gte_1	gte_2	gte_3	gte_4	gte_5	gte_6	gte_7	gte_8	gte_9	gte_10	gte_11	gte_12	gte_13	gte_14	gte_15	gte_16	gte_17	gte_18	gte_19	gte_20	gte_21	gte_22	gte_23	gte_24	gte_25	gte_26	gte_27	gte_28	gte_29	gte_30	gte_31	gte_32	gte_33	gte_34	gte_35	gte_36	gte_37	gte_38	gte_39	gte_40	gte_41	gte_42	gte_43	gte_44	gte_45	gte_46	gte_47	gte_48	gte_49	gte_50	gte_51	gte_52	gte_53	gte_54	gte_55	gte_56	gte_57	gte_58	gte_59	gte_60	gte_61	gte_62	gte_63	gte_64	gte_65	gte_66	gte_67	gte_68	gte_69	gte_70	gte_71	gte_72	gte_73	gte_74	gte_75	gte_76	gte_77	gte_78	gte_79	gte_80	gte_81	gte_82	gte_83	gte_84	gte_85	gte_86	gte_87	gte_88	gte_89	gte_90	gte_91	gte_92	gte_93	gte_94	gte_95	gte_96	gte_97	gte_98	gte_99	gte_100	gte_101	gte_102	gte_103	gte_104	gte_105	gte_106	gte_107	gte_108	gte_109	gte_110	gte_111	gte_112	gte_113	gte_114	gte_115	gte_116	gte_117	gte_118	gte_119	gte_120	gte_121	gte_122	gte_123	gte_124	gte_125	gte_126	gte_127	gte_128	gte_129	gte_130	gte_131	gte_132	gte_133	gte_134	gte_135	gte_136	gte_137	gte_138	gte_139	gte_140	gte_141	gte_142	gte_143	gte_144	gte_145	gte_146	gte_147	gte_148	gte_149	gte_150	gte_151	gte_152	gte_153	gte_154	gte_155	gte_156	gte_157	gte_158	gte_159	gte_160	gte_161	gte_162	gte_163	gte_164	gte_165	gte_166	gte_167	gte_168	gte_169	gte_170	gte_171	gte_172	gte_173	gte_174	gte_175	gte_176	gte_177	gte_178	gte_179	gte_180	gte_181	gte_182	gte_183	gte_184	gte_185	gte_186	gte_187	gte_188	gte_189	gte_190	gte_191	gte_192	gte_193	gte_194	gte_195	gte_196	gte_197	gte_198	gte_199	gte_200	gte_201	gte_202	gte_203	gte_204	gte_205	gte_206	gte_207	gte_208	gte_209	gte_210	gte_211	gte_212	gte_213	gte_214	gte_215	gte_216	gte_217	gte_218	gte_219	gte_220	gte_221	gte_222	gte_223	gte_224	gte_225	gte_226	gte_227	gte_228	gte_229	gte_230	gte_231	gte_232	gte_233	gte_234	gte_235	gte_236	gte_237	gte_238	gte_239	gte_240	gte_241	gte_242	gte_243	gte_244	gte_245	gte_246	gte_247	gte_248	gte_249	gte_250	gte_251	gte_252	gte_253	gte_254	gte_255	gte_256	gte_257	gte_258	gte_259	gte_260	gte_261	gte_262	gte_263	gte_264	gte_265	gte_266	gte_267	gte_268	gte_269	gte_270	gte_271	gte_272	gte_273	gte_274	gte_275	gte_276	gte_277	gte_278	gte_279	gte_280	gte_281	gte_282	gte_283	gte_284	gte_285	gte_286	gte_287	gte_288	gte_289	gte_290	gte_291	gte_292	gte_293	gte_294	gte_295	gte_296	gte_297	gte_298	gte_299	gte_300	gte_301	gte_302	gte_303	gte_304	gte_305	gte_306	gte_307	gte_308	gte_309	gte_310	gte_311	gte_312	gte_313	gte_314	gte_315	gte_316	gte_317	gte_318	gte_319	gte_320	gte_321	gte_322	gte_323	gte_324	gte_325	gte_326	gte_327	gte_328	gte_329	gte_330	gte_331	gte_332	gte_333	gte_334	gte_335	gte_336	gte_337	gte_338	gte_339	gte_340	gte_341	gte_342	gte_343	gte_344	gte_345	gte_346	gte_347	gte_348	gte_349	gte_350	gte_351	gte_352	gte_353	gte_354	gte_355	gte_356	gte_357	gte_358	gte_359	gte_360	gte_361	gte_362	gte_363	gte_364	gte_365	gte_366	gte_367	gte_368	gte_369	gte_370	gte_371	gte_372	gte_373	gte_374	gte_375	gte_376	gte_377	gte_378	gte_379	gte_380	gte_381	gte_382	gte_383	gte_384	gte_385	gte_386	gte_387	gte_388	gte_389	gte_390	gte_391	gte_392	gte_393	gte_394	gte_395	gte_396	gte_397	gte_398	gte_399	gte_400	gte_401	gte_402	gte_403	gte_404	gte_405	gte_406	gte_407	gte_408	gte_409	gte_410	gte_411	gte_412	gte_413	gte_414	gte_415	gte_416	gte_417	gte_418	gte_419	gte_420	gte_421	gte_422	gte_423	gte_424	gte_425	gte_426	gte_427	gte_428	gte_429	gte_430	gte_431	gte_432	gte_433	gte_434	gte_435	gte_436	gte_437	gte_438	gte_439	gte_440	gte_441	gte_442	gte_443	gte_444	gte_445	gte_446	gte_447	gte_448	gte_449	gte_450	gte_451	gte_452	gte_453	gte_454	gte_455	gte_456	gte_457	gte_458	gte_459	gte_460	gte_461	gte_462	gte_463	gte_464	gte_465	gte_466	gte_467	gte_468	gte_469	gte_470	gte_471	gte_472	gte_473	gte_474	gte_475	gte_476	gte_477	gte_478	gte_479	gte_480	gte_481	gte_482	gte_483	gte_484	gte_485	gte_486	gte_487	gte_488	gte_489	gte_490	gte_491	gte_492	gte_493	gte_494	gte_495	gte_496	gte_497	gte_498	gte_499	gte_500
M1	1.00	1.00	0.99	0.99	0.99	0.99	0.98	0.98	0.98	0.97	0.97	0.96	0.96	0.96	0.95	0.95	0.94	0.94	0.93	0.92	0.92	0.91	0.91	0.90	0.89	0.89	0.88	0.88	0.87	0.86	0.85	0.85	0.84	0.83	0.83	0.82	0.81	0.80	0.80	0.79	0.78	0.77	0.77	0.76	0.75	0.74	0.74	0.73	0.72	0.71	0.70	0.70	0.69	0.68	0.67	0.67	0.66	0.65	0.64	0.64	0.63	0.62	0.61	0.61	0.60	0.59	0.58	0.58	0.57	0.56	0.56	0.55	0.54	0.54	0.53	0.52	0.52	0.51	0.50	0.50	0.49	0.48	0.48	0.47	0.46	0.46	0.45	0.45	0.44	0.43	0.43	0.42	0.42	0.41	0.41	0.40	0.39	0.39	0.38	0.38	0.37	0.37	0.36	0.36	0.35	0.35	0.34	0.34	0.33	0.33	0.32	0.32	0.31	0.31	0.31	0.30	0.30	0.29	0.29	0.28	0.28	0.28	0.27	0.27	0.26	0.26	0.26	0.25	0.25	0.24	0.24	0.24	0.23	0.23	0.23	0.22	0.22	0.22	0.21	0.21	0.21	0.20	0.20	0.20	0.19	0.19	0.19	0.18	0.18	0.18	0.18	0.17	0.17	0.17	0.17	0.16	0.16	0.16	0.16	0.15	0.15	0.15	0.15	0.14	0.14	0.14	0.14	0.13	0.13	0.13	0.13	0.13	0.12	0.12	0.12	0.12	0.12	0.11	0.11	0.11	0.11	0.11	0.10	0.10	0.10	0.10	0.10	0.10	0.10	0.09	0.09	0.09	0.09	0.09	0.09	0.08	0.08	0.08	0.08	0.08	0.08	0.08	0.08	0.07	0.07	0.07	0.07	0.07	0.07	0.07	0.07	0.06	0.06	0.06	0.06	0.06	0.06	0.06	0.06	0.06	0.06	0.05	0.05	0.05	0.05	0.05	0.05	0.05	0.05	0.05	0.05	0.05	0.05	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.03	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.02	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.01	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00`

Which coverage to consider now?

**Comment by yfarjoun** [comment]
CalculateHsMetrics is a deprecated CLP that is a wrapper around
CollectHsMetrics but with different default values. in
particular, MINIMUM_MAPPING_QUALITY and MINIMUM_BASE_QUALITY are different
by default, and CLIP_OVERLAPPING_READS is false. the recommended CLP is
CollectHsMetrics.

cheers,

**Comment by Anupriya014** [comment]
Thank you so much for the clarification Yossi. I'll be using CollectHsMetrics now. 
I wish to change the code as you suggested but I'm unable to do so as I don't know Java. Can you help me with that?

Regards,
Anupriya
