### ISSUE TITLE
use Static file endings for ".vcf", ".bcf", ".vcf.gz"

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/picard#854]
The static strings are already defined in VcfUtils, just need to use them in the rest of the code. 

Actually, there's a skeleton of this in htsjdk, so it might make more sense to make the changes there first and then use them in Picard.

**Comment by eitanbanks** [comment]
@yfarjoun our summer intern went ahead and did this for you.  See https://github.com/broadinstitute/picard/pull/892.  Is it okay to resolve this?

**Comment by yfarjoun** [comment]
thanks!
