### ISSUE TITLE
Resurrect Picard docker repo and populate with images of new versions

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#857]
There is a docker repo at https://hub.docker.com/r/broadinstitute/picard/ that purports to have automated picard builds but it hasn't been updated in over a year and there aren't any usable images. 

It would be of great value to the community to have an official Picard image pushed for every new release. At Broad we need this for FireCloud. 

@jacarey and @lbergelson

**Comment by vdauwera** [comment]
@lbergelson Any chance you guys can surface this in the next couple of weeks?

**Comment by lbergelson** [comment]
@vdauwera Ack, sorry I totally forgot about this.  What do you want in the docker, just the picard jar?

**Comment by vdauwera** [comment]
Yep that's all I want -- latest Picard jar on a stick, updated for every release. Thanks!

**Comment by vdauwera** [comment]
@lbergelson Sorry to bug you -- any progress on this? If you feel it won't happen soon (like this week) I'll have to bite the bullet and make my own dockers for immediate support purposes.

**Comment by kbergin** [comment]
It looks like dockerhub is being updated regularly with images - @vdauwera does it currently meet the request in this ticket? Going through picard backlog :)

**Comment by vdauwera** [comment]
All good, thanks Kylee!
