### ISSUE TITLE
UpdateVcfSequenceDictionary cannot write index

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#863]
@ronlevine looks like you introduced a bug, can you fix?  Try writing it to a file with `CREATE_INDEX=true`.  Since you wrapped it with an output stream :/.  I am curious as to why the change was made at all, since shouldn't `VariantContextWriterBuilder.determineOutputTypeFromFile` handle this? What was the original problem?

https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/vcf/UpdateVcfSequenceDictionary.java#L92-L99

**Comment by nh13** [comment]
@ronlevine even better, if the output file is `output.vcf.gz`, it doesn't write a gzipped file, but rather a text file named `output.vcf.gz`.

**Comment by nh13** [comment]
https://github.com/broadinstitute/picard/pull/741

**Comment by nh13** [comment]
@ronlevine I have added a potential fix into htsjdk so that `setOutputFile` should work: https://github.com/samtools/htsjdk/pull/933

**Comment by ronlevine** [comment]
Reverted the non-test changes from https://github.com/broadinstitute/picard/pull/741 and fixed/expanded tests on https://github.com/broadinstitute/picard/compare/rhl_uvsd_fix_stdout.

**Comment by nh13** [comment]
I checked out both your htsjdk and picard branches and got the following when testing it:

```
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at htsjdk.variant.variantcontext.writer.VCFWriter.writeAndResetBuffer(VCFWriter.java:125)
	at htsjdk.variant.variantcontext.writer.VCFWriter.writeHeader(VCFWriter.java:136)
	at picard.vcf.UpdateVcfSequenceDictionary.doWork(UpdateVcfSequenceDictionary.java:94)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

**Comment by ronlevine** [comment]
The Picard branch should get that NPE since the htsjdk fix from nh_vcf_to_stdout is not yet in. Update nh_vcf_to_stdout and try again, it should work fine. It runs without error locally for me as well as on travis, the automated testing framework.

**Comment by nh13** [comment]
Still getting the NPE.  I checked out the branch in htsjdk, ran `./gradlew install printVersion`, then ran `$ ./gradlew shadowJar -Dhtsjdk.version=2.10.1-17-g269f0c1-SNAPSHOT` in Picard.  Can you send me an executable jar for me to verify?

**Comment by ronlevine** [comment]
I am getting the same error. VCFWriter is trying to write a buffer to a null `outputStream`.This needs to be set. I added your original change back into htsjdk and am still getting the same error. The htsjdk snapshot is now 2.10.1-18-gc24bd07-SNAPSHOT.

**Comment by ronlevine** [comment]
I just made a change to htsjdk  and rebuilt. The following command successfully wrote to stdout:
` java -jar ./build/libs/picard.jar UpdateVcfSequenceDictionary INPUT=testdata/picard/vcf/vcfFormatTest.vcf OUTPUT=/dev/stdout SD=testdata/picard/vcf/dummy.reference.dict`. I need to fix Picard test for stdout because the output is not being captured in a file.

**Comment by nh13** [comment]
@ronlevine can you take a look at this?

**Comment by yfarjoun** [comment]
@cmnbroad feel like taking this one too?
