### ISSUE TITLE
picard-2.10.2: Failed to apply plugin [id 'org.ajoberstar.grgit']

### ISSUE THREAD

**Issue by mmokrejs** [broadinstitute/picard#872]
Hi,
  when trying to compile 2.10.2 from source using gradle I get:

```
$ GRADLE_USER_HOME="${WORKDIR}"  ./gradlew
...
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
Download https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.53/jsch-0.1.53.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/scratch/var/tmp/portage/sci-biology/picard-2.10.2/work/picard-2.10.2/build.gradle' line: 20

* What went wrong:
An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version: '1.4.2']
> Failed to apply plugin [id 'org.ajoberstar.grgit']
   > One of setGitDir or setWorkTree must be called.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

[build.log.txt](https://github.com/broadinstitute/picard/files/1150374/build.log.txt)

**Comment by XingGemini** [comment]
Have the same issue!

**Comment by gbggrant** [comment]
Hi @mmokrejs and @XingGemini 

You will need to clone the picard git repo and build it from that.

There is an outstanding ticket (https://github.com/broadinstitute/picard/issues/605) for making the build of picard work without requiring a .git directory, but we haven't tackled that yet.

For now, here's the git syntax to do a shallow clone of the released tagged version that you are interested in:
git clone -b 2.10.2 --depth 1 https://github.com/broadinstitute/picard.git
