### ISSUE TITLE
Post-Intel Deflator there's now an unsightly log4j warning when running any Picard tool

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/picard#883]
## Bug Report

Running any Picard tool with the new intel deflator as default generates an extra log message at the start of every run:

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
```

It's not the end of the world, but it is unsightly.  Any chance something can be done to suppress this?

### Affected tool(s)
All tools

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest development/master branch as of [date of test?]

**Comment by lbergelson** [comment]
I think we had the same issue in gatk and fixed it by adding a log4j2 config file...

log4j2.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm:ss.SSS} %-5level %logger{1} - %msg%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="INFO">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
```

**Comment by splaisan** [comment]
Thanks for relinking my post.
Will there be a fix any soon?
I do not build my copy but take it as jar and do not know what to do there.
Thanks

**Comment by ktibbett** [comment]
@splaisan , we are looking at it today.

**Comment by splaisan** [comment]
thanks a lot @ktibbett

**Comment by ktibbett** [comment]
Fixed in 2.10.7.

**Comment by zo0z** [comment]
Hi!
Thank you for attending to this matter. V2.10.7 solves the error on Picard, but I also get it when running the GATK v3.8. Simply passing the above file snippet as an option doesn't work:
```
java -Dlog4j.configurationFile=<path_to_log4j2.xml_containing_code_above> -jar GenomeAnalysisTK.jar -R <refGenome> -T SelectVariants -V <input_vcf> -L 1 -o <split.vcf>
```
Thanks again,
Azza

**Comment by splaisan** [comment]
Thanks @zoOz,
Do you mean the path/to/GenomeAnalysisTK.jar when you write <path_to_log4j2.xml_containing_code_above> or path within the jar archive which I do not know?
Thanks
Stephane

**Comment by zo0z** [comment]
Neither. The error above indicates the need to an apache configuration file for the log4j2, so I just copied and pasted the snippet provided in the comment by @lbergelson, saved it in a file named `log4j2.xml` and passed it as an option in `-Dlog4j.configurationFile`. This would work if one is building a project up, so I assumed it would fix the problem.

**Comment by splaisan** [comment]
Thanks @zoOz, I should have figured this out :-)
Best
Stephane

**Comment by bounlu** [comment]
when running gatk3.8 i got a similar error as below. any fix by gatk soon or how to fix exactly by myself?

INFO  02:12:00,367 HelpFormatter - Date/Time: 2017/10/22 02:12:00
INFO  02:12:00,367 HelpFormatter - ----------------------------------------------------------------------------------
INFO  02:12:00,367 HelpFormatter - ----------------------------------------------------------------------------------
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/speed/software/anaconda2/opt/gatk-3.8/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

**Comment by vdauwera** [comment]
Yes it’s fixed in the latest nightly and we plan to push out a patch release soon.

**Comment by Suggii** [comment]
Thanks this worked for me too :)
