### ISSUE TITLE
Intel Inflate/deflate default causing picard to never actually start

### ISSUE THREAD

**Issue by shanesturrock** [broadinstitute/picard#886]
### Affected tool(s)
CreateSequenceDictionary

### Affected version(s)
- 2.10.4+

### Description 
Picard never starts processing for any tool that uses Intel deflate/inflate. Using a Dell R930 server running CentOS 7.

#### Steps to reproduce
Just try and run any tool that relies on the Intel deflate. Change back to JDK deflate and it works fine.

#### Expected behavior
Should create a sam file from a fasta file

#### Actual behavior
Stalls indefinitely without producing any output. Hit CTRL-C and you get the following message: ^C08:54:31.170 WARN  IntelGKLUtils - Error starting process to check for AVX support : grep -i avx /proc/cpuinfo

**Comment by danxmoran** [comment]
Hi @shanesturrock, looks like this was a known issue in the GKL v0.5.2: Intel-HLS/GKL#33. It should be fixed in v0.5.3, so I'm going to bump our dependency.

**Comment by danxmoran** [comment]
@shanesturrock 2.10.7 should include the fix for this issue, but the CentOS box I had access to for testing wasn't on the same version as your machine. Can you try out the new version and confirm things are working?

**Comment by shanesturrock** [comment]
That's great Daniel, I can confirm that 2.10.7 works fine on our system.

Shane
