### ISSUE TITLE
A discussion on Picard release notes and forum questions

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/picard#896]
@nh13 @tfenne @jacarey @snovod @dianekaplan @ktibbett @chandrans @yfarjoun @meganshand @droazen @eitanbanks @vdauwera 

Hi everyone,

I have been asked to focus on GATK4 work and to _discontinue_ any work I do for Picard. I wanted to let you know, so that if there is interest, then someone else can continue the work I had been doing.

This work consists mainly of writing [release notes](https://github.com/broadinstitute/picard/releases) and answering forum Picard questions.

As a few of you know, I have been keeping up with changes to the Picard code and I have been writing human-readable release notes from the collection of commit comments that the repo auto-generates. This is not something I did alone. I receive great help from Megan on this front and also Yossi. 

I had taken this upon myself at the start of the year (~v2.9.0) so as to be able to keep up with changes. The reason I needed to keep up with changes is because I was told that taking on the Picard tool questions on the [GATK forum](https://software.broadinstitute.org/gatk/) would be most helpful towards alleviating the Communications team's support burden. A fraction of Picard tool questions require extreme digging that soaks up a lot of time.

My time is needed elsewhere. There is currently a release, v2.10.7, whose notes require finessing. I hope you can all sort this out and continue to help our users help themselves with better release notes.

-Soo Hee

**Comment by vdauwera** [comment]
This is being discussed internally. We will post a followup if there is any movement relevant to the Picard community.
