### ISSUE TITLE
Release picard to Maven Central repository

### ISSUE THREAD

**Issue by heuermh** [broadinstitute/picard#9]
Please release picard and its upstream dependencies to the Maven Central repository.

Currently downstream projects (e.g. ADAM, Google Genomics API, etc.) are depending on a rather out-of-date un-official build of picard distributed by the UTGB (University of Tokyo Genome Browser) Toolkit project
http://search.maven.org/#search|ga|1|picard

Sonatype OSSRH (Open Source Software Repository Hosting) provides a service to sync to Maven Central
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by jacarey** [comment]
Picard is now being published via sonatype

**Comment by heuermh** [comment]
Thank you.

**Comment by pgrosu** [comment]
Thank you :)

**Comment by chapmanb** [comment]
Brilliant, thanks so much.
