### ISSUE TITLE
Speeding up MarkDuplicates by not modifying per read PG tag

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/picard#902]
We want to speed up MarkDuplicates by not having it write out a PG tag for every read in the bam file.  If we no longer are writing out this tag then on the 2nd pass we can turn off the `EAGERLY_DECODE` option [here](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java#L210) (changes only turn this off for 2nd pass) when reading the SAM file and this gives a ~16% speedup on WGS data.  This is due to the fact that if we no longer are modifying the PG tag then all we do with the record on the 2nd pass is look at the RG tag for every read so we save time by not decoding the whole record which makes writing the file out is much faster.

Some runtimes before and after the changes.  Runtime is in minutes

Still writing PG tag with `EAGERLY_DECODE` enabled on both passes 
![image](https://user-images.githubusercontent.com/13023616/29133770-88910294-7d02-11e7-8315-31cfc179e201.png)

Not Writing PG tag with `EAGERLY_DECODE` on second pass disabled
![image](https://user-images.githubusercontent.com/13023616/29133854-cba451bc-7d02-11e7-8e05-67d194d0d650.png)

These were all run on HDD,  you do see further gains with SSD but thats outside the realm of the proposed changes.

Some questions to answer is if this is an acceptable change in general to MD (and MBA as far as writing PG tags to every read).  If this is an acceptable change, should this be the default mode for these programs in the future.

**Comment by vdauwera** [comment]
I've always wondered why we tagged every read in this way, considering we don't do it with any other tools that modify reads (afaik). I would support getting rid of it as long as we keep a PG tag in the header to tell us the data has been deduped.

**Comment by yfarjoun** [comment]
I'm for it. :+1:

Also would be nice if

1. MBA would leave it's own PG record (not only that of the aligner) so that the arguments of that swiss-army-knife of sequencing tools can be recorded somewhere (not so easy)
2. PG records are chained using the PP tag
3. MBA also drops the PG tag.

**Comment by magicDGS** [comment]
This can be closed after #907, no?
