### ISSUE TITLE
Document ValidateSamFile return codes

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/picard#903]
### Tool(s) involved
ValidateSamFile

### Description 
Tool outputs the following return codes. This should be in the user-facing doc because it is important for pipelining. 

````
exit(-1) - program failed to complete execution
exit(0) - program ran successfully
exit(1) - validation warnings but no errors
exit(2) - validation errors and possibly warnings
````

**Comment by vdauwera** [comment]
(I self-assigned so that I don't forget this is a thing but if someone else wants to pick it up please go ahead)

**Comment by kbergin** [comment]
From @dekling 
> Validation errors associated with ValidateSamFile tool are not listed anywhere.
> Doc system should pull the error table and their respective definitions from the SAMValidationError.java file.
