### ISSUE TITLE
ValidateSamFile doesn't warn when quality scores are missing

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/picard#906]
ValidateSamFile does not currently issue any warnings or errors if run on a BAM file that has had the quality scores removed (or set to `*` in SAM).  While this is valid in terms of the BAM specification, many Picard tools crash in uninformative ways if the quality scores are not present.  I think it would be better to produce a _warning_ if the quality scores are absent on a record.

**Comment by yfarjoun** [comment]
👍

**Comment by yfarjoun** [comment]
fixed
