### ISSUE TITLE
Picard 2.10.0 fails SetNmMdAndUqTags 

### ISSUE THREAD

**Issue by fhzh** [broadinstitute/picard#911]
Picard 2.10.0 fails SetNmMdAndUqTags

I got a message in running SetNmMdAndUqTags, saying "Must
have a non-null REFERENCE_SEQUENCE" and the program stop working but gave out the description of the tool, such as USAGE and options. 
I have searched online but did not find any clue about this issue. 

I am using Picard 2.10.0 and the Java 1.18 on the server. The script I used
to run SetNmMdAndUqTags tool is as follows:

#!/usr/bin/bash
java -jar /usr/local/apps/picard/picard-2.10.0/picard.jar SetNmMdAndUqTags \
Input = /share3/hfang4/GBS_data/samtools.out/sorted.NC_13_101.bam \
Output= /share3/hfang4/GBS_data/samtools.out/NC_13_101.fixed.bam

Could anyone please help me out with this?
Thanks

fhzh

**Comment by yfarjoun** [comment]
As the error says, you need to give the program a REFERENCE_SEQUENCE pointing to the fasta file you have aligned to.
