### ISSUE TITLE
Accept piped input FastqToSam

### ISSUE THREAD

**Issue by yesimon** [broadinstitute/picard#915]
### Tool(s) involved
_SAM/BAM, Metrics etc._

### Description
_Allow Picard to accept piped input for commands working with large files_

Currently this is not possible for most tools operating on SAM/BAM input because of file type autodetection by reading the beginning of the file and then `.reset()` on the `InputStream`, which cannot be done on `/dev/stdin` or named pipe input. Similarly `FastqToSam` does autodetection of quality score format and the reopens the stream. However, by using something like `RereadableInputStream` https://tika.apache.org/1.2/api/org/apache/tika/utils/RereadableInputStream.html, picard can support input pipes combined with file autodetection.

**Comment by notestaff** [comment]
https://gatkforums.broadinstitute.org/gatk/discussion/8500/using-pipes-for-bwa-picard-tools

**Comment by nh13** [comment]
In some cases, special built tools were built to allow streaming (ex. `MarkDuplicatesWithMateCigar` versus `MarkDuplicates`), while in other cases, the tools could be modified on a case-by-case basis if there is a valid case and enough developer interest.  @yesimon was `FastqToSam` the only one you were interested in?  Happy to give some direction if you are interested in submitting a PR.

**Comment by yesimon** [comment]
The most basic would be letting `FastqToSam` support piped input. Right now it has to do quality score format autodetection (one non-backwards compatible change is setting `QUALITY_FORMAT=Standard` actually just sets the quality instead of providing something to sanity check against). More broadly, the `SamReaderFactory` of `htsjdk` can wrap around `RereadableInputStream` with a very small performance penalty (probably insignificant), allowing piped SAM. VCFs tend to be smaller so there's less of a need there.

I don't see how any of the `MarkDuplicates...` functions allow piped input right now. They all seem to be using the `SamReaderFactory` class which does autodetection. It is a one-pass program which means it should be quite amenable to piped inputs.

**Comment by nh13** [comment]
MarkDuplicates is not one pass... sorry. Also, a lot of tools allow piped SAM. I'd be excited for some more benchmarks on the implementation you propose. Likely folks are busy with their own work (i.e. Likely They don't get paid to support Picard)so if your up for a PR, I am sure I am not out of line to suggest folks would be willing to review. But that's better left to the Broad Picard folks.

**Comment by yfarjoun** [comment]
:+1: @nh13.

if there's truly no performance hit, and it's a small localized change I'll
be happy to review a PR. As @nh13 said, MarkDuplicates is not single pass,
so it will not stream, but FastqToSam is a reasonable one. My concern woudl
be that the change need to be in htsjdk where they will not be
localized...but I'm happy to be proven wrong!

Care to submit a PR? or at least a skeleton of a solution?

**Comment by yesimon** [comment]
It turns out that most tools accepting sam inputs do work on piped input (which all boils down to checking `InputStream.markSupported()` on the input). In that case this limits this to just `FastqToSam`. My thoughts are to not do quality score sanity-checking if the `QUALITY_FORMAT` is provided and the input is a pipe.

**Comment by yfarjoun** [comment]
In that case you could add a command line argument to forgo the check.
