### ISSUE TITLE
What is the meaning of the histogram produced by MarkDuplicates

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/picard#917]
When I plot data from mrkdup.metrics.txt it I always get a nice diagonal. What else may I get and how to interpret it?

<pre>## HISTOGRAM	java.lang.Double
BIN	VALUE
1.0	1.000016
2.0	1.999896
3.0	2.999639
4.0	3.999245
5.0	4.998715
6.0	5.998049
...
98.0	97.355606
99.0	98.342333
100.0	99.328926
</pre>

We found a sentence in the FAQ which I try to rephrase here:
My data above indicates that if we would sequence 6x more than done now, we would get 5.99 times the current coverage?

In case of many duplicates, the second column will result in much lower values, indicating that sequencing more will not add proportionally to the obtained effective coverage.
If this is correctly interpreted, the title of the two columns should be more explicit than 'BIN'	'VALUE'

### from https://broadinstitute.github.io/picard/faq.html 
Q: What is the meaning of the histogram produced by MarkDuplicates?
A: MarkDuplicates estimates the return on investment for sequencing a library to a higher coverage than the observed coverage. The first column is the coverage multiple, and the second column is the multiple of additional actual coverage for the given coverage multiple. The first row (1x, i.e. the actual amount of sequencing done) should have ROI of approximately 1. The next row estimates the ROI for twice as much sequencing of the library. As one increases the amount of sequencing for a library, the ROI for additional sequencing diminishes because more and more of the reads are duplicates.

Thanks

**Comment by yfarjoun** [comment]
@splaisan I have merged a partial solution to this. please check if this is enough, and if not, please reopen.
