### ISSUE TITLE
Incorrect optical duplicates with HiSeqX bam file data (integer overflow)

### ISSUE THREAD

**Issue by yipal** [broadinstitute/picard#921]
### Affected tool(s)
picard MarkDuplicates optical duplicate detection

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest development/master branch as of [date of test?]

### Description 
The optical duplicate detection produces incorrect results when the X, Y location values exceed Short.MAX_VALUE (32,767).  The problem appears to be that picard uses Short to store the X and Y coordinates in a few different places.  When the name parser reads the values, it overflows, and causes aliasing if the X or Y value exceeds 65535 - (optical duplicate distance) because the overflowed value wraps around and picard compares the wrapped around value with values around 0.

#### Steps to reproduce
Create two reads that are duplicates by alignment position.  Then give them locations such as: (80000, 0) and (14400, 0):
`Foo:Bar:1:80000:0`
`Foo:Bar:1:14400:0`
Then run MarkDuplicates and Tag the optical duplicates with an optical distance of 2500.  Picard will mark these two reads as duplicates, even though their X coordinate distance is 65,600, and exceeds 2500.

#### Expected behavior
These two reads should not be optical duplicates.

#### Actual behavior
These two reads are considered optical duplicates.

I believe I have fixed the problem with this patch:
https://github.com/yipal/picard/commit/fc4160b7ba38a5dd4e8dac39a9e92094d97d3708

**Comment by yfarjoun** [comment]
While this is true, I am not sure about the cost/utility of fixing it. The PhysicalLocationInt implementation was written for a different purpose in mind (PositionBasedDownsampling) for which the overflow make a big difference. 

- Do you see significant differences in the metrics when running the two versions? 
- What are the differences in runtime/memory/disk usage?

**Comment by yipal** [comment]
I ran a test with a 16GB file, and here are the difference in optical counts, estimated library size, memory, and runtimes:

unmodified: Optical 26005762, ELS 44719706, maxMemory 4140302336, runtime 53.43 min
modified: Optical 26139665, ELS 44736636, maxMemory 4170711040, runtime 54.37 min

I forgot to mention that the optical count can also go down for coordinates that are just above 32,767 because they will become very negative numbers, and the distance will appear very large even though the true distance is short.  This causes the unmodified version to count a lower number of optical duplicates.

The actual number of optical duplicates is 0.51% higher, and the estimated library size is also different.

The memory consumption and runtimes are slightly higher, but it's probably not enough to show up in my test.  It doesn't seem like the cost to fix is very high, and I can imagine individual cases where the differences in metrics are larger.

It seems wrong to me to leave this bug in place.  At the very least picard should warn the user if the coordinates overflow.

**Comment by nh13** [comment]
The main issue is disk not memory in RAM. Do you have those numbers. Likely we could come up with a good estimate since the data size is fixed.

**Comment by yipal** [comment]
Where can I find out how much disk was used?

**Comment by yfarjoun** [comment]
Hmm. Reading the code I'm a little confused @nh13.

It seems that the ReadEndsForMarkDuplicates actually contains int values for the `x` and `y` instead of shorts. the commit message claims that "Now there are two concrete implementations, one that stores x/y as shorts, and the other as ints. " but I don't see the short **implementation** I see an int implementation and a short override of the access functions, but not of the member variables..what am I missing?

**Comment by nh13** [comment]
@yfarjoun agreed that `ReadEndsForMarkDuplicates ` actually stores an `int` since it goes all the way back up to `PhysicalLocationInt`, but the actual read/write codec is `ReadEndsForMarkDuplicatesCodec`, which writes a [`short`](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicatesCodec.java#L69-L70).

**Comment by yfarjoun** [comment]
aha! thanks for clarifying that....I was indeed confused.

**Comment by yfarjoun** [comment]
seeming lack of interest.
