### ISSUE TITLE
CollectRnaSeqMetrics uses platform unit instead of read group ID

### ISSUE THREAD

**Issue by kmhernan** [broadinstitute/picard#933]
### Affected tool(s)
_CollectRnaSeqMetrics_

### Affected version(s)
- 2.10.1
- 2.12.1

### Description 
_When running this tool and collecting metrics at `READ_GROUP` and `ALL_READS` levels, the metrics file has the `PU` string in the `READ_GROUP` column. For example, when I have this `@RG` header in my bam:_
```
@RG	ID:110429_UNC14-SN744_0106_AB066TABXX_1	SM:TCGA-CJ-4638-01A-02R-1325-07	LB:unknown	PL:illumina	PU:AB066TABXX.1	CN:UNC-LCCC
```

_The last three columns of the metrics section are:_

```
TCGA-CJ-4638-01A-02R-1325-07	unknown	AB066TABXX.1
```

_and the histrogram header is:_

```
## HISTOGRAM	java.lang.Integer
normalized_position	All_Reads.normalized_coverage	AB066TABXX.1.normalized_coverage
```

_I tested on the most recent version with a different bam, and still had the same issue. Is this expected?_

#### Steps to reproduce
_You should be able to reproduce this on and RNAseq bam with appropriate `@RG` header when requesting `METRIC_ACCUMULATION_LEVEL=READ_GROUP`._

#### Expected behavior
_I expect the `ID` string from the `@RG` header to be used in the `READ_GROUP` column of the metrics file instead of the `PU` (why not call it PLATFORM_UNIT instead if that's what you expect to happen?)._

#### Actual behavior
_The `PU` string is extracted and placed in the `READ_GROUP` column of the metrics file instead of the `ID` string._

**Comment by kmhernan** [comment]
Quick update this impacts all metrics as far as I can tell. I also see the exact line where this seems to be happening 

https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/metrics/MultiLevelCollector.java#L269

**Comment by yfarjoun** [comment]
Unlike the PU tag, the RG tag is not intended to be globally unique.
Mergimg files will change the RG  tag which is why we expose the PU tag
which is unique and unusable.

This is expected.

**Comment by kmhernan** [comment]
Interesting since PU isn't even part of the official SAM spec. In addition, the Broad GATK forums explicitly says this about read groups as seen here https://gatkforums.broadinstitute.org/gatk/discussion/6472/read-groups

```
This tag identifies which read group each read belongs to, so each read group's ID must be unique. It is referenced both in the read group definition line in the file header (starting with @RG) and in the RG:Z tag for each read record. Note that some Picard tools have the ability to modify IDs when merging SAM files in order to avoid collisions. In Illumina data, read group IDs are composed using the flowcell + lane name and number, making them a globally unique identifier across all sequencing data in the world.
```
I guess if you're taking only a Broad world view, then following the PU guidelines of `flowcell.lane.barcode` does make them universally unique, but again that's only the Broad world view.

**Comment by yfarjoun** [comment]
I'm not sure what spec you mean by "PU isn't even part of the official SAM spec."

From https://samtools.github.io/hts-specs/SAMv1.pdf:

>ID "Read group identifier. Each @RG line must have a unique ID. The value of ID is used in the RG tags of alignment records. Must be unique among all read groups in header section. Read group IDs may be modified when merging SAM files in order to handle collisions." (my emphasis)

> PU "Platform unit (e.g. flowcell-barcode.lane for Illumina or slide for SOLiD). Unique identifier." 

While I agree that PU is not required,  it is definitely "in the SAM spec." (with the same "world view" as in the GATK forum.)

Simply put, you have no control over the ID and thus using it as an external identifer is ill advised. if you put a good identifier you'll get meaningfull identifiers in your metrics.

**Comment by kmhernan** [comment]
ah yes, I looked at the same PDF but it looked like the table ended instead of overflowed to next page. However, I do indeed have control over the ID as I do not use picard for merging, and think that should be the responsibility of the user to manage. But obviously that isn't the picard way of merging. Thanks for the clarification.
