### ISSUE TITLE
Why is median target coverage is same for all samples

### ISSUE THREAD

**Issue by nansbn** [broadinstitute/picard#938]
Hello,
I am using Picard HsMetrics to calculate the mean/median coverage for each exon . The baits file is the whole target region of 150 genes and the interval file provided is a subset (genes of interest for that sample) of the bait file. The command I'm using is as follows
`java -Xmx8g -jar $picard CollectHsMetrics \
        I=$BAMDIROUT/$s_id.${RUNNAME}.bam \
        REFERENCE_SEQUENCE=$ind.fa \
        TARGET_INTERVALS=/Picard_exons/$panel.bed.interval_list \
        BAIT_INTERVALS=$baits \
        MQ=0 Q=0 CLIP_OVERLAPPING_READS=false \
PER_TARGET_COVERAGE=$PANELMETRICS/$s_id.${RUNNAME}.$panel.perTargetCoverage.txt \
        O=$PANELMETRICS/$s_id.${RUNNAME}.$panel.HsMetrics.txt
`

The result I end up getting is the median target coverage for each samples is 200. This can't be right ?

**Comment by yfarjoun** [comment]
Hi!

Thanks for your interest, could you please use the user forum here: https://gatkforums.broadinstitute.org/gatk/post/question/gatk-support-forum

(I know it's the GATK forum, but they also answer Picard questions.)

Thanks!
