### ISSUE TITLE
INVALID_FLAG_FIRST_OF_PAIR error for paired reads

### ISSUE THREAD

**Issue by zkamvar** [broadinstitute/picard#955]
### Affected tool(s)
_ValidateSamFile_, _MarkDuplicates_

### Affected version(s)

version 2.9.0

### Description 

I've logged a description of this problem at https://github.com/zkamvar/read-processing/issues/11

In short, I'm receiving the error `INVALID_FLAG_FIRST_OF_PAIR` on a bam file consisting of merged reads from paired and unpaired data when I attempt to run `MarkDuplicates`. The error is applied to two reads that appear to be paired (they have the 80 and 128 flags, respectively). This happened for 3 out of 55 samples. The strange part is that this has no problem when I attempt to run this using only paired-end data. I apologize for the bug report if this is a non-issue, I just couldn't find anything about this elsewhere.

Below is the error log of my run.

<details>
<summary>picard error report</summary>

```
[Thu Oct 12 11:42:43 CDT 2017] picard.sam.markduplicates.MarkDuplicates MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 INPUT=[BAMS/SS.11.16_fixed.bam] OUTPUT=BAMS/SS.11.16_dupmrk.bam METRICS_FILE=BAMS/SS.11.16_marked_dup_metrics.txt ASSUME_SORTED=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 SORTING_COLLECTION_SIZE_RATIO=0.25 REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag REMOVE_DUPLICATES=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Thu Oct 12 11:42:43 CDT 2017] Executing as kamvarz@c3107.tusker.hcc.unl.edu on Linux 2.6.32-696.10.3.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_92-b15; Picard version: 2.9.0-1-gf5b9f50-SNAPSHOT
INFO	2017-10-12 11:42:43	MarkDuplicates	Start of doWork freeMemory: 507124736; totalMemory: 514850816; maxMemory: 954728448
INFO	2017-10-12 11:42:43	MarkDuplicates	Reading input file and constructing read end information.
INFO	2017-10-12 11:42:43	MarkDuplicates	Will retain up to 3672032 data points before spilling to disk.
INFO	2017-10-12 11:43:04	MarkDuplicates	Read     1,000,000 records.  Elapsed time: 00:00:19s.  Time for last 1,000,000:   19s.  Last read position: CP017816.1_Sclerotinia_sclerotiorum_chromosome_3_complete_sequence:358,773
INFO	2017-10-12 11:43:04	MarkDuplicates	Tracking 1997 as yet unmatched pairs. 184 records in RAM.
INFO	2017-10-12 11:43:14	MarkDuplicates	Read     2,000,000 records.  Elapsed time: 00:00:30s.  Time for last 1,000,000:   10s.  Last read position: CP017818.1_Sclerotinia_sclerotiorum_chromosome_5_complete_sequence:2,137,460
INFO	2017-10-12 11:43:14	MarkDuplicates	Tracking 3127 as yet unmatched pairs. 91 records in RAM.
INFO	2017-10-12 11:43:24	MarkDuplicates	Read     3,000,000 records.  Elapsed time: 00:00:40s.  Time for last 1,000,000:   10s.  Last read position: CP017821.1_Sclerotinia_sclerotiorum_chromosome_8_complete_sequence:1,987,969
INFO	2017-10-12 11:43:24	MarkDuplicates	Tracking 3489 as yet unmatched pairs. 95 records in RAM.
[Thu Oct 12 11:43:38 CDT 2017] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.91 minutes.
Runtime.totalMemory()=891289600
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 3122379, Read name K00133:265:HF75NBBXX:2:1101:1113:12251, First of pair flag should not be set for unpaired read.
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:448)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:796)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:781)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:751)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:569)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:543)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:438)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:222)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
 	Full Command: picard MarkDuplicates I=BAMS/SS.11.16_fixed.bam O=BAMS/SS.11.16_dupmrk.bam M=BAMS/SS.11.16_marked_dup_metrics.txt MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 ASSUME_SORTED=true
	Memory (kb): 866624
	# SWAP (freq): 0
	# Waits (freq): 30990
	CPU (percent): 161%
	Time (seconds): 55.94
	Time (hh:mm:ss.ms): 0:55.94
	System CPU Time (seconds): 2.98
	User CPU Time (seconds): 87.22

```

</details>
<br>

Checking the bam file shows that these reads mapped to different chromosomes

```
> samtools view BAMS/SS.11.16_fixed.bam | grep 'K00133:265:HF75NBBXX:2:1101:1113:12251'
K00133:265:HF75NBBXX:2:1101:1113:12251	80	CP017822.1_Sclerotinia_sclerotiorum_chromosome_9_complete_sequence	690388	42	70M	*	0	0ATCACTACTAATCCATGAAGAGGATTATTACTCAGATGAAGAAGATGTGGGATTTATAGATGTCCCTGCG	FJA7JJJJFA<JJJFJFFAJJJJFJJJJFFJJJFJFJFJFJFAJFJJJJJJFJJJJJJJFJJJFJFFFAA	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:70	YS:i:-3	YT:Z:DP	RG:Z:HF75NBBXX.2
K00133:265:HF75NBBXX:2:1101:1113:12251	128	CP017829.1_Sclerotinia_sclerotiorum_chromosome_16_complete_sequence	761051	42	51M	*	0	0TGTAGTTGCCATTTATTAACATACTTCTAATTAGATCCTTCTTGAATCGCC	AAAFF<FJFJJFJJJ<FJJJJ7FFFFFFFJJJJJJAFJ<7FAAFJJAFA-F	AS:i:-3	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:49T1	YS:i:0	YT:Z:DP	RG:Z:HF75NBBXX.2
```

But, when I look at the originating FASTQ files, these are marked as paired:

```
> zcat TRIM/SS.11.16_1P.fq.gz | grep -n K00133:265:HF75NBBXX:2:1101:1113:12251
73101:@K00133:265:HF75NBBXX:2:1101:1113:12251 1:N:0

> zcat TRIM/SS.11.16_2P.fq.gz | grep -n K00133:265:HF75NBBXX:2:1101:1113:12251
73101:@K00133:265:HF75NBBXX:2:1101:1113:12251 2:N:0
``` 

#### Steps to reproduce

Unfortunately, the steps I took to get here are long and convoluted. Here is a summary:

 - trim reads with trimmomatic 0.36: https://github.com/zkamvar/read-processing/blob/422f93981a50687622807233fde5cff2a1f8ba6c/scripts/trim-reads.sh#L43-L49
 - align paired reads to reference with bowtie 2.2: https://github.com/zkamvar/read-processing/blob/422f93981a50687622807233fde5cff2a1f8ba6c/scripts/make-alignment.sh#L73-L86
 - sort and convert sam files to bam files: https://github.com/zkamvar/read-processing/blob/422f93981a50687622807233fde5cff2a1f8ba6c/scripts/sam-to-bam.sh#L53
 - merge paired and unpaired reads: https://github.com/zkamvar/read-processing/blob/422f93981a50687622807233fde5cff2a1f8ba6c/scripts/merge-bam.sh#L33
 - run samtools fixmate, sort, and calmd https://github.com/zkamvar/read-processing/blob/422f93981a50687622807233fde5cff2a1f8ba6c/scripts/add-MD-tag.sh#L56-L59
 - run MarkDuplicates: https://github.com/zkamvar/read-processing/blob/422f93981a50687622807233fde5cff2a1f8ba6c/scripts/mark-duplicates.sh#L32-L34

**Comment by yfarjoun** [comment]
Thanks for teaching me about `<details>` that's awesome! 

It seem that your bams are not created properly. 

Flag 80 is not valid as it is saying:
"unpaired" && "First in pair" 

similarly 128 is saying:
"unpaired" & "Second in pair"

so whatever program you are running that is creating these flags probably needs to be adjusted...

I recommend that you run (picard) ValidateSamFile on your Sam/Bam files in your pipeline and find out when they because invalid. the different chromosome sounds like a red herring...but it might be that bow-tie or some other tool is getting confused by it and marking the paired reads as unpaired for some reason...

If you need more help, please write in the GATK forum: https://gatkforums.broadinstitute.org/gatk they also support Picard there.
