### ISSUE TITLE
QuerySortedMarkDuplicatesTester is unused

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/picard#967]
### Description 
`QuerySortedMarkDuplicatesTest` was removed in #548, but the `QuerySortedMarkDuplicatesTester` remained and is unused.  

`QuerySortedMarkDuplicatesTest` seems to have been replaced by  replaced by `AsIsMarkDuplicatesTester`, which tests a `BySumOfBaseQAndInOriginalOrderMDTester`

Should it be deleted? Or was `QuerySortedMarkDuplicatesTest` removed by accident?

The also, the naming seems off for `AsIsMarkDuplicatesTester`, all the other test files are listed as `Test`, not `Tester`.

**Comment by yfarjoun** [comment]
fixed by #1174
