### ISSUE TITLE
*bam files with the same size (# of contigs) to merge?

### ISSUE THREAD

**Issue by SergioB1983** [broadinstitute/picard#969]
Hi,

I am trying to merge multiple (4 files data fom UCEs) *bam files using **MergeSamFiles.jar**. However, the script shows this message:

`Exception in thread "main" net.sf.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (3857, 3743)`

Indeed, the *bam files have different sizes, but my _experiment_ dont allow _edit_ the files to be equal in size. I use the `samtools view -H` command(s) to see the format and information of each file, so I think that that is not the problem.

So, i have a question:

- It is necessary that the *bam/sam files have the same size (contigs) to be merged?

Sorry by the basic questions, but I dont find information on this.

Thanks in advance.

**Comment by vdauwera** [comment]
Hi, can you please post your question in the GATK support forum as indicated in the instructions on the front page? The team will answer you there.

**Comment by SergioB1983** [comment]
Thanks!
