### ISSUE TITLE
ReorderSAM crashes with Invalid reference index -1 error after it is done

### ISSUE THREAD

**Issue by chrarnold** [broadinstitute/picard#974]
I receive this message for ReorderSAM, which I never saw before and I am not sure what it could be... Any hints?

[Sat Nov 11 18:34:17 GMT+01:00 2017] picard.sam.ReorderSam INPUT=382_rep1.cleaned3.s.bam OUTPUT=382_rep1.cleaned4.s.bam REFERENCE=GATK/Homo_sapiens_assembly38.fasta ALLOW_INCOMPLETE_DICT_CONCORDANCE=true CREATE_INDEX=true    ALLOW_CONTIG_LENGTH_DISCORDANCE=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Sat Nov 11 18:34:17 GMT+01:00 2017] Executing as ... on Linux 3.10.0-693.2.2.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_112-b15; Picard version: 2.9.0-1-gf5b9f50-SNAPSHOT

...
INFO    2017-11-11 18:40:37     ReorderSam        Processing chrUn_KI270742v1
INFO    2017-11-11 18:40:37     ReorderSam      Wrote 1294 reads
INFO    2017-11-11 18:40:37     ReorderSam        Processing chrUn_GL000216v2
INFO    2017-11-11 18:40:37     ReorderSam      Wrote 7644 reads
INFO    2017-11-11 18:40:37     ReorderSam        Processing chrUn_GL000218v1
INFO    2017-11-11 18:40:37     ReorderSam      Wrote 1574 reads
[Sat Nov 11 18:40:37 GMT+01:00 2017] picard.sam.ReorderSam done. Elapsed time: 6.33 minutes.
Runtime.totalMemory()=7847018496
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
        at picard.sam.ReorderSam.doWork(ReorderSam.java:124)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)

**Comment by yfarjoun** [comment]
0. Just checking that you know that ReorderSam is not SortSamFile...
1. the -1 seems to be the result of running with incompatible dictionaries...if you really need ReorderSam (and not SortSamFile) re-run your command without the ALLOW_INCOMPLETE_DICT_CONCORDANCE=true part and you'll get an error message explaining which contig in the source file is missing from the reference you are using.

**Comment by chrarnold** [comment]
Why is this closed so quickly? I used ReorderSam a lot of times before, and it always worked. The ALLOW_INCOMPLETE_DICT_CONCORDANCE=true also was necessary for me previously. In any case, the error message should not be like but instead informative and pointing to the problem somehow. I will try your suggestions. Thanks for the quick reply, I will need further testing.

**Comment by chrarnold** [comment]
I receive the same error message and no further explanation also without ALLOW_INCOMPLETE_DICT_CONCORDANCE. Debugging is very difficult in this case, as ReOrderSam just crashes without giving any details why.

**Comment by yfarjoun** [comment]
The stack trace didn't really make sense with regards to the current code. Could you run this in master and post the new stack trace?

**Comment by chrarnold** [comment]
With the newest version (just followed the instructions in the Git), I get something almost idential:

at Nov 11 20:48:36 GMT+01:00 2017] picard.sam.ReorderSam done. Elapsed time: 7.11 minutes.
Runtime.totalMemory()=5367136256
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at picard.sam.ReorderSam.doWork(ReorderSam.java:141)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

**Comment by chrarnold** [comment]
I think this is indeed a contig issue since GATK prints the following message on the same file when trying to recalibrate base quality scores: 

##### ERROR MESSAGE: Badly formed genome location: Parameters to GenomeLocParser are incorrect:The contig index 194 is bad, doesn't equal the contig index 455 of the contig from a string chrEBV. 

But for both the BAM and the fasta, this contig has the same length, I don't quite understand yet what the problem is.

**Comment by yfarjoun** [comment]
Thanks for the new stack trace. 
The GATK message is complaining that the order is incorrect. Which makes sense.

It seems that there's a contig in your BAM that is not present in the reference. 
Could you post the full output and error log of the command?

**Comment by chrarnold** [comment]
The full output and error I already posted, the new version did not change that. No further diagnostic messages even with VERBOSITY=DEBUG. There is nothing else printed except what I posted here.
Again, all contigs from the BAM file are in the fasta reference, with the same length. The reference contains some additional contigs, that should not be a problem, though.

**Comment by yfarjoun** [comment]
Your posts included "..." and so I assumed that you cut out some of the output (which is very reasonable as the output can be large). Also, the code has a section that prints out (as an INFO log) the dictionary entries from both the REFERENCE and the INPUT, and since I didn't see these in the output that you posted, my assumption was corroborated.

Could you please double-check that you have posted _all_ the output from the program?

**Comment by chrarnold** [comment]
This can be closed I guess, the only suggestion I have is to print a clear error message at the end rather than the real crash that is hard to interpret. In the end, I rebuild the bowtie2 index with the fasta file, realigned, and the error disappeared. It is still unclear to me because all contigs had identical size, but I did not have enough time to dig deeper into it.

**Comment by fac2003** [comment]
I am also seeing this error with Picard version: 2.17.1-SNAPSHOT. The input has only three chromosomes, and the error occurs when trying to write reads for a chromosome absent form the BAM file:

INFO	2018-01-12 20:55:56	ReorderSam	Reordering SAM/BAM file:
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr10 [index=10] to => ref contig chr10 [index=0]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr11 [index=11] to => ref contig chr11 [index=1]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr12 [index=12] to => ref contig chr12 [index=3]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr13 [index=13] to => ref contig chr13 [index=4]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr14 [index=14] to => ref contig chr14 [index=5]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr15 [index=15] to => ref contig chr15 [index=6]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr16 [index=16] to => ref contig chr16 [index=7]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr17 [index=17] to => ref contig chr17 [index=9]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr18 [index=18] to => ref contig chr18 [index=14]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr19 [index=19] to => ref contig chr19 [index=16]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr1 [index=1] to => ref contig chr1 [index=19]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr20 [index=20] to => ref contig chr20 [index=22]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr21 [index=21] to => ref contig chr21 [index=23]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr22 [index=22] to => ref contig chr22 [index=25]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr2 [index=2] to => ref contig chr2 [index=26]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr3 [index=3] to => ref contig chr3 [index=27]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr4 [index=4] to => ref contig chr4 [index=29]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr5 [index=5] to => ref contig chr5 [index=32]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr6 [index=6] to => ref contig chr6 [index=36]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr7 [index=7] to => ref contig chr7 [index=41]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr8 [index=8] to => ref contig chr8 [index=43]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chr9 [index=9] to => ref contig chr9 [index=46]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chrM [index=0] to => ref contig chrM [index=51]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chrX [index=23] to => ref contig chrX [index=91]
INFO	2018-01-12 20:55:56	ReorderSam	  Reordering read contig chrY [index=24] to => ref contig chrY [index=92]
INFO	2018-01-12 20:55:56	ReorderSam	Writing reads...
INFO	2018-01-12 20:55:56	ReorderSam	  Processing chr10
INFO	2018-01-12 20:55:56	ReorderSam	Wrote 0 reads
INFO	2018-01-12 20:55:56	ReorderSam	  Processing chr11
INFO	2018-01-12 20:55:56	ReorderSam	Wrote 0 reads
[Fri Jan 12 20:55:56 UTC 2018] picard.sam.ReorderSam done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=1931476992
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at picard.sam.ReorderSam.doWork(ReorderSam.java:141)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)

**Comment by yfarjoun** [comment]
Your stacktrace doesn't agree with the master branch. could you please run this against the current release?

**Comment by yfarjoun** [comment]
also, please provide as much data as you can:

- commandline
- all output,
- versions
- input if possible.

**Comment by fac2003** [comment]
I just fixed the bug in a fork from master. I will send you a pull request. I just had to protect the call to fetch reads in a statement that checks if the sequence exits in the BAM/SAM file.
