### ISSUE TITLE
Block user ananda8

### ISSUE THREAD

**Issue by nh13** [broadinstitute/picard#995]
They have been spamming. Perhaps notify @ananda8 and the https://github.com/blog/2146-organizations-can-now-block-abusive-users

**Comment by lbergelson** [comment]
I reported them to github, but I haven't heard anything back yet.

**Comment by lbergelson** [comment]
@lukwam Do you have power to block people?  If so, could you put @ananada8 on the list?

**Comment by jmthibault79** [comment]
From Github support:

> Hi Joel,Thanks for taking the time to send this report. That user's content should no longer be visible.

**Comment by nh13** [comment]
👍
