### ISSUE TITLE
add the support of --maxReadsInRegionPerSample to DownSampleSAM

### ISSUE THREAD

**Issue by wangyugui** [broadinstitute/picard#996]
### Tool(s) involved
DownSampleSAM

### Description
Can we add the support of --maxReadsInRegionPerSample(https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller.php) to DownSampleSAM?

It will help many use case such as RNA assembly and DNA/RNA SNV caller.

**Comment by yfarjoun** [comment]
I think that it would be difficult to do this while still adhering to the policy that mates should be filtered together. You are welcome to submit a PR, but the resulting BAM must be valid (according to Picard's ValidateSamFile.)

**Comment by wangyugui** [comment]
or something like
```
 -dcov,--downsample_to_coverage <downsample_to_coverage>                Coverage [integer] to downsample to at any given 
```

**Comment by wangyugui** [comment]
It maybe difficult , but GATK/samtools mpileup/cufflinks all have the process of coverage.
If we have a better standalone tool, it is wildly used to replace these function.

**Comment by wangyugui** [comment]
this is no downsample_to_coverage in gatk4 PositionBasedDownsampleSam too.

**Comment by yfarjoun** [comment]
PositionBasedDownsampleSam is not (reference)PositionBasedDownsampleSam, but rather it is (flowcell)PositionBasedDownsampleSam...I guess this is unclear (though the documentation does say so...)

Also note, the gatk version is the same PositionBasedDownsampleSam from Picard.

can you explain what you need this functionality for?

**Comment by wangyugui** [comment]
There are two case that have high coverage at some regions.
a)MT and some region  when SNV caller@DNA-seq
   samtools mpileup/GATK have downsample feature, but freebayes have not.

b)RNA assembly@RNA-seq
   trinity have a kmer-based downsample feature.
   cufflinks have downsample function. but stringtie have not.

If we have a reference PositionBased Downsample standalone tool, that can be used for improving performance and benchmarking the feature of some tools.

And reference PositionBased Downsample tool will be better than kmer-based downsample too?

**Comment by wangyugui** [comment]
It is difficult to implement this feature, but in fact, it is difficult to find out whether the downsample function in samtools mpileup/gatk/cufflinks works as expected too.

It is a feature need by many tools /already in many tool , then we have the needs to standard it and make it as a standalone tool?

**Comment by wangyugui** [comment]
This tool may need much memory to keep the passed/failed record to generate a prefect bam file without any warning.

**Comment by wangyugui** [comment]
I tried a dirty image, it seems works well.

1,  use the 1/2 of reads length as the region length.
2,  the reads mapped(not 0x900) in this region(POS of sam in this region) and prev region as the depth of this region.
3,  if the depth of this region is over 500,  remove some of them by random.
4, manage all passed/failed reads to output/remove both end of the reads.

**Comment by kbergin** [comment]
Hi @wangyugui, were you interested in submitting a PR for this feature request? If not or if we don't hear back, we'll close this issue for now, given it hasn't had other up votes.

**Comment by wangyugui** [comment]
Let's close it. More tools have the DownSample functions inside just like GATK now.
